### ISSUE TITLE
improve error of insufficient number of arguments or no entry found

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack-cli#1003]
**Is your feature request related to a problem? Please describe.**

Unfriendly errors and bad DX. Steps:
- create empty project
- create package.json with
```
"scripts": {
    "build": "webpack"
}
```
- run script using `npm`/`yarn`, for example `npm run build`

It is output:
```
Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.
```

Using `webpack-cli --help` output many information about flags and i still can't understand what i am missing. Based on docs you can see `webpack [option]` is allowed.

**Describe the solution you'd like**

Better errors. Like `The nameOfArgument argument is missing` or `Can't resolve 'path/to/entry.js', please make sure file exists`.

**Describe alternatives you've considered**

using node api because it is have simple and easy api

**Additional context**

no, steps above

**Comment by evilebottnawi** [comment]
Note:
```
ERROR in Entry module not found: Error: Can't resolve './src' in '/path/to/project'
```

is unfriendly because i can have `src` directory, but entry file can have other name like `main.js`, `script.js` and etc, will be great to see filename in error.

**Comment by rajasekarm** [comment]
Shall I pick this?

**Comment by evenstensberg** [comment]
No need, we're working on v4, not a priority

**Comment by evilebottnawi** [comment]
@evenstensberg it will be fixed in `v4`?

**Comment by evenstensberg** [comment]
yes
