### ISSUE TITLE
[TESTS]: Write tests for the arguments we support

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#1012]
**Is your feature request related to a problem? Please describe.**
In the next branch, we're replacing old test in favor for new ones. We can still use logic from the old test suite, but we need to write new assertions. Those include:

- [x] create
- [x] migrate
- [x] loader
- [x] plugin
- [x] info
- [x] negated flags
- [x] entry
- [x] dotfolder lookup
- [x] output
- [x] watch
- [x] merge
- [x] global
- [x] sourcemap
- [x] help
- [x] json
- [x] dev
- [x] prod
- [x] version
- [x] config

 **Describe the solution you'd like**

As listed in the previous section, these are the arguments we need to test. In addition, we need a replacement for the `mode` property, by reading the node env instead or by letting users pass the environment as a param to the webpack config, maybe both. I prefer that we read the node environment, because this means that we'll opt out of having to support a flag for setting mode, rather users can use the environment to set webpack mode. 

Furthermore, we need to in specific, test the way we combine the cli arguments with a config specified, in such fashion that we know that we're not creating any bugs.

I'd prefer that CLI arguments outrule configuration, but I'm open for discussion on that part. 

**Describe alternatives you've considered**
N/A

**Additional context**
Please comment in this issue for questions instead of reaching out to my personal accounts. This way it's public and everyone can chime in on what's happening.

**Comment by evenstensberg** [comment]
FYI after this issue is closed, the args that (might) cause trouble are fixed, we can tag a beta

**Comment by rishabh3112** [comment]
> Furthermore, we need to in specific, test the way we combine the cli arguments with a config specified, in such fashion that we know that we're not creating any bugs.
>
> I'd prefer that CLI arguments outrule configuration, but I'm open for discussion on that part.

I think this makes sense (i.e. CLI arguments should have a higher priority in case of conflict with config).
Are there some tests I can start working on @evenstensberg?

**Comment by evenstensberg** [comment]
Just pick a flag to test

**Comment by rishabh3112** [comment]
@evenstensberg I started on `--version` flag. I am afraid that I can't understand the requirements of this use case:

`webpack-cli --version` (in the empty project)
Instead of printing the version of the webpack CLI, it complies with errors.

Just for info, I understand this behaviour of command as per the current codebase, but is this the expected behaviour?

**Comment by anshumanv** [comment]
Writing tests for info ℹ️

**Comment by anikethsaha** [comment]
Trying tests for `config`

**Comment by anikethsaha** [comment]
I guess you can checkmark the ` config `. 
Anything left for that!?

**Comment by evenstensberg** [comment]
Config done as of https://github.com/webpack/webpack-cli/commit/fa9d5c22b41458a71b91e73bfe48924a61ba6e3e

**Comment by evenstensberg** [comment]
For testing env, I think we'll add a stdout line where it says the current env for each compilation, both main and child compilations. Needs a PR to core and then drag that out to stats and tty

**Comment by anikethsaha** [comment]
Writing for `output`

**Comment by anikethsaha** [comment]
@evenstensberg can you update which flags are still required to add tests ?

**Comment by evenstensberg** [comment]
The ones that are listed here are the ones missing, crossing them out as we go

**Comment by anikethsaha** [comment]
Tests for `Output` flag is done. You mark it checked if it's fine.

**Comment by anikethsaha** [comment]
Will submit for `info` by this weekend. 
Also can you explain about the dotfolder look up? Is it something like tests for ignoring them in the bundle?

**Comment by evenstensberg** [comment]
Dotfolder is a convention where you have a folder `.webpack` which will look in parent folder for source files

**Comment by anikethsaha** [comment]
command tests already exist as independent package tests.

**Comment by evenstensberg** [comment]
We need to have E2E tests for thsoe

**Comment by niravasher** [comment]
@anikethsaha are you still working on writing test for info? If not can I work on it?

**Comment by anikethsaha** [comment]
> @anikethsaha are you still working on writing test for info? If not can I work on it?

go for it 👍

**Comment by niravasher** [comment]
![Screenshot from 2020-01-09 23-39-29](https://user-images.githubusercontent.com/32176296/72092920-5aef3500-3339-11ea-864c-d54a5ab082db.png)

This is what I get on typing webpack info.
So in my test I should match the OS, CPU, Node and npm version, webpack and webpack-cli version. Am i right? @anikethsaha . What else can I do here?

**Comment by anikethsaha** [comment]
yeah, pretty much that.
you can do tests with the plugins mentioned in the webpack config and do assertion.
and also with other dependencies.

> OS, CPU

I guess it may be different for the CI version, you can consider to skip these

**Comment by niravasher** [comment]
> you can do tests with the plugins mentioned in the webpack config and do assertion.
> and also with other dependencies.

Test with plugins should be done in separate test right? Which other dependencies? @anikethsaha

**Comment by niravasher** [comment]
I keep getting this
![Screenshot from 2020-01-10 16-35-46](https://user-images.githubusercontent.com/32176296/72148716-7d2f9400-33c7-11ea-9604-25776a82c64c.png)

How to continue after this?
![Screenshot from 2020-01-10 16-36-09](https://user-images.githubusercontent.com/32176296/72148762-99333580-33c7-11ea-8ba6-1e5d0087ec28.png)

**Comment by anikethsaha** [comment]
You need to investigate that. Might be some installation error. 

> Which other dependencies?

I meant webpack plugins only... Installed as a dep

**Comment by niravasher** [comment]
While installing webpack-cli error says I am installing webpack-cli in a project named webpack-cli. @anikethsaha

**Comment by anikethsaha** [comment]
You don't have to install webpack cli for working in this project locally. 
Read the contribution guide. All steps are mentioned there. 
In order to tests and use the local version you need to link it....

**Comment by niravasher** [comment]
I can test other cmds like help, json etc. Just `run(__dirname, [info])` gives the install msg. So in place of `info` what else can I run? @anikethsaha @rishabh3112

**Comment by anshumanv** [comment]
Writing for create

**Comment by snitin315** [comment]
I have Added Tests for some Negated flags

**Comment by anshumanv** [comment]
I think we have covered everything, closing.
