### ISSUE TITLE
[NEXT] Support for Making default true boolean flags false via --no-option or --option=false

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack-cli#1013]
**Is your feature request related to a problem? Please describe.**

When a boolean CLI flag defaulted to `true` with `yargs` (eg. `--option`), `yargs` let us make it `false` by doing either `--no-option` or `--option=false`. (see https://github.com/yargs/yargs/blob/master/docs/tricks.md).

With `command-line-args`, this feature is not supported: https://github.com/75lb/command-line-args/issues/71

I'm not sure on the reasoning behind switching from `yargs` to `command-line-args`, but I think for booleans this is a useful feature that we had available to us. Possibly the switch is being made to receive the benefits of the complementary [`command-line-usage`](https://www.npmjs.com/package/command-line-usage)?

**Describe the solution you'd like**

It might be easiest to manually add a `--no-option` for these cases. However, I've personally seen the `--option=false` syntax used more often, but if you just add an option in `command-line-args` with `name: 'option=false'`, it will be misleading, suggesting that you can set other values using the "equals" syntax.

**Describe alternatives you've considered**

- Make a helper to go through the argument definitions, and if it finds a boolean flag that defaults to true, add a `no-flagname` option as well. There could be some logic as well to prevent it from being printed with `webpack-cli help`, if needed.
- Alternatively, switch back to `yargs`

**Additional context**

I've seen this feature used with `webpack-dev-server`, and only was aware that the `--option=false` syntax existed until I looked into it now and found the `--no-option` syntax as well. For example, I've seen `webpack-dev-server --inline=false`.

**Comment by evenstensberg** [comment]
Thanks for filling out a detailed issue! Will have a look

**Comment by evenstensberg** [comment]
Fixed https://github.com/webpack/webpack-cli/commit/239a67ea4fa32b3da180f374732d4c4a761dc4ac
