### ISSUE TITLE
[NEXT] improve missing babel dependency support

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack-cli#1015]
**Is your feature request related to a problem? Please describe.**

The `webpack-cli` command uses configs that utilize `babel-loader` and other babel dependencies, as seen here: https://github.com/webpack/webpack-cli/blob/98e180f0372808891ce4cdde7d28689b66234e24/lib/utils/prod-config.js#L14. When I first ran `webpack-cli`, I got some unresolved dependency problems with these babel dependencies, because I did not have them installed in my sample project. I did not start off the project with `webpack-cli init` Installing them solved the problem.

**Describe the solution you'd like**

I'm not sure if `webpack-cli init` installs these for the user, but if not, it probably should.

Even if the user does not use `webpack-cli init`, but simply drops `webpack-cli` into an existing project, `webpack-cli` should recognize that the user is missing these dependencies and ask the user for permission to install them.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by anikethsaha** [comment]
> I'm not sure if webpack-cli init installs these for the user, but if not, it probably should.

https://github.com/webpack/webpack-cli/blob/30bc7ad769049a68423f1b4ce67fe453d39ba282/packages/generators/init-generator.ts#L253

I guess this 👆  line should cover it. 
```js
 install() {
    this.npmInstall();
 }
```
May be this can be replaced with 👆   Not sure about it.
