### ISSUE TITLE
[NEXT]: Missing bin

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack-cli#1016]
**Describe the bug**

Entry script is missing from the `.bin`

**What is the current behavior?**

The missing entry point in the `node_modules/.bin`

**To Reproduce**
Steps to reproduce the behaviour:
1. checkout next branch
2. yarn link
3. Add the linked package to another project
4. Try to find an entry point in the bin `node_modules/.bin` for `webpack-cli`

**Expected behavior**
Entry point must be present

![Screenshot from 2019-08-01 23-53-04](https://user-images.githubusercontent.com/32242596/62317724-e1b10380-b4b7-11e9-8ac6-48831a7b5d4f.png)

**Comment by anikethsaha** [comment]
> 3. Add the linked package to another project

didnt get this ???

Also, it seems to be fine if simply linking with the current. May be I am missing something to re-create it ?

**Comment by evenstensberg** [comment]
This is not an issue
