### ISSUE TITLE
bug: webpack -watch is logging an error on startup (when there is no error)

### ISSUE THREAD

**Issue by cowwoc** [webpack/webpack-cli#1017]
# Bug report

**What is the current behavior?**
`webpack -watch` outputs the following on startup:

```
[ERROR] 
[ERROR] webpack is watching the files…
[ERROR] 
```

even if the project is perfectly fine.

**What is the expected behavior?**
Log the aforementioned lines using `INFO` log level.

**Other relevant information:**
webpack version:  4.38.0
Node.js version: 10.16.0
Operating System: Windows 10
Additional tools:

Justification: many tools (IntelliJ IDEA in my case) highlight anything logged with `ERROR` as ... well ... an error. Because webpack uses this logging level, the IDE always warns about run that don't actually exist.

**Comment by cowwoc** [comment]
I see. Any idea who is prefixing stderr output with `[ERROR]`?

**Comment by evenstensberg** [comment]
I don't think we are doing that, which tools are you using?

**Comment by cowwoc** [comment]
IntelliJ IDEA, npx, webpack --watch

**Comment by cowwoc** [comment]
I found the culprit: https://github.com/eirslett/frontend-maven-plugin/blob/0766bf616266ff6ea55960e8a2d4d4702b25cfdb/frontend-plugin-core/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/ProcessExecutor.java#L64

Sorry for the false alarm.
