### ISSUE TITLE
[ENHANCEMENT]: Add help for core commands

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#1053]
**Is your feature request related to a problem? Please describe.**
We can have help commands for individual core commands for ex `webpack-cli create --help`

**Describe the solution you'd like**
Check if the help flag is present along with the core command and then print relative command.

**Describe alternatives you've considered**
NA

**Additional context**
Would love suggestions on this and will implement once agreed.

**Comment by anshumanv** [comment]
@evenstensberg @ematipico wdyt about this?


Here's how vue does this.
![image](https://user-images.githubusercontent.com/21009455/63325425-b3507680-c347-11e9-8f58-8bef5b097ff3.png)

**Comment by evenstensberg** [comment]
Yep we should do that if invoked with command syntax

**Comment by anshumanv** [comment]
Adding them in that case 👍

**Comment by evenstensberg** [comment]
Need help with this?

**Comment by anshumanv** [comment]
> Need help with this?

Not yet, will send a patch in some time! :)
