### ISSUE TITLE
ReferenceError: getConfigExtension is not defined

### ISSUE THREAD

**Issue by williamnie** [webpack/webpack-cli#1055]
**Describe the bug**
run 
```
webpack -c ./config/webpack.base.js
```
error:` ｢webpack｣:  ReferenceError: getConfigExtension is not defined`
my version :     "webpack-cli": "^4.0.0-alpha-5",

i read webpack-cli code
need change  file :webpack-cli/lib/groups/config.js:72
```
if (config) {
			//TODO: check for existence, give user feedback otherwise
			const configPath = path.resolve(process.cwd(), config);
			const ext = getConfigExtension(configPath);     // this is wrong
			this.configFiles = {
				path: configPath,
				ext
			};
		}
```
change to
```
if (config) {
			//TODO: check for existence, give user feedback otherwise
			const configPath = path.resolve(process.cwd(), config);
			const ext = this.getConfigExtension(configPath);
			this.configFiles = {
				path: configPath,
				ext
			};
		}
```

**Comment by rishabh3112** [comment]
Hi @williamnie, thanks for reporting. Would be nice if you could send a PR for this!

**Comment by williamnie** [comment]
> Hi @williamnie, thanks for reporting. Would be nice if you could send a PR for this!

i use "webpack-cli": "^4.0.0-alpha-5",

**Comment by rishabh3112** [comment]
Send up it to `next` branch with `next` branch as base.

**Comment by williamnie** [comment]
> Send up it to `next` branch with `next` branch as base.

I found this bug has been fixed. Thank you
