### ISSUE TITLE
Enhancements: Use TypeScript

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#106]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

We have a clutty codebase with no real type support, which makes it hard to make approximations and to get involved in what enters the parameters etc..

**What is the expected behavior?**

TypeScript integration

**If this is a feature request, what is motivation or use case for changing the behavior?**
project structure and developer experience.

**Comment by okonet** [comment]
Please don't. If you want to use types, let use flow which is much easier to introduce to the existing project but this will also require pre-processing the code. I'd say for project like CLI the benefit is too low. Having unit tests should solve most of the problems IMO.

**Comment by ev1stensberg** [comment]
Moved to #87
