### ISSUE TITLE
[QUESTION]: webpack-cli@3.3.7 raises "Expected Identifier" in IE11

### ISSUE THREAD

**Issue by hummal** [webpack/webpack-cli#1069]
**Describe the bug**

If I build my config with 3.3.7 it raises an error in execution in IE11 with the message "Expected indentifier". After downgrading to 3.3.5 it works as expected. 

**What is the current behavior?**

The reason why this is happening is the new implemented function of "./node_modules/debug/src/common.js" - log(...array) - which is an ES6 syntax and can not be read by IE11.
This function has no parameters in the 3.3.5 version. These packages are included by webpack itself and exists also in the production build. 

**To Reproduce**
1. Install 3.3.7
2. build'
3. open page in IE11

**Expected behavior**
Build and use output in IE without error

**Comment by evenstensberg** [comment]
You'll need to come up with repo that I can run this in. Most likely this is an issue with babel, not webpack itself.

**Comment by Download** [comment]
Please re-open. My [beta 19 of `ulog`](https://github.com/Download/ulog/releases/tag/2.0.0-beta.19) exhibits this issue and AFAICT it started with my upgrade to latest of Webpack and Webpack CLI.

Please check https://ulog.js.org/tutorial in IE11.

**Comment by Download** [comment]
Not using Babel BTW if that helps.
