### ISSUE TITLE
[Feature Request] Having a helper function for parsing the outputOptions

### ISSUE THREAD

**Issue by wood1986** [webpack/webpack-cli#1075]
**Is your feature request related to a problem? Please describe.**
I am writing a tool and I want to reuse the implementation of parsing the outputOption that `webpack-cli` has already done rather than making mine or duplicating it. I am talking about 
https://github.com/webpack/webpack-cli/blob/9487ee52dbb84d63bb9b6c158ced8b458da6289b/bin/cli.js#L139-L265

**Describe the solution you'd like**
just move these logics into another file called `bin/utils/prepareOutputOptions.js` and then export it

**Describe alternatives you've considered**
There is no way to achieve until you expose it

**Additional context**
If you guys approve, I am going to make it

**Comment by evenstensberg** [comment]
I think we're not gonna do anything with this file as it's on the master branch and we're working on improving the CLI at the next branch.
