### ISSUE TITLE
[ENHANCEMENT]: Yarn PnP support for serve command

### ISSUE THREAD

**Issue by vhiairrassary** [webpack/webpack-cli#1080]
**Is your feature request related to a problem? Please describe.**

When using yarn v2, we can't use `serve` as `@webpack-cli/serve` is not declared as a dependency. It should be be declared as an **optional** peer dependency. Same for `webpack-dev-server`:

```json
{
  "peerDependencies": {
    "@webpack-cli/serve": "*",
    "webpack-dev-server": "*"
  },
  "peerDependenciesMeta": {
    "@webpack-cli/serve": {
      "optional": true
    },
    "webpack-dev-server": {
      "optional": true
    }
  }
}
```

**Additional context**

Similar work for `webpack-dev-server`: https://github.com/webpack/webpack-dev-server/pull/2191 (but not enough as next major version will not include the webpack-dev-server binary, and we will have to use webpack-cli)

Optional peer dependencies RFC: https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md

**Comment by evenstensberg** [comment]
Yep we can do that, will need for https://github.com/webpack/webpack-cli/pull/1011 to land then we can fix this.

**Comment by evenstensberg** [comment]
@Loonride could you pick this up? Would greatly appreciate it and we really need it.

CC @evilebottnawi

**Comment by Loonride** [comment]
> @Loonride could you pick this up? Would greatly appreciate it and we really need it.
> 
> CC @evilebottnawi

@evenstensberg I already added `webpack-dev-server` as optional peer dependency here: https://github.com/webpack/webpack-cli/blob/181822ffc78de8fc5dd3ba14db9def961316bd05/packages/serve/package.json#L26-L33

Do we need this for all the packages (serve, init, etc.)?

**Comment by evilebottnawi** [comment]
What `@webpack-cli/serve` is it?

**Comment by evilebottnawi** [comment]
For `webpack-dev-server` all solved

**Comment by evilebottnawi** [comment]
@evenstensberg you should install `@webpack-cli/serve` for using `webpack serve`?

**Comment by evilebottnawi** [comment]
Look at the others CLI programs, no one forces you to install additional modules for basic work
