### ISSUE TITLE
"errors-warnings" stats preset not supported

### ISSUE THREAD

**Issue by yellowjello** [webpack/webpack-cli#1094]
**Describe the bug**

Webpack currently provides an `errors-warnings` stats preset that outputs only errors and warnings on build, but `webpack-cli` does not support that preset as an argument to `--display` yet.

**What is the current behavior?**

Outputs:
```
Invalid values:
  Argument: display, Given: "errors-warnings", Choices: "", "verbose", "detailed", "normal", "minimal", "errors-only", "none"
```

**To Reproduce**
1. Run `npx webpack --display errors-warnings`

**Expected behavior**
Builds with the `errors-warnings` stats preset.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
```
  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 67.0.4
    Safari: 13.0.2
  npmPackages:
    clean-webpack-plugin: ^0.1.19 => 0.1.19
    copy-webpack-plugin: ^5.0.4 => 5.0.4
    fork-ts-checker-webpack-plugin: ^1.5.0 => 1.5.0
    moment-locales-webpack-plugin: ^1.1.0 => 1.1.0
    webpack: ^4.41.0 => 4.41.0
    webpack-cli: ^3.3.9 => 3.3.9
    webpack-fix-style-only-entries: ^0.4.0 => 0.4.0
```

**Comment by evenstensberg** [comment]
As we're developing the new CLI, I don't think that this is going to be fixed. Thanks for reporting, if it's causing you any trouble, you can edit stats directly through a configuration file meanwhile! 

https://webpack.js.org/configuration/stats/#stats
