### ISSUE TITLE
[Feature Request]: --no-cache flag for webpack@5

### ISSUE THREAD

**Issue by Andarist** [webpack/webpack-cli#1095]
**Is your feature request related to a problem? Please describe.**
I often (well, from time to time) find myself editing node_modules by hand to debug a particular problem with some dependency. And webpack@5 with its persistent caching might make this process rather difficult - because it would require changing a config.

Actually you already have `--cache=false` here, but I'm not sure if this right now can disable persistent caching and Tobias has kinda redirected me to here with this feature request. If this is already handled - then sorry for reporting and feel free to close this.

**Describe the solution you'd like**
a special CLI flag that would disable persistent caching for a current build

**Describe alternatives you've considered**
n/a

**Additional context**
https://github.com/webpack/webpack/issues/9802#issuecomment-541089703

**Comment by anikethsaha** [comment]
This is actually good if it's not present already! It will be too handy for the user to use it from CLI
I don't think right now the persistent caching flag is there. Is it @evenstensberg?
But as far as the webpack@5 is concerned, I guess we can wait for the major release as that is currently in beta, and then it can be added in the CLI. What do you think?

**Comment by evenstensberg** [comment]
We can add the cache flag for the new cli

**Comment by Andarist** [comment]
Would be great to at least prepare a PR for this before webpack@5 hits stable, but please do whatever you see most appropriate here

**Comment by evenstensberg** [comment]
Can do both

**Comment by evenstensberg** [comment]
Fixed https://github.com/webpack/webpack-cli/releases/tag/v3.3.10
