### ISSUE TITLE
[bug generate-loader  v0.1.8]: webpack generate-loader command error

### ISSUE THREAD

**Issue by zhouzhiqiangzzq** [webpack/webpack-cli#1104]
**Describe the bug**

I  init a project ,then install webpack ,config like below 

` 
"devDependencies": {
    "@webpack-cli/generate-loader": "^0.1.8",
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.9"
}
`

then use command 'webpack generate-loader' , get a error 

`
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: path/to/my-loader/node_modules/@webpack-cli/generate-loader/test/fixtures/simple-file.js.tpl
`

**To Reproduce**
1、mkdir my-loader
2、cd  my-loader  && yarn init
3、yarn add webpack-cli webpack -D 
4、webpack  generate-loader 
5、use default set and confirm
6、get error

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
` 
npmPackages:
    webpack: ^4.41.2 => 4.41.2 
    webpack-cli: ^3.3.9 => 3.3.9 
`

**Comment by rishabh3112** [comment]
@zhouzhiqiangzzq with webpack-cli v4, you have to use `webpack loader` instead of `webpack generate-loader`.

**Comment by evenstensberg** [comment]
This is using the old cli @rishabh3112 , non-related
