### ISSUE TITLE
[QUESTION]: Running `webpack` always gives an error, saying that you need to install `webpack-cli` but I have already installed it.

### ISSUE THREAD

**Issue by d1y** [webpack/webpack-cli#1106]
**Describe the bug**

I installed `webpack` globally and used `webpack-cli` as a `devDependencies`

the `package.json`

```jsonc
{
  "devDependencies": {
    "ts-loader": "^6.2.1",
    "typescript": "^3.6.4",
    "webpack-cli": "^3.3.10"
  }
}
```

**To Reproduce**

init project

```
npm init -y
// I use cnpm (from china)
cnpm i -D typescript
cnpm i -D webpack
cnpm i -D ts-loader
```

add `webpack.config.js`

```js

const path = require('path');

module.exports = {
  entry: './src/index.ts',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  }
};

```

`webpack` is globaled

```
sudo cnpm i -g webpack
```

run: `webpack`, Please take a look at the screenshot below, obviously I have already installed it...

**Screenshots**

I have used `npm i -D`, and also use `cnpm i -D` for insurance, but every time I run `webpack` I will need to install `webpack-cli`.

![image](https://user-images.githubusercontent.com/45585937/68096732-c3f79e00-feed-11e9-8489-423f1e5d79d1.png)

`webpack-cli info` is not found, Because it is not installed on the whole, is it?

我有一个疑惑, 为什么 `webpack-cli` 不能安装全局? 每个项目都要重新安装一次依赖, 这个设计很不明智(也可能是我的操作问题, 我不知道)

I have a doubt, why can't `webpack-cli` install globally? Every project has to re-install dependencies. This design is not wise (maybe my operation problem, I don't know)

希望解答一下, 谢谢

I hope to answer, thank you.

**Comment by evenstensberg** [comment]
Don't install webpack globally, have both dependencies locally. Does that help you?

**Comment by d1y** [comment]
> Don't install webpack globally, have both dependencies locally. Does that help you?

Yes. I set it to -save, it really works, but I am confused, why can't I install it `global` , can I have this dependency on a project, I have to have `-save`, so the file will be very big, This design is stupid :3

**Comment by ematipico** [comment]
The common choice is to have all the deps inside the project. Having `webpack` globally is a case we don't handle.
