### ISSUE TITLE
[Question]: Eslint config not found

### ISSUE THREAD

**Issue by yovanoc** [webpack/webpack-cli#1110]
**Describe the bug**

When I'm trying to `yarn lint` in my project (yarn worksapces, monorepo) there is an eslint config which doesn't find another to extend to in the bin folder of webpack-cli.

**Expected behavior**
Should lint my project without errors.

**Screenshots**
<img width="1288" alt="Screen Shot 2019-11-09 at 8 25 35 AM" src="https://user-images.githubusercontent.com/7302317/68524752-bc0f7380-02ca-11ea-8377-4248789377e4.png">

Doesn't work with `^3.3.10` but with `4.0.0-alpha-5` we have this error:

`✖ ｢webpack｣:  ReferenceError: getConfigExtension is not defined`

**Comment by ematipico** [comment]
Quick question: why your project is extending webpack-cli eslint?

**Comment by yovanoc** [comment]
That's all the trouble! It does not extend it

**Comment by ematipico** [comment]
Did you set `"root": true` inside your eslint configuration file?

**Comment by yovanoc** [comment]
I checked true or false, doesn't change anything

**Comment by ematipico** [comment]
I don't think this is related to this project but if you can share your project, it might be easier to debug.

**Comment by yovanoc** [comment]
I'ts a private enterprise project so hard :/ but it can be an eslint issue then? all was perfectly fine until now but we are upgrading versions often

**Comment by yovanoc** [comment]
Oh I just found the problem. He has a really simple solution. We don't have to lint node_modules things, so just put node_modules in the .eslintignore solve this issue.
