### ISSUE TITLE
[Question]: library-target is an array and should be a string or object.

### ISSUE THREAD

**Issue by scottnicolson** [webpack/webpack-cli#1113]
the latest webpack-cli release 3.3.10 does not play well with webpack@4.41.2 when configured to output an amd library target.
The following error is thrown by webpack `library name must be a string for amd target`.

This issue seems to be introduced by issue #557.  Current webpack documentation states only string and object are valid. https://webpack.js.org/configuration/output/#outputlibrary

Can #557 be reverted? or am I missing something?  Sorry I don't know the history behind this change.

**Comment by evenstensberg** [comment]
I don't remember, but you can declare that in your configuration file instead?

**Comment by scottnicolson** [comment]
correct, you can declare it in the configuration file.  however i dont as i use standard webpack config for most of my projects and instead prefer to pass in the library-name on the command line.  

Setting the library as an array is not supported, so can we not change it back to a string?  

This arg switches for --output-library and --output-library-target should be correct when --output-library-target is set to amd.  I am happy to submit a PR.

**Comment by evenstensberg** [comment]
We're not actively maintaining the v3 release line anymore

**Comment by scottnicolson** [comment]
Oh that is a shame.  is the next version far away?

**Comment by evenstensberg** [comment]
We're collecting feedback and iterating now

**Comment by evilebottnawi** [comment]
bump

**Comment by evilebottnawi** [comment]
Need a test

**Comment by evilebottnawi** [comment]
Tests added for webpack@5
