### ISSUE TITLE
[BUG]: core cli-flags exported twice

### ISSUE THREAD

**Issue by godcrampy** [webpack/webpack-cli#1114]
**Describe the bug**

In the `libs/utils/cli-flags.js`, the exported object contains the core key twice [here](https://github.com/webpack/webpack-cli/blob/next/lib/utils/cli-flags.js#L113) and [here](https://github.com/webpack/webpack-cli/blob/next/lib/utils/cli-flags.js#L255).

**What is the current behavior?**

As a result, only the later defined `core` key value pair is exported. Both the values of the `core` keys are arrays which are about 80% similar to each other.

**Comment by evenstensberg** [comment]
They're not exported twice I think, it's 2 different configurations that needs to be parsed differently by cmd-line-args

**Comment by godcrampy** [comment]
A recent change removed this bug.
