### ISSUE TITLE
[BUG]: webpack-cli@4.0.0-beta.1 no longer supports function-export-based webpack.config.js

### ISSUE THREAD

**Issue by wood1986** [webpack/webpack-cli#1126]
**Describe the bug**

When my webpack.config.js is exporting a function instead of a simple object. Webpack won't recognize my config anymore. I have checked your test case on your next branch and I do not see any webpack.config.js which is exporting a function. When I export an object, it works Are you work in progress? Or Will you deprecate that kind of export?

**What is the current behavior?**

See the previous

**To Reproduce**

use this webpack.config.js
```js
module.exports = (env, argv) => {
  return {
    "entry": {
      "web.index": path.resolve(__dirname, "src", "web.index.jsx")
    },
    "output": {
      "filename": `[name].${argv.mode}.[chunkhash].js`,
      "libraryTarget": "umd",
      "path": path.resolve(__dirname, "dist")
    }
  }
}
```

and then run
```
webpack-cli --config=./webpack.config.js
```

**Expected behavior**
/

**Screenshots**
/

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

webpack: next
webpack-cli: 4.0.0-beta.1
node: 13.1.0
OS: macOS 10.15.1

**Additional context**
/

**Comment by wood1986** [comment]
+ @TheLarkInn

**Comment by TheLarkInn** [comment]
cc @evenstensberg this is considered a release-blocking bug.

**Comment by evenstensberg** [comment]
Considered!

**Comment by evenstensberg** [comment]
Thx for your bug report @wood1986 , appreciate you putting in the time ❤️

**Comment by wood1986** [comment]
I have one more request. webpack-cli 3 has a private function https://github.com/webpack/webpack-cli/blob/f9f08604a1ce5272b20d4f942e6861f3dc170dc0/bin/cli.js#L125 to convert function-export-base to the real object. I want to reuse but it is not exposed. In webpack-cli 4, is it possible to expose that?

**Comment by evenstensberg** [comment]
I think that the edit needs to be done here:

https://github.com/webpack/webpack-cli/blob/next/lib/groups/config.js#L86-L88

**Comment by anikethsaha** [comment]
Not sure why this bug is happening but the tests seems fine and passing for config type function

https://github.com/webpack/webpack-cli/tree/next/test/config/type/function

![Screenshot_2019-11-27-15-09-17-544_com android chrome](https://user-images.githubusercontent.com/26347874/69712032-1eb89a00-1128-11ea-9ff1-d9df1105c074.jpg)

**Comment by ematipico** [comment]
Is it fixed with latest beta?

**Comment by anshumanv** [comment]
Done @evilebottnawi 👍
