### ISSUE TITLE
Stats.preset is an unknown property @4.41.2 

### ISSUE THREAD

**Issue by isitgeorge** [webpack/webpack-cli#1128]
**Describe the bug**

According to the docs at https://webpack.js.org/configuration/stats/#extending-stats-behaviours I'm able to specify a preset stat and then extend/overwrite with other options. However the latest normal release @4.41.2 suggests this is an unexpected property.

```
module.exports = {
  //..
  stats: {
    preset: 'minimal',
    moduleTrace: true,
    errorDetails: true
  }
};
```

**What is the current behavior?**

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].stats has an unknown property 'preset'. These properties are valid:
   object { all?, assets?, assetsSort?, builtAt?, cached?, cachedAssets?, children?, chunkGroups?, chunkModules?, chunkOrigins?, chunks?, chunksSort?, colors?, context?, depth?, entrypoints?, env?, errorDetails?, errors?, exclude?, excludeAssets?, excludeModules?, hash?, logging?, loggingDebug?, loggingTrace?, maxModules?, moduleAssets?, moduleTrace?, modules?, modulesSort?, nestedModules?, optimizationBailout?, outputPath?, performance?, providedExports?, publicPath?, reasons?, source?, timings?, usedExports?, version?, warnings?, warningsFilter? }

```

**To Reproduce**
Execute `webpack` with the above configuration

**Expected behavior**
No invalid configuration warning

**Additional context**
I've dug around in the docs Git repo and can see that particular feature was only updated 13 days ago, but couldn't see any applicable versions, so I'm assuming it's the latest general release. Perhaps I'm wrong.

Thanks!

**Comment by rishabh3112** [comment]
@isitgeorge please share `webpack-cli` version and also share a minimum reproducible repository.

**Comment by isitgeorge** [comment]
@rishabh3112 
```
➜  ~ webpack-cli --version     
3.3.10
➜  ~ webpack --version
4.41.2
```

The minimum reproducible is a `webpack.config.json` consisting of just
```
module.exports = {
  stats: {
    preset: 'minimal',
    moduleTrace: true,
    errorDetails: true
  }
}
```

`➜  ~ webpack` and you will get `- configuration[0].stats has an unknown property 'preset'.`

Thanks!

**Comment by rishabh3112** [comment]
Hi @isitgeorge, I looked and it isn't a problem with `webpack-cli` package, configuration was ill structured as per v4.41.2.
`preset` is meant to be passed directly:
```js
module.exports = {
    stats: 'minimal'
}
```
For further info checkout https://v4.webpack.js.org/configuration/stats/
Hope that solves your issue !

**Comment by isitgeorge** [comment]
Hi @rishabh3112,

Thanks for the reply, that does solve things.

I imagine this is an issue with the docs then if the ability to extend presets via `stats.preset` isn't available in the current stable version? The v4 docs you linked make sense.

Cheers

**Comment by rishabh3112** [comment]
> I imagine this is an issue with the docs then if the ability to extend presets via stats.preset isn't available in the current stable version?

Yup, main site contains some changes corresponding to webpack v5 ( which is in beta ).

**Comment by isitgeorge** [comment]
Sweet, thanks for your help!
