### ISSUE TITLE
NPX WEBPACK-CLI INIT

### ISSUE THREAD

**Issue by r00nscapenab** [webpack/webpack-cli#1129]
version 0.3.0
when I run 
`npx webpack-cli init`
it returns "init isn't a valid name. It should be prefixed with 'webpack-scaffold', but have different suffix.

**Comment by rishabh3112** [comment]
@r00nscapenab 
If you want to use `webpack-cli` v3, please downgrade `@webpack-cli/init` to version `0.2.2`.
If you want to use `webpack-cli` v4(beta) (which would be nice), use following commands after installing `webpack-cli@beta`
```
npx webpack-cli create
```

**Comment by ParrotStone** [comment]
If I wanted to use `webpack-cli` v4(beta), what version of `@webpack-cli/init` should I use?
Currently, I have the same issue with `webpack-cli` v3.3.10 and `@webpack-cli/init@0.3.0`

**Comment by Legends** [comment]
@rishabh3112 

When I run: `npx webpack-cli create --auto`

I get:

> ERROR in Entry module not found: Error: Can't resolve 'create' in 'D:\SystemFolders\....'

My entry module is `src/index.js`?!

```
 "devDependencies": {
    "@webpack-cli/init": "^0.3.0",
    "babel-loader": "^8.0.6",
    "webpack": "^4.41.5",
    "webpack-cli": "^3.3.10"
  },
```

**Comment by lihas** [comment]
> @rishabh3112
> 
> When I run: `npx webpack-cli create --auto`
> 
> I get:
> 
> > ERROR in Entry module not found: Error: Can't resolve 'create' in 'D:\SystemFolders....'
> 
> My entry module is `src/index.js`?!
> 
> ```
>  "devDependencies": {
>     "@webpack-cli/init": "^0.3.0",
>     "babel-loader": "^8.0.6",
>     "webpack": "^4.41.5",
>     "webpack-cli": "^3.3.10"
>   },
> ```

I hade to run `npm install webpack-cli@beta`

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack-cli/issues/1127
