### ISSUE TITLE
[Bug]: merge config not working

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack-cli#1136]
**Describe the bug**
Merging config not working.
A 💯 way to do this is to provide your configuration via a GitHub gist and/or to use markdown when describing which commands you used when the error occurred! Be precise and clear in your description of the bug.

**What is the current behavior?**
Now working
This is where you elaborate on the current behavior of the cli, how it behaves normally differing from the previous version/build you did. 

**Expected behavior**
Return a new merged config file.

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
Add any other context about the problem here like linking to an similar issue you might think is the cause.

**Comment by niravasher** [comment]
Merging two config files
Let's say I have 3 files - webpack.config.js, webpack.dev.js and webpack.prod.js
In webpack.dev.js environment is production and in webpack.prod.js environment is production
webpack.config.js has loaders and plugins while the other two files don't.
Hence to include the loader and plugin functionality from webpack.config.js we merge all the three by using a package `webpack merge` which can be installed by `npm i --save-dev webpack-merge`
This functionality has to be included in the webpack-cli
Am I right? @pranshuchittora ? I would like to work on this issue.

**Comment by ematipico** [comment]
No information have been provided so it's impossible to understand what's the issue. Please open a new issue and follow the template, so we can follow up the issue!
