### ISSUE TITLE
[ref]: use enum instead of direct string comparison

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#1138]
**Do you want to request a *feature* or report a *bug*?**
We're using string comparison in bootstrap.js (will take a look at other files as well later), which can lead to bugs due to possible typos in future, use enums to stick to standard errs.

**What is the current behavior?**
Need refactor

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Define enums and use switch to pick the appropriate err.

**If this is a feature request, what is motivation or use case for changing the behavior?**
more maintainable code

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**

**Comment by ematipico** [comment]
Closing the issue as it doesn't bring enough value to the code
