### ISSUE TITLE
webpack-cli doesn't work with config file authored in typescript

### ISSUE THREAD

**Issue by smashercosmo** [webpack/webpack-cli#1144]
**What is the current behavior?**
Webpack-cli doesn't work with config file authored in typescript. Following this recipe
 https://webpack.js.org/configuration/configuration-languages/#typescript result in an error
```
(function (exports, require, module, __filename, __dirname) { import webpack from 'webpack'
                                                                     ^^^^^^^

SyntaxError: Unexpected identifier
```

**To Reproduce**
https://github.com/smashercosmo/webpack-ts-config-issue
run: 
```
npm i
npm run build
```

**Expected behavior**
webpack-cli should work with config file authored in typescript

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

  System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 89.48 MB / 16.00 GB
  Binaries:
    Node: 11.15.0 - /usr/local/bin/node
    Yarn: 1.10.1 - ~/.yarn/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 71.0
    Safari: 12.0
  npmPackages:
    webpack: 4.41.2 => 4.41.2 
    webpack-cli: 3.3.10 => 3.3.10

**Comment by rishabh3112** [comment]
Hi @smashercosmo Thanks for opening issue with awesome details.
You didn't include `"allowSyntheticDefaultImports"` option in your `tsconfig.json`.

Here is the minimal solution to your issue https://github.com/rishabh3112/issues/tree/master/cli%231144

![image](https://user-images.githubusercontent.com/15812317/70812367-7ffd9000-1ded-11ea-8a45-c5cbe5d3da29.png)

**Comment by smashercosmo** [comment]
@rishabh3112 I added allowSyntheticDefaultImports to my tsconfig.json. I didn't fix the issue. https://github.com/smashercosmo/webpack-ts-config-issue/commit/02130e0de5aa9500da632e8d7ca788b16a5590a2

**Comment by rishabh3112** [comment]
@smashercosmo Have you tried up the repository with the solution I provided above ? Let me if that also isn't solving the issue for you.

**Comment by rishabh3112** [comment]
Also try using `cross-env` as suggested by the documentation.
https://github.com/smashercosmo/webpack-ts-config-issue/blob/02130e0de5aa9500da632e8d7ca788b16a5590a2/package.json#L7

**Comment by smashercosmo** [comment]
Turned out that I forgot to install typescript 🤦‍♂️🤦‍♂️🤦‍♂️
thx @rishabh3112
