### ISSUE TITLE
[Documentation]: Migration guide for version 4

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack-cli#1154]
**Do you want to request a *feature* or report a *bug*?**

A Documentation update

**What is the current behavior?**
webpack-cli v4 breaking changes are not known to users

**If the current behavior is a bug, please provide the steps to reproduce.**

N/A

**What is the expected behavior?**
A migration guide

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**
N/A

**Comment by anshumanv** [comment]
Please also list down all the docs that need migration so it can be done incrementally.

**Comment by rishabh3112** [comment]
@anshumanv have a look at commit history for these changes.

**Comment by evilebottnawi** [comment]
bump

**Comment by JulianMar** [comment]
Does anyone actually know all the breaking changes, as far as I can tell there are alot.

I just tried to migrate to v4 but my setup isn't working anymore. My command is now outputing the name always as `main.js` instead of `output.js`.
```
webpack /assets/js/integration.js -o /static/js/output.js --mode development --module-bind js=babel-loader
```

This is huge change and should be documented somewhere :)

**Comment by snitin315** [comment]
@JulianMar now `-o` is an alias for `--output-path` and `--module-bind` is not supported anymore. As per my understanding, your command should be updated as - 

`webpack /assets/js/integration.js --output-path /static/js --output-filename output.js --mode development`

**Comment by JulianMar** [comment]
Thanks for the quick reply, if I do it like you suggested. I get the following error

```
ERROR in multi ./assets/js/integration.js output.js
Module not found: Error: Can't resolve 'output.js' in '/Volumes/Projects/frontend'
 @ multi ./assets/js/integration.js output.js main[1]
```

**Comment by alexander-akait** [comment]
Docs was updated, anyway feel free to feedback

**Comment by likerRr** [comment]
@alexander-akait can you add a link to upgrade guide? Can't find any breaking changes in a [changelog](https://github.com/webpack/webpack-cli/blob/master/CHANGELOG.md#400-2020-10-10)
