### ISSUE TITLE
support `webpack.config.cjs` by default

### ISSUE THREAD

**Issue by xiaoxiangmoe** [webpack/webpack-cli#1165]
> If a webpack.config.js is present, the webpack command picks it up by default. We use the --config option here only to show that you can pass a config of any name. This will be useful for more complex configurations that need to be split into multiple files.

We should also pick it up when a `webpack.config.cjs` is present

**Comment by ematipico** [comment]
This requires a minimum of node right?

**Comment by xiaoxiangmoe** [comment]
No, we can just regard cjs as js

**Comment by smelukov** [comment]
Seems like we can't just support it - https://github.com/gulpjs/interpret/issues/65

**Comment by ExE-Boss** [comment]
Actually, you can, as `.cjs` can be used anywhere a `.js` file can be used currently.

**Comment by Parikshit-Hooda** [comment]
Hi. Can I take up this issue? @ematipico

**Comment by Parikshit-Hooda** [comment]
Hi. I have made some changes, how do I test that the changes resolve the issue?
Specifically, I have made changes to the 'packages/webpack-cli/lib/groups/configGroup.js' file to include support for '.cjs' file. Thanks.

**Comment by snitin315** [comment]
>  how do I test that the changes resolve the issue

@Parikshit-Hooda As this is a new feature you are implementing you have to write your own tests.

Also, you can run the current tests with `yarn test`

**Comment by Parikshit-Hooda** [comment]
@snitin315 Actually, I want to confirm if the feature addition actually fixes this issue or not? I imagine that the modified repo(fixed webpack-cli) will need to be imported in a dummy project and check. How do I go about checking this?

**Comment by snitin315** [comment]
you can use `npm link` or `yarn link`

**Comment by Parikshit-Hooda** [comment]
Haven't done this kind of an activity before. Can you please elaborate or tell me what exactly should I google?

**Comment by anshumanv** [comment]
> Haven't done this kind of an activity before. Can you please elaborate or tell me what exactly should I google?


You need to run your changes locally, https://docs.npmjs.com/cli/link.html
 Link the package and try to run with a .cjs config file then write tests for it.

**Comment by Parikshit-Hooda** [comment]
Question: Should I link [the repo after following the contributing.md and making edits](https://github.com/webpack/webpack-cli/blob/next/.github/CONTRIBUTING.md) or without following the instructions in CONTRIBUTING.md. I am asking because I am not sure if going through yarn install ->bootstrap -> build causes some unrequired changes.

**Comment by anshumanv** [comment]
> build causes some unrequired changes.

What are the unrequired changes? 

Yep please install, bootstrap, build then link the webpack-cli package in the packages folder.

Then you need to `npm link webpack-cli`  in a folder, that folder will then use the local code that you have.

**Comment by Parikshit-Hooda** [comment]
![Capture](https://user-images.githubusercontent.com/25405707/76750838-e86d5c00-67a4-11ea-9630-7100cf306461.PNG)
After linking it, its still requiring me to 'npm install webpack-cli' to run the npm run build. What am I doing wrong?

**Comment by anshumanv** [comment]
Invoke using `webpack-cli`, after you run `npm link webpack-cli` in your test folder.

**Comment by Parikshit-Hooda** [comment]
Doesn't seem to work.
`$ webpack-cli --entry src/index.js --config webpack.config.cjs` 
`bash: webpack-cli: command not found `

**Comment by anshumanv** [comment]
You didn't symlink properly then.

**Comment by Parikshit-Hooda** [comment]
got it. will raise a PR in a couple of days.

**Comment by Parikshit-Hooda** [comment]
Alternative solution: wondering if replacing the extension '.cjs' with '.js' is a better solution?

**Comment by ExE-Boss** [comment]
`.js` is parsed as an **ECMAScript** module [when `package.json` has `type: "module"` specified](https://nodejs.org/api/esm.html#esm_package_json_type_field).

`.cjs` is always parsed as a **CommonJS** module, which is the only module format which **webpack** supports for its configuration files.

**Comment by anshumanv** [comment]
^
+
> Alternative solution: wondering if replacing the extension '.cjs' with '.js' is a better solution?

Nope, as stated above they are interpreted differently, so not a good solution.

**Comment by Thomazella** [comment]
> `.js` is parsed as an **ECMAScript** module [when `package.json` has `type: "module"` specified](https://nodejs.org/api/esm.html#esm_package_json_type_field).
> 
> `.cjs` is always parsed as a **CommonJS** module, which is the only module format which **webpack** currently supports for its configuration files.

Hey yall. Is it currently planned to support esm for config files? I guess it would raise the minimum node version way to high right?
