### ISSUE TITLE
TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by rostaryms** [webpack/webpack-cli#1185]
I'm getting an error on my command prompt when I type 'npm run dev'.

This is the first time I've tried to type in npm run dev, so the error has been happening from the beginning.

To reproduce this error I just type in 'npm run dev' into the command prompt.

I expect typing in npm run dev to create a bundle.js file in the file folder I'm currently in.

![JS_Error](https://user-images.githubusercontent.com/56840832/72912212-4b90c400-3d09-11ea-8261-52d564061f30.png)

I'm not sure what webpack cli info is.

The context of this error is that I'm watching a paid for online video tutorial from udemy.

If you need any more info let me know.

Thanks for the help!

**Comment by ematipico** [comment]
@rostaryms  please next time do not remove the template or we'd need to close the issue.
Could you please fill the original template and provide a repo to reproduce (config file, version of webpack and webpack cli).

**Comment by rishabh3112** [comment]
Replying to your doubt,
> I'm not sure what webpack cli info is.

`@webpack-cli/info` is a npm package that outputs versions of `webpack` and `webpack-cli`. If you don't feel like installing it, please attach output of following commands.
```
npx webpack --version
```
Also we need minimum reproducible repository as @ematipico suggested to work on the issue.

**Comment by rostaryms** [comment]
> @rostaryms please next time do not remove the template or we'd need to close the issue.
> Could you please fill the original template and provide a repo to reproduce (config file, version of webpack and webpack cli). I think this is a problem with your webpack config file

Yes next time I can keep the template paragraphs within the issue post, sure.

As for providing a repo to reproduce, a config file, a version of webpack, and webpack cli, I'm not sure how to show those things. I'll have to do some research before I can provide that for you. Let me try now.

**Comment by ematipico** [comment]
It's really difficult to debug your issue without having a repository to reproduce the issue and without config file.

**Comment by ematipico** [comment]
Closing. Feel free to open a new issue one you have a repo.

**Comment by danlafreniere** [comment]
Late to the party but having a more up-to-date webpack-cli `npm install webpack-cli@3 --save-dev` worked for me. I also updated xcode (unsure if related but here you go: https://stackoverflow.com/questions/34617452/how-to-update-xcode-from-command-line).

**Comment by Zeesy** [comment]
Also in the Udemy course, MacOS 10.14. With @ danlafreniere's suggestion to update, I'm still unable to run `npm run dev` and am receiving new error messages. Specifically:

```
Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: 7b2687bf27424b83f3d2
Version: webpack 4.44.2
Time: 36ms
Built at: 10/25/2020 3:40:31 PM

ERROR in Entry module not found: Error: Can't resolve './src/js/index.js' in '/Users/Zeesy/Documents/EDUCATION/complete-javascript-course-master/9-forkify'
npm ERR! code 2
npm ERR! path /Users/Zeesy/Documents/EDUCATION/complete-javascript-course-master/9-forkify
npm ERR! command failed
npm ERR! command sh -c webpack
```
Log attached here 🤷‍♂️

[2020-10-25T19_40_31_636Z-debug.log](https://github.com/webpack/webpack-cli/files/5435817/2020-10-25T19_40_31_636Z-debug.log)

**Comment by TonisPiip** [comment]
> Late to the party but I'm in the same course and encountered a similar issue. Having a more up-to-date webpack-cli npm install webpack-cli@3 --save-dev worked for me.

I was trying to run a random older project from GH and got this same error.  
Unsure why / how this comment was minified,  but this worked for me too, I can't give a :+1: to it  for some reason so making this comment.
