### ISSUE TITLE
@webpack-cli/utils should move jest to devDependencies

### ISSUE THREAD

**Issue by ankurk91** [webpack/webpack-cli#1190]
Hi,

I was trying to install `webpack-cli@4.0.0-beta.1` and found out it also installs `jest`.
Why i run command `yarn why jest`, i found the package `@webpack-cli/utils` is installing `jest`.

This package should be moved to `devDependencies`

https://github.com/webpack/webpack-cli/blob/aa6d82b649c9a1f4c54566b80597576d9bb554b4/packages/utils/package.json#L18

### Steps to re-produce
* `yarn add webpack-cli@4.0.0-beta.1`
* Run `yarn why jest`
* You will find `jest` was installed by `@webpack-cli/utils` package.

Another finding :
The package.json has exact versions, it can be relaxed to have `^`.

**Comment by anshumanv** [comment]
> Why i run command yarn why jest, i found the package @webpack-cli/utils is installing jest.

Certainly doesn't belong there, can you PR?

> The package.json has exact versions, it can be relaxed to have ^.

It is intentional.
