### ISSUE TITLE
Donations message frequency check should handle EPERM

### ISSUE THREAD

**Issue by tathougies** [webpack/webpack-cli#1202]
**Do you want to request a *feature* or report a *bug*?**

feature?

**What is the current behavior?**

webpack-cli uses utime to determine when to show a donations message. This means webpack-cli is unusable with package managers like nix: https://hydra.intrustd.com/build/1399/nixlog/3

**If the current behavior is a bug, please provide the steps to reproduce.**

Use webpack in a nix build on Monday. Webpack-cli will fail because it attempts to use utime() on a nix file system path, which results in EPERM.

**What is the expected behavior?**

There should be no failure.

**If this is a feature request, what is motivation or use case for changing the behavior?**

I understand you want to ask for donations, but this shouldn't cause the compiler to crash when the check fails. I think it would be sufficient to handle EPERM, and if you can't run your check, display the donations message anyways. That way, you win by having your message displayed (and in my log file forever, for posterity's sake), and I win by not having failing builds.

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**

This is with webpack-cli 3.3.10.

**Comment by evilebottnawi** [comment]
We remove donation message in favor `func` field for v4, so let's close, also can't reproduce with v3
