### ISSUE TITLE
[create]: Unable to invoke create package

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#1208]
**Describe the bug**

No longer able to invoke the create package from the cli

**What is the current behavior?**

Command errors out.

**To Reproduce**
`webpack-cli create`

**Expected behavior**
The command should function properly

**Screenshots**
![image](https://user-images.githubusercontent.com/21009455/73965543-633b8f80-493a-11ea-9b29-8292be37c2d9.png)

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by anshumanv** [comment]
Fix is in https://github.com/webpack/webpack-cli/pull/1201

**Comment by rishabh3112** [comment]
Resolved in #1201
