### ISSUE TITLE
Suggest matching arguments if the user mistypes

### ISSUE THREAD

**Issue by jamesgeorge007** [webpack/webpack-cli#1210]
**Is your feature request related to a problem? Please describe.**
Say the user makes a typo, `webpack-cli --confgi` as of now he'll be greeted with a warning such that the respective argument is not recognized.

**Describe the solution you'd like**
Suggest the nearest matching argument.

**Describe alternatives you've considered**
Levenshtein distance algorithm.

**Additional context**
![Screenshot from 2020-02-08 21-58-42](https://user-images.githubusercontent.com/25279263/74088611-3e702500-4abe-11ea-9a2f-f9c30c5c08ac.png)

**Comment by ematipico** [comment]
What about cases of multiple argument that are mistyped or multiple arguments just one is mistyped? How would that work?

**Comment by anshumanv** [comment]
To what extent are we checking that a flag is a mistype and matches some arg/flag? How is the diff of closest matching flag evaluated?

**Comment by rishabh3112** [comment]
I feel that a warning for wrong arguments is enough.

P.S.
> To what extent are we checking that a flag is a mistype and matches some arg/flag? How is the diff of closest matching flag evaluated?

Using https://en.wikipedia.org/wiki/Levenshtein_distance

**Comment by jamesgeorge007** [comment]
> What about cases of multiple argument that are mistyped or providing multiple arguments and just one is mistyped? How would that work?

We're just taking the very first argument into account.

**Comment by jamesgeorge007** [comment]
> I feel that a warning for wrong arguments is enough.

This is essentially an addition on top of what we already have onboard. Getting suggestions is definitely gonna add to the UX.

**Comment by anshumanv** [comment]
> Using https://en.wikipedia.org/wiki/Levenshtein_distance

Saw the repo. 👍 

I think showing help with warning in case any invalid flag is supplied is sufficient feedback. https://github.com/webpack/webpack-cli/pull/1051

**Comment by ematipico** [comment]
How would that work with alias?

**Comment by jamesgeorge007** [comment]
As of now it just checks for the fully qualified flag names. (Since, the distance specified is < 3)

**Comment by jamesgeorge007** [comment]
As of now it just checks for the fully qualified flag names ignoring aliases. #1211

**Comment by ematipico** [comment]
> We're just taking the very first argument into account

Which is not ideal. If user passes a series of parameters and the last one is wrong, the feature would fail

**Comment by jamesgeorge007** [comment]
In-fact the very first unknown argument.

**Comment by jamesgeorge007** [comment]
closing in regard to #1255
