### ISSUE TITLE
v4.0.0-beta.2 module error

### ISSUE THREAD

**Issue by pierredarrieutort** [webpack/webpack-cli#1215]
I've just install the last version of the package and at the build command :
`npx webpack -p` it returns me the following error about the 'production_config' module

![image](https://user-images.githubusercontent.com/25182438/74231609-451db880-4cc7-11ea-9225-53a0a43b0a47.png)

How can it will be fixed ?

**Comment by rishabh3112** [comment]
Hi @pierredarrieutort!
Can you share a minimum reproducible repository that has this issue for us to investigate?

**Comment by pierredarrieutort** [comment]
Here it is :https://github.com/pierredarrieutort/Jape/tree/min_repro_repo
