### ISSUE TITLE
Unknown argument: --env

### ISSUE THREAD

**Issue by Namchee** [webpack/webpack-cli#1216]
**Describe the bug**

I'm trying to set my webpack `env` for configuration purposes with

```
webpack --env.platform=node
```

But, `webpack-cli` keeps throwing `⬢ webpack: Unknown argument: --env` error to me

**What is the current behavior?**

`webpack-cli` refuses to read the flag and throw an error instead 

**To Reproduce**

Just try to add `--env` flag to any `webpack` command.

**Expected behavior**

`webpack-cli` should accept and set this variable correctly

**Screenshots**

![error](https://user-images.githubusercontent.com/32661241/74233500-5d102f00-4cfd-11ea-8a92-f63de07b0330.png)

**Additional context**

This works on `3.3.10`. I'm currently using `4.0.0-beta.2`

**Comment by lobsterkatie** [comment]
I am having the exact same problem with the `mode` flag. And yet the docs still include it, and the migration guide for webpack 4 -> 5 mentions it, so it's pretty clear it hasn't been removed... Very confused with this one.

**Comment by ematipico** [comment]
Please don't install `4.0.0-beta.2` just yet. Unfortunately I published an incorrect version on npm, so sorry about that. Please keep using `3.3.10` or `3.3.11`.

In `4.0.0-beta.2` we removed `--mode` and `--env`. If you feel you'd back that argument, feel free to leave a feedback [here](https://github.com/webpack/webpack-cli/issues/1222)

**Comment by robertlevy** [comment]
I'm seeing this issue in the 4.0.0 release

**Comment by anshumanv** [comment]
Hi, @robertlevy we've changed the env flag format in v4 because we changed the arg parser, new docs will be released on official site soon. Meanwhile, you can use CLI docs from this deployment - https://vercel.com/webpack-docs/webpack-js-org/e6mjiydwu

**Comment by robertlevy** [comment]
@anshumanv thanks but that link is not working for me.  could you paste a summary or working example?

**Comment by anshumanv** [comment]
@robertlevy ofcourse! You should get a good idea from this test - https://github.com/webpack/webpack-cli/blob/master/test/config/type/function-with-env/function-with-env.test.js

Let us know if you have any problems 😄

**Comment by thealjey-eib** [comment]
@anshumanv so, we have only two options now, either the env variable will be a boolean `true` or a value configured with `DefinePlugin`, but we cannot pass an arbitrary string from the command line?

**Comment by snitin315** [comment]
>  but we cannot pass an arbitrary string from the command line?

@thealjey-eib  You can pass any arbitrary string from the command line.

**Comment by thealjey-eib** [comment]
how?

**Comment by thealjey-eib** [comment]
it used to be as simple as 
`webpack --env.app=foobar --env.title=qwerty`
but now, this throws "Unknown argument" errors

**Comment by anshumanv** [comment]
@thealjey-eib for now yes, this is how the behaviour was restored when it was removed.

```sh
webpack --env appFoobar --env titleQwerty
```
And use these variables to write conditional logic in your config, does it not cover your use case? If not, please give an example.

**Comment by fabianmarcus** [comment]
> @thealjey-eib for now yes, this is how the behaviour was restored when it was removed.
> 
> You can use
> 
> ```shell
> webpack --env appFoobar --env titleQwerty
> ```
> 
> And use these variables to write conditional logic in your config, does it not cover your use case? If not, please give an example.

I am used to do it this way:

```bash
npx webpack --mode production --config webpack.config.build.js --env name="staging" --env.service="login"
```

Now I get `[webpack-cli] Unknown argument: --env.service=staging`.

What's the working equivalent in Webpack CLI 4.x?

When I change the syntax to your example, the properties in `env` are just booleans:

```bash
{ 'service=staging': true, 'name=login': true }
```

But that's not what I need.

**Comment by anshumanv** [comment]
Thanks for the examples, migration of both config and scripts to use booleans will add a considerable overhead and current format seems not the most verbose thing to work with. I've opened https://github.com/webpack/webpack-cli/issues/1932 to track it, will PR soon

Since we've migrated our arg parser to commander so `--env.name="staging" --env.service="login"` won't be possible but we can do `--env name="staging" --env service="login"` Is that something you can work with?

**Comment by fabianmarcus** [comment]
Yeah, of course. Thanks!

**Comment by thealjey-eib** [comment]
@anshumanv my example is a multi-application project
I have an "applications" folder and I want to build any one one of them by name.
Maybe `env` is not ideal, I do not know, but I have not been able to find a better way to pass custom variables into `webpack.config.js`
I cannot hardcode the names of every app in `webpack.config.js`, and even if I did a boolean value is just not suitable for getting a single value from a list.

**Comment by anshumanv** [comment]
If you have a config per application, you can use flag `--config-name` to run webpack for just that config with that name, maybe it suits your use case better, can you try using that?

**Comment by thealjey-eib** [comment]
I don't want a config per application either, because they would all be the same.
It would only complicate things.

**Comment by anshumanv** [comment]
Ah okay so you have a single config for all applications, then `env` is the way to go 👍

**Comment by evolopment** [comment]
The documentation still has the old format, I've just had the same problem for following the docs:
https://webpack.js.org/guides/environment-variables/

**Comment by chenxsan** [comment]
@evolopment Maybe you can help fixing it :) Here's the source page https://github.com/webpack/webpack.js.org/blob/master/src/content/guides/environment-variables.md to edit.

**Comment by evolopment** [comment]
PR sent. Thanks.

**Comment by cranphin** [comment]
Can there be some easy to find simple fix for this? A lot of people are going to be running into this now, I read the comments and I'm still not sure what the exact fix is

**Comment by snitin315** [comment]
@cranphin see https://github.com/webpack/webpack-cli/pull/1939 for new `--env` format.

**Comment by ZebraFlesh** [comment]
This is a breaking change that really needs to be called out as such. In addition, I don't think webpack-cli 4.x can claim compatibility with webpack v4 with this change -- the `--env.prod=foo` form is explicitly called out [in the webpack v4 docs](https://v4.webpack.js.org/api/cli/#environment-options). If there is no desire to undo this change, then the `peerDependencies` should change.

**Comment by AsebWebDev** [comment]
So, setting up the enviroment variables like this is the way to go: `--env prod=foo` - no dot notation.

**Comment by snitin315** [comment]
@AsebWebDev yep exactly!

**Comment by DeepakJyoti878** [comment]
![Screenshot_2022_0615_204718](https://user-images.githubusercontent.com/71035974/173863817-90fd50fd-464c-46b5-a8e1-f710def7de17.jpg)

**Comment by alexander-akait** [comment]
Please open an issue in angular-cli repo

**Comment by Carles11** [comment]
(with versions "webpack": "^5.73.0" and "webpack-cli": "^4.10.0")

This solved the issue for me:

/package.json -->
"scripts": {
    "start": "webpack --mode=development && nodemon server",
    "build": "webpack --mode=production && NODE_ENV=production",
     ...
}

Hope it helps.
