### ISSUE TITLE
Beta version accidentally tagged as latest in NPM?

### ISSUE THREAD

**Issue by teuneboon** [webpack/webpack-cli#1217]
Let me preface this with the fact that I'm not too familiar with how versioning works with npm, so I might be wrong here.

When I look at https://www.npmjs.com/package/webpack-cli it looks like 4.0.0-beta.2 got the "latest" tag, but if I look at other projects like https://www.npmjs.com/package/vue and https://www.npmjs.com/package/eslint the alpha version isn't getting the "latest" tag there at least.

I came across this when webpack-cli accidentally got updated to 4.0.0-beta.2 a few hours ago on our CI server(which we should have version pinned a bit better).

**Comment by rishabh3112** [comment]
cc @ematipico

**Comment by silverwind** [comment]
Tag `latest` is generally supposed to be for stable releases, not beta version. I think this is an publishing error.

**Comment by geocolumbus** [comment]
There seems to be more than a handful of bugs. Did the wrong version get released?

**Comment by ematipico** [comment]
Yeah that was a mistake of mine! I will fix it ASAP! Sorry about that

**Comment by ematipico** [comment]
Hi, 

Again, apologies for the inconvenience! It was my first release and of course I had to do something wrong 😅 

Anyway, I released a patch release `v3.3.11` which is stable and it contains only a bump of the version. 
Also, I did release a beta version of npm  under `v4.0.0-beta.3`.

**Comment by teuneboon** [comment]
Thanks for the fix, it seems to be correct to me now so I'll close this issue.
