### ISSUE TITLE
mode switch not working [4.0.0-beta.2]

### ISSUE THREAD

**Issue by geocolumbus** [webpack/webpack-cli#1219]
```webpack --mode=development```

results in

```⬢ webpack: Unknown argument: --mode=development```

I rolled back to 3.3.10 and it works fine.

**Comment by geocolumbus** [comment]
Similar to #1216.

**Comment by ematipico** [comment]
Hi @geocolumbus, I apologise for the incorrect deployment of `4.0.0-beta.2` as latest on npm. 

Anyway, `--mode` is part of the breaking changes. You should use `--dev`
