### ISSUE TITLE
auto-detect and use yarn if available

### ISSUE THREAD

**Issue by rossipedia** [webpack/webpack-cli#123]
I know `create-react-app` does this, it would be nice if `webpack-cli init` detected yarn and used it if available for faster install times.

**Comment by ev1stensberg** [comment]
We are planning to do so, but there's a bug in `jscodeshift` -> `recast` preventing us to do so. Also, we're running a local fork of `yeoman-generator`, as we're soon transitioning to a full yeoman support for the CLI.

**Comment by ev1stensberg** [comment]
@pksjce any update on this? Discussed at the PR, but need feedback on the original issue
