### ISSUE TITLE
[init]: invoking init command doesn't create a webpack config anymore

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#1230]
**Describe the bug**

I don't see a webpack config scaffolded after running the init command. Just the `.yo-rc.json` is being created.

**What is the current behavior?**
init command is no longer creating webpack config 

**To Reproduce**
`webpack-cli init`

**Expected behavior**
It should create a webpack config from the `.yo-rc.json` that the generator creates

**Screenshots**
NA

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by anshumanv** [comment]
Looking into it.

**Comment by SampsonCrowley** [comment]
@anshumanv this is still happening with 3.3.12

**Comment by anshumanv** [comment]
Can you try with `4.0.0-rc.1`?

**Comment by SampsonCrowley** [comment]
Doesn't that only support webpack 5?

**Comment by anshumanv** [comment]
Supports 4 as well
