### ISSUE TITLE
Better integration with webpack ecosystem

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#1239]
As for webpack 4, we need to make sure that `webpack`, `webpack-dev-server` and `webpack-cli` are aligned all together and use the same resources.

In order to do so, the following features have to be implemented:
- negated flags #1240 
- consume arguments/options from `webpack` once the are available and implement them using a custom function #1241 
- the CLI will decide which webpack options will be supported as CLI arguments. For instance, if one option cannot be supported via CLI, it won't be exposed as supported CLI argument
- the CLI will override existing arguments (it should be already like this)
- support multiple types for arguments e.g.: boolean OR string at the same time (`hot` is one of the cases) 
- webpack options will be moved under `webpack` repo and `webpack-cli` will consume them, parse them and expose them as CLI arguments. 
- expose, by default, the webpack output and make opt-in the fancy output (which is an experiment)
- align the stats functionality with webpack core

**Comment by snitin315** [comment]
@ematipico I would like to work on this issue. It would be great if you can point me to some reference or share any tip/prerequisite .

**Comment by evilebottnawi** [comment]
I think most of features already implements, some of them remove, like `expose, by default, the webpack output and make opt-in the fancy output (which is an experiment)`, because we don't need it, closing in favor roadmap issue
