### ISSUE TITLE
Error message when no options are passed

### ISSUE THREAD

**Issue by montogeek** [webpack/webpack-cli#124]
Hi!

Congrats for the release!

I am getting a duplicate message when no options are passed to the CLI, I know it needs at least one option.

It would be nice to have `-h` printed, or a little more user friendly error printed.

![image](https://cloud.githubusercontent.com/assets/1002461/25823097/914a1952-3400-11e7-9384-7bded95981a3.png)

**Comment by ev1stensberg** [comment]
I can see why this is important! @okonet is doing some stuff to revamp the CLI #121 , and we're planning to make the old CLI better visually too :)

**Comment by ev1stensberg** [comment]
@kingdaro This one might be nice too, if no args present, add `-h` to the argv array

**Comment by kingdaro** [comment]
Sure, I can pick this one up another time.

**Comment by sumit-gupta91** [comment]
Hi, I would like to pick this bug up if no one is working on it.

**Comment by kingdaro** [comment]
@sumit-gupta91 You can go ahead. I have a solution but I'm not all that happy with it.
