### ISSUE TITLE
Negated flags

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#1240]
**Is your feature request related to a problem? Please describe.**
The CLI should support negated flags.

**Describe the solution you'd like**
The CLI should support same negated flags
- `--no-hot`
- `--no-colors`
- `--no-mode`

**Comment by snitin315** [comment]
@ematipico I would like to work on this issue. It would be great if you can point me to some reference or share any tip/prerequisite .

**Comment by rishabh3112** [comment]
Thanks for trying to work on the issue.
You can look at how other flags are added in the CLI, that would be enough to get you working on the issue.
You can ask for more help here if you need in future 🙌

**Comment by snitin315** [comment]
@rishabh3112 thanks , Looking into it.

**Comment by snitin315** [comment]
@rishabh3112 correct me if I'm wrong the `--no-mode` flag should set `mode = "none"` .?

**Comment by ematipico** [comment]
It depends on us. What do you think?

**Comment by snitin315** [comment]
I think it should set `mode = "none"`

**Comment by ematipico** [comment]
Sounds good :)

**Comment by snitin315** [comment]
@ematipico @rishabh3112  , I am able to add `nomode` or `no_mode` but I can't pass `no-mode` in the code below in `zero-config.js` like this  -

```
function getEnvFromOptionsAndMode(mode, optionsObject) {
     const { dev, prod, **no-mode** } = optionsObject;

```
Whats the trick here to do so?

**Comment by anshumanv** [comment]
`-` would be seen as an operator while destructuring since what you're destructuring is not a valid key, syntactically wrong.

Maybe add an alias variable for the flag like `--no-mode` stores a property is stored with key `no_mode`?

**Comment by snitin315** [comment]
@anshumanv 
>INVALID_DEFINITIONS: Invalid option definition: an alias must be a single character

:-(

**Comment by ematipico** [comment]
As the file says, that's a file we use for covering the case the user doesn't use any configuration.

The reading and parsing of the new flag will occur inside the group you decide to put.
