### ISSUE TITLE
Import flags from webpack core

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#1241]
**Is your feature request related to a problem? Please describe.**
At the moment we defined the supported flags inside the CLI (`cli-flags.js`). This could create discrepancy between webpack core supported options and webpack CLI supported arguments.

**Describe the solution you'd like**
The solution would be to import this flags straight from webpack core (missing at the moment). @evilebottnawi will help us here, he volunteered to integrate them inside webpack core. Later, we will import them here and decide which arguments we want to support. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by aquibbaig** [comment]
Hi @ematipico, Can I try this one here?

**Comment by ematipico** [comment]
Hi @aquibbaig ! 
This cannot be implemented yet. At the moment `webpack` doesn't expose any flag. We need to wait :)

**Comment by aquibbaig** [comment]
@ematipico Sure. Thanks for the light!

**Comment by ematipico** [comment]
PR created on webpack: https://github.com/webpack/webpack/pull/10499

**Comment by git-anurag-hub** [comment]
hi @ematipico can I try this?
