### ISSUE TITLE
chore(tools): add release-drafter

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1242]
**Is your feature request related to a problem? Please describe.**
Currently we don't have any tooling for release notes. This tool is very useful to keep track of a project. As pull requests are merged, a draft release is kept up-to-date listing the changes, ready to publish when you’re ready.
Right Configuration can  categorises the changes into headings, and automatically suggests the next version number as well.

for more info visit [here](https://github.com/release-drafter/release-drafter)

![Screenshot from 2020-02-21 13-49-22](https://user-images.githubusercontent.com/46647141/75016455-0d75f400-54b1-11ea-9420-ed1fdbda256c.png)

**Additional context**
Please verify if this is valid. If So i would like to work on this.

**Comment by ematipico** [comment]
How the tool work with `lerna`?

**Comment by snitin315** [comment]
> I mean we have lerna as tool to create changelogs and release notes.
Then This additional tooling will not be requiered then I guess.

**Comment by rishabh3112** [comment]
What is advantage of having it along with the `changelog` we publish for a release ?

**Comment by snitin315** [comment]
>What is advantage of having it along with the changelog we publish for a release ?

I'm not sure about the advantages , but the only difference is that with `release-drafter` we dont need additional `changelog.md` file it list down the changes in release-notes with mentioning the contributor's Name responsible for that change.

The current setup also seems fine  , I missed the presence of changelog file before creating this issue.

**Comment by ematipico** [comment]
Lerna does that for us (release draft too)

**Comment by snitin315** [comment]
> Lerna does that for us (release draft too)

It's not required then . Hence can be closed.
