### ISSUE TITLE
README: broken link for supported arguments and commands

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1243]
**Describe the bug**

Self Explainatory.

**What is the current behavior?**
Broken link. 404 Page not found

This is where you elaborate on the current behavior of the cli, how it behaves normally differing from the previous version/build you did. 

**To Reproduce**
1. Go to 'Redame'
3. Scroll down to 'supported arguments and commands'
3. Click on link.
4. See Error.

**Expected behavior**
Link should be valid.

**Screenshots**
![Screenshot from 2020-02-21 14-01-07](https://user-images.githubusercontent.com/46647141/75017228-9e999a80-54b2-11ea-8b91-808f62fc2069.png)

**Additional context**
I would like to work on this issue.

**Comment by ematipico** [comment]
PR welcome :)

**Comment by snitin315** [comment]
@ematipico can you provide the correct link?

**Comment by ematipico** [comment]
https://github.com/webpack/webpack-cli/blob/next/packages/webpack-cli/README.md
