### ISSUE TITLE
Revise the readme files.

### ISSUE THREAD

**Issue by mohitm15** [webpack/webpack-cli#1245]
**Describe the bug**

Spelling typos and grammatical errors in the various readme file

**What is the current behavior?**

Spelling error in Security.md and in webpack-scaffold/Readme.md

**To Reproduce**
1. Go to 'above-mentioned files'
2. See error

**Expected behavior**
Needs to be corrected

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
Working on it

**Comment by rishabh3112** [comment]
Closing via #1246
