### ISSUE TITLE
[Enhancement] : Make predefined question descriptions as comment in ISSUE Templates.

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1249]
**Describe the bug**

>A 💯 way to do this is to provide your configuration via a GitHub gist and/or to use markdown when describing which commands you used when the error occurred! Be precise and clear in your description of the bug.

the discriptions like above in issue templates should be comments , So user can add his description directly without removing them first.

**What is the current behavior?**
Currently user have to remove the predefine description first . Making the predefined descrpition as comment will lead to a bertter user experience while reporting a bug or submitting a feature request.

**Screenshots**
NA

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
NA

**Additional context**
I would like to work on this issue If valid.

**Comment by snitin315** [comment]
@ematipico Should I make a PR for this?

**Comment by ematipico** [comment]
You mean we should change the comments `<!-- -->` into a quote (using the markdown symbol `>`? 

I mean the comments done `<!-- -->` can stay there, you don't need to remove them. In fact when you hit preview, they are not rendered. 

What's the real problem?

**Comment by snitin315** [comment]
@ematipico they are being rendered in preview.

![Screenshot from 2020-02-22 21-48-34](https://user-images.githubusercontent.com/46647141/75095651-2c61ac80-55bd-11ea-8cc5-1f4893897616.png)

They are not wraped in `<!-- -->` 

![Screenshot from 2020-02-22 21-50-32](https://user-images.githubusercontent.com/46647141/75095670-62069580-55bd-11ea-9795-ecbf3faf9a79.png)


Thats what I am saying they should be wrapped in `<!-- -->`

**Comment by ematipico** [comment]
In your first comment you wrote
> Currently user have to remove the predefine description first .

This is misleading. I don't need to remove anything at the moment. So, to recap:
- why do you want to change the template in a way where the user has to delete some text?
- what's the value of this change?

**Comment by snitin315** [comment]
I will not remove anything , as you can see that in preview the description is being rendered. I want to make the descriptions as comment by wrapping them inside `<!-- -->`  so they will not be rendered in preview. Just like in PR templates.

**Comment by mohitm15** [comment]
@snitin315 then we also have to apply these changes also to `Feature request issue` where each section's description is not in comments currently.

**Comment by snitin315** [comment]
@mohitm15 Yes , I am hanging both bug report and feature report as well.

**Comment by ematipico** [comment]
I can see the confusion here now. You are talking about the wrong file :)
