### ISSUE TITLE
chore: add codacy code-quality badge in README

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1263]
**Is your feature request related to a problem? Please describe.**
Add codacy code-quality badge in README.

**Describe the solution you'd like**
![Screenshot from 2020-02-24 20-38-09](https://user-images.githubusercontent.com/46647141/75163721-b89edb80-5745-11ea-8973-8a8ad3e7bc2e.png)

**Additional context**

If this is a valid Issue , I would like to work on this.

**Comment by ematipico** [comment]
We already have it :)
https://codeclimate.com/github/webpack/webpack-cli

**Comment by snitin315** [comment]
This one is shows `D` for `MAINTAINABILITY` also provided by [codeclimate](https://codeclimate.com/github/webpack/webpack-cli)

I was refernecing for this one from [codacy](https://app.codacy.com/manual/ev1stensberg/webpack-cli/dashboard) -

![Screenshot from 2020-02-24 20-36-45](https://user-images.githubusercontent.com/46647141/75166069-534ce980-5749-11ea-94b1-ff010d278371.png)

**Comment by ematipico** [comment]
So what's your proposal? Use both?

**Comment by snitin315** [comment]
> Use both?

Yes

**Comment by ematipico** [comment]
Why both? What's the benefit?

**Comment by snitin315** [comment]
> What's the benefit?

webpack-cli is widely used by developers across the globe .When they'll come here, they will know about the high quality of code used to build this tool. This might inspire them to contribute to it, and build their trust over it.

**Comment by ematipico** [comment]
What's the benefit of having TWO tools that do THE SAME THING?

**Comment by snitin315** [comment]
We are already using both the tools , codacy is already used as a PR quality check. I think we should replace the Current `codeclimate` badge with `codacy` that makes more sense.

**Comment by ematipico** [comment]
Makes sense. Go ahead

**Comment by snitin315** [comment]
@evenstensberg Can you provide the corresponding badge link ?

**Comment by ematipico** [comment]
We can't implement it at the moment, sorry about it
