### ISSUE TITLE
docs: add section to test the CLI locally

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#1264]
Creating a new section inside `CONTRIBUTING.md` that would help people to test the CLI locally.

Sometimes people use the command `yarn link` or `npm link` but I think there's a batter way to improve the experience.

We could create a new package called `@webpack-cli/issue-repo` (`"name": "create-webpack-issue"`) which will be downloaded by people that wants to create a repo for an issue AND by people that are triaging the issue/

Inside the `package.json` of this template project, we should add [`relativeDeps`](https://github.com/mweststrate/relative-deps) which will be used by people that need to recreate the issue. 

Calling the package like this will help us to integrate with scaffolding tools such as [`yarn create`](https://classic.yarnpkg.com/en/docs/cli/create/)

**Comment by snitin315** [comment]
@ematipico I would like to help on this one.

**Comment by ematipico** [comment]
Go ahead!

**Comment by snitin315** [comment]
@ematipico can you explain this line a bit more `people that wants to create a repo for an issue ` , or can provide an example case.

**Comment by ematipico** [comment]
Usually we ask people for a repo to reproduce the issue. This could be a time consuming problem.
To alleviate the burden, we can create a yarn template (a la `create-reacrt-app`) with everything prepared (package.json, files, etc.)

**Comment by adrijshikhar** [comment]
@ematipico i would like to contribute on this issue.
Can you assign it to me? Thanks

PS: I have already setup the repo.

**Comment by snitin315** [comment]
@adrijshikhar you can go ahead with this one.

**Comment by Parikshit-Hooda** [comment]
Hi. Can I take up this issue? It seems @adrijshikhar is unresponsive.

**Comment by adrijshikhar** [comment]
Already working on it.

**Comment by Parikshit-Hooda** [comment]
alright!

**Comment by nlok5923** [comment]
is this issue still open
if yes 
can i work on it

**Comment by snitin315** [comment]
@nlok5293 Yes

**Comment by nlok5923** [comment]
Ok I am working on it

**Comment by nlok5923** [comment]
@ematipico please can you guide me with this issue

**Comment by adrijshikhar** [comment]
According to what I have understood, the `@webpack-cli/issue-repo` package will help users to report bugs easily. It will provide a boilerplate to the users and with the help of [`relativeDeps`](https://github.com/mweststrate/relative-deps), the dependencies will be pointed to the webpack-cli version, on which the user is facing a problem. Now with the basic structure of the project ready, the user can upload to GitHub and add the link to the repo in the issue itself. Correct me if I am wrong. 

I also wanted to know what can be the bare minimum requirements in the issue repo?

**Comment by Deepak-du** [comment]
Hi. Can I take up this issue?

**Comment by anshumanv** [comment]
I don't think we need this.

**Comment by snitin315** [comment]
+1

**Comment by anshumanv** [comment]
Closing, feel free to open a new issue if anyone faces any problem in testing.
