### ISSUE TITLE
Migrate error

### ISSUE THREAD

**Issue by JackPu** [webpack/webpack-cli#127]
I try to use `webpack-cli migrate webpack.config.js` 。 But I met the error:
``` bash
usr/local/lib/node_modules/webpack-cli/lib/migrate.js:77
								throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
								^

Error
    at fs.writeFile (/usr/local/lib/node_modules/webpack-cli/lib/migrate.js:77:15)
    at /usr/local/lib/node_modules/webpack-cli/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:111:15)
ali-4c32758be77b:react-core-image-upload ali-130257n$ cat webpack.config.
cat: webpack.config.: No such file or directory
```

My webpack-cli verson:  1.3.1 .

Anyone knows hot to solve it?

**Comment by okonet** [comment]
@JackPu can you paste your webpack config herer?

**Comment by ev1stensberg** [comment]
Try using relevant paths, I see you're doing `webpack-cli migrate webpack.config.js`, try out `webpack-cli migrate ./webpack.config.js`.

**Comment by JackPu** [comment]
webpack.config.js : https://github.com/Vanthink-UED/react-core-image-upload/blob/master/webpack.config.js

**Comment by ev1stensberg** [comment]
Hi @JackPu , did it get resolved?

**Comment by dhruvdutt** [comment]
@JackPu Did it work?

**Comment by ev1stensberg** [comment]
Probably, this has been fixed.
