### ISSUE TITLE
init: npx webpack-cli init command not working 

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1270]
**Describe the bug**

When the command is triggered as per the docs ,  it says **`init isn't a valid name`**
![Screenshot from 2020-02-26 16-53-41](https://user-images.githubusercontent.com/46647141/75341214-f755a280-58b9-11ea-8774-8d3e7564dddc.png)

### Though **`npx webpack-cli init --auto`** is working fine

![Screenshot from 2020-02-26 17-05-31](https://user-images.githubusercontent.com/46647141/75341359-41d71f00-58ba-11ea-928a-84733f6d9d57.png)

**What is the current behavior?**

`npx webpack-cli init` not working properly

**To Reproduce**

Run `npx webpack-cli init`

**Expected behavior**
Should create a config file.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
![Screenshot from 2020-02-26 17-09-59](https://user-images.githubusercontent.com/46647141/75341640-de012600-58ba-11ea-879e-c62d50a0edd3.png)

**Comment by ematipico** [comment]
Could you the same against the beta version?

**Comment by snitin315** [comment]
Working fine with beta :+1:

**Comment by ematipico** [comment]
I'd suggest to skip this bug then. It's not like there users that are not able work
