### ISSUE TITLE
bug: can't build the project.

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1275]
**Describe the bug**

While running `yarn build` it shows the following output - 

![Screenshot from 2020-02-27 14-10-35](https://user-images.githubusercontent.com/46647141/75426769-545d6100-596b-11ea-8469-ed1a9f7d8509.png)
 
**What is the current behavior?**

Unable to build. 

**To Reproduce**

1. Run `yarn build`

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Comment by anshumanv** [comment]
Did you `yarn bootstrap` ?

**Comment by snitin315** [comment]
>Did you yarn bootstrap ?

@anshumanv 

![Screenshot from 2020-02-27 19-07-26](https://user-images.githubusercontent.com/46647141/75450231-6f909680-5994-11ea-87b9-001c160adf83.png)

**Comment by anshumanv** [comment]
🤔 hmm, that's unusual

Maybe try, `yarn clean:all` then `yarn` then `yarn bootstrap` ?

**Comment by snitin315** [comment]
Build Succesful , Thanks for help @anshumanv . 

![Screenshot from 2020-02-27 19-24-45](https://user-images.githubusercontent.com/46647141/75451708-fe9eae00-5996-11ea-8ef6-29b6527721a6.png)

**Comment by anshumanv** [comment]
Awesome! 😄 Happy to help.
