### ISSUE TITLE
docs(): Revising the basic plugin architecture template 

### ISSUE THREAD

**Issue by mohitm15** [webpack/webpack-cli#1278]
**Is your feature request related to a problem? Please describe.**
The current basic structure for plugin along with the reference is outdated.

**Describe the solution you'd like**
To update it with the latest version

**Describe alternatives you've considered**

**Additional context**
Working on this

**Comment by anshumanv** [comment]
Fixed in https://github.com/webpack/webpack-cli/pull/1354, Closing.
