### ISSUE TITLE
bug(cli): mode flag accepts any value

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1282]
**Describe the bug**

 `--mode` is accepting any value and outputs development build. I can pass `--mode=abcd` , and it produces the build(development).

![Screenshot from 2020-02-28 15-33-34](https://user-images.githubusercontent.com/46647141/75539120-bedfd100-5a3f-11ea-9a7d-4c462ca2436c.png)

**Expected behavior**
It should accept only `production , development or none`

**Comment by anshumanv** [comment]
In case of invalid mode value we can probably use dev mode as default and print a warning that the given mode is invalid so dev will be used by default.

**Comment by snitin315** [comment]
I will work on this issue.

**Comment by anshumanv** [comment]
Awesome, thanks!

**Comment by ematipico** [comment]
You can use `type` to validate your argument. 

https://github.com/75lb/command-line-args/blob/master/doc/option-definition.md#module_option-definition--OptionDefinition+type
