### ISSUE TITLE
Handle the promise rejection if the user interrupts in between package installation prompt

### ISSUE THREAD

**Issue by jamesgeorge007** [webpack/webpack-cli#1283]
**Describe the bug**
Say the user fires in a command, `webpack-cli init` which results in the respective prompt showing up:-

```sh
✖ Would you like to install @webpack-cli/init? (That will run yarn add -D @webpack-cli/init) (Y/n) ·
```
And if the user interrupts the regular workflow, a promise rejection occurs which is left unhandled. 

**What is the current behavior?**
```sh
[webpack-cli] Promise rejection:
```

**Expected behavior**
Handles the promise rejection thereby replacing what is currently logged with an appropriate message.

**Additional context**
N/A

**Comment by ematipico** [comment]
The expected behaviour should be more descriptive

**Comment by jamesgeorge007** [comment]
@ematipico please take a look at ffe7a6b
