### ISSUE TITLE
[Docs] Add node CI badge to README.md

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#1286]
We could add the Github CI badge to our Readme file

![Node CI](https://github.com/webpack/webpack-cli/workflows/Node%20CI/badge.svg?branch=next)

**Comment by snitin315** [comment]
On it.

**Comment by snitin315** [comment]
Can you share the corresponding link?

**Comment by snitin315** [comment]
Is this correct?

[https://github.com/webpack/webpack-cli/workflows/Node%20CI/badge.svg?branch=next](https://github.com/webpack/webpack-cli/workflows/Node%20CI/badge.svg?branch=next)

**Comment by ematipico** [comment]
The link provided is correct :)

**Comment by ematipico** [comment]
Could you please leave the issue to someone else? As you can this it is marked for "first contributors"

**Comment by snitin315** [comment]
Sure No problem .  I will close the corresponding draft PR.

P.S. - Up for grabs

**Comment by aman29271** [comment]
@ematipico can i work on this issue?

**Comment by ematipico** [comment]
Go ahead! :)

**Comment by aman29271** [comment]
#1292 PR has been made.
