### ISSUE TITLE
webpack entry config doesn't work if defaultEntry file existed

### ISSUE THREAD

**Issue by Mistyyyy** [webpack/webpack-cli#1288]
**What is the current behavior?**

webpack.config.js

```javascript
module.exports = {
  mode: 'development',

  entry: {
    index: './src/entry.js',
  },

  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].bundle.js',
  },

  plugins: [
    new CleanWebpackPlugin()
  ]
}
```
below is project Directory Structure
```
├── index.js
├── package.json
├── src
│   ├── a.js
│   └── entry.js
└── webpack.config.js
```

when running` npx webpack`, the output is` main.bundle.js  `, the content of the final bundle includes index.js module and excludes entry.js module

**how I know this is a webpack-cli bug rather webpack bug**

I debug the program locally

**To Reproduce**

https://github.com/Mistyyyy/webpack-cli-entry-repo

**Expected behavior**

`output: index.bundle.js`

**Screenshots**

![image](https://user-images.githubusercontent.com/37856353/75847913-92e79580-5e1b-11ea-939c-6a1d608875e8.png)

I had fix it locally, the reason is  BasicGroup has a default entry value and override the config entry value if find defaultEntry file.

If appropriate, I am willing to submit a PR

**version**

Node: v12.10.0
webpack: 5.0.0-beta.13
webpack-cli: 4.0.0-beta.8

**Comment by anshumanv** [comment]
This is a bug surely, please feel free to submit a PR.

**Comment by ematipico** [comment]
This is a nice chance for first contributors to tackle the issue. A good way to tackle issue would be to create a test first and make that fails.
