### ISSUE TITLE
docs: master branch being reffered instead of next 

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1291]
**What is the current behavior?**

Currently the default branch is `next` , but `master` branch is being refered in the docs .

>![Screenshot from 2020-03-04 20-36-04](https://user-images.githubusercontent.com/46647141/75892717-cba56000-5e57-11ea-9eba-ce27d61a2439.png)
 

**Expected behavior**

`next` branch should be refered.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
I would like to fix it if valid.

**Comment by anshumanv** [comment]
A good candidate for initial contributions, go for it!

**Comment by snitin315** [comment]
I think this should be fixed soon , as it may cause some confusion for first time contributor. Like he may checkout master as per the docs.

**Comment by ematipico** [comment]
Well I can say that this depends from the point of view. People might want to checkout `master` to fix important bugs for the current version. 

If we change the docs now it means we will have to change the docs again once we will publish a stable version. I think a small comment in the main readme (at the beginning, where we have a quote saying that the docs refers to next version) is enough. What do you think?

**Comment by snitin315** [comment]
Sounds Good !

**Comment by snitin315** [comment]
We have something like this now , 
![Screenshot from 2020-03-05 05-44-10](https://user-images.githubusercontent.com/46647141/75935202-9b37e300-5ea4-11ea-9855-8a3c403962dc.png)

how about this @ematipico @anshumanv  - 

> ## This is the documentation of the beta version (being maintained on branch next).
