### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by piaic65617** [webpack/webpack-cli#1295]
I am geeting typeError .solution please

<html>
    <head>
        <meta charset="utf-8">
        <title>error</title>
        <style>
            #error{
                color: red;
            }
        </style>

    </head>
    <body>
        <p> your password should contain atleast 6 characters,1 capital letter,1 number</p>
        <p>Enter password : <br/> <input id="password1" type="password"></p>
        <p>Re-Enter password : <br/> <input id="password2" type="password"></p>
        <button onclick="check()">Submit</button>
        <p id="error"></p>
        <script>
            // function check will validate the user input
            function check(){
                var password1=
                document.getElementById("password1").innerHTML.value;
                var password2=
                document.getElementById("password2").innerHTML.value;
                var errmessage=document.getElementById("error");
                var errortothrow="";
                try {
                    if (password1.length < 6 ){
                        errortothrow += "< br/> password to short .";
                    }
                    if(/[A-Z]/g.test(password1) == false){
                        errortothrow += "<br /> password should contain one capital letter.";
                    }
                    if (/\d/g.test (password1) == false){
                        errortothrow += "<br/> password should contain one number. ";
                    }
                    if (password1 != password2){
                        errortothrow += "<br/> passwords should match. ";
                    }
                    // we use throw statment after tehe try statement once.If we use inside try ater every if statement
                    // then it will take the compiler out of try statement.
                 throw errortothrow;
                }
                // here err is a string,cause we are throwing a string
                catch (err){
                    errmessage.innerHTML=err;
                }
            }   
            // try {
            //     sum(4,5);
            // }
            // here err is an OBJECT ,cause we donot speciy anything to throw,and we get message by message poperty.
            // catch (err){
            //     document.getElementById("error").innerHTML = err.message;
            // }
        </script>
    </body>
</html>

**Comment by snitin315** [comment]
@piaic65617 how is this related to webpack ?
