### ISSUE TITLE
docs: Adding readme.md in folders

### ISSUE THREAD

**Issue by himanshu010** [webpack/webpack-cli#1297]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
The readme file does not have the file system describing the locations of files. Sometimes it is very tedious to find a particular file, therefore projects like this needs a fully descriptive file system.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The readme file should contain file system. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**

I would Like to work on this issue

**Comment by ematipico** [comment]
Could you help me here and explain me what you'd like to see?

**Comment by himanshu010** [comment]
it is something like this : 

![Screenshot (27)](https://user-images.githubusercontent.com/43860289/76080754-9f135480-5fcd-11ea-8649-b0889137067e.png)

**Comment by maria99williams** [comment]
Yeah I think that it would be great for someone like me as I am new to open source. I am looking forward to contribute to webpack.

**Comment by anshumanv** [comment]
+1 for this as this could provide a general overview of the code.

**Comment by snitin315** [comment]
It's Nice to have a folder structure.

**Comment by ematipico** [comment]
Which section would you think makes sense to have it? The contribution section?

**Comment by snitin315** [comment]
Yes Contribution .

**Comment by himanshu010** [comment]
> Which section would you think makes sense to have it? The contribution section?

Yeah

**Comment by ematipico** [comment]
Thank you! Feel free to make a PR!

**Comment by rishabh3112** [comment]
@himanshu010 I didn't get the exact benefit it would bring to the first time contributors as we have individual READMEs in each package which explains their functionalities.

Instead I would like to propose to add READMEs in the folders which you think you faced issues to understand, something like this:
https://github.com/webpack/webpack/blob/master/examples/README.md

**Comment by himanshu010** [comment]
okay, I would work on this.

**Comment by adrijshikhar** [comment]
Is this issue still open? I have been using webpack for quite a while now and I absolutely love it. I feel like this will be a nice starting point. I will go through the existing PRs and post a final conclusion if that suits or if anyone else has an idea of what has to be done here, please guide me through that.

**Comment by snitin315** [comment]
I think we already have Readme files at appropriate  places.
/cc @webpack/cli-team

**Comment by evilebottnawi** [comment]
Yep, we don't need readme at each directory

**Comment by snitin315** [comment]
Lets close it then 👍🏻

**Comment by snitin315** [comment]
@adrijshikhar maybe you can check help with some other newly created issues.

**Comment by adrijshikhar** [comment]
Yeah sure. Thanks 😀
