### ISSUE TITLE
Watch mode --save: rebuild on save regardless of changes

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack-cli#13]
I would like the option to be able to rebuild on save when using watch without webpack looking at the last modified date of files.

I understand rebuild can be resource intensive, but sometimes it is useful to the dev to be able to build as a sanity check or just to refresh the project.

**Moved from https://github.com/webpack/webpack/issues/1992**

**Comment by ev1stensberg** [comment]
If I were to understand this correctly, it's just a rebuild after save regardless if it's a change or not?

**Comment by bebraw** [comment]
@gkiely Can you expand on the idea?

**Comment by ev1stensberg** [comment]
If there's a change, you'll get an update. If there isn't, you'll get an update too.

**Comment by gkiely** [comment]
Sorry I never got back on this, this is awesome though @ev1stensberg, did this end up getting fixed?

**Comment by ev1stensberg** [comment]
#24 Was merged, but I think it got removed. Maybe nodemon is a better option for you

**Comment by gkiely** [comment]
@evenstensberg Thankyou for writing this! 
I'll see if I can re-submit it?

**Comment by evenstensberg** [comment]
I think maybe we should wait until the new CLI is done to see what features are needed and wanted

**Comment by jayjun** [comment]
Hmm, @evenstensberg then removed it?

Documentation removed [here](https://github.com/webpack/webpack-cli/pull/105/commits/cd5562cf2bedd8db6f407ea21383bf495afb2cfa#diff-86ffe53e663ae3f143b8e2219c8ded35L169). Implementation removed [here](https://github.com/webpack/webpack-cli/pull/448/commits/e87fd7d1912024d8671bd67f10bea703ce4035bc#diff-9b4dfe50c0b618f49bf5bb3aac15b80bL187).

**Comment by evenstensberg** [comment]
Yes, I think it got lost in the rebase against the new branch of webpack. But the removal is good. We need less flags and features to focus on maintaining, check out nodemon if that works out
