### ISSUE TITLE
import-local doesn't make sense

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack-cli#1318]
**Describe the bug**

import-local package does not prefer the local installation of webpack-cli, it only allows you to check whether the local launch or global

**What is the current behavior?**

Code exists and does nothing

**To Reproduce**

1. `webpack` or `node packages/webpack-cli/bin/cli.js`

**Expected behavior**

Code should be removed or improved, example of the improvement https://github.com/avajs/ava/blob/master/cli.js

**Screenshots**

No need

```
  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (6) x64 AMD FX(tm)-6300 Six-Core Processor
    Memory: 1.05 GB / 11.73 GB
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    Yarn: 1.13.0 - /usr/bin/yarn
    npm: 6.14.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 73.0.1
  npmPackages:
    webpack: ^4.42.0 => 4.42.0 
  npmGlobalPackages:
    webpack-cli: 3.3.6
```

**Additional context**

No

**Comment by snitin315** [comment]
@evilebottnawi I would like to work on this.

**Comment by evilebottnawi** [comment]
Need investigate - should we remove it or improve, wait other developers

**Comment by snitin315** [comment]
+1 for removal.

**Comment by snitin315** [comment]
Let's open a PR and move the discussion there.

**Comment by evilebottnawi** [comment]
:+1:
