### ISSUE TITLE
feat: refreshing folder structure on each commit

### ISSUE THREAD

**Issue by himanshu010** [webpack/webpack-cli#1320]
**Is your feature request related to a problem? Please describe.**
Automatically refreshing folder-structure on each commit

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I will work on this

**Comment by snitin315** [comment]
Please don't create issues unnecessarily, it just creates confusion the main issue is #1311.

**Comment by himanshu010** [comment]
As all the pr are solving different problems therefore I created them different issues. This will not happen in future.

**Comment by snitin315** [comment]
> As all the pr are solving different problems, therefore, I created them different issues.

The problem is not different. Its the same issue you are solving. 

Developers who are reviewing the code should use their time efficiently.

**Comment by himanshu010** [comment]
Now the contributor doesn't have to do something specific to change the folder structure. And I think this will solve the whole problem and make the folder structure automatic. What are your views on this @ematipico

**Comment by maria99williams** [comment]
Good Work @himanshu010 . In my opinion, everything will work fine now.

**Comment by rishabh3112** [comment]
Closing in favour of #1297
