### ISSUE TITLE
webpack-cli: wrong behavior of defaults flag

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#1322]
**Describe the bug**

`--defaults` doesn't work as expected, uses local config when it should enforce defaults.

**What is the current behavior?**

Not applying defaults.

**To Reproduce**

- Create a config with some entry/output,

- `webpack-cli --defaults`

- Uses entry from the config.

**Expected behavior**

Should apply the default config.

**Screenshots**

NA.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

This is originally pointed out by @ematipico here - https://github.com/webpack/webpack-cli/pull/1258#discussion_r383209904 Thank You!

WIP

**Comment by snitin315** [comment]
@anshumanv, I think this can be closed now as we removed `--defaults`.
