### ISSUE TITLE
webpack-cli: Passing silent flag doesn't work

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#1324]
**Describe the bug**

Still seeing webpack output when the silent flag is passed.

**What is the current behavior?**

Passing silent flag still logs webpack build data.

**To Reproduce**
`webpack-cli --silent`

**Expected behavior**

Should disable all logs. We should still log errors right?

**Screenshots**
when there are no errs - 
![image](https://user-images.githubusercontent.com/21009455/76701277-d7114a80-66e5-11ea-8136-96dbca88d9e1.png)

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by anshumanv** [comment]
@ematipico @rishabh3112 wdyt, we should still log errors or nothing at all?

**Comment by anshumanv** [comment]
Ah so we're just passing options to the webpack compiler, will discuss this later at webpack/webpack.

**Comment by snitin315** [comment]
`--silent` is removed. Hence closing.
