### ISSUE TITLE
core-team link in CODE_OF_CONDUCT not present

### ISSUE THREAD

**Issue by Parikshit-Hooda** [webpack/webpack-cli#1328]
**Describe the bug**

[core-team link not present](https://github.com/webpack/webpack-cli/blob/next/CODE_OF_CONDUCT.md)

**What is the current behavior?**

link not present

**To Reproduce**
1. Go to 'https://github.com/webpack/webpack-cli/blob/next/CODE_OF_CONDUCT.md'
2. observe in written , '@webpack/core-team'
3. observe that link isn't present

**Expected behavior**

I believe that like '@webpack/cli-team', '@webpack/core-team' link should also work.

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by Parikshit-Hooda** [comment]
Would like to resolve this.

**Comment by anshumanv** [comment]
Please go ahead. 👍

**Comment by Parikshit-Hooda** [comment]
Please provide me the link. I am not able to resolve the validity of the team link because it won't route me there. Also, I think the 'cli-team' link is broken as well. Can someone confirm? @rishabh3112 @anshumanv

**Comment by anshumanv** [comment]
cli-team link works fine, here' the core team link - https://github.com/orgs/webpack/teams/core-team

**Comment by Parikshit-Hooda** [comment]
Pretty symmetric, thanks!
