### ISSUE TITLE
minor typos in the changelog

### ISSUE THREAD

**Issue by Parikshit-Hooda** [webpack/webpack-cli#1330]
**Describe the bug**

Found about 8 typos when I was recently going through the changelog file. like reolve, ouput, etc. This issue is raised to consider fixing these typos.

**What is the current behavior?**

Typos in the CHANGELOG.md file

**To Reproduce**

1. Go to 'CHANGELOG.md'
2. search for 'reolve', 'ouput',(among other typos)

**Expected behavior**

no typos.

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

Would like to fix these typos, if desired and wanted by the team.

**Comment by anshumanv** [comment]
It's usually not a good idea to touch the changelog once it's generated. :)

https://github.com/webpack/webpack-cli/pull/1306#issuecomment-596792265

**Comment by snitin315** [comment]
Changelogs are auto generated

**Comment by Parikshit-Hooda** [comment]
alright
