### ISSUE TITLE
Example for commit-message template  in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Parikshit-Hooda** [webpack/webpack-cli#1340]
**Is your feature request related to a problem? Please describe.**
It took me time to find an example commit-message when I was making my first commit to this repo.

**Describe the solution you'd like**
An example commit-message in CONTRIBUTING.md would be nice under the 'commit message format' section

**Describe alternatives you've considered**
none.

**Additional context**
I intend to copy the one already present and being used in [webpack-dev-middle contributing file](https://github.com/webpack/webpack-dev-middleware/blob/master/.github/CONTRIBUTING.md#-webpack-contrib-commit-conventions)

**Comment by evilebottnawi** [comment]
Done https://github.com/webpack/webpack-cli/pull/1364
