### ISSUE TITLE
typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Parikshit-Hooda** [webpack/webpack-cli#1346]
**Describe the bug**
typo in CONTRIBUTING.MD(project is written as 'poject')

**What is the current behavior?**
project is written as 'poject'

**To Reproduce**

1. Go to https://github.com/webpack/webpack-cli/blob/next/.github/CONTRIBUTING.md
2. Search for 'poject' word
3. See error

**Expected behavior**
'poject' should be 'project'

**Screenshots**
not applicable

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
not applicable

**Comment by evilebottnawi** [comment]
Please do not create issues on each typo, if you can send a PR, it is create small spam, just send a PR and we will be grateful to you, thanks
