### ISSUE TITLE
docs(contributing.md): missing some content in the table

### ISSUE THREAD

**Issue by himanshu010** [webpack/webpack-cli#1349]
**Do you want to request a *feature* or report a *bug*?**

N/A
**What is the current behavior?**
N/A
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
N/A
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**

**Comment by snitin315** [comment]
for small changes create a PR direct, no need to create issues. [comment](https://github.com/webpack/webpack-cli/issues/1346#issuecomment-600190166)
