### ISSUE TITLE
webpack-cli init doesn't install webpack, uglifyjs-webpack-plugin, babel-preset-es2015

### ISSUE THREAD

**Issue by nilliams** [webpack/webpack-cli#135]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
```
$ webpack-cli init

Insecure about some of the questions?

https://github.com/webpack/webpack-cli/blob/master/INIT.md

? Will you be creating multiple bundles? No
? Which module will be the first to enter the application? index.js
? Which folder will your generated bundles be in? [default: dist]:
? Are you going to use this in production? No
? Will you be using ES2015? Yes
? Will you use one of the below CSS solutions? No
? If you want to bundle your CSS files, what will you name the bundle? (press enter to skip)
? Name your 'webpack.[name].js?' [default: 'config']:
...
├─┬ babel-core@6.24.1
│ ├─┬ babel-code-frame@6.22.0
│ │ ├─┬ chalk@1.1.3
...
└── UNMET PEER DEPENDENCY webpack@2
```

Then:
```
$ webpack-cli
module.js:471
    throw err;
    ^

Error: Cannot find module 'webpack'
```

If install webpack (`npm i -S webpack`), next error is:
```
$ webpack-cli
module.js:471
    throw err;
    ^

Error: Cannot find module 'uglifyjs-webpack-plugin'
```

If install that, we get (after fixing `"./dist" is not an absolute path` which is I see is fixed now):

```
$ webpack-cli
Hash: 5492c18c1852ed5bd45b
Version: webpack 2.5.1
Time: 3144ms
         Asset     Size  Chunks             Chunk Names
main.bundle.js  1.99 kB       0  [emitted]  main
   [0] ./index.js 1.49 kB {0} [built] [failed] [1 error]

ERROR in ./index.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory
```

**What is the expected behavior?**

`webpack-cli init` to install all needed deps

**Version**
```
$ webpack-cli --version
1.3.1
```

**Comment by ev1stensberg** [comment]
Hi! The `dist` output is fixed in #125 . It should install your dependencies, what's your repository structure, and where do you run the command from?

**Comment by nilliams** [comment]
Hmm, it does seem odd no-one else has hit this!

Thought it might be an env thing, so now tried in 2 envs, (empty dir each time):

- 2 x in MacOS
- 2 x in Ubuntu (via Vagrant)

... and get the same.

Dir structure is a new, empty dir. I am running command from a global install (`npm i -g webpack-cli`).

MacOS: 
```
$ which webpack-cli
/Users/nick/.nvm/versions/node/v6.9.5/bin/webpack-cli
```
Ubuntu:
```
$ which webpack-cli
/home/vagrant/.nvm/versions/node/v6.9.1/bin/webpack-cli
```

[Here's a more complete dump from the Vagrant attempt](https://gist.github.com/nilliams/864326cdf0a75af53eb84e08a7cff897), which shows the 3 modules I named not being included in the install.

**Comment by nilliams** [comment]
Hmm ... is this not (partly) the bug, it overrwrites, rather than appends-to `this.npmInstalls`, which clobbers the line from the constructor (`this.npmInstalls = ['webpack', 'uglifyjs-webpack-plugin']`):

https://github.com/webpack/webpack-cli/blob/master/lib/creator/yeoman/webpack-generator.js#L96

**Comment by ev1stensberg** [comment]
Hi! Thanks for the PR, saw the typo! Closing #136
