### ISSUE TITLE
FEATURE: --version for sub packages

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1363]
**Is your feature request related to a problem? Please describe.**

Feature request. 

Currently the version command shows version of only `webpack` & `webpack-cli`. But it is not possible to get the version details of the sub-packages via the cli.

`webpack-cli info --version`

![Screenshot from 2020-03-23 11-25-40](https://user-images.githubusercontent.com/46647141/77286359-10a31080-6cf9-11ea-86c0-88a051919406.png)

**Describe the solution you'd like**

The version command should show versions of sub-packages as well.

**Describe alternatives you've considered**

NA

**Additional context**

I will work on this issue.

**Comment by aman29271** [comment]
@snitin315 are you working on this issue?

**Comment by snitin315** [comment]
Yes, I already have a PR for this.
