### ISSUE TITLE
Feature: add alias for version flag 

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1368]
**Is your feature request related to a problem? Please describe.**

Currently only `webpack --version` is supported.

Most of the CLI supports both `--version` & `-v` 

Example -  `node -v` &  `node --version`

**Describe the solution you'd like**

`webpack -v` should be supported as well.

**Screenshots**

![Screenshot from 2020-03-24 20-06-08](https://user-images.githubusercontent.com/46647141/77437744-02ddb000-6e0b-11ea-8c77-02109e893f39.png)

**Additional context**

I will work on this issue if valid.

**Comment by evilebottnawi** [comment]
Low priority, you can focus on priority issues from roadma
