### ISSUE TITLE
Feature: Webpack PWA add-on/scaffold

### ISSUE THREAD

**Issue by addyosmani** [webpack/webpack-cli#137]
As part of #101, we'd like to create a minimal, but useful, Webpack add-on for those getting started with Progressive Web Apps. This would build on the work that was done for the default `--init` starting point in https://github.com/webpack/webpack-cli/issues/119.

* Handle favicons and Web App Manifest. Either via a static include of some defaults (just the files) that get wired up using HTML Webpack Plugin with another plugin like https://github.com/jantimon/favicons-webpack-plugin. Most people do this statically.
* Add [offline caching support](https://www.npmjs.com/package/sw-precache-webpack-plugin) for static assets (CSS, JS) w/sw-precache. We could also do it for HTML - if someone is building an SPA this would get them closer to an AppShell model style level of caching. If not, it would do full-page caching.
* Performance budgets by default?

**Validation:** It should be possible to take a simple app, even something like a rando TodoMVC implementation, run it with webpack-cli and this add-on and be able to generate an offline-first PWA that an get a decent score on Lighthouse.

I've also filed https://github.com/webpack/webpack.js.org/issues/1145 for us to think about guidance around this topic for the official Webpack docs.

**Comment by TheLarkInn** [comment]
@ev1stensberg Is this already started?

**Comment by ev1stensberg** [comment]
@TheLarkInn  Going to SF right now, will continue on this tomorrow.

**Comment by ev1stensberg** [comment]
Leaving this for grabs within 30 days, or I'll make one myself.

**Comment by ev1stensberg** [comment]
This is still up for grabs and on the agenda

**Comment by sendilkumarn** [comment]
@addyosmani 

> Handle favicons and Web App Manifest. 

Makes sense to add the static default and users to change them whatever they need to. Probably give an option to choose between advanced and simple configuration 

>Add offline caching support for static assets 

I think workbox is mature enough to use it here. WDYT?

**Comment by Symphoria** [comment]
@ev1stensberg Hey, I am a newcomer here. I would like to work on this issue. Can you guide me how to approach?

**Comment by sendilkumarn** [comment]
@Symphoria You can have a look at how to create an addon over [here](https://github.com/ev1stensberg/webpack-addons-demo) 

I have started something on this over [here](https://github.com/sendilkumarn/webpack-addons-pwa/) 
(it is just a start)

**Comment by dhruvdutt** [comment]
@Symphoria @sendilkumarn Hey guys! :) I'm also looking to work on this. Maybe we all can do something in collaboration.

**Comment by sendilkumarn** [comment]
Well that sounds great and my idea is this. Lets have workbox plugin to take care of sw. and use copywebpackplugin for manifest and favicon.
If that sounds good to you lets start working on (this)[ https://github.com/sendilkumarn/webpack-addons-pwa/]

**Comment by ev1stensberg** [comment]
@sendilkumarn create a collab team and get them in a slack / gitter 👍

**Comment by Symphoria** [comment]
@ev1stensberg  How do I test the addon? On running the command
`webpack-cli init webpack-addons-pwa`, I get `TypeError: Package isn't registered on npm.`

**Comment by ev1stensberg** [comment]
Right, so it should work, but it's not officially published yet. I've got a alpha version registered on npm, but that is different from @sendilkumarn 's. Are you running `webpack-cli version 2.0.6` ?

**Comment by Symphoria** [comment]
@ev1stensberg  Yes, I am running `webpack-cli version 2.0.6`

**Comment by sendilkumarn** [comment]
Have you linked the project?

**Comment by ev1stensberg** [comment]
@sendilkumarn any update on the PWA you're making?

**Comment by sendilkumarn** [comment]
Not at the moment, still few pending things to complete.

But I think we can close this Issue and redirect users to that addon would be a better option.

Also, the name is pending 😉

**Comment by rishabh3112** [comment]
@sendilkumarn @dhruvdutt  is work is still in progress [here](https://github.com/sendilkumarn/webpack-addons-pwa) ?
I have submitted a PR [sendlikumarn/webpack-addons-pwa#19](https://github.com/sendilkumarn/webpack-addons-pwa/pull/19).
Also package on npm needs to be updated to `webpack-scaffold-pwa`

**Comment by sendilkumarn** [comment]
@rishabh3112 Yeah sure we can do this 👍

**Comment by sendilkumarn** [comment]
Lets close this 👍
