### ISSUE TITLE
Environment variable interpreted as floating point number

### ISSUE THREAD

**Issue by Gearshxft** [webpack/webpack-cli#1380]
**Describe the bug**

There seems to be no way of forcing environment variables to be treated as a string.

**What is the current behavior?**

For example, our build pipeline automatically passes the git commit hash as an environment variable:

`yarn webpack --env.hash="838132e2"`

The webpack.config file would interpret this as a floating point number: 83813200

**Expected behavior**

We need a way to always treat this as a string, so the webpack config file should receive "838132e2".

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by evilebottnawi** [comment]
We remove `env` flag in future version, please use configuration for that
