### ISSUE TITLE
jest ReferenceError: describe is not defined

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack-cli#1386]
**Describe the bug**

When I run tests on my local machine, I'm getting the error `ReferenceError: describe is not defined` for any typical jest `describe` function call.

I've pinpointed that this is the last commit where it was working: https://github.com/webpack/webpack-cli/commit/f8ec20382702450134032a65403894573b04be8d

and the error starts happening with this commit: https://github.com/webpack/webpack-cli/commit/e4e1bb9d33e4f6c6084d9c083ed50aa57a00740d

My guess is some dependency change is causing the problem, but I haven't gone through yet and found exactly where the problem is. I'm curious if others are having this same issue.

Edit: Using Zorin OS 15.2 (based on Ubuntu 18.04), Node v10.13.0
Edit 2: The issue is solved with Node v13.12.0

**Comment by evilebottnawi** [comment]
It is fixed, right?

**Comment by Loonride** [comment]
> It is fixed, right?

Yes
