### ISSUE TITLE
source-map-array-test is failing

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1389]
**Describe the bug**

`source-map-array-test` is failing unexpectedly. 

**What is the current behavior?**

![Screenshot from 2020-03-29 16-03-48](https://user-images.githubusercontent.com/46647141/77846967-3b98d300-71d7-11ea-8a3f-6e0e0c2ffea1.png)

**To Reproduce**

1. Reset branch with `next`
2. `yarn test`
3. See error

**Expected behavior**

The test should pass.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

![Screenshot from 2020-03-29 16-08-35](https://user-images.githubusercontent.com/46647141/77847018-95010200-71d7-11ea-9a83-eb74b692c5e1.png)

**Additional context**

This needs verification, not sure if the issue is valid.

**Comment by anshumanv** [comment]
I'll verify in a bit, thanks for the report 👍

**Comment by evilebottnawi** [comment]
Can't reproduce

**Comment by snitin315** [comment]
Working fine now.
