### ISSUE TITLE
CSS Option Does Not Include style.loader in Rule

### ISSUE THREAD

**Issue by larkintuckerllc** [webpack/webpack-cli#139]
webpack: 2.5.1
webpack-cli: 1.3.1

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Choosing `CSS` option gives unexpected *webpack.config.js*; uses *css-loader* without *style-loader*. 

**If the current behavior is a bug, please provide the steps to reproduce.**

```
? Will you be creating multiple bundles? No
? Which module will be the first to enter the application? ./src/index.js
? Which folder will your generated bundles be in? [default: dist]: 
? Are you going to use this in production? No
? Will you be using ES2015? No
? Will you use one of the below CSS solutions? CSS
? If you want to bundle your CSS files, what will you name the bundle? (press en
ter to skip) 
? Name your 'webpack.[name].js?' [default: 'config']: 
```

**What is the expected behavior?**

Similar rule to the `SASS` option:

```
      {
        test: /\.css$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader'
          }
        ]
      }
```

**Comment by ev1stensberg** [comment]
Hey! Thank you so much for filing this! Fixed in #141 . Please, do tell if there's more of these! Cheers 👍
