### ISSUE TITLE
Type Error: argv._.includes('init') in Node 4.4

### ISSUE THREAD

**Issue by pavkout** [webpack/webpack-cli#140]
In Windows 10, node 4.4 i get this error.
TypeError: argv._.includes is not a function.

The problem is solved after upgrading to node 6 but since in the package.json it says it is compatible with node >= 4 i thought i should create this issue.

**Comment by ev1stensberg** [comment]
Mind posting a screenshot of your output w/ stacktrace?

**Comment by zowers** [comment]
upgrade to nodejs-6 fixes the issue

**Comment by ev1stensberg** [comment]
We support v4 too @zowers , this should work 👍

**Comment by okonet** [comment]
AFAIK `includes` isn't in Node v4. See http://node.green/#ES2015-built-ins-well-known-symbols-Symbol-match--String-prototype-includes

So we either should polyfill it or rewrite it with ES5.

**Comment by ev1stensberg** [comment]
Rewrite would be appropriate in this situation :)

**Comment by ev1stensberg** [comment]
Closed À la #183
