### ISSUE TITLE
webpack-dev-server 3.10.3 failed run in webpack-cli v4.0.0-beta.2

### ISSUE THREAD

**Issue by jundge** [webpack/webpack-cli#1404]
![1](https://user-images.githubusercontent.com/24717511/78243831-0f52be80-7517-11ea-98de-da33138c2c73.jpg)
![2](https://user-images.githubusercontent.com/24717511/78243971-50e36980-7517-11ea-9c56-c55dc9a79de8.jpg)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Also already reported
