### ISSUE TITLE
[FEATURE]: Add a warning when using absolute path in resolve.modules (it breaks the node resolution_

### ISSUE THREAD

**Issue by NitroBAY** [webpack/webpack-cli#1407]
**What is the expected behavior?**
Add a warning when using absolute path in resolve.modules (it breaks the node resolution)

**What is motivation or use case for adding/changing the behavior?**
This : 
https://github.com/fb55/htmlparser2/issues/434

> It took me literally days and severally delayed my project and drived my insane but the problem was : webpack was using only the modules from TOP LEVEL node_modules (which is another version of entities whose structure is different which explains why require failed) instead of going firs trying to use the nested node_modules of this package.
And this was because I used ABSOLUTE path instead of RELATIVE one https://webpack.js.org/configuration/resolve/ in resolve.modules

**How should this be implemented in your opinion?**
A warning in the CLI.

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
Can you provide example? Many small reproducible test repo?

**Comment by NitroBAY** [comment]
Example ?
But this behavior of absolute path changing the resolution from node's one to only looking in the absolute path is documented https://webpack.js.org/configuration/resolve/
It is an intentional behavior which is really confusing and not intuitive and the resulting behavior is really hard to debug because you have to figure out so many things and eventually finding the relevant webpack documentation.

**Comment by evilebottnawi** [comment]
@NitroBAY We should do it webpack side, webpack validate configuration, why I ask minimum reproducible test repo? because it is hard to understand that do you mean

**Comment by rishabh3112** [comment]
This can't be done on CLI side alone, it should be done by webpack when it is validating configuration by throwing a warning. Please open the issue for it at main webpack repository.

**Comment by NitroBAY** [comment]
@rishabh3112 okay thanks
