### ISSUE TITLE
bug: version flag doesn't care about other arguments

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1412]
**Describe the bug**

version flag doesn't care about other arguments supplied at the same time.

**What is the current behavior?**

![Screenshot from 2020-04-03 07-44-58](https://user-images.githubusercontent.com/46647141/78355271-0e7b6480-75cb-11ea-933d-c76e9eabbfbb.png)

**To Reproduce**

`webpack --version --abc`

**Expected behavior**

Should throw a warning fo invalid args.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

Looking into it. Open for discussion

**Comment by evilebottnawi** [comment]
Should output error like do other cli, for example eslint do:
```
Invalid option '--abc'.
```

**Comment by snitin315** [comment]
Sounds good. I will work on it.

**Comment by rishabh3112** [comment]
Same is the case with `--help` flag, take on both of them together.

**Comment by anshumanv** [comment]
What happens in case of multiple commands? Which takes precedence?

**Comment by snitin315** [comment]
@anshumanv Can you provide some examples?

**Comment by anshumanv** [comment]
`webpack-cli version init` or `webpack-cli init version`

**Comment by snitin315** [comment]
It should output the version of init as well

**Comment by anshumanv** [comment]
Yep that would be good 👍

**Comment by aman29271** [comment]
I think json flag also doesn't care about any other flag
