### ISSUE TITLE
[BUG]: Output displayed is not colored

### ISSUE THREAD

**Issue by aman29271** [webpack/webpack-cli#1428]
**Describe the bug**

**What is the current behavior?**
The Output result displayed after compilation is not colored in version `4.0.0-beta.8`.

![Screenshot from 2020-04-07 19-17-51](https://user-images.githubusercontent.com/30979779/78677180-0d1ca580-7905-11ea-8d4f-c97c9e09426e.png)

**To Reproduce**
Simply use the updated webpack-cli.
**Expected behavior**
It should display colored output by default.
![Screenshot from 2020-04-07 19-33-33](https://user-images.githubusercontent.com/30979779/78678282-5e796480-7906-11ea-88ad-7853bed8a2f5.png)

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
System Information:
![Screenshot from 2020-04-07 19-27-53](https://user-images.githubusercontent.com/30979779/78677613-9633dc80-7905-11ea-9660-55df4b84bb23.png)

**Additional context**

**Comment by anshumanv** [comment]
We'll be using core flags soon, in that there's a `--stats-colors` flag which will make the stats coloured, CLI should not interfere with the output from core.
