### ISSUE TITLE
docs: packages readme is using url instead of relative path

### ISSUE THREAD

**Issue by himanshu010** [webpack/webpack-cli#1430]
**Describe the bug**

**What is the current behavior?**
![Screenshot (45)](https://user-images.githubusercontent.com/43860289/78702404-27b34680-7926-11ea-92fd-3414d46c9d64.png)
This can be a problem in the forked repo

**To Reproduce**

1. Go to 'Packages directory'
2. Click on 'README.md'
3. See error

**Expected behavior**

Use of relative Path
**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
**Additional context**
I want to work on this issue

**Comment by evilebottnawi** [comment]
No need issue for docs
