### ISSUE TITLE
webpack-cli test organization

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack-cli#1440]
It bothers me that it seems there are 2 places a test could go for a package based on the current system of organization. Take the `info` package for example. Tests for it could either go in `test/info` or in `packages/info/__tests__`.

Is there an intentional distinction between these two locations that I'm missing? It seems all the js tests are in `test/`, while all the ts tests are in `packages/*/__tests__`, but I'm not sure if that is intentional.

I think anything directly testing a particular package should be found at `packages/*/__tests__`. Directories such as `test/info` should be moved into `packages/info/__tests__`, if they pertain to a particular package like `info`. Thoughts?

**Comment by rishabh3112** [comment]
The `test/*` is to check the package behaviour if used through CLI (kindof integration tests).

The tests in the packages are more or less unit tests.

But I am up for this change, if we can maintain the integration tests of packages with CLI in new structure too.

**Comment by evilebottnawi** [comment]
`packages/*/__tests__` are directories for test package directly
`test/*` for integration tests with webpack

**Comment by Loonride** [comment]
This makes sense :+1: It generally seems well organized in that regard
