### ISSUE TITLE
cli[BUG]: --json flag doesn't work

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#1459]
**Describe the bug**

--json flag does not work.

**What is the current behavior?**

--json flag is not respected by the cli, tests are also skipped.

**To Reproduce**

`webpack-cli --json`

**Expected behavior**

Should output the JSON data from the compiler.

**Screenshots**

NA

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
- Fix is wip.

**Comment by aman29271** [comment]
It's working fine with CLI version`3.3.11`.

**Comment by anshumanv** [comment]
Seems broken with next, can you verify?

**Comment by aman29271** [comment]
yup. It's broken.

**Comment by anshumanv** [comment]
Right, tests are also being skipped, will enable them too.
