### ISSUE TITLE
feat(cli): making the CLI help interface more documented

### ISSUE THREAD

**Issue by aman29271** [webpack/webpack-cli#1463]
**Is your feature request related to a problem? Please describe.**
Using CLI help commands gives a list of available commands, flags and their short description. But, when you wanna explore more lets say you want to know about stats flag, like how can i use stats flag or which arguments are valid. It should also provide a more descriptive information about stats flag. But right now, It just provide a short desc about that flag.
```bash
~/Desktop/test$ npx webpack-cli help --stats
Usage: webpack --stats verbose
Description: It instructs webpack on how to treat the stats
Documentation: https://webpack.js.org/configuration/stats/#stats

                  Made with ♥️  by the webpack team
```

**Describe the solution you'd like**
So, I propose to provide a long and short description for each flag and commands available through CLI. 

Benefits 
- more descriptive 
- for starters, they don't have to go through documentation.
- offline support :smile: 

**Describe alternatives you've considered**
```bash
~/Desktop/test$ npx webpack-cli help --stats
Usage: webpack --stats verbose

Description: 

Example: npx webpack-cli --stats verbose

Accepted Value:  none | errors-only | minimal | normal | detailed | verbose | errors-warnings

It instructs webpack on how to treat the stats

Documentation: https://webpack.js.org/configuration/stats/#stats

                  Made with ♥️  by the webpack team
```

**Additional context**
Hit me up for any suggestions

**Comment by snitin315** [comment]
Well we are already providing a link to docs, For more information.

**Comment by snitin315** [comment]
But we should print accepted values,  nice to have.

**Comment by aman29271** [comment]
PR #1461

**Comment by snitin315** [comment]
Please don't mix various corrections in one PR. create a new PR for this one.
Also this needs discussion first.

**Comment by aman29271** [comment]
Some of the tests fails due to `--color` flag. So, Are this gonna implement `--color`  in future or should I just comment out them.

**Comment by snitin315** [comment]
No, don't skip the tests. If tests are failing means code should be reviewed. You can always create a PR and ask for help if got stuck somewhere.

**Comment by evilebottnawi** [comment]
bump
