### ISSUE TITLE
@webpack-cli/package-utils should have dependency on cross-spawn

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [webpack/webpack-cli#1494]
**Describe the bug**

The `@webpack-cli/package-utils` package uses the `cross-spawn` package but does not list `cross-spawn` as a dependency in its `package.json` file. With Yarn's new Plug-and-Play infrastructure, this results in an error:

> @webpack-cli/package-utils tried to access cross-spawn, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: cross-spawn (via "cross-spawn")

Can we please add `cross-spawn`, and any other packages that `@webpack-cli/package-utils` utilizes via `require()`, to the `package-utils` `package.json` file?

Thanks :)

**Comment by anshumanv** [comment]
It already has it - https://github.com/webpack/webpack-cli/blob/c16789b9e00c1c8ded754bdad8a0b1f8e5f79456/packages/package-utils/package.json#L37

**Comment by Bosch-Eli-Black** [comment]
Thanks, @anshumanv. It looks like when I download the [webpack-cli@4.0.0-beta.8](https://github.com/webpack/webpack-cli/releases/tag/webpack-cli%404.0.0-beta.8) and open `packages/package-utils/package.json`, then `cross-spawn` isn't listed as a dependency, though.

Do you think the newest version of that file just isn't included in the 4.0.0-beta.8 release, or is it perhaps somehow being stripped out by Lerna or another tool?

**Comment by anshumanv** [comment]
Yes @Bosch-Eli-Black,

I added it last month in this commit https://github.com/webpack/webpack-cli/commit/0fd89e697f4c01bb9301512a06b420a84a79bdb1 which was after the release, should be alright after the next release. :)

**Comment by Bosch-Eli-Black** [comment]
@anshumanv  Oh, okay, great! Thanks a ton :)

**Comment by thefoxie** [comment]
@anshumanv this issue remains unresolved since the next beta package hasn't been released yet

**Comment by anshumanv** [comment]
Yep, @evilebottnawi will be making a release soon
