### ISSUE TITLE
Bug: ProgressPlugin in config file doesn't work as expected

### ISSUE THREAD

**Issue by aman29271** [webpack/webpack-cli#1497]
**Describe the bug**

**What is the current behavior?**
When I mention `ProgressPlugin` in webpack config file. It does not show the progress of webpack compilation. 

**To Reproduce**

Add `ProgressPlugin` in webpack config file

**Expected behavior**
It should show the progress of compilation process. 

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by snitin315** [comment]
we support `webpack --progress`  to show progress.

**Comment by evilebottnawi** [comment]
@snitin315 we should add tests and keep what we don't add  `ProgressPlugin` twice and respect output with `ProgressPlugin` and with the `--progress` flag

**Comment by anshumanv** [comment]
in near future

**Comment by anshumanv** [comment]
@evilebottnawi what should be the behaviour when ProgressPlugin is manually applied along with `--progress` should we add it only once and if yes then the one coming from config right?

**Comment by evilebottnawi** [comment]
Yes, `--progress` should do nothing if you already have `ProgressPlugin`

**Comment by evilebottnawi** [comment]
I think it is already fixed, need add test(s)

**Comment by anshumanv** [comment]
gotcha on it
