### ISSUE TITLE
TypeError: Ajv is not a constructor

### ISSUE THREAD

**Issue by okonet** [webpack/webpack-cli#151]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

```
okonet@Okonet-MBP:~/Projects/OSS/webpack-cli% node bin/webpack.js migrate ./lib/transformations/loaders/__testfixtures__/loaders-7.input.js
/Users/okonet/Projects/OSS/webpack-cli/lib/utils/validateSchema.js:9
const ajv = new Ajv({
            ^

TypeError: Ajv is not a constructor
    at Object.<anonymous> (/Users/okonet/Projects/OSS/webpack-cli/lib/utils/validateSchema.js:9:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/okonet/Projects/OSS/webpack-cli/lib/migrate.js:7:24)
    at Module._compile (module.js:570:32)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Check out master
1. Run `npm install`
1. Run `node bin/webpack.js migrate ./lib/transformations/loaders/__testfixtures__/loaders-7.input.js`

**What is the expected behavior?**

It should run the migration

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

node v6.10.2
npm 3.10.10

**Comment by ev1stensberg** [comment]
Try `rm -rf node_modules && npm install` ?

**Comment by okonet** [comment]
I did try this already. Still happening...

**Comment by ev1stensberg** [comment]
It's not happening on mine. Do you have any more test cases? Tried running your reproduce, but didn't get the error as expected .

**Comment by okonet** [comment]
One more attempt to remove everything and reinstalling helped. We should probably move to `yarn` to prevent this in future.

**Comment by ev1stensberg** [comment]
Gotcha. Discard my last message from an thread earlier today. Yarn is good to go after yeoman migration hopefully.
