### ISSUE TITLE
[Feature]: Re-add old CLI flags

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#1517]
**Is your feature request related to a problem? Please describe.**

Right now, we don't have all the old CLI flags. It would be good to add them back along with new webpack v5 config options.

**Describe the solution you'd like**

Flags added back in `cli-flags.js` file.

**Describe alternatives you've considered**

N/A
**Additional context**

You can have a look at the old flags by looking at the master branch of webpack-cli

**Comment by evilebottnawi** [comment]
No, now we have API for flags on webpack side and we should use it, for webpack@4 we should support only minimum flags (what we supported now), we don't need doing extra unnecessary work

**Comment by evenstensberg** [comment]
I think we should have the old api, minimal flags makes the CLI just a skeleton. We should support a set of features that the old CLI provided

**Comment by evilebottnawi** [comment]
@evenstensberg Why? We don't need to do double work, most of developers prefer configurations over CLI flags, so it is not priority and require a lot of unnecessary work, which most likely will not be used by most developers

**Comment by evenstensberg** [comment]
Okay, I'm +1 on that. My idea was that we support it nonetheless to make it more sleek to devs that end up using the CLI only for development purposes instead of a config file.

**Comment by snitin315** [comment]
As per roadmap:
-   for __webpack@4__ support only popular, like `mode`, `stats`  and etc  (already supported)
-   for __webpack@5__ support all flags provided by webpack API

**Comment by evilebottnawi** [comment]
@snitin315 Yes :+1:

**Comment by evilebottnawi** [comment]
Let's close it, we don't need old flags, webpack@5 have api, for webpack@4 we will support only limited flags
