### ISSUE TITLE
[BUG]: fix linting and test suite

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#1526]
**Describe the bug**

I'm trying to run webpack-cli test locally.

**What is the current behavior?**
Right now, if you do a fresh test, the tests aren't being run due failing linting errors.

**To Reproduce**

1. clone webpack-cli
2. yarn install
3. yarn test

**Expected behavior**

Tests and linting being correct

**Screenshots**

<img width="564" alt="Screen Shot 2020-05-06 at 18 20 01" src="https://user-images.githubusercontent.com/16735925/81202389-d484f000-8fc6-11ea-836d-ab20d9418c5f.png">

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

N/A

**Additional context**

Does anybody know which commit this started to fail from?

**Comment by snitin315** [comment]
I remember I encountered the same issue once, but the next day everything was working fine.

**Comment by snitin315** [comment]
And what about `yarn test:cli` , working as expected?

**Comment by snitin315** [comment]
@evenstensberg I was unable to reproduce, everything worked as expected for me with a fresh clone and installation.

![Screenshot at 2020-05-07 14-15-28](https://user-images.githubusercontent.com/46647141/81274119-8119ad00-906d-11ea-8584-54b32b6b1bb8.png)
 
/cc @rishabh3112 @jamesgeorge007 @anshumanv @evilebottnawi

**Comment by anshumanv** [comment]
Unable to repro, lint, test everything works.

@evenstensberg maybe try removing the node_modules and yarn.lock and reinstalling once?

**Comment by evilebottnawi** [comment]
Yes, please install latest dependencies, maybe you have global prettier or broken local configuration
