### ISSUE TITLE
Update loader-utils on v3 branch to fix audit vulnerability.

### ISSUE THREAD

**Issue by dscalzi** [webpack/webpack-cli#1532]
`npm audit` is unable to fix a a vulnerability because there is no version range on the `loader-utils` dependency (https://github.com/webpack/webpack-cli/blob/master/package.json#L123).

![image](https://user-images.githubusercontent.com/9703873/81503216-61be9200-92b0-11ea-976c-409cbc17c69a.png)

Updating this dependency and releasing v3.3.12 will fix the issue. (https://www.npmjs.com/advisories/1179/versions)

**Comment by anshumanv** [comment]
Thanks for reporting.

Will submit a fix 👍

**Comment by dscalzi** [comment]
Any update?

**Comment by anshumanv** [comment]
Hi, occupied with other tasks, can your PR or anyone from @webpack/cli-team would like to pick this up?

**Comment by jamesgeorge007** [comment]
@evilebottnawi please do a patch release.

**Comment by evilebottnawi** [comment]
@jamesgeorge007 in TODO

**Comment by dscalzi** [comment]
Thanks, fixed
