### ISSUE TITLE
Stats output without stdout

### ISSUE THREAD

**Issue by fgarcia** [webpack/webpack-cli#1535]
## Feature request
Generate a JSON stats file directly without forcing the user to redirect the stdout output

**What is the expected behavior?**
An option like --json that writes the output directly into a file

**What is motivation or use case for adding/changing the behavior?**
Build stats are a key feature for tracking (and linting) the quality of a build-pipeline. According the current documentation the only way to save the stats is [redirecting the stdout](https://webpack.js.org/api/stats/). 

The major problem is that when a user runs a manual build, it is not possible to get a build progress status because the progress line/text would mangle the json output.

**How should this be implemented in your opinion?**

1) add an option with the file output
--json-output [file]
--json-file [file]

2) Reference in the documentation the [Json Stats plugin]( https://www.npmjs.com/package/webpack-stats-plugin) 

Yes, there is already a plugin for this, but I believe the need for this feature justifies at a minimum a clear reference in the documentation about how to achieve this.

**Are you willing to work on this yourself?**
no

**Comment by anshumanv** [comment]
Can't we just do `webpack-cli --json >> stats.json` ?

**Comment by snitin315** [comment]
Now we support multiple types, hence we can easily support -

- `webpack --json` : print on console.
- `webpack --json path/to/stats.json`

**Comment by fgarcia** [comment]
@anshumanv `webpack-cli --json >> stats.json` will not print any report after the command finishes. I wanted the json report AND the nicely printed console report, not being forced to choose just one. It is just not possible to have two reports if both depend on stdout

@snitin315 I am running `3.3.12` and it is still just stdout output. Did you mean instead that it could be done?

**Comment by anshumanv** [comment]
> @anshumanv webpack-cli --json >> stats.json will not print any report after the command finishes. I wanted the json report AND the nicely printed console report, not being forced to choose just one. It is just not possible to have two reports if both depend on stdout

Makes sense, should we add a flag for this @evilebottnawi?

**Comment by snitin315** [comment]
> @snitin315 I am running `3.3.12` and it is still just stdout output. Did you mean instead that it could be done?

I meant we can easily implement this feature in v4.

**Comment by fgarcia** [comment]
@snitin315 I am not sure if there is a regression regarding this feature or I did miss a detail about this feature.

In the latest release I see this message:

```
webpack --progress --json _build/reports/webpack.json
[webpack-cli] stats are successfully stored as json to  {...}/_build/reports/webpack.json
```

So the first part of the issue is OK but now all the nice reports/warnings from webpack are gone too

My original intention was being able to preserve the useful bits printed to stdout/stderr printed by a normal `webpack --progress` run (like stats, assets, warnings...) while also generating a JSON report for analytic tools

Right now using `--json {file}` kills the usual reports, so I am back to being forced between just JSON report or nice  stdout/stderr.

I think the issue should be either reopened

**Comment by alexander-akait** [comment]
`--progress` write output in stderr

**Comment by fgarcia** [comment]
Not anymore, I've just tested the pipe method:

`NODE_ENV=production webpack --progress --json > /tmp/foo.json`

Before I could see the stderr from `--progress` printed to screen and the json report redirected. However that sacrificed the user-friendly report with the assets/sizes summary

Now with that line the progress does not show in screen (stderr) or the redirected file (stdout)

The end goal was preserving nice stdout/stdin for the user and a file for CI tools like bundle analyzer

**Comment by alexander-akait** [comment]
hm, yep, `webpack --progress=profile --json > stdout 2> stderr` should work, but stderr is empty, need to fix
