### ISSUE TITLE
Last webpack 5.0.0-beta.16 and webpack-cli 4.0.0-alpha-5 are not compatibile

### ISSUE THREAD

**Issue by predragdavidovic** [webpack/webpack-cli#1559]
**Describe the bug**
I'm trying tu upgrade webpack to version 5. And when I upgrade webpack-cli from version 3 to version 4 I got this bug: 

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

If I go back, and install webpack-cli version 3, I do not have this bug.
But I'm wondering how newest webpack do not work with newest webpack-cli, but work with old version.
And is it possbile to use webpack 5 with webpack-cli 4?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

If you run webpack-dev-server please use `webpack server` and please respect other developers and use the issue template in the future
