### ISSUE TITLE
[Migrate] ES2015 file with import / export couldn't be migrated

### ISSUE THREAD

**Issue by okonet** [webpack/webpack-cli#156]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

File with `export` keyword throws an error

**If the current behavior is a bug, please provide the steps to reproduce.**

`node bin/webpack.js migrate ./lib/transformations/loaders/__testfixtures__/loaders-7.input.js`

## Error:

```
 ✔ Reading webpack config
 ✔ Migrating config from v1 to v2
-         loaders: [
+         rules: [
-                 loader: 'babel-loader',
                query: {
+                 use: [{
                    loader: 'babel-loader'
                }],
                options: {
? Are you sure these changes are fine? Yes
/Users/okonet/Projects/OSS/webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-7.input.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at fs.writeFile (/Users/okonet/Projects/OSS/webpack-cli/lib/migrate.js:72:84)
```

**Comment by ev1stensberg** [comment]
Yeah, but export default isn't valid in node explicitly, is it? We're using babel, but might be something there.

**Comment by okonet** [comment]
Okay If we decide not to support it we can close it then.

**Comment by ev1stensberg** [comment]
We are supposed to support it, I just dont understand how export default could work :)

**Comment by okonet** [comment]
What do you mean how it could work. The problem is that the syntax isn't recognized

**Comment by ev1stensberg** [comment]
Yeah and that part is what I dont understand, couøf you give me a link to some blog post? Ive always done module.exports

**Comment by okonet** [comment]
http://2ality.com/2014/09/es6-modules-final.html

**Comment by ev1stensberg** [comment]
Ok gotcha. My guess is that in defineTest we do something that is reliant on the standard defininition. I can check it out next week

**Comment by ev1stensberg** [comment]
Don't know if we can support this, feel free to submit another issue if you believe it should
