### ISSUE TITLE
Terser is executed twice, when explicit configured as minimizer

### ISSUE THREAD

**Issue by CGollhardt** [webpack/webpack-cli#1564]
# Bug report

**What is the current behavior?**
It seems the *default* terser is executed, even if configured a custom one

- default `*.LICENSE.txt`, and custom `*.OTHER.LICENSE.txt` is created
- even if disabled, sourceMap is generated

![Output](https://i.imgur.com/RGKmT1g.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Have the following optimization:
```
const TerserPlugin = require('terser-webpack-plugin');
optimization = {
    minimizer:
    [
        new TerserPlugin({
            sourceMap: false,
            extractComments: {
                filename: (fileData) => {
                    return `${fileData.filename}.OTHER.LICENSE.txt${fileData.query}`;
                }
            }
        })
    ]
}
```

**What is the expected behavior?**

Terser is not executed twice.

**Other relevant information:**
webpack version:
^5.0.0-beta.16
terser version:
^3.0.1
Node.js version:
12.16.3
Operating System: 
Windows 10

**Comment by anshumanv** [comment]
@evilebottnawi is it because we're hardcoded devtool in production config which is used when mode production/development? https://github.com/webpack/webpack-cli/blob/dec153e428b584e9480e1ae51657a718663a16ab/packages/webpack-cli/lib/utils/production-config.js#L8

**Comment by evilebottnawi** [comment]
@anshumanv we should not merge this config in production mode, it is a whole invalid logic, just set `compiler.mode` to `production`

**Comment by evilebottnawi** [comment]
webpack provide default configuration for a mode out of box

**Comment by anshumanv** [comment]
Will fix

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack-cli/pull/1565
