### ISSUE TITLE
BUG: --plugin flag does not work

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1570]
**Describe the bug**

`--plugin` flag is not working.

**What is the current behavior?**
`--plugin` is using a function that is commented out.

https://github.com/webpack/webpack-cli/blob/505843c510a89756b17650ee1d0ae90465b2bc6e/packages/webpack-cli/lib/groups/AdvancedGroup.js#L8

https://github.com/webpack/webpack-cli/blob/505843c510a89756b17650ee1d0ae90465b2bc6e/packages/webpack-cli/lib/groups/AdvancedGroup.js#L73

**To Reproduce**

`webpack --plugin <plugin-name>`

**Expected behavior**

Should load the given plugin.

**Screenshots**
![Screenshot at 2020-05-22 17-51-08](https://user-images.githubusercontent.com/46647141/82667130-d7cddc00-9c54-11ea-92bd-694ddbb0da7e.png)

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
NA
**Additional context**
NO

**Comment by snitin315** [comment]
I guess developers prefer to load plugin via webpack config.

**Comment by evilebottnawi** [comment]
I think same, let's remove it

**Comment by snitin315** [comment]
I will create a PR shortly.
