### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by anyulled** [webpack/webpack-cli#158]
**What is the current behavior?**
Whenever I try to instal webpack cli I receive the following error:

> npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
> -get remote.origin.url
> npm WARN addRemoteGit
> npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
> npm WARN addRemoteGit     at emitTwo (events.js:106:13)
> npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
> npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
> npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
> npm WARN addRemoteGit  git://github.com/kalcifer/recast.git#bug/allowbreak resetting remote C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\git-github-com-kalcifer-recast-git-bug-allowbreak-1a0638d4 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
> npm WARN addRemoteGit
> npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
> npm WARN addRemoteGit     at emitTwo (events.js:106:13)
> npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
> npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
> npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
> npm WARN addRemoteGit   killed: false,
> npm WARN addRemoteGit   code: 1,
> npm WARN addRemoteGit   signal: null,
> npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
> npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
> npm WARN addRemoteGit
> npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
> npm WARN addRemoteGit     at emitTwo (events.js:106:13)
> npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
> npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
> npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:11)
> npm WARN addRemoteGit     at emitOne (events.js:96:13)
> npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
> npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:492:12)
> npm WARN addRemoteGit  git://github.com/ev1stensberg/generator.git#Feature-getArgument resetting remote C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ev1stensberg-generator-git-Feature-getArgument-9d0a58a8 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
> npm WARN addRemoteGit
> npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
> npm WARN addRemoteGit     at emitTwo (events.js:106:13)
> npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
> npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
> npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:11)
> npm WARN addRemoteGit     at emitOne (events.js:96:13)
> npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
> npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:492:12)
> npm WARN addRemoteGit   killed: false,
> npm WARN addRemoteGit   code: 1,
> npm WARN addRemoteGit   signal: null,
> npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
> npm ERR! git clone --template=C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/ev1stensberg/generator.git C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ev1stensberg-generator-git-Feature-getArgument-9d0a58a8: Cloning into bare repository 'C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ev1stensberg-generator-git-Feature-getArgument-9d0a58a8'...
> npm ERR! git clone --template=C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/ev1stensberg/generator.git C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ev1stensberg-generator-git-Feature-getArgument-9d0a58a8: fatal: unable to connect to github.com:
> npm ERR! git clone --template=C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/ev1stensberg/generator.git C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ev1stensberg-generator-git-Feature-getArgument-9d0a58a8: github.com[0: 192.30.253.112]: errno=Invalid argument
> npm ERR! git clone --template=C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/ev1stensberg/generator.git C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ev1stensberg-generator-git-Feature-getArgument-9d0a58a8: github.com[1: 192.30.253.113]: errno=Invalid argument
> npm ERR! git clone --template=C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/kalcifer/recast.git C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\git-github-com-kalcifer-recast-git-bug-allowbre
> ak-1a0638d4: Cloning into bare repository 'C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\git-github-com-kalcifer-recast-git-bug-allowbreak-1a0638d4'...
> npm ERR! git clone --template=C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/kalcifer/recast.git C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\git-github-com-kalcifer-recast-git-bug-allowbreak-1a0638d4: fatal: unable to connect to github.com:
> npm ERR! git clone --template=C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/kalcifer/recast.git C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\git-github-com-kalcifer-recast-git-bug-allowbreak-1a0638d4: github.com[0: 192.30.253.112]: errno=Invalid argument
> npm ERR! git clone --template=C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/kalcifer/recast.git C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\git-github-com-kalcifer-recast-git-bug-allowbreak-1a0638d4: github.com[1: 192.30.253.113]: errno=Invalid argument
> npm ERR! code 128
> npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/ev1stensberg/generator.git C:\Users\alrs\AppData\Roaming\npm-cache\_git-remotes\g
> it-github-com-ev1stensberg-generator-git-Feature-getArgument-9d0a58a8
> npm ERR! Cloning into bare repository 'C:\Users\alrs\AppData\Roaming\npm-cache\_
> git-remotes\git-github-com-ev1stensberg-generator-git-Feature-getArgument-9d0a58a8'...
> npm ERR! fatal: unable to connect to github.com:
> npm ERR! github.com[0: 192.30.253.112]: errno=Invalid argument
> npm ERR! github.com[1: 192.30.253.113]: errno=Invalid argument
> npm ERR!
> npm ERR!

**If the current behavior is a bug, please provide the steps to reproduce.**
npm i webpack-cli -g

**What is the expected behavior?**
successful installation

**Node version:** 6.3.1
**npm version:** 4.5.0
**operating system:** Windows 10
**programming language:** Javascript
**webpack version:** 2.6.0

**Comment by anyulled** [comment]
Hi, I was checking the issues list and got it working by doing
`git config --global url."https://".insteadOf git://` as suggested in #132 .

**Comment by ev1stensberg** [comment]
Yep, just saw. Commented there, need some more info to reproduce.

**Comment by dchhetri** [comment]
@anyulled suggestion didn't work for me due to a SSL certification issue.

```
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t git://github.com/ev1stensberg/generator.git
npm ERR!
npm ERR! fatal: unable to access 'https://github.com/ev1stensberg/generator.git/': SSL certificate problem: self signed certificate
npm ERR!
npm ERR! exited with error code: 128
```

**Comment by ev1stensberg** [comment]
Yeah, that's the fork messing things up. Let's bundle the discussion at the other thread
