### ISSUE TITLE
webpack-cli v4-beta.8 ignoring loader's error.

### ISSUE THREAD

**Issue by mstssk** [webpack/webpack-cli#1581]
**Describe the bug**

webpack-cli v4-beta.8 ignoring loader's error.

Reproduction code: https://github.com/mstssk/webpack-cli-v4-beta8-ignore-loader-error

I wrote reproduction code of ts-loader, but this problem occurs with other loaders. e.g. file-loader.

**What is the current behavior?**

webpack-cli v3.3.11 fails and returns exit code 2 when an error occurs in loaders.
But webpack-cli v4.0.0-beta.8 does not fail and return exit code 0.

**To Reproduce**

1. Setup webpack@4.43.0, webpack-cli@4.0.0-beta.8, and some loaders
2. Write codes which raise error in loaders.
3. Run webpack
4. See error logs and status code.

**Expected behavior**

webpack fails and returns non-zero exit code when an error occurs in loaders.

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

`webpack-cli info` fails in my env.

<details>
<summary>`webpack-cli info` Log</summary>

```
 $ npx webpack-cli info
[webpack-cli] Promise rejection: TypeError: Cannot convert undefined or null to object
[webpack-cli] TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Object.<anonymous> (/private/tmp/webpack-cli-v4-beta8-ignore-loader-error/node_modules/@webpack-cli/info/index.js:45:41)
    at Generator.next (<anonymous>)
    at /private/tmp/webpack-cli-v4-beta8-ignore-loader-error/node_modules/@webpack-cli/info/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/private/tmp/webpack-cli-v4-beta8-ignore-loader-error/node_modules/@webpack-cli/info/index.js:4:12)
    at Object.info [as default] (/private/tmp/webpack-cli-v4-beta8-ignore-loader-error/node_modules/@webpack-cli/info/index.js:44:12)
    at Function.run (/private/tmp/webpack-cli-v4-beta8-ignore-loader-error/node_modules/webpack-cli/lib/commands/ExternalCommand.js:34:51)
    at WebpackCLI.runCommand (/private/tmp/webpack-cli-v4-beta8-ignore-loader-error/node_modules/webpack-cli/lib/webpack-cli.js:286:60)
    at runCLI (/private/tmp/webpack-cli-v4-beta8-ignore-loader-error/node_modules/webpack-cli/lib/bootstrap.js:61:26)
```

</details>

**Additional context**

https://github.com/webpack/webpack-cli/issues/1222#issuecomment-633485026

**Comment by consp1racy** [comment]
✖ ｢atl｣: Checking finished with 2 errors

and exits with 0.

**Comment by snitin315** [comment]
I will debug.

**Comment by snitin315** [comment]
@mstssk I have the following observations 
  
## with `webpack-4` and `webpack-cli@3` -
![Screenshot at 2020-08-06 14-29-11](https://user-images.githubusercontent.com/46647141/89513527-4cdf9500-d7f2-11ea-9ab5-56f6f099feb9.png)

## with `webpack-4` and `webpack-cli@4.0.0-beta.8`
![Screenshot at 2020-08-06 14-29-34](https://user-images.githubusercontent.com/46647141/89513624-6aacfa00-d7f2-11ea-9049-9ced40bf0270.png)

## with `webpack@next` and `webpack-cli next branch` 
![Screenshot at 2020-08-06 14-42-43](https://user-images.githubusercontent.com/46647141/89514198-2a01b080-d7f3-11ea-9e4d-055bda0f3269.png)

**Comment by snitin315** [comment]
> Expected behavior
webpack fails and returns exit code 0 when an error occurs in loaders.

Exit code 0 means the code was executed successfully without any failures. So if webpack fails it should exit with a non-zero exit code. Please correct me if I'm wrong.

**Comment by mstssk** [comment]
@snitin315 Thank you for your help.

> Expected behavior
webpack fails and returns exit code 0 when an error occurs in loaders.

Oops! I typoed it. 
`non-zero exit code` is correct.

I edit this issue's description.
Thank you.

**Comment by snitin315** [comment]
I think then it's work as expected against the `webpack-cli next branch` I will add tests for the same.

**Comment by evilebottnawi** [comment]
@snitin315 Can you add test on this?

**Comment by snitin315** [comment]
Yes. Work in progress.
