### ISSUE TITLE
docs: update installation guidelines

### ISSUE THREAD

**Issue by shrey** [webpack/webpack-cli#1584]
**What kind of changes does this PR introduce?**
DOCS
**Did you add tests to your PR?**
NA
**If relevant, did you update the documentation?**
Yes
**Summary**
Tried to start working with the CLI, although had to download the beta version and also add npx before the commands, So I think the contribution guidelines should be updated. I'd be more than willing to do that.
**Does this PR introduce a breaking change?**
No
**Other Information**

**Comment by snitin315** [comment]
First, you used our PR template instead of Issue template,
Second, if you don't want to use `npx` install the package globally.

**Comment by shrey** [comment]
Oh alright, thanks
