### ISSUE TITLE
Watch mode doesn't work in specific folder

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack-cli#16]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
Windows 7

**Current behavior:**

Minimal test case.

Consider the following JS file `index.js` (the only file in a folder):

```
var k = 0;
```

I'm trying to start webpack in watch mode:

```
webpack index.js bundle.js --watch
```

When my work folder is `c:\dev\`, everything works as expected. But if I work in folder `c:\Program Files (x86)\Apache Software Foundation\Apache2.2\htdocs\`, webpack doesn't rebuild project after I change `index.js` file.

**Expected/desired behavior:**
Watch mode should work in any folder.

**Notes**
I tried to understand the source of the problem. Looks like npm module `is-glob` (dependency list: `webpack`->`watchpack`->`chokidar`->`is-glob`) thinks that `c:\Program Files (x86)\Apache Software Foundation\Apache2.2\htdocs\` is a glob and `watchpack` tries to listen changes in wrong not existing directory (`c:\Program Files x86\Apache Software Foundation\Apache2.2\htdocs\`?).

Maybe, it will help you to fix this bug!

**Moved from https://github.com/webpack/webpack/issues/2994**

**Comment by SpaceK33z** [comment]
Moving again since this was the wrong project :smile:. Moved to https://github.com/webpack/watchpack/issues/42.
