### ISSUE TITLE
Error: Cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by richburdon** [webpack/webpack-cli#1602]
**Describe the bug**

Possible regression of: https://github.com/webpack/webpack-dev-server/issues/2029

**What is the current behavior?**

The following error running webpack-dev-server:

```
The CLI moved into a separate package: webpack-cli
Please install 'webpack-cli' in addition to webpack itself to use the CLI
-> When using npm: npm i -D webpack-cli
-> When using yarn: yarn add -D webpack-cli
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /Users/burdon/Projects/src/dxos/console/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/burdon/Projects/src/dxos/console/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/burdon/Projects/src/dxos/console/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
```

**To Reproduce**

`yarn webpack-dev-server'

**Expected behavior**

Dev server should start

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

```
  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.71 GB / 32.00 GB
  Binaries:
    Node: 12.16.3 - /var/folders/g3/bdcdx0l516l_x6lh5pnsksxw0000gn/T/yarn--1590950071541-0.6189552325477377/node
    Yarn: 1.22.4 - /var/folders/g3/bdcdx0l516l_x6lh5pnsksxw0000gn/T/yarn--1590950071541-0.6189552325477377/yarn
    npm: 6.14.4 - ~/.nodenv/versions/12.16.3/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 76.0.1
    Safari: 13.1.1
  npmPackages:
    dotenv-webpack: ^1.8.0 => 1.8.0
    html-webpack-plugin: ^4.3.0 => 4.3.0
    webpack: ^4.41.2 => 4.43.0
    webpack-cli: ^3.3.11 => 3.3.11
```

With config:

```
    "webpack": "^4.41.2",
    "webpack-bundle-analyzer": "^3.6.0",
    "webpack-cli": "^3.3.10",
    "webpack-dev-server": "^3.11.0",
    "webpack-merge": "^4.2.2",
    "webpack-version-file-plugin": "^0.4.0",
```

**Comment by richburdon** [comment]
This seems to be an issue with monorepos when `webpack-cli` is hoisted.

The workaround is to add the dependency to the monorepo root `package.json` but this shouldn't be necessary.

**Comment by evilebottnawi** [comment]
Yes it is a bug, not related to `webpack-cli`, bug on `webpack-dev-server` side

**Comment by hpachy** [comment]
Hello,

I would like to know is a solution is currently available... I started webpack yesterday to improve and have more control on my application. This bug make me puzzled about it's because in the webpack tutorial a lot of manipulation use webpack-dev-server.

Hopefully it's a good place to ask my question.

Regards

**Comment by evilebottnawi** [comment]
@hpachy Can you provide links?

**Comment by hpachy** [comment]
for example this one : 

-https://webpack.js.org/guides/development/
-https://webpack.js.org/guides/build-performance/ (compile memory)
-https://webpack.js.org/guides/development-vagrant/
-https://webpack.js.org/guides/hot-module-replacement/ (webpack-dev-server --hotOnly)

for now I stoped here but I'm still following the tutorial, it's maybe my bad but I tried it and it's not working / not fixed so I just asking you if it s totaly fine or not ;)

regards

**Comment by evilebottnawi** [comment]
Big thanks, WIP on docs

**Comment by evilebottnawi** [comment]
@hpachy PR was sent

**Comment by hpachy** [comment]
your welcome it's been a pleasure!

**Comment by rajivbandaru97** [comment]
npm run build

> vuedj@1.0.0 build G:\shareip\vuedj
> cross-env NODE_ENV=production webpack --progress --hide-modules

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'v8-compile-cache'
Require stack:
- C:\Users\lenovo\AppData\Roaming\npm\node_modules\webpack-cli\bin\cli.js
- G:\shareip\vuedj\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\lenovo\AppData\Roaming\npm\node_modules\webpack-cli\bin\cli.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\lenovo\\AppData\\Roaming\\npm\\node_modules\\webpack-cli\\bin\\cli.js',
    'G:\\shareip\\vuedj\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuedj@1.0.0 build: `cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vuedj@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2020-11-22T07_22_05_093Z-debug.log



I ran the command npm-doctor.
It asked me to update my npm and node. I did that as mentioned. I even changed my environment variable path to c:/program files/nodejs, still getting the same error. Is the error related with the webpack-cli? It would be really helpful if I get some insight into this. Thanks in advance.
