### ISSUE TITLE
v3.3.12 listed as released but has not been published to public npm registry

### ISSUE THREAD

**Issue by claytonhottinger** [webpack/webpack-cli#1620]
**Describe the bug**
v3.3.12, which fixes a [low vulnerability](https://snyk.io/vuln/npm:yargs-parser) by [updating the yargs dependency](https://github.com/webpack/webpack-cli/commit/33574ec82e1f6d8b71e872db086bbfaaf77707ba), is listed [under releases](https://github.com/webpack/webpack-cli/releases/tag/v3.3.12) but the npm registry still shows [3.3.11 as the latest version](https://www.npmjs.com/package/webpack-cli)

**What is the current behavior?**
v3.3.12 is unavailable via `npm install`

**To Reproduce**
1. `npm install webpack-cli@3.3.12`
2. Notice "No matching version found" error

**Expected behavior**
v3.3.12 can be installed

**Comment by evilebottnawi** [comment]
Yes, some problems with npm, release will be tomorrow

**Comment by claytonhottinger** [comment]
@evilebottnawi thanks for the update... however it looks like the release still hasn't happened. Can you provide a new eta?

**Comment by evilebottnawi** [comment]
today/tomorrow

**Comment by danactive** [comment]
Hey @evilebottnawi I'm also waiting on this `npm publish` command otherwise I will break my build with a snyk test

**Comment by evilebottnawi** [comment]
Done, sorry for delay
