### ISSUE TITLE
Error loading a plugin created via plugin command

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1623]
**Describe the bug**

The default plugin created via `webpack plugin` throws the following error when loaded in `webpack.config.js`

**What is the current behavior?**
`SyntaxError Unexpected token '.'`

**To Reproduce**

1. generate a plugin via `webpack-cli plugin`
2. Go to examples/simple
3. Run `webpack`

**Expected behavior**
Should work properly

**Screenshots**
![Screenshot at 2020-06-08 08-45-32](https://user-images.githubusercontent.com/46647141/83989707-e7436980-a964-11ea-8419-71da2f33d9cc.png)

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by evilebottnawi** [comment]
Feel free to fix it :+1:
