### ISSUE TITLE
webpack-cli init <your-scaffold> is error

### ISSUE THREAD

**Issue by fangbao-0418** [webpack/webpack-cli#1626]
![image](https://user-images.githubusercontent.com/19402021/84169145-d997fc00-aaaa-11ea-8ed7-771630bd35b4.png)

webpack-cli version 3.3.11

**Comment by snitin315** [comment]
Can you once try with webpack-cli@beta ?

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack-cli/issues/1127
