### ISSUE TITLE
exclude functions in OccurrenceOrderPlugin

### ISSUE THREAD

**Issue by wormen** [webpack/webpack-cli#163]
What parameters do I need to write so that certain function names remain unchanged after optimization?

In the documentation I did not see it

**Comment by ev1stensberg** [comment]
https://webpack.js.org/guides/migrating/#occurrenceorderplugin-is-now-on-by-default its by default in webpack 2. What you could do, is writing your own plugin!

**Comment by pksjce** [comment]
@wormen - I don't think this is an issue with the CLI. Would be great to open a relevant stackoverflow issue. Please re-open when you can add more details on the issue.
