### ISSUE TITLE
feature: integration of serve package into cli

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack-cli#1634]
**Is your feature request related to a problem? Please describe.**
Part of roadmap, we would be integrating serve by default into the CLI so that user need not install it to use dev-server from command line.

**Describe the solution you'd like**
- [ ] Robust tests for `serve`'s current features (if needed)
- [ ] Refactor `serve` and add/remove features from it
- [ ] Add tests for the previous step changes (if any)
- [ ] Integrate it with CLI
- [ ] Add integration tests for verifying integration

**Describe alternatives you've considered**

**Additional context**
Roadmap #717 

/cc @evilebottnawi

**Comment by evilebottnawi** [comment]
+ https://github.com/webpack/webpack-cli/issues/1469

**Comment by anshumanv** [comment]
The fix for the above issue is here - https://github.com/webpack/webpack-cli/pull/1470

Can we move forward in it @evilebottnawi ?

**Comment by rishabh3112** [comment]
Yes, we can.

**Comment by evilebottnawi** [comment]
Thanks for helping
