### ISSUE TITLE
Cannot install webpack-cli using npm

### ISSUE THREAD

**Issue by krnaveen14** [webpack/webpack-cli#165]
I cannot install `webpack-cli` using npm. I tried using different node versions too.

> npm install -g webpack-cli
>
> npm ERR! exited with error code: 128
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/admin/.npm/_logs/2017-06-20T05_23_22_802Z-debug.log

<details>
<summary>Debug Log</summary>

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/home/admin/.nvm/versions/node/v8.1.2/bin/node',
> 1 verbose cli   '/home/admin/.nvm/versions/node/v8.1.2/bin/npm',
> 1 verbose cli   'install',
> 1 verbose cli   '-g',
> 1 verbose cli   'webpack-cli' ]
> 2 info using npm@5.0.3
> 3 info using node@v8.1.2
> 4 verbose npm-session 903a6b37097d0ba2
> 5 silly install loadCurrentTree
> 6 silly install readGlobalPackageData
> 7 http fetch GET 200 https://registry.npmjs.org/webpack-cli 22ms (from cache)
> 8 silly pacote tag manifest for webpack-cli@latest fetched in 40ms
> 9 silly install loadIdealTree
> 10 silly install cloneCurrentTreeToIdealTree
> 11 silly install loadShrinkwrap
> 12 silly install loadAllDepsIntoIdealTree
> 13 silly resolveWithNewModule webpack-cli@1.3.3 checking installable status
> 14 http fetch GET 200 https://registry.npmjs.org/babel-preset-stage-3 41ms (from cache)
> 15 http fetch GET 200 https://registry.npmjs.org/diff 40ms (from cache)
> 16 http fetch GET 200 https://registry.npmjs.org/babel-code-frame 43ms (from cache)
> 17 http fetch GET 200 https://registry.npmjs.org/global-modules 38ms (from cache)
> 18 http fetch GET 200 https://registry.npmjs.org/enhanced-resolve 42ms (from cache)
> 19 http fetch GET 200 https://registry.npmjs.org/fit-commit-js 41ms (from cache)
> 20 silly pacote range manifest for babel-preset-stage-3@^6.17.0 fetched in 45ms
> 21 silly resolveWithNewModule babel-preset-stage-3@6.24.1 checking installable status
> 22 silly pacote range manifest for diff@^3.2.0 fetched in 46ms
> 23 silly resolveWithNewModule diff@3.2.0 checking installable status
> 24 silly pacote range manifest for babel-code-frame@^6.22.0 fetched in 48ms
> 25 silly resolveWithNewModule babel-code-frame@6.22.0 checking installable status
> 26 silly pacote range manifest for global-modules@^0.2.3 fetched in 43ms
> 27 silly resolveWithNewModule global-modules@0.2.3 checking installable status
> 28 silly pacote range manifest for enhanced-resolve@^3.0.2 fetched in 49ms
> 29 silly resolveWithNewModule enhanced-resolve@3.1.0 checking installable status
> 30 silly pacote range manifest for fit-commit-js@^0.3.1 fetched in 48ms
> 31 silly resolveWithNewModule fit-commit-js@0.3.1 checking installable status
> 32 http fetch GET 200 https://registry.npmjs.org/jscodeshift 19ms (from cache)
> 33 http fetch GET 200 https://registry.npmjs.org/listr 17ms (from cache)
> 34 silly pacote range manifest for jscodeshift@^0.3.30 fetched in 23ms
> 35 silly resolveWithNewModule jscodeshift@0.3.31 checking installable status
> 36 silly pacote range manifest for listr@^0.11.0 fetched in 22ms
> 37 silly resolveWithNewModule listr@0.11.0 checking installable status
> 38 http fetch GET 200 https://registry.npmjs.org/p-each-series 7ms (from cache)
> 39 silly pacote range manifest for p-each-series@^1.0.0 fetched in 9ms
> 40 silly resolveWithNewModule p-each-series@1.0.0 checking installable status
> 41 http fetch GET 200 https://registry.npmjs.org/p-lazy 1ms (from cache)
> 42 silly pacote range manifest for p-lazy@^1.0.0 fetched in 2ms
> 43 silly resolveWithNewModule p-lazy@1.0.0 checking installable status
> 44 http fetch GET 200 https://registry.npmjs.org/prettier 1ms (from cache)
> 45 silly pacote range manifest for prettier@^1.2.2 fetched in 3ms
> 46 silly resolveWithNewModule prettier@1.4.4 checking installable status
> 47 http fetch GET 304 https://registry.npmjs.org/cross-spawn 663ms (from cache)
> 48 http fetch GET 304 https://registry.npmjs.org/chalk 668ms (from cache)
> 49 silly pacote range manifest for cross-spawn@^5.0.1 fetched in 668ms
> 50 silly resolveWithNewModule cross-spawn@5.1.0 checking installable status
> 51 http fetch GET 304 https://registry.npmjs.org/got 626ms (from cache)
> 52 silly pacote range manifest for chalk@^1.1.3 fetched in 678ms
> 53 silly resolveWithNewModule chalk@1.1.3 checking installable status
> 54 http fetch GET 304 https://registry.npmjs.org/babel-preset-es2015 681ms (from cache)
> 55 silly pacote range manifest for got@^6.6.3 fetched in 638ms
> 56 silly resolveWithNewModule got@6.7.1 checking installable status
> 57 silly pacote range manifest for babel-preset-es2015@^6.18.0 fetched in 689ms
> 58 silly resolveWithNewModule babel-preset-es2015@6.24.1 checking installable status
> 59 http fetch GET 200 https://registry.npmjs.org/resolve-cwd 22ms (from cache)
> 60 http fetch GET 304 https://registry.npmjs.org/lodash 623ms (from cache)
> 61 silly pacote range manifest for resolve-cwd@^2.0.0 fetched in 30ms
> 62 silly resolveWithNewModule resolve-cwd@2.0.0 checking installable status
> 63 http fetch GET 200 https://registry.npmjs.org/webpack 16ms (from cache)
> 64 silly pacote range manifest for lodash@^4.17.4 fetched in 649ms
> 65 silly resolveWithNewModule lodash@4.17.4 checking installable status
> 66 http fetch GET 200 https://registry.npmjs.org/webpack-addons 33ms (from cache)
> 67 silly pacote range manifest for webpack@^2.5.1 fetched in 40ms
> 68 silly resolveWithNewModule webpack@2.6.1 checking installable status
> 69 silly pacote range manifest for webpack-addons@^1.1.2 fetched in 49ms
> 70 silly resolveWithNewModule webpack-addons@1.1.2 checking installable status
> 71 http fetch GET 304 https://registry.npmjs.org/loader-utils 689ms (from cache)
> 72 http fetch GET 304 https://registry.npmjs.org/interpret 693ms (from cache)
> 73 http fetch GET 200 https://registry.npmjs.org/yargs 37ms (from cache)
> 74 http fetch GET 200 https://registry.npmjs.org/yeoman-environment 24ms (from cache)
> 75 silly pacote range manifest for loader-utils@^0.2.16 fetched in 696ms
> 76 silly resolveWithNewModule loader-utils@0.2.17 checking installable status
> 77 silly pacote range manifest for interpret@^1.0.1 fetched in 701ms
> 78 silly resolveWithNewModule interpret@1.0.3 checking installable status
> 79 http fetch GET 304 https://registry.npmjs.org/inquirer 701ms (from cache)
> 80 silly pacote range manifest for yargs@^6.5.0 fetched in 46ms
> 81 silly resolveWithNewModule yargs@6.6.0 checking installable status
> 82 silly pacote range manifest for yeoman-environment@^1.6.6 fetched in 29ms
> 83 silly resolveWithNewModule yeoman-environment@1.6.6 checking installable status
> 84 silly pacote range manifest for inquirer@^2.0.0 fetched in 705ms
> 85 silly resolveWithNewModule inquirer@2.0.0 checking installable status
> 86 http fetch GET 304 https://registry.npmjs.org/babel-core 763ms (from cache)
> 87 silly pacote range manifest for babel-core@^6.21.0 fetched in 766ms
> 88 silly resolveWithNewModule babel-core@6.25.0 checking installable status
> 89 http fetch GET 304 https://registry.npmjs.org/supports-color 154ms (from cache)
> 90 silly pacote range manifest for supports-color@^3.1.2 fetched in 155ms
> 91 silly resolveWithNewModule supports-color@3.2.3 checking installable status
> 92 silly fetchPackageMetaData error for recast@git://github.com/kalcifer/recast.git#bug/allowbreak exited with error code: 128
> 93 silly fetchPackageMetaData error for yeoman-generator@git://github.com/ev1stensberg/generator.git#Feature-getArgument exited with error code: 128
> 94 verbose stack Error: exited with error code: 128
> 94 verbose stack     at ChildProcess.onexit (/home/admin/.nvm/versions/node/v8.1.2/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
> 94 verbose stack     at emitTwo (events.js:125:13)
> 94 verbose stack     at ChildProcess.emit (events.js:213:7)
> 94 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
> 95 verbose cwd /home/admin/projects/gst-masters/web
> 96 verbose Linux 4.4.0-79-generic
> 97 verbose argv "/home/admin/.nvm/versions/node/v8.1.2/bin/node" "/home/admin/.nvm/versions/node/v8.1.2/bin/npm" "install" "-g" "webpack-cli"
> 98 verbose node v8.1.2
> 99 verbose npm  v5.0.3
> 100 error exited with error code: 128
> 101 verbose exit [ 1, true ]

</details>

### Also tried to install using yarn

> yarn global add webpack-cli
> 
> yarn global v0.24.5
> warning No license field
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> error Command failed.
> Exit code: 128
> Command: git
> Arguments: ls-remote --tags --heads git://github.com/ev1stensberg/generator.git
> Directory: /home/admin/projects/gst-masters/web
> Output:
> fatal: unable to connect to github.com:
> github.com[0: 192.30.255.112]: errno=Connection timed out
> github.com[1: 192.30.255.113]: errno=Connection timed out
> info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

**Comment by ev1stensberg** [comment]
This may be because I've deleted my fork, so sorry. We're working on a migration this week, which will discard the use of the local fork

**Comment by ev1stensberg** [comment]
Nevermind, the fork is still up, removed it locally so you should be cool. Try using `npm`, yarn is disabled while we are migrating :)

**Comment by DanielaValero** [comment]
Closing as seems to be solved. @krnaveen14 feel free to reopen if you still face issues
