### ISSUE TITLE
Globally installed webpack instance should delegate to local one

### ISSUE THREAD

**Issue by tandrewnichols** [webpack/webpack-cli#1653]
**Is your feature request related to a problem? Please describe.**

If you have webpack installed globally and try to run something like `webpack --json` (any command, really), webpack offers to install webpack-cli for you, but it installs it locally and therefore the command you're trying to run still doesn't work. You end up getting `Error: Cannot find module 'webpack-cli'`. See #1560 for more information.

**Describe the solution you'd like**

If you run `webpack` (using a global installation) in a directory where webpack is installed locally, it should delegate to the local install. At that point, if webpack-cli is missing, prompting and subsequently installing it will make the command you ran work. Grunt/grunt-cli does something like this.

**Describe alternatives you've considered**

If you're using a global install of webpack, then the prompt to install webpack-cli should install it globally as well so that the command works.

At the very least, webpack should warn you that you are using a global install.

**Additional context**

None.

**Comment by evenstensberg** [comment]
This is fixed in the latest beta

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack-cli/blob/next/packages/webpack-cli/bin/cli.js#L9
