### ISSUE TITLE
Support setting the config name for multiple configs

### ISSUE THREAD

**Issue by DBosley** [webpack/webpack-cli#1657]
Operating System: Ubuntu 18.04
Node Version: 8.11.1
NPM Version: 6.0.0
webpack Version: 4.12.0
webpack-hot-client Version: 4.0.3

- [x] This is a **feature** request
- [ ] This is a **bug**

### What is the motivation and/or use-case for the feature?
Webpack supports multiple configurations in a single file by exporting an array.
[Info Here](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations)
A new feature that was added recently (but currently lacks total documentation) is that you can set a 'name' property in your webpack config and pass `--config-name` to the cli to choose a specific config to build if you don't want to build all of them.

This feature request is to allow support of this functionality in the webpack-dev-middleware and related plugins.

Implementing this could be done in a couple ways:
- Support passing webpack-cli options into the middleware somehow
- Support choosing a config-name in the middleware options

I think the first solution is going to be the best approach if it's possible. This is because it would allow any webpack-cli arguments to be used with middlewares. If for some reason there's no way to go down this route, the second option would suffice for my use case, but it might be a good idea to look at other options listed [here](https://webpack.js.org/api/cli/) to see if they would merit being included as well

**Comment by evilebottnawi** [comment]
We need implement the `name` flag to run one/two/more of multiple compilers, also it can be `--name=web --name=server` (multiple args)

/cc @webpack/cli-team

**Comment by snitin315** [comment]
@evilebottnawi multiple compilers simultaneously?

**Comment by evilebottnawi** [comment]
Yes

**Comment by rishabh3112** [comment]
@snitin315 a heads up, the name flag will also be  underwork #1649, I suggest to start working on this (if needed) after that PR gets merged to avoid duplicate work :)

**Comment by snitin315** [comment]
makes sense :+1:

**Comment by snitin315** [comment]
> Yes. With `--name=web` - run compiler with `web` name. Should be easy, just filter configuration and remove compiler with `web` name, same for multiple values

@evilebottnawi Now we support `--name=web`(which runs compiler with web name) for `webpack@next`, but it can't accept multiple values. 
https://github.com/webpack/webpack/blob/a3bef27457d8936f81525beaa633eb1931382dc0/test/__snapshots__/Cli.test.js.snap#L1099

**Comment by evilebottnawi** [comment]
@snitin315 Let's improve it

**Comment by snitin315** [comment]
We should improve it at the core or here (in CLI)?

**Comment by evilebottnawi** [comment]
CLI, it is out of scope core

**Comment by snitin315** [comment]
`--name=web` flag purpose is set `options.name = 'web'`. To implement the ability to choose between multiple configs we should implement a different flag `--config-name` for example like done in v3.

**Comment by evilebottnawi** [comment]
Yes, you are right
