### ISSUE TITLE
Initial Documentation for MIGRATE.md

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#166]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Right now, we don't have any documentation for `MIGRATE.md`. It would be nice to have some information about the migrate feature, how it works and what you may need to manually migrate.

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
A populated `MIGRATE.md` with information about the migrate feature and how it works.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A
**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
N/A

**Comment by okonet** [comment]
I'm wondering what kind of documentation are we looking for?

**Comment by ev1stensberg** [comment]
Consistency between `INIT.md` and `MIGRATE.md`

**Comment by thescientist13** [comment]
@ev1stensberg 
To get started on this, it seems like it would be a matter of taking a webpack v1 based config, running `migrate` on it, and documenting the general experience?

**Comment by ev1stensberg** [comment]
Yep, that's correct. Align with @okonet  & @pksjce with this, so that you have enough context in the readme 👍
