### ISSUE TITLE
Invalid configuration object: `mangleExports` using 5.0.0-beta.14

### ISSUE THREAD

**Issue by JAicewizard** [webpack/webpack-cli#1677]
# Bug report

**What is the current behavior?**
When I use the example configuration for mangleExports:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.optimization has an unknown property 'mangleExports'. These properties are valid:
   object { checkWasmTypes?, chunkIds?, concatenateModules?, flagIncludedChunks?, hashedModuleIds?, mangleWasmImports?, mergeDuplicateChunks?, minimize?, minimizer?, moduleIds?, namedChunks?, namedModules?, noEmitOnErrors?, nodeEnv?, occurrenceOrder?, portableRecords?, providedExports?, removeAvailableModules?, removeEmptyChunks?, runtimeChunk?, sideEffects?, splitChunks?, usedExports? }
   -> Enables/Disables integrated optimizations
```

**If the current behavior is a bug, please provide the steps to reproduce.**

create webpack.config.js as example profided in documentation:
```
module.exports = {
  //...
  optimization: {
    mangleExports: false
  }
};
```

**What is the expected behavior?**
Webpack should not mangle exports like the documentation provides

**Other relevant information:**
webpack version:  5.0.0-beta-14
Node.js version: v13.12.0
Operating System: linux
Additional tools: webpack-cli@4.0.0-beta.8

**Comment by evilebottnawi** [comment]
Need add tests

**Comment by anshumanv** [comment]
will add 👍

**Comment by VladimirMikulic** [comment]
@sokra I have the same issue.

OS: Kubuntu 20.04
Node: v12.8.2
```json
"webpack": "^4.43.0",
"webpack-cli": "^3.3.12"
```

**Comment by anshumanv** [comment]
adding now 👍

**Comment by anshumanv** [comment]
Seems to be working fine on webpack/webpack latest beta and latest CLI, adding test
