### ISSUE TITLE
CLI: while importing some flags have pre-appended values

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1679]
# Bug report
While importing flags from core some flags are preappended with values , for example -
- `--module-no-parse`
- `--module-no-parse-reset`
- `--optimization-no-emit-on-errors`

**What is the current behavior?**
These flags have pre appended values and seems we cant override .

![Screenshot at 2020-07-11 14-03-34](https://user-images.githubusercontent.com/46647141/87220293-2b6cc400-c380-11ea-91c8-f04ae225a911.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Import flags and process them.

**What is the expected behavior?**

The flags should not have pre appended values.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by snitin315** [comment]
> @snitin315 I think it is bug on our side, can you provide more information? Why `compilers` is undefined?

No idea :confused: , /cc @webpack/cli-team can anyone look into this? It is a major blocker for #1630

**Comment by evilebottnawi** [comment]
@snitin315 Can we try to test `--optimization-no-emit-on-errors` with pure setup without webpack-cli and check value?

**Comment by snitin315** [comment]
> @snitin315 Can we try to test `--optimization-no-emit-on-errors` with pure setup without webpack-cli and check value?

`--optimization-no-emit-on-errors` works fine on the webpack side. I don't know how but these 3 flags seem to be set to true by our `arg-parser`.
arg-parser should do this only if we have `defaultValue: true` for these which isn't the case here.

**Comment by snitin315** [comment]
I think I found the bug, I can see `defaultValue: true` in `parserInstance`. Looking more into it.

![Screenshot at 2020-07-16 20-28-38](https://user-images.githubusercontent.com/46647141/87687221-1ab6b680-c7a3-11ea-8eb8-e2ff72dc61ae.png)

**Comment by snitin315** [comment]
I think it is a bug in `commander.js`, Actually, it sets `defaultValue: true` if the option starts with `no-`, but instead it is doing same for all options that include `no-`. 
As mentioned in their docs - https://github.com/tj/commander.js/#other-option-types-negatable-boolean-and-flagvalue

> You can specify a boolean option long name with a leading no- to set the option value to false when used. Defined alone this also makes the option true by default.

I will raise an issue there.

**Comment by evilebottnawi** [comment]
Good catch :+1:

**Comment by snitin315** [comment]
fix sent to `commander.js`, now we wait to merge and release.
