### ISSUE TITLE
integrate `interpret`

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack-cli#1683]
**Is your feature request related to a problem? Please describe.**

We need to use `interpret`(https://github.com/gulpjs/interpret) instead https://github.com/webpack/webpack-cli/blob/7489e639d13e8b89690a50595eb48214e9cdb1d9/packages/webpack-cli/lib/groups/ConfigGroup.js#L29

**Describe the solution you'd like**

Description above

**Describe alternatives you've considered**

No need

**Additional context**

Ref: https://github.com/webpack/webpack/issues/5053

**Comment by anshumanv** [comment]
will take a look

**Comment by evilebottnawi** [comment]
Thanks!

**Comment by snitin315** [comment]
fixed with https://github.com/webpack/webpack-cli/pull/1690 ?

**Comment by anshumanv** [comment]
Yep
