### ISSUE TITLE
webpack watch mode not working....

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack-cli#17]
General Information:
webpack version: 1.13.2
OS: Windows 10 Anniversary Update and webpack is running in Windows Subsystem for Linux(The new bash on Ubuntu)

I"m trying to run webpack in watch mode by using:

``` batch
webpack --watch
```

and by also setting watch mode in config:

``` javascript
context: path.join(__dirname, '/src'),
devtool: debug ? 'inline-sourcemap' : null,
entry: './js-src/scripts.js',
watch: true,
module: {
```

All webpack does is run the transpiler and exit.  
Example of output when running watch mode:

``` bash
Hash: 045070ba2ed9ce40edf7
Version: webpack 1.13.2
Time: 2146ms
         Asset     Size  Chunks             Chunk Names
scripts.min.js  1.89 MB       0  [emitted]  main
    + 172 hidden modules
```

I'm not sure what i'm doing incorrect?

**Moved from https://github.com/webpack/webpack/issues/2949**

**Comment by SpaceK33z** [comment]
Moving again since this was the wrong project :smile:. Moved to https://github.com/webpack/watchpack/issues/43.
