### ISSUE TITLE
tests: fix serve tests on windows

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack-cli#1743]
**Describe the bug**
Currently we are skipping tests for serve on windows platform, those should be implemented after serve implementation is completed.

**What is the current behavior?**
Tests are skipped on windows platform

**To Reproduce**
Check `tests/serve/*.test.js` files.

**Expected behavior**
Consistent performance across platforms

**Screenshots**
N/A

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
N/A

**Additional context**
N/A

**Comment by snitin315** [comment]
Looking into it.

**Comment by evilebottnawi** [comment]
We have more windows problems, so I think here not only serve :+1:

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack-cli/pull/2587
