### ISSUE TITLE
refactor: utils and package-utils

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack-cli#1752]
**Is your feature request related to a problem? Please describe.**
Currently we have shared code that is being used by different sub-packages in these packages. But this way, It allows for duplication of dependencies as `webpack-cli` package(dependendt on `package-utils`) package that is a peer dependency of all other sub-packages. Also, there may be a situation in which there would be multiple versions of these packages in user's codebase.

**Describe the solution you'd like**
Simplest solution would be to keep all the utils `webpack-cli` package.
(caveat: we would be increasing package size with code it may never use if some particular sub-package isn't installed by the user)
![image](https://user-images.githubusercontent.com/15812317/90607069-56b7be00-e21e-11ea-962b-2b12247a5a7e.png)

**Describe alternatives you've considered**
N/A

**Additional context**
/cc @evilebottnawi

**Comment by evilebottnawi** [comment]
package-utils was removed, I think we need move `utils` package inside webpack-cli, but need think how we can reduce size

**Comment by evilebottnawi** [comment]
Let's close, `package-utils` unions with `utils`
