### ISSUE TITLE
bail = true should not kill watch mode on ModuleNotFound error

### ISSUE THREAD

**Issue by spion-h4** [webpack/webpack-cli#1794]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When `bail = true`, a ModuleNotFound error during a change of the files will cause the entire watch process to either abort or get stuck. Subsequent rebuilds will not happen even if the file changes.

**If the current behavior is a bug, please provide the steps to reproduce.**

* run webpack in watch mode
* add `import './non-existant-module'` to any file
* webpack rebuild fails or exits
* remove the import
* rebuild is not triggered either due to webpack exit (3.10 and below) or due to hang (3.11)

node version: 8.9.4

Webpack 3.11 made one step towards fixing this with https://github.com/webpack/webpack/pull/5797

However even though the process does not die, rebuilds stop happening.

**Comment by snitin315** [comment]
Yes, I will do it.
