### ISSUE TITLE
[Question] Which version of webpack-cli support webpack 5?

### ISSUE THREAD

**Issue by achenwei-chwy** [webpack/webpack-cli#1807]
So I can upgrade without worrying too much. Because I saw some post indicate latest version webpack-cli was not working with webpack5.

Thanks

**Comment by evenstensberg** [comment]
Both versions latest at master branch and next branch supports webpack 5, if you run `npm install --save-dev webpack-cli` and `npm install --dev webpack-cli@next` both supports it

**Comment by evenstensberg** [comment]
https://github.com/webpack/webpack-cli/blob/next/SECURITY.md
