### ISSUE TITLE
[Discussion] Creating a roadmap, milestones , strategy 

### ISSUE THREAD

**Issue by fokusferit** [webpack/webpack-cli#181]
This Issue is also related to #180 but is more related to:

- How can we provide some milestones (or roadmap) transparently, so everyone knows what to focus on next ?

I'm sure some of the first contributors and Even have a clear list of next steps and features in mind and now this 'issue' here is more about getting this documented and shared broadly.

**Comment by thescientist13** [comment]
Hello!

I just started helping out with the CLI but have had some experience with using GitHub and managing projects on it and had a couple thoughts.

### Projects and Milestones
Could we use the Projects + Milestones features in GitHub for this repo?  I've used them in the following manner (just as a suggestion):
- Milestone: long term release tracking (new version, refactoring plan, etc)
- Projects: smaller term project tracking, like sprints working towards the completion of Milestong

From there, I think the README of the CLI could then have a section that discusses the current plan of the project by listing the Milestones and related projects, with their dates and general notes about the objective of it.

This would be a good way to easily communicate the state of development at any given time during the project by maintaining this section of the README.

### "Project Manager" (working name for the role)
Is there someone dedicated to tracking and maintaining issues, or organizing the work?  Maybe this person could be the "goto" for officially on boarding new developers when join the group are looking for where to get started helping out.  This would be a good time to share what's being / going to be done in #180 .  

This member could also help maintain the Projects and Milestones, organize meetings, take notes, and help facilitate collaboration in general.

**Comment by fokusferit** [comment]
I like the idea of using GH projects, but in the past when I used it in different projects the maintenance "cost" was also quite high. And maybe we could start using more labels as a first step towards moving into GH projects, but I'm open for it. 

Regarding "Project Manager", maybe "Community (Onboarding) Manager" might be a better fit ? 😄 I think some are already doing this but I think this is also part of #180 where once we have more documentation, information for contributors I think this position could be a shared one. I think any OSS project needs 1-2 main people who are really feeling responsible for it which we already have with Even and Daniela I think.

**Comment by okonet** [comment]
I just started using Projects for 🚫💩 lint-staged https://github.com/okonet/lint-staged/projects/1 and so far I like it. It's a bit early to say of the outcome but I think it helps everyone to stay focused on important things.

**Comment by ematipico** [comment]
Yeah I agree that we should have an area where people can read and understand what are the goals of the library. I know that there are discussions around but those tend to get lost. We can create a Milestone for version 2.0 of the project, so contributors and first time contributors can have a better idea of where we are going. 

About the **Project Manager**: the idea is nice but I think there should be rota for this role, so it won't create too restrictions. After all people are not forced to do something and they should be free to pass over their duties/action items to somebody else without problems.

**Comment by fokusferit** [comment]
So regarding this specific **Project Manager** role, in the meeting yesterday, we realized that it is not exactly about managing, but more about organizing, supporting developers when they create issues, organizing meetings, tracking agenda etc. 

I'm also a big fan of rotation but for now, I will try to be this kind of "Organizer" (or call it Scrum Master, Producer) who will try to get webpack-cli to an autonomous, self-organized state, so this role fades out naturally or is not really needed anymore. In my personal experience, a need for such role in companies mostly results from the need that "upper" people want to track progress to report. In an open source project, I would challenge that role and rather think that everyone should have the mindset of facilitating and maintaining that project 😄  

So one of the clear next steps here is to have such contributing "culture code" defined.
