### ISSUE TITLE
 TypeError: Cannot read property 'size' of undefined

### ISSUE THREAD

**Issue by mrzie** [webpack/webpack-cli#1818]
**Describe the bug**

Occurs when I just run `webpack` command.

**What is the current behavior?**

**To Reproduce**

1. using `webpack-cli@4.0.0-beta.2` and `webpack@5.0.0-rc.0`
2. run `webapck` command

It seems in `lib/utils/CompilerOutput.js` line 33 webpack-cli compares `assert.name` with `assertName`. But in this case I found the `assertName` is an object `{name: 'xxx.js', size: 30}` not a string. I wonder if this part caused this problem.

**Comment by anshumanv** [comment]
Can you try with `beta.9`?

**Comment by mrzie** [comment]
> Can you try with `beta.9`?

Thanks. The TypeError didn't appear again. 
And I saw that `beta.9` use an empty checking to avoid the error, which couldn't print the bundle table.

Is that the final solution?

**Comment by evilebottnawi** [comment]
@mrzie Please clarify

**Comment by mrzie** [comment]
> @mrzie Please clarify

@evilebottnawi Today I upgrade my webpack version and get `webpack-cli@4.0.0-beta.2` for some reason I don't know. Then it throws the TypeError every time I try to build. It may because of the `generateFancyOutput()` never get the correct `asset` in my view.


And I just found the table-way output is removed by [238b4015cd889ae1efb550481fda8cea40b1440d](https://github.com/webpack/webpack-cli/commit/238b4015cd889ae1efb550481fda8cea40b1440d)...so it seems solved with `generateFancyOutput()` being removed.
