### ISSUE TITLE
Cannot install webpack-cli using npm

### ISSUE THREAD

**Issue by trignolo** [webpack/webpack-cli#182]
I'm trying to install webpack-cli with npm, but I'm getting error code 128.

Thanks in advance

**Comment by ev1stensberg** [comment]
Hi! Could you post a stacktrace for us? I.E print a screenshot of your terminal?

**Comment by trignolo** [comment]
Sure, here it is:

> sudo npm install -g webpack-cli
> Password:
> npm ERR! Error while executing:
> npm ERR! /usr/bin/git ls-remote -h -t git://github.com/kalcifer/recast.git
> npm ERR!
> npm ERR! fatal: unable to connect to github.com:
> npm ERR! github.com[0: 192.30.253.113]: errno=Operation timed out
> npm ERR! github.com[1: 192.30.253.112]: errno=Operation timed out
> npm ERR!
> npm ERR!
> npm ERR! exited with error code: 128

> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/.../.npm/_logs/2017-09-01T14_53_03_375Z-debug.log

**Comment by ev1stensberg** [comment]
- https://stackoverflow.com/questions/35021692/npm-install-error-code-128
- https://docs.npmjs.com/troubleshooting/try-clearing-the-npm-cache

**Comment by ematipico** [comment]
Are you behind a proxy? It looks like it's related to the cli but to a connection error to github

**Comment by trignolo** [comment]
I've also realized that is a connection problem looking at the logs, but I've never experienced a problem like this in the recent past with other tools. 

My first googlings take on this issue:

https://github.com/webpack/webpack-cli/issues/165

that seems to be the exact problem that I have now.

So I think that it's not very likely that is a proxy problem. But I'm investigating yet with infos from ev1stensberg.

**Comment by trignolo** [comment]
A little update: I attach a clean log of the exceution of the command. What I see is that the connection time out is related to this repo:

/usr/bin/git ls-remote -h -t git://github.com/kalcifer/recast.git


[2017-09-01T15_20_12_242Z-debug.log.txt](https://github.com/webpack/webpack-cli/files/1270712/2017-09-01T15_20_12_242Z-debug.log.txt)

**Comment by ev1stensberg** [comment]
@trignolo Recast & Yeoman are local forks, so that makes sense. Planning to remove those after we've migrated into [`webpack-addons`](https://github.com/webpack-contrib/webpack-addons)

**Comment by RobotnickIsrael** [comment]
Any updates on this issue?
I want to use the cli to migrate my project from webpack 1.X to 2.X (and later 3\4). 
When do you thing the migration to webpack-addons will finish?
Will it affect the migration tool?

Thanks

**Comment by wojtekmaj** [comment]
I get similar error:

```cmd
> npm install webpack-cli@latest
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t git://github.com/ev1stensberg/generator.git
npm ERR!
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=No such file or directory
npm ERR! github.com[1: 192.30.253.113]: errno=No such file or directory
npm ERR!
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
```

**Comment by internetErik** [comment]
I also get the same 'error' as above. I think it may have to do with some kind of local network settings.

If I try running these commands:

git ls-remote -h -t git://github.com/ev1stensberg/generator.git

git ls-remote -h -t https://github.com/ev1stensberg/generator.git

The second command works, while the first doesn't. So the issue (at least for me) seems connected to the use of the git protocol.

**Comment by ev1stensberg** [comment]
It's the fork that won't let you download through a secure network. Planning to fix this soon, promise. Alternative is to download the generator manually and link it to a cloned version of the cli if you really need to use it

**Comment by erikchristianson** [comment]
@ev1stensberg Thanks

**Comment by dchhetri** [comment]
:+1: Awaiting for this as well. Thanks.

**Comment by dchhetri** [comment]
:+1: Waiting on the fix here as well. Best.

**Comment by tgandrews** [comment]
Is the switch to use `https` instead of `git` protocol an option? At the moment we cannot install this as we are behind a proxy. The workaround of cloning and linking seems unnecessary if a protocol fix is quick and works.

**Comment by ematipico** [comment]
Just made a PR as temporary fix :)

**Comment by ev1stensberg** [comment]
Awesome sauce 🎉🎉

**Comment by erikchristianson** [comment]
Any chance a new version of webpack-cli, with the recent merge, could be published on npm?

**Comment by ev1stensberg** [comment]
I'll have a chat with the team this week. We need to merge some long standing PRs like adding test cases from webpack and another minor one

**Comment by erikchristianson** [comment]
@ev1stensberg Any word on when a new version can be published to npm? Very inconvenient not being able to run npm install on certain projects while in the office.

**Comment by ev1stensberg** [comment]
`yarn add webpack-cli 2.0.5` out now

**Comment by TomFoyster** [comment]
I'm still unable to `npm install webpack-cli`? Is this meant to have been fixed?

**Comment by dhruvdutt** [comment]
@TomFoyster Most likely it could be because of #161. There's currently an issue with installation when we're behind a proxy.

**Comment by LittleJellycat** [comment]
Same issue or my fault?
``` 
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b Feature-getArgument git://github.com/ev1stensberg/generator.git /home/jelly/.npm/_cacache/tmp/git-clone-c87ab068

npm ERR! /home/jelly/.npm/_cacache/tmp/git-clone-c87ab068/.git: Permission denied
```

**Comment by TomFoyster** [comment]
@dhruvdutt Correct, I found that weirdly if I connected to our VPN I was able to download it without issue!
