### ISSUE TITLE
feat: support webpack-bundle-analyzer with CLI

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#1838]
**Is your feature request related to a problem? Please describe.**
We can have an `analyze` flag which invokes webpack-bundle-analyzer as bundle information is crucial limiting size and determining potential bloats

**Describe the solution you'd like**
we can list it in peer dep and use the analyzer which the user has installed instead of shipping out of the box to keep package size low.

**Describe alternatives you've considered**

**Additional context**
/cc @evilebottnawi

**Comment by evilebottnawi** [comment]
Yes:
- Put in `peerDependenciesMeta` with `options`
- for the `--analyze` flag adding `webpack-bundle-analyzer` as a plugin
- need implement schema for `webpack-bundle-analyzer` and read options from schema (can be done late)

**Comment by evilebottnawi** [comment]
> need implement schema for webpack-bundle-analyzer and read options from schema (can be done late)

to respect built-in options

**Comment by evilebottnawi** [comment]
> need implement schema for webpack-bundle-analyzer and read options from schema (can be done late)

to respect built-in options

**Comment by snitin315** [comment]
Bump

**Comment by snitin315** [comment]
Bump

**Comment by snitin315** [comment]
Let's start working on next first before adding more fetures.

**Comment by info-arnav** [comment]
Hi, can you please providde a basic idea on how to proceed with this

**Comment by info-arnav** [comment]
> Hi, can you please providde a basic idea on how to proceed with this

Like the basic implimentation would be to create a plugin webpack-bundle-analyzer
adding  a --analyze flag to automatically add the plugin
maybe save the analysed data in a file

can you tell me about how can i go about the analyzing part, like the webpack functions or data to be used

**Comment by info-arnav** [comment]
> > Hi, can you please providde a basic idea on how to proceed with this
> 
> Like the basic implimentation would be to create a plugin webpack-bundle-analyzer adding a --analyze flag to automatically add the plugin maybe save the analysed data in a file
> 
> can you tell me about how can i go about the analyzing part, like the webpack functions or data to be used

@alexander-akait @snitin315

**Comment by info-arnav** [comment]
So Ill then start reffering to https://github.com/webpack-contrib/webpack-bundle-analyzer

**Comment by info-arnav** [comment]
As per what I see, we already have a --analyze flag added, which loads the webpack-bundle-analyzer plugin. I will try to add the plugin to webpack itself and then load it with the same.
