### ISSUE TITLE
`webpack-cli init` does not work on < Node v6

### ISSUE THREAD

**Issue by ianjsikes** [webpack/webpack-cli#184]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The `webpack-cli init` command does not work on Node v4 or v5. From experimenting with #183, I believe this is because the `yeoman-generator` package is distributed in ES6.

**If the current behavior is a bug, please provide the steps to reproduce.**
```bash
$ nvm install 5        # or 4
$ nvm use 5            # or 4
$ npm install -g webpack-cli
$ webpack-cli init
```

**What is the expected behavior?**
The yeoman generator should run, prompt for user input, and generate a new Webpack project.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Tested on Ubuntu 16.10 and MacOS 10.11, with Node v4 and v5.

**Comment by ianjsikes** [comment]
A solution would be to compile the `yeoman-generator` package to ES5, I'm just not sure what the best way to go about it is.

**Comment by ev1stensberg** [comment]
@ianjsikes I'm not sure we can do that, as yeoman got some class exports that are wrongly compiled in babel

**Comment by ev1stensberg** [comment]
Since webpack@next is supporting node 6+, we're not supporting it either. I think we've removed babel, so it might work now 👍
