### ISSUE TITLE
test: add test for cache-location flag from webpack@5

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#1841]
**Describe the bug**

supply location to cache path

**What is the current behavior?**
no tests present

**Expected behavior**
- tests present

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
/cc @evilebottnawi 
https://github.com/webpack/webpack-cli/pull/1832#discussion_r495111318

**Comment by anshumanv** [comment]
It seems we already have test 
```js
it('should set cache.cacheLocation with --cache-cache-locations', () => {
        const { stderr, stdout } = run(__dirname, ['--cache-type', 'filesystem', '--cache-cache-location', '/test-locate-cache']);

        expect(stderr).toBeFalsy();
        expect(stdout).toContain('test-locate-cache');
    });
```

@evilebottnawi can you clarify the expectation you had?

**Comment by evilebottnawi** [comment]
@anshumanv we should check what cache is was used, run two compilation

**Comment by evilebottnawi** [comment]
Ref: https://github.com/webpack/webpack-cli/issues/1842

**Comment by evilebottnawi** [comment]
/cc @webpack/cli-team We need to look at this, and test `cache` is more better:
- run compilation twice with and without changes
- changing something in webpack.config.js should invalid cache 
- we should put config(s) in https://github.com/webpack/webpack/blob/master/lib/config/defaults.js#L282 to achieve cache invalidation

Somebody can take care before stable release?

**Comment by snitin315** [comment]
Looking into it.
