### ISSUE TITLE
Bug: Output flag should only set path

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#1844]
**Describe the bug**

@evilebottnawi : It is invalid because we will specify HTML and CSS as entry points in the near future + dependOn, if you have HTML entrypoint and use --output=/path/to/file.js it was wrong, Ideally we should remove --output in favor --output-path, also this one will be consistent with webpack@5 cli args

**What is the current behavior?**

Passing a file in output flag sets filename object in output

**To Reproduce**
Pass `/path/to/file.js`

**Expected behavior**
It should only set `output.path`, filename should only be configured using config

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
https://github.com/webpack/webpack-cli/pull/1832#discussion_r495921619

**Comment by evilebottnawi** [comment]
I think better to remove `--output` in favor `--output-path`

**Comment by anshumanv** [comment]
Yep will do that in PR 👍
