### ISSUE TITLE
[Bug]: delegate default entry assigning to core

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#1852]
**Describe the bug**

Presently we assign our own default entry which is invalid since it can be `ts/mjs` etc so delegate this to core, we only need to assign entry when user passes

**What is the current behavior?**

Entry assigned to `index.js` or `src/index.js`

**To Reproduce**
Add some non js index file then it won't work

**Expected behavior**
It should work

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by evilebottnawi** [comment]
@anshumanv Can you send a PR, it is very important

**Comment by anshumanv** [comment]
yep on it 👍
