### ISSUE TITLE
Adding a build step

### ISSUE THREAD

**Issue by andrei-zhidkov** [webpack/webpack-cli#188]
Currently, building & running the project locally unfortunately proves to be quite troublesome.

First of all, there seems to be a missing dependency required from `bin/webpack.js` — `resolve-cwd` is missing from `package.json`.
Then, there are flow typings in the project now, which predictably result in `Unexpected token` error.

I think that it's time to add a proper build step to the project — this will allow us to continue using Flow, and will make possible to use the ES2015+ features (including ES2015 modules instead of CommonJS).

I also think that doing so will also help #180, since it will be easier to actually get things going.

I would be glad to work on this, but I think that #186 should be merged before that, since it already addresses removing Flow annotations.

**Comment by ev1stensberg** [comment]
@andrei-zhidkov Thanks for opening an issue! We're addressing this in the upcoming PR's!

**Comment by ev1stensberg** [comment]
I'm very fond of TypeScript, if we were to transpile the CLI, @okonet what do you think?

**Comment by okonet** [comment]
I think Flow is better :) but either way we need to transpile. To transpile Flow we only need to introduce Babel.

**Comment by ev1stensberg** [comment]
Fixed in 1.4.9 <=
