### ISSUE TITLE
cli executer fails to invoke runCLI()

### ISSUE THREAD

**Issue by jamesgeorge007** [webpack/webpack-cli#1901]
**Describe the bug**
#1255 brought a better way to handle unknown flags by showing up the available options and asking the user to pick what they required. Everything works well except that it fails to supply the chosen args further up.

**What is the current behavior?**
`cli-executer` won't supply the chosen args since it fails to recognize `runCLI()` as a function.

<img width="363" alt="Screenshot 2020-10-10 at 12 23 31 AM" src="https://user-images.githubusercontent.com/25279263/95621156-de87af00-0a8e-11eb-90cd-a11f1d1b7a98.png">

**To Reproduce**

An interactive prompt shows up with all of the available `cli-flags` if the user makes a typo.
Say, `webpack-cli --entyr ./a.js`

Choose `--entry` and supply `./a.js` as the value. Notice that an error message shows up. (screenshot is given below)

**Expected behavior**
`cli-executer` supplies the chosen args to `runCLI()`.

**Screenshots**

<img width="1101" alt="Screenshot 2020-10-10 at 12 13 47 AM" src="https://user-images.githubusercontent.com/25279263/95621061-bac46900-0a8e-11eb-870c-46e59ea3237d.png">

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

https://github.com/webpack/webpack-cli/blob/c0eb2801e32bb1b297a4bf21f9cc6dfbe7a12c83/packages/webpack-cli/lib/bootstrap.js#L59

https://github.com/webpack/webpack-cli/blob/c0eb2801e32bb1b297a4bf21f9cc6dfbe7a12c83/packages/webpack-cli/lib/utils/cli-executer.js#L58

**Comment by evilebottnawi** [comment]
Yep, feel free to send a fix :+1:
