### ISSUE TITLE
v4: stats colors not enabled by default

### ISSUE THREAD

**Issue by llooz** [webpack/webpack-cli#1915]
**Describe the bug**

I have just upgraded from v3.3.12 to v4.0.0 and I don't see a colored output on the terminal as before.

**What is the current behavior?**

Webpack works fine but I don't have colored output.

**To Reproduce**

Upgrade to v4.0.0.

**Expected behavior**

Colored output as on v3.3.12.

```
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 471.39 MB / 16.00 GB
  Binaries:
    Node: 14.13.0 - ~/.nvm/versions/node/v14.13.0/bin/node
    Yarn: 2.3.2 - ~/.nvm/versions/node/v14.13.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.13.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 81.0
    Safari: 14.0
  Packages:
    fork-ts-checker-webpack-plugin: ^5.2.0 => 5.2.0 
    webpack: 5.0.0-rc.6 => 5.0.0-rc.6 
    webpack-cli: 4.0.0 => 4.0.0 
```

**Additional context**

I have tried to:
- downgrade to `v3.3.12` -> WORKS
- downgrade webpack from v5 to v4 while keeping cli at v4 -> DOESN'T WORK

**Comment by llooz** [comment]
It seems that's just a different default configuration of the `stats` portion passed down to webpack.

On v3.x.x I see that if there isn't a a chosen preference then it's automatically enabled if the terminal supports a colored output.
https://github.com/webpack/webpack-cli/blob/33574ec82e1f6d8b71e872db086bbfaaf77707ba/bin/cli.js#L169
https://github.com/webpack/webpack-cli/blob/33574ec82e1f6d8b71e872db086bbfaaf77707ba/bin/config/config-yargs.js#L379

**Comment by evilebottnawi** [comment]
We should fix it, because wepack don’t know noting about env, it can be cli and node or browser, or something else

**Comment by evilebottnawi** [comment]
WIP
