### ISSUE TITLE
Inconsistent behavior of webpack --flag --help

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#1917]
**Describe the bug**

`webpack --flag --help`  shows inconsistent behavior, sometimes it prints help sometimes it considers `--help` as value for `--flag`.

**What is the current behavior?**

**To Reproduce**

Try running -

`webpack --stats --help`
`webpack --mode --help`
`webpack -hot --help`
`webpack --entry --help`

See inconsistency.

**Expected behavior**
The behavior should be consistent either print help (recommended) or throw an error/warning.

**Screenshots**
![Screenshot at 2020-10-11 08-11-21](https://user-images.githubusercontent.com/46647141/95669083-1f201f00-0b9a-11eb-899a-b48b92340b87.png)

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
https://github.com/webpack/webpack.js.org/pull/4051#discussion_r502856883

**Comment by evilebottnawi** [comment]
Existing help in flags should always output help information, feel free to send a fix

**Comment by Bhavik-Ardeshna** [comment]
@snitin315 Hey I need to work on this issu

**Comment by Bhavik-Ardeshna** [comment]
And also can I join webpack community in telegram or discord , link?

**Comment by snitin315** [comment]
@Bhavik-Ardeshna feel free to send a PR.

**Comment by Bhavik-Ardeshna** [comment]
I want to join the community server if possible to learn new things ...

**Comment by snitin315** [comment]
https://gitter.im/webpack/webpack

**Comment by Bhavik-Ardeshna** [comment]
thnx
