### ISSUE TITLE
config file with function doesn't work if path contains `.webpack`

### ISSUE THREAD

**Issue by dillonkrug** [webpack/webpack-cli#1925]
webpack config file where `module.exports`  is a function doesn't work depending on the file path.

If the config file path contains `.webpack`, the result of calling the config function is ignored.

```
// project/config.webpack.js -- note that filename contains ".webpack"
module.exports = (env) => ({
    entry: 'some-file.js'
    output: {
        path: './dist',
        file: 'some-bundle.js'
    }
});
```

```
$/project> webpack --config config.webpack.js
```

This produces an error saying "`./src` cannot be resolved" because the actual config is ignored, and webpack falls back to default configuration.

** Cause **

`lib/groups/ConfigGroup.js` in the `finalize` [function](https://github.com/webpack/webpack-cli/blob/5ef1e7b074390406b76cb3e25dd90f045e1bd8a2/packages/webpack-cli/lib/groups/ConfigGroup.js#L190):

```
    if (configOptions && configPath.includes('.webpack')) {
        // overrides the resolved options
    }
```

this condition is not specific enough.

**Comment by evilebottnawi** [comment]
Please do not ignore the issue template, in future it will be closed without reply
