### ISSUE TITLE
Unknown argument --node-args 

### ISSUE THREAD

**Issue by Khauri** [webpack/webpack-cli#1928]
**Describe the bug**

Seems as if `node-args` is no longer a supported argument. If `node-args` was removed on purpose, I can't seem to find any documentation on an alternative syntax. [The docs](https://webpack.js.org/api/cli/#pass-cli-arguments-to-nodejs) seem to still mention this arg as well.

**What is the current behavior?**

Current behavior is to throw an unknown argument error whereas previous versions would pass multiple node-arg flags on to the script.

**To Reproduce**

1. Run a webpack project using node-args, ie `webpack --node-args="--max-old-space-size=4096"`

**Expected behavior**

The node-args flag should be passed to the start script OR the documentation should be updated to reflect an alternative syntax if one exists or both.

**Screenshots**

```
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 35.64 MB / 8.00 GB
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.75
    Safari: 13.1.2
  Packages:
    clean-webpack-plugin: ^3.0.0 => 3.0.0 
    eslint-import-resolver-webpack: ^0.13.0 => 0.13.0 
    speed-measure-webpack-plugin: ^1.3.3 => 1.3.3 
    webpack: ^4.44.2 => 4.44.2 
    webpack-bundle-analyzer: ^3.9.0 => 3.9.0 
    webpack-cli: ^4.0.0 => 4.0.0 
    webpack-merge: ^5.2.0 => 5.2.0 
    webpack-node-externals: ^2.5.2 => 2.5.2 
    webpack-plugin-browser-json: ^1.1.3 => 1.1.3 
```

**Additional context**

**Comment by evilebottnawi** [comment]
Do not use `--node-args`, docs will be updated in near future

**Comment by evilebottnawi** [comment]
https://nodejs.org/api/cli.html#cli_node_options_options

**Comment by evilebottnawi** [comment]
It works always
