### ISSUE TITLE
Unknown argument: --config-register

### ISSUE THREAD

**Issue by seahindeniz** [webpack/webpack-cli#1929]
**Describe the bug**

I can't register @babel/register with the following command
`webpack --config-register @babel/register`

**What is the current behavior?**

It returns following output
```bash
> webpack --config-register @babel/register "-w"

[webpack-cli] Unknown argument: --config-register
[webpack-cli] Unknown argument: @babel/register
? Which flags do you want to use? …
✔ --entry: The entry point(s) of your application e.g. ./src/main.js
✔ --config: Provide path to a webpack configuration file e.g. ./webpack.config.js
✔ --color: Enable/Disable colors on console
✔ --merge: Merge two or more configurations using webpack-merge e.g. -c ./webpack.config.js -c ./webpack.test.config.js --merge
✔ --progress: Print compilation progress during build
✔ --help: Outputs list of supported flags
✔ --output-path: Output location of the file generated by webpack e.g. ./dist/
✔ --target: Sets the build target e.g. node
✔ --watch: Watch for files changes
✔ --hot: Enables Hot Module Replacement
✔ --devtool: Determine source maps to use
✔ --prefetch: Prefetch this request
✔ --json: Prints result as JSON or store it in a file
✔ --mode: Defines the mode to pass to webpack
✔ --version: Get current version
✔ --stats: It instructs webpack on how to treat the stats e.g. verbose
✔ --env: Environment passed to the configuration when it is a function
✔ --name: Name of the configuration. Used when loading multiple configurations.
✔ --config-name: Name of the configuration to use
```
**To Reproduce**

1. Go to 'package.json' file
2. Add a new script with `"webpack --config-register @babel/register"`
3. Open the terminal and run the script
4. See the warning

**Expected behavior**

It should start executing webpack with no problem

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

```bash
  System:
    OS: Linux 4.19 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 1.31 GB / 4.82 GB
  Binaries:
    Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.1/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.18.1/bin/npm
  Packages:
    tsconfig-paths-webpack-plugin: ^3.3.0 => 3.3.0
    webpack: ^5.0.0 => 5.0.0
    webpack-cli: ^4.0.0 => 4.0.0
    webpack-extension-reloader: ^1.1.4 => 1.1.4
    webpack-watched-glob-entries-plugin: ^2.1.7 => 2.1.7
```
**Additional context**

**Comment by snitin315** [comment]
@seahindeniz  `webpack-cli` doesn't support `--config-register`, you can see available options & commands here https://github.com/webpack/webpack-cli/tree/master/packages/webpack-cli#supported-arguments-and-commands

**Comment by seahindeniz** [comment]
Hmm, thank you @snitin315

**Comment by juwens** [comment]
@snitin315 or @seahindeniz  can you please say which parameter replaced `--config-register`.
Because i don't see any equivalent.

**Comment by seahindeniz** [comment]
Hey @juwens 

I use `--config-register` to register babel to be able to use ES6 es6 stuff on the config file. After @snitin315's message, I simply switched from JS config file to TS.

Here, you can check my config from my repo
https://github.com/seahindeniz/BrainlyTools_Extension/blob/master/webpack.config.ts

https://github.com/seahindeniz/BrainlyTools_Extension/blob/master/package.json#L165

**Comment by snitin315** [comment]
@juwens I believe it was removed without replacement. 
Though if you find this is something that should be supported feel free to open a new issue about it with your use case.

**Comment by evilebottnawi** [comment]
Yes, we support ts/babel/etc files without extra options
