### ISSUE TITLE
Unknown argument: -p in v4

### ISSUE THREAD

**Issue by aleksandrlat** [webpack/webpack-cli#1934]
**Describe the bug**

Looks like argument `-p` is not supported in v4. What can be used instead?

**Comment by evilebottnawi** [comment]
`--progress`

**Comment by aleksandrlat** [comment]
@evilebottnawi no `-p` was before
```
--optimize-minimize --define process.env.NODE_ENV="production"
```
https://v4.webpack.js.org/api/cli/#shortcuts

Not progress for sure

**Comment by evilebottnawi** [comment]
`--mode production`
