### ISSUE TITLE
nodejs 13.0-13.6 and colorette dependency

### ISSUE THREAD

**Issue by ym-project** [webpack/webpack-cli#1943]
**Describe the bug**

nodejs 13.0-13.6 has a bug. If any package has ESM support (exports key in package.json) nodejs catches an error
```
Error: No valid exports main found for '/node_modules/packageName'
```
webpack-cli has a dependency [colorette](https://github.com/jorgebucaran/colorette). This dependency break a building because of it has an esm support ([issue](https://github.com/jorgebucaran/colorette/issues/48#issuecomment-654669713)).

**To Reproduce**

I created an repository to reproduce this error [https://github.com/ym-project/webpack-cli-bug](https://github.com/ym-project/webpack-cli-bug). You should have nodejs 13.0-13.6 or use docker.

**How to fix**

Use dependency that doesn't have an esm support until nodejs version is deprecated. Or write about this problem in README file or somewhere.

**Versions**

nodejs: 13.0-13.6
webpack: 5.1.0
webpack-cli: 4.0.0

**Comment by evilebottnawi** [comment]
Do not use `node@13.0-13.6`, because it is broken and it is not lts version
