### ISSUE TITLE
Add "webpack-cli" bot to the repo

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#195]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Right now, we do not have any bot that will improve contributors experience, it would be nice to add a bot that looks at tests and adds labels etc on demand. 
**If the current behavior is a bug, please provide the steps to reproduce.**

N/A
**What is the expected behavior?**
A bot that is added to the repo
**If this is a feature request, what is motivation or use case for changing the behavior?**
 Better Developer Experience
**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

A nice starting point is to look at the botfile in the webpack repo and adjust to this one

**Comment by ematipico** [comment]
What the bot should do? The same thing that the bot inside `webpack` does?

**Comment by ev1stensberg** [comment]
Yep, just adjust it to our labels, and it should looks for our unit tests instead of Appveyor etc

**Comment by ematipico** [comment]
I'd like to take the PR if anybody else wants to

**Comment by ev1stensberg** [comment]
Go for it @ematipico !
