### ISSUE TITLE
Multiple config + devServer + different HMR options don't work

### ISSUE THREAD

**Issue by Jack-Works** [webpack/webpack-cli#1955]
**Describe the bug**

I try to use 2 configs that one uses HMR and the other one doesn't. It doesn't work.

**To Reproduce**

> package.json

```json
{
    "dependencies": {
        "webpack": "^4.44.2",
        "webpack-cli": "^4.0.0",
        "webpack-dev-server": "^3.11.0"
    }
}
```

> webpack.config.js

```js
module.exports = () => {
    return [
        { mode: "development", entry: { a: "./a.js" }, devServer: { writeToDisk: true, hot: true, port: 4858 } },
        {
            mode: "development",
            entry: { b: "./b.js" },
            devServer: { writeToDisk: true, hot: false, injectClient: false, port: 4868, injectHot: false },
        },
    ];
};
```

> a.js and b.js empty

Run `webpack serve`

**Expected**: The dist/b.js don't have HMR related code

**Actual**: It has

**Comment by topocount** [comment]
I've also found this to be true with the `inline: false` config. before upgrading to v4, webpack wouldn't attempt to inject the client (HMR/ auto-refresh) code into files and now it's attempting to do so. The upshot of this is that SSR files don't have the ability handle this code.

**Comment by evilebottnawi** [comment]
`inline` was removed in the next version, don't use it, **never**

**Comment by topocount** [comment]
@evilebottnawi Thanks, good to know. I don't see this reflected in the docs (v4 or v5) yet, though

**Comment by evilebottnawi** [comment]
Expected, you have `hot: false` and `injectHot: false` for the second config, so no HMR for this

**Comment by Jack-Works** [comment]
> Expected, you have hot: false and injectHot: false for the second config, so no HMR for this

@evilebottnawi hi please read again. my expectation is that has no HMR for the second config, but it _has_

**Comment by evilebottnawi** [comment]
My mistake

**Comment by Jack-Works** [comment]
I have workaround this problem by providing a function to `injectHot` and `injectClient`. But still hope this can be resolved.

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack-cli/issues/2408, we need improve multiple dev servers support
