### ISSUE TITLE
Enhancement of the Code Structure 

### ISSUE THREAD

**Issue by Cronus1007** [webpack/webpack-cli#1957]
**Describe the Bug**
The main workspace of the packages folder consist of the interfaces and stand alone functions i.e they lack the cohesion principle.
This issue is to list down the enhancement of the Code Structure.
**What is the Current Behaviour ?**
Wrapping down the interconnected interfaces and functions in a Class and explicitly exporting the function.

**Additional Context**
I have some ideas, will put a PR for feedback.
@snitin315  @anshumanv  Please share few ideas realted to this topic.

**Comment by evilebottnawi** [comment]
@Cronus1007 please describe your problem

**Comment by Cronus1007** [comment]
Sir actually the Code Structure is lacking the cohesion principle of the Classes i.e. The functions generated in the packages folder 
which are explicitly exported are stand alone functions but they also have dependencies on the Interfaces. So it would be better to wrap them up in a class and then exporting the functions. In this way,our code will be much more manageable.

**Comment by Cronus1007** [comment]
Sir let me send a PR realted to this issue.

**Comment by anshumanv** [comment]
I don't think wrapping in a class is a good idea, need to keep code minimal. Also, I don't get how this will help in managing the code.

> Sir let me send a PR realted to this issue.

Please discuss your approach before PR so nobody uses up their time unnecessarily.

**Comment by Cronus1007** [comment]
Okk sir.

**Comment by Cronus1007** [comment]
@anshumanv  Sir have a look #1933
