### ISSUE TITLE
Use babel-preset-env instead of 2015

### ISSUE THREAD

**Issue by kingdaro** [webpack/webpack-cli#196]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
The CLI initializes a project with the 2015 preset.

**What is the expected behavior?**
The CLI should use the env preset instead.

**If this is a feature request, what is motivation or use case for changing the behavior?**
It does the same as 2015, with additional fine-grained control for environment targets if the user cares to configure it. Also gets rid of the warning, bothersome or even confusing to some users.

I'd be happy to create a pull request for this 🙂

**Comment by ev1stensberg** [comment]
Yep, totally agree @kingdaro ! A PR would be great! Hit me up if you need help getting to know the codebase. The preset & installation is here:

https://github.com/webpack/webpack-cli/blob/master/lib/creator/yeoman/webpack-generator.js#L111-L119

https://github.com/webpack/webpack-cli/blob/master/lib/creator/yeoman/utils/module.js

**Comment by ev1stensberg** [comment]
It would be great if you PR this against my PR #194 , as there's a lot of changes in that one to the directory structure, but that's optional!

**Comment by kingdaro** [comment]
Done, made a pr against the feature/add branch. Hope I did it right 😄
