### ISSUE TITLE
Unknown argument: --plugin

### ISSUE THREAD

**Issue by lorenzodallavecchia** [webpack/webpack-cli#1965]
**Describe the bug**

The `--plugin` option is no longer recognized. I suspect that it has been renamed/moved, but I cannot find migration information anywhere.
I'm trying to migrate one of our tools to webpack 5 and therefore supporting the new CLI. The tool needs to dynamicallyl inject a plugin in a webpack execution: I cannot just add it to the configuration file.

**What is the current behavior?**

The error message `[webpack-cli] Unknown argument: --plugin` is printed.

**To Reproduce**

```sh
webpack --plugin C:\path\to\plugin.js
```

**Expected behavior**

Well, I'm kind of expecting that a "master" flag like `--plugin` is still supported, since it enables tapping into many other behaviors. Otherwise, it would be good to have a changelog explaining the migration path for the removed options.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

```
  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
    Memory: 9.71 GB / 15.94 GB
  Binaries:
    Node: 10.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (86.0.622.38)
    Internet Explorer: 11.0.19041.1
  Packages:
    html-webpack-plugin: ^4.5.0 => 4.5.0
    terser-webpack-plugin: ^5.0.0 => 5.0.0
    webpack: ^5.1.3 => 5.1.3
    webpack-cli: ^4.0.0 => 4.0.0
    webpack-dev-server: ^3.11.0 => 3.11.0
    workbox-webpack-plugin: ^5.1.4 => 5.1.4
```

**Comment by evilebottnawi** [comment]
No `--plugin` support anymore, it was removed

**Comment by lorenzodallavecchia** [comment]
I see... IMO these breakages should have been reported more clearly in a changelog.
Anyway, I have found another way to hack a plugin into the process, so it's fine for me.
Thank you.
