### ISSUE TITLE
Webpack 5 migration codemods

### ISSUE THREAD

**Issue by coderaiser** [webpack/webpack-cli#1968]
Errors provided by `webpack v5` is very useful, but would be much better to process `webpack.config.js` using codemods, for this purpose I started working on plugin [@putout/plugin-webpack](https://github.com/coderaiser/putout/tree/master/packages/plugin-webpack) for code transformer [putout](https://github.com/coderaiser/putout).

Right now it handles two kinds of errors:
- Exclamation mark separated loader lists has been removed in favor of the 'use' property with arrays
- Query arguments on 'loader' has been removed in favor of the 'options' property

Any ideas or improvements highly appreciated, and I want to ask core webpack team, what do you think about such way of doing migration? I find it very useful for my projects, because fix all things by hand again and again is pretty frustrating.

**Comment by alexander-akait** [comment]
We decide to deprecate `webpack migrate` due complex breaking changes and many of them impossible/very hard to solve using tools, sorry
