### ISSUE TITLE
webpack-cli cannot see @webpack-cli/serve from global install

### ISSUE THREAD

**Issue by wintercounter** [webpack/webpack-cli#1969]
**Describe the bug**

We are using a global tool that is able to share development environments across hundreds of projects/repositories to avoid spamming the developers machine and to make sure the environments are always synchronized. I tried an update to Webpack 5 and trying to move to `webpack serve` and running the command will try to search for `@webpack-cli/serve` in local node_modules only.

```
"webpack": "5.1.3",
"webpack-cli": "4.0.0",
```

**What is the current behavior?**

```
webpack serve
The command moved into a separate package: @webpack-cli/serve
Would you like to install serve? (That will run npm install -D @webpack-cli/serve) (yes/NO) : no
@webpack-cli/serve needs to be installed in order to run the command.
```

**To Reproduce**

1. `npm i webpack webpack-cli @webpack-cli/serve -g`
2. `webpack serve`
3. Observe message.

**Expected behavior**

Webpack-cli is able to resolve relative to `__dirname`.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

I have the same issue with `info` also.

**Comment by evilebottnawi** [comment]
Thanks for the issue
