### ISSUE TITLE
[Init] Add keyboard functionality for interpretor lists

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack-cli#198]
**Do you want to request a *feature* or report a *bug*?**

Bug (Usability)
**What is the current behavior?**
Currently when you get a multiple choice list from the init generator, there is no way to key through the options with arrow keys. (Technically with interpreter this is possible [cant remember if we use that])
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Be able to key up and down through lists in the cli generators with arrow keys. 

**If this is a feature request, what is motivation or use case for changing the behavior?**
Usability!

webpack-cli@latest

**Comment by ev1stensberg** [comment]
fixed in 541ba62f02c4a1fcc807eac62a551fcae3f2d2c3
