### ISSUE TITLE
webpack-cli@4 exits with 0 even when failing

### ISSUE THREAD

**Issue by fregante** [webpack/webpack-cli#1980]
# Bug report

`$ webpack` should exit with a non-0 code when it finds an error in `webpack.config.js`

**What is the current behavior?**

`$ webpack` exits with `0` even if it throws a fatal error:

<img width="237" alt="" src="https://user-images.githubusercontent.com/1402241/96945484-834cb800-14a3-11eb-8eb1-0605f5eb9d4d.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

```sh
npm install -g webpack webpack-cli@4
echo '.' > webpack.config.js
webpack
```

Notice that `webpack`’s version is irrelevant. `webpack-cli` is the problem

**What is the expected behavior?**

`webpack-cli@3` worked correctly, it exited with `1`. 

<img width="241" alt="" src="https://user-images.githubusercontent.com/1402241/96945472-7cbe4080-14a3-11eb-80e3-46e9733c0781.png">

**Other relevant information:**
webpack version: 4 or 5 (webpack version irrelevant)
webpack-cli version: 4.1.0
Node.js version: v13.8.0
Operating System: macOS 10.15.4
Additional tools:

**Comment by evilebottnawi** [comment]
@fregante Can you create reproducible test repo, i think fixed in master

**Comment by fregante** [comment]
@evilebottnawi it's https://github.com/fregante/webpack-issue-11789 

The repro is in GitHub Action

**Comment by benmvp** [comment]
Just ran into this problem. Upgraded to `4.2.0` and verified it worked. Thanks for the fix @snitin315!
