### ISSUE TITLE
Regression: socket option for serve is ignored

### ISSUE THREAD

**Issue by Roang-zero1** [webpack/webpack-cli#1982]
**Describe the bug**

If using the socket option while using the webpack serve command, it is ignored and default parameters (localhost:8000) are used.

This is a regression of https://github.com/webpack/webpack-cli/commit/4668ea78e125a698e0988ead30c82bec0f9bb8e3 caused by https://github.com/webpack/webpack-cli/commit/2cdf5ce159f63ac65b33f4aca4c82fa1e959fef5

**What is the current behavior?**

webpack serve will listen to the default TCP host and port instead of the socket.

**To Reproduce**

Minimal reproduction repository: https://github.com/Roang-zero1/webpack-dev-server-unix-socket-bug

1. Clone the https://github.com/Roang-zero1/webpack-dev-server-unix-socket-bug repository
1. Run `yarn install`
1. Use `yarn run serve` to start the server
1. Server is now available under localhost:8000

**Expected behavior**

webpack should serve on the configured socket

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (1) x64 Intel(R) Core(TM) i5-9400H CPU @ 2.50GHz
    Memory: 1.56 GB / 3.77 GB
  Binaries:
    Node: 10.19.0 - /tmp/yarn--1603453945580-0.7487274551062431/node
    Yarn: 1.22.10 - /tmp/yarn--1603453945580-0.7487274551062431/yarn
  Packages:
    webpack: ^5.2.0 => 5.2.0
    webpack-cli: ^4.1.0 => 4.1.0
    webpack-dev-server: ^3.11.0 => 3.11.0

**Additional context**

This is related to webpack-dev-server ignoring the socket option (https://github.com/webpack/webpack-dev-server/issues/2787)

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack-dev-server/issues/2787#issuecomment-715305922

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack.js.org/pull/4091
