### ISSUE TITLE
npm issues

### ISSUE THREAD

**Issue by vaxiobbxx** [webpack/webpack-cli#1983]
when running 'webpack' and i install webpack cli from 'npm install -D' it errors with:
```
npm ERR! code EINVAL
npm ERR! EINVAL: invalid argument, read
```

To reproduce:
Install webpack using:
npm i webpack --save-dev
then run 'webpack'
try to install webpack-cli on the command 'webpack'
errors on npm install

**Comment by evilebottnawi** [comment]
Please open an issue in npm repo
