### ISSUE TITLE
historyApiFallback not doing rewrites in webpack 5

### ISSUE THREAD

**Issue by superheri** [webpack/webpack-cli#1986]
- Operating System: Windows 10
- Node Version: 12.18.4
- NPM Version: 6.14.6
- webpack Version: 5.2.0
- webpack-dev-server Version: 3.11.0
- Browser: Google Chrome 86.0.4240.111

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```js
// webpack.config.js

devServer : {
    index: 'index.html',
    historyApiFallback: {
        rewrites: [
            {from: /a\/.*/, to: 'a/index.html'},
            {from: /b\/.*/, to: 'b/index.html'}
        ]
    }
}
```

### Expected Behavior

I expect this to actually return me to `a/index.html` when I do whatever url starting with `a/`.
I expect the same thing with `b`.
I also expect the 'index' option to be the file returned in any other case.

### Actual Behavior

It always return me the base `index.html`... Whatever value in `index` is the one returned.
From what it seems, it is like the code is doing a
```js
if (historyApiFallback) {...}
```
somewhere and it always acts like we wrote `true` in the `historyApiFallback` setting.

In webpack 4, it all worked well. I can't use only one file in index.html in my case because I need 2 'apps' (each with a different path), to be running at the same time.

### For Bugs; How can we reproduce the behavior?
Just reproduce a webpack.config.js with some config like my exemple and you can reproduce the bug easy.

**Comment by piecyk** [comment]
@eavichay yes, will check it.

**Comment by piecyk** [comment]
Problem here is that the `publicPath: '/'` is not pass in options to dev server. If publicPath is included in v4 then the rewrites works as in v3.

having this configuration in v3 we pass dev server as options

```js
{
  index: 'index.html',
  contentBase: './dist',
  writeToDisk: true,
  port: 3000,
  compress: true,
  historyApiFallback: _options.historyApiFallback,
  host: 'localhost',
  publicPath: '/',
  hot: undefined,
  hotOnly: undefined,
  clientLogLevel: 'info',
  stats: {
    cached: false,
    cachedAssets: false,
    colors: { level: 3, hasBasic: true, has256: true, has16m: true }
  }
}
```

but in v4 we pass

```js
{
  index: 'index.html',
  contentBase: './dist',
  writeToDisk: true,
  port: 3000,
  compress: true,
  historyApiFallback: { verbose: true, rewrites: [ [Object], [Object] ] },
  liveReload: true,
  serveIndex: true,
  inline: true,
  clientLogLevel: 'info'
}
```

Wondering how to resolve this as there are more difference like missing stats, plus liveReload, serveIndex, inline true by default

**Comment by evilebottnawi** [comment]
> Problem here is that the publicPath: '/' is not pass in options to dev server. If publicPath is included in v4 then the rewrites works as in v3.

yes `publicPath` will be works for v4 as for v3

**Comment by piecyk** [comment]
@superheri if you add `publicPath` to devServer in config then it will work as in v3

```js
devServer: {
  publicPath: '/',
  index: 'index.html',
  contentBase: './dist',
  writeToDisk: true,
  port: 3000,
  compress: true,
  historyApiFallback: {
      rewrites: [
          { from: /a\/.*/, to: 'a/index.html' },
          { from: /b\/.*/, to: 'b/index.html' }
      ]
  }
}
```

**Comment by evilebottnawi** [comment]
@piecyk Oh, yes, I see, thanks

@superheri webpack@5 have `publicPah: 'auto'` by default, it was breaking change

**Comment by superheri** [comment]
Just to be sure all I need to do is add the publicPath to '/'? If yes, I think the documentation should at least be updated to reflect the new default value since it is still shown as '/' by default on the documentation website https://webpack.js.org/configuration/dev-server/#devserverpublicpath-
![image](https://user-images.githubusercontent.com/30275781/97437863-747a6100-18fa-11eb-83cd-3589f599b7ab.png)

**Comment by evilebottnawi** [comment]
Found a bugs:
- docs are invalid, it should be `auto`
- webpack-dev-middleware@3 doesn't respect `publicPath: 'auto'`, but it is fixed for `v4` release will be today (we need couple days for updating it in webpack-dev-server)

**Comment by alexander-akait** [comment]
Fixed in `webpack-dev-server@4-beta.0` (we are working on the next beta, eta is current month)

**Comment by alexander-akait** [comment]
Feel free to feedback
