### ISSUE TITLE
Dedicated section to "breaking changes" in 4.0.0 release notes

### ISSUE THREAD

**Issue by dclowd9901** [webpack/webpack-cli#1995]
**Is your feature request related to a problem? Please describe.**

The real problem is I unfortunately don't have enough time to comb in great detail through release docs to figure out what will stop working with a module update (one of dozens that our application has).

**Describe the solution you'd like**

For major updates, it would be helpful if there was a section in the release notes dedicated to which changes are breaking changes, so we may easily find and address them.

**Describe alternatives you've considered**

I've considered combing through the notes, but there are about 100 commits listed, and it's not even clear which ones might contribute to a breaking change.

**Additional context**

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by dclowd9901** [comment]
> PR welcome

Is that supposed to be sarcasm or a joke? How am I supposed to know better than the contributors what constitutes a breaking change? If I _could_ have done this, I would have, believe me.

**Comment by evilebottnawi** [comment]
The main problem - some contributions made a lot of wrong releases and rewrite everything so much that now it's hard for me to say what has changed, unfortunately I would have done it too if I could

**Comment by dclowd9901** [comment]
I appreciate the honesty. Best wishes.
