### ISSUE TITLE
webpack --watch is not working on windows if root folder contains '(' or ')' in its name

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack-cli#20]
Hi,

I'm doing one of the tutorials that involves using webpack in watch mode, I noticed that whenever my 'root' (or rather current folder) contains '(' or ')' symbols in its paths, watching is not happening.

Am I missing anything? Can I tweak it in some way to get correct watching behaviour?

**Moved from https://github.com/webpack/webpack/issues/2258**

**Comment by SpaceK33z** [comment]
Moving again since this was the wrong project :smile:. Moved to https://github.com/webpack/watchpack/issues/42.
