### ISSUE TITLE
[serve] --hot-only is broken 

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#2004]
**Describe the bug**

`--hot-only` is broken.

**What is the current behavior?**

![Screenshot at 2020-10-31 16-39-01](https://user-images.githubusercontent.com/46647141/97777714-0ce14180-1b98-11eb-948d-1bfe97627678.png)

**To Reproduce**

`webpack serve --hot-only`

**Expected behavior**

Should work properly.

**Screenshots**
pasted above

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
No

**Comment by snitin315** [comment]
The webpack-dev-server v4 schema seems to work fine.

**Comment by anshumanv** [comment]
wip

**Comment by anshumanv** [comment]
There's a problem with config creator for serve package

**Comment by snitin315** [comment]
https://github.com/webpack/webpack-cli/blob/f86ef2d6c0a4cba3b2002baf32b78e06cbaafc4a/packages/serve/src/createConfig.ts#L22-L26

`v3` -> https://github.com/webpack/webpack-dev-server/blob/4ab1f21bc85cc1695255c739160ad00dc14375f1/lib/options.json#L136-L138

`v4` -> https://github.com/webpack/webpack-dev-server/blob/9f1d02b909e22ece60dde2e57cbfce14feafde69/lib/options.json#L133-L148

**Comment by anshumanv** [comment]
I think we should check dev server version and apply corresponding options 😞

**Comment by snitin315** [comment]
I believe it's here. This block should be executed for `v4` only.

>I think we should check dev server version and apply corresponding options disappointed

Yes
