### ISSUE TITLE
serveIndex is always true

### ISSUE THREAD

**Issue by 3bl3gamer** [webpack/webpack-cli#2018]
**Describe the bug**

`devServer.serveIndex` is always `true` regardless of config value.

**What is the current behavior?**

Dev server serves index with `serveIndex: false` in config.

**To Reproduce**

```js
// webpack.config.js
module.exports = {
    devServer: {
        serveIndex: false
    }
}
```

Empty `src/index.js`.

Run `./node_modules/.bin/webpack-cli serve`.

Project root files get listed on `http://127.0.0.1:8080`.

**Expected behavior**

No files at `http://127.0.0.1:8081`.

**`webpack-cli info`**

```
  System:
    OS: Linux 5.8 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 293.57 MB / 11.60 GB
  Binaries:
    Node: 14.13.1 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.7 - /usr/bin/npm
  Browsers:
    Firefox: 81.0.2
  Packages:
    webpack: ^5.3.2 => 5.3.2 
    webpack-cli: ^4.1.0 => 4.1.0 
    webpack-dev-server: ^3.11.0 => 3.11.0 
```

**Additional context**

`devServerArgs` contains `opts.serveIndex: true` though `args` is just `['--mode=development']` here:

https://github.com/webpack/webpack-cli/blob/master/packages/serve/src/index.ts#L16

Later in `startDevServer` that `true` value overrides `serveIndex: false` from config.

**Comment by anshumanv** [comment]
Checking this

**Comment by anshumanv** [comment]
@evilebottnawi this flag has a default value to `true` in dev-server flags hence it's always seen as a CLI arg after parsing and so config values are not able to override it.

**Comment by snitin315** [comment]
Yes, need to create PR in `webpack-dev-server`.

**Comment by anshumanv** [comment]
Yeah, let's remove defaults from flags and apply them in CLI directly.

**Comment by anshumanv** [comment]
wip

**Comment by alexander-akait** [comment]
I will fix it in near future

**Comment by alexander-akait** [comment]
Should be fixed https://github.com/webpack/webpack-dev-server/releases/tag/v3.11.2 I want to test it

**Comment by alexander-akait** [comment]
Yes, fixed
