### ISSUE TITLE
[Question] How to remove logging in watch mode?

### ISSUE THREAD

**Issue by BigMeat233** [webpack/webpack-cli#2019]
I find cli always printing message(ex: Compilation finished, watching files for updates) in v4.

But I only need the error message.

So how to close the success message in v4?

**Comment by snitin315** [comment]
I don't think you can.

**Comment by evilebottnawi** [comment]
Yes, no ability, why do you need this?

**Comment by piecyk** [comment]
This will be possible when webpack-cli would use `InfrastructureLogger` for logging. Similar as webpack-dev-server v4 will. 

There are two issues to use it in plugin 
1. webpack InfrastructureLogger is logging to stderr, that would be change from current stdout.
2. InfrastructureLogger is created from compiler, how we should log before?

**Comment by BigMeat233** [comment]
@evilebottnawi Hello, there is my scenarios:

I use webpack-cli watch mode to build project automatically. 

And I use a webpack plugin named ```friendly-errors-webpack-plugin``` to hide log message in building progress.

But the console always print '99% done plugins watchInfo[webpack-cli] Compilation finished [webpack-cli] watching files for updates...' when building success.

**Comment by BigMeat233** [comment]
@piecyk Hello, I want a flag to open/close the logger in **Line 288** and **Line 340** of the file ```/webpack-cli.js```.

**Comment by rishabh3112** [comment]
Seems to be a valid use-case to me. Many users may prefer to have a less verbose output in watch-mode.

**Comment by BigMeat233** [comment]
> Seems to be a valid use-case to me. Many users may prefer to have a less verbose output in watch-mode.

bingo！

**Comment by piecyk** [comment]
@BigMeat233 output from webpack should be controlled by the level in infrastructureLogging

 
So you would configure it in webpack config via 
```js
infrastructureLogging: {
  level: "error"
},
```

https://webpack.js.org/api/logging

**Comment by BigMeat233** [comment]
@piecyk Thanks for your anwser.

But I still can't hide the cli logging message in watch mode:

```
[webpack-cli] Compilation finished

[webpack-cli] watching files for updates...
```

**Comment by piecyk** [comment]
@BigMeat233 because it's not implemented yet.

**Comment by evilebottnawi** [comment]
In theory we can respect `infrastructureLogging` from config, it should be not hard

**Comment by piecyk** [comment]
@evilebottnawi yep i think that also, would go into this direction

https://github.com/webpack/webpack-cli/compare/master...piecyk:webpack-cli/infrastructure-logging

**Comment by piecyk** [comment]
@evilebottnawi can you have a quick look at that branch https://github.com/piecyk/webpack-cli/tree/webpack-cli/infrastructure-logging, ping me if that is something we would like to merge, need to fix tests 🙈

**Comment by evilebottnawi** [comment]
Looks good, but I am afraid it is not solve the whole problem, we use logger out of plugin too, so I think right way to fix it, just read the `infrastructureLogging` option from config

**Comment by piecyk** [comment]
> Looks good, but I am afraid it is not solve the whole problem, we use logger out of plugin too, so I think right way to fix it, just read the `infrastructureLogging` option from config

Yes we do. Most cases we log errors and exit process so in that case tooling based on webpack will never reach them `friendly-errors-webpack-plugin`

At first started also with replacing `utils/logger` with `require('webpack/lib/logging/runtime')` but this would make bigger breaking change. And configuring it with infrastructureLogging from options, we would need to drop `logger.raw` etc.

So decided going simpler, for now we can switch to infrastructureLogging in WebpackCLIPlugin that handles output from webpack what 99% users wants.

**Comment by evilebottnawi** [comment]
Yep, anyway feel free to send a PR and we continue improvements in PR, code looks good

**Comment by piecyk** [comment]
Ok, pushed a PR. Let's discuss there, i'm proposing there some changes to messages we log.
