### ISSUE TITLE
Could not find a yeoman configuration file.

### ISSUE THREAD

**Issue by arokia-innominds** [webpack/webpack-cli#2021]
when i run the webpack-cli init ./ i am getting this error

Could not find a yeoman configuration file.

Please make sure to use 'this.config.set('configuration', this.configuration);' at the end of the generator.

Unexpected Error
please file an issue here https://github.com/webpack/webpack-cli/issues/new?template=Bug_report.md

[TypeError: Cannot read property 'usingDefaults' of undefined]

**Comment by rishabh3112** [comment]
@arokia-innominds `webpack init` doesn't accept path for scaffolding, instead you run this in folder you may want to scaffold project.
Here is a example assuming a global installation of `webpack-cli` as per your report:
```
mkdir project
cd project
webpack init
```

P.S.
Please don't remove our issue template while filing issues in future. This may lead to closing of issue without response in future.

**Comment by evilebottnawi** [comment]
I want to mark it as feature, allow to generate loader/plugin code in any directory

**Comment by evilebottnawi** [comment]
@webpack/cli-team should be easy to implement

**Comment by jamesgeorge007** [comment]
I'll take a look at it.

**Comment by jamesgeorge007** [comment]
For `init`, isn't it better to have a flag for the purpose? (say, `--generate-path`)

**Comment by jamesgeorge007** [comment]
Closing.
