### ISSUE TITLE
tests: progress profile test is failing on CI

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack-cli#2028]
**Describe the bug**
https://github.com/webpack/webpack-cli/blob/56d32285c96c367669d9bc1317e53d466ad153aa/test/progress/progress-flag.test.js#L15 fails on CI.

**What is the current behavior?**
Described above

**To Reproduce**
https://github.com/webpack/webpack-cli/pull/2024/checks?check_run_id=1343622694
https://github.com/webpack/webpack-cli/pull/2005/checks?check_run_id=1343392331
https://github.com/webpack/webpack-cli/pull/2026/checks?check_run_id=1343806596

N/A

**Expected behavior**
Test should pass

**Screenshots**
N/A

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
N/A

**Additional context**
N/A

**Comment by rishabh3112** [comment]
Seems to be failing on webpack v4.

**Comment by evilebottnawi** [comment]
Yep, let's fix it

**Comment by anshumanv** [comment]
Fixed in https://github.com/webpack/webpack-cli/pull/2026
