### ISSUE TITLE
webpack-cli@v4.2.0 breaks color support on CI/CD

### ISSUE THREAD

**Issue by proton-ab** [webpack/webpack-cli#2038]
**Describe the bug**

Automated color detection was broken in v4.0.0 and subsequently fixed in v4.1.0. It is now broken again in v4.2.0 but only partially. The removal of `--color` flag also means we can not override this behavior and are left with uncolored output on CI.

**Expected behavior**

Either color support is properly detected or an override flag is provided again.

**Screenshots**

v4.1.0:
![firefox_2020-11-04_21-44-42](https://user-images.githubusercontent.com/25139420/98165963-0aa81b80-1ee7-11eb-8f31-a2487c84e951.png)

v4.2.0:
![firefox_2020-11-04_21-44-59](https://user-images.githubusercontent.com/25139420/98165976-109dfc80-1ee7-11eb-98f0-cd0e76855d4b.png)

Please note that Drone fully supports ANSI colors but might not be properly detected by some tools (or outright blocked due to CI environment variable being detected)

**Comment by snitin315** [comment]
Thanks for the report. I'm looking into it.

**Comment by snitin315** [comment]
>The removal of --color flag also means we can not override this behavior and are left with uncolored output 

We still support `--color` flag. You can use it.

https://github.com/webpack/webpack-cli/blob/0caa9184e22ed857e175c8dc0dd1e0a26f216374/packages/webpack-cli/lib/utils/cli-flags.js#L93

**Comment by proton-ab** [comment]
>We still support --color flag. You can use it.

Was going by comment https://github.com/webpack/webpack-cli/issues/1967#issuecomment-716034558

**Comment by evilebottnawi** [comment]
Note for myself:
```
// webpack.config.js
module.exports = [{
    entry: './src/index.js',
},
{
    entry: './src/index.js',
}];
```

adding test for multi compiler mode
