### ISSUE TITLE
Dynamic port selection for webpack-dev-server does not work

### ISSUE THREAD

**Issue by mkampmey** [webpack/webpack-cli#2051]
- Operating System: Windows 10
- Node Version: 11.9.0
- NPM Version: 6.5.0
- webpack Version: 5.4.0
- webpack-dev-server Version: 3.11.0
- Browser: Firefox

- [x] This is a **bug**
- [ ] This is a **modification** request

### Code

```
// package.json
{
    "name": "webpack-dynamic-port-test",
    "version": "0.1.0-SNAPSHOT",
    "description": "",
    "main": "./src/index.js",
    "private": false,
    "scripts": {
        "serve": "webpack serve --mode=development"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "@babel/core": "^7.12.3",
        "@babel/preset-env": "^7.12.1",
        "babel-loader": "^8.1.0",
        "webpack": "^5.4.0",
        "webpack-cli": "^4.1.0",
        "webpack-dev-server": "^3.11.0"
    }
}
```

```js
// webpack.config.js
module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'js/lib.js',
    libraryTarget: 'system',
  },
  devServer: {
    injectClient: false,
  },
  module: {
    rules: [
      {
        test: /\.m?js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
        },
      },
    ],
  },
}
```

### Expected Behavior
When executing `npm run serve`, the webpack-dev-server should automatically select the next available port starting from 8080.

### Actual Behavior
webpack-dev-server always selects port 8080.

### For Bugs; How can we reproduce the behavior?
Create a new directory and create the above mentioned two files. Additionally you need an empty `index.js` in the directory `src`. Open a shell and run `npm run serve`. Open another shell and also execute `npm run serve`. Then you will receive the error `EADDRINUSE`.

**Comment by evilebottnawi** [comment]
@webpack/cli-team we should move logic from webpack-dev-server to here

**Comment by snitin315** [comment]
@evilebottnawi Can you share a link for the logic in`webpack-dev-server`.

**Comment by evilebottnawi** [comment]
@snitin315 https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/processOptions.js for v3 and I think for v4 we have the same logic (but need to look), we should move logic for `findPort` here

**Comment by alexander-akait** [comment]
Fixed for webpack-dev-server@4-beta.0

**Comment by andyhall** [comment]
Hi, has this issue regressed? Using current webpack-* , if I try to serve two different projects that don't specify a port, they both serve to `8080` and the second one reports error `EADDRINUSE`.

Versions are current:
```json
  "devDependencies": {
    "webpack": "^5.39.0",
    "webpack-cli": "^4.7.2",
    "webpack-dev-server": "^3.11.2"
  }
```

Zero webpack config:
```js
module.exports = (env) => ({
    mode: 'development',
    entry: './index.js',
    devServer: {
        stats: "minimal",
    },
})
```

Output (testing on current macos, node `v14.17.0`):
```sh
> npx webpack serve
✖ ｢wds｣:  Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1503:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:8) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080
}
```

**Comment by andyhall** [comment]
Hi, can this be reopened? 

I can file a new issue, but the details would be mostly identical to this one.

**Comment by snitin315** [comment]
Can you try with webpack-dev-server@4-beta.3

**Comment by andyhall** [comment]
@snitin315 Thanks, the issue doesn't reproduce in 4-beta for me.

(v4 breaks lots of other things though - I don't suppose there's a migration document?)

**Comment by snitin315** [comment]
I am working on a migration documentation. It will be available within few days.

For now you can refer the changelog.
