### ISSUE TITLE
stats option is not respected in watch mode in 4.2.0

### ISSUE THREAD

**Issue by mihkeleidast** [webpack/webpack-cli#2052]
**Describe the bug**

Specifiying the stats option in webpack config has no impact on cli output with webpack-cli 4.2.0. Everything is always output. 
```
// webpack.config.js
module.exports = {
  ...whatever
  stats: 'none',
};
```
Using 4.1.0 outputs what I specify in the stats option.

**Expected behavior**

I expect the stats option to be respected.

**Screenshots**

4.2.0 (a lot more but i don't think a large image helps):
![image](https://user-images.githubusercontent.com/1892091/98397352-ea539a80-2067-11eb-8ec3-dfc15f498967.png)

4.1.0:
![image](https://user-images.githubusercontent.com/1892091/98397641-52a27c00-2068-11eb-9488-a57bec734528.png)

**Additional context**

`"webpack": "^4.44.2"
`

**Comment by anshumanv** [comment]
Thanks for the report, checking

**Comment by anshumanv** [comment]
Seems to work for me, with both webpack 5 and 4.44.2 - 

![image](https://user-images.githubusercontent.com/21009455/98399096-f18aa080-2087-11eb-8395-01198a9b8f94.png)

Here's my simple config - 


```js
module.exports = {
    stats: 'none'
}

```

@mihkeleidast can you make a minimal reproducible test repo so I can look into it further? Thanks!

**Comment by mihkeleidast** [comment]
Oh, looks like `watch: true` needs to be specified also.

```
module.exports = {
    stats: 'none',
    watch: true,
};
```

4.1.0:
![image](https://user-images.githubusercontent.com/1892091/98400731-3e14b280-206d-11eb-93dd-43d05423bd91.png)

4.2.0:
![image](https://user-images.githubusercontent.com/1892091/98400774-52f14600-206d-11eb-8331-ac52e0cd38b3.png)

**Comment by anshumanv** [comment]
Great, thanks! Yep seems a problem when watch is present, strange though doesn't happen with webpack 5 but only with 4.44.2, will PR a solution for this.

**Comment by anshumanv** [comment]
@evilebottnawi do you have any ideas what may be causing this?

**Comment by evilebottnawi** [comment]
@anshumanv Do you reproduce it?

**Comment by anshumanv** [comment]
@evilebottnawi yep, but only with webpack 4.
