### ISSUE TITLE
stats are not colored in v4 when config returns multiple objects

### ISSUE THREAD

**Issue by mihkeleidast** [webpack/webpack-cli#2054]
**Describe the bug**

When a webpack config returns multiple configurations as an array, the output stats are not colored.

```
// webpack.config.js
module.exports = [{
    entry: './src/index.js',
},
{
    entry: './src/index.js',
}];
```

**Expected behavior**

Stats should be colored when there are more than one configurations returned by the config file.

**Screenshots**

4.2.0, multiple configurations (example above):
![image](https://user-images.githubusercontent.com/1892091/98409025-d4030a00-207a-11eb-9493-806f272fcbef.png)

4.2.0, single config (file can return an array with a single object):
![image](https://user-images.githubusercontent.com/1892091/98409129-f72db980-207a-11eb-840c-360121b468ac.png)

3.3.12, same config as above:
![image](https://user-images.githubusercontent.com/1892091/98409201-10366a80-207b-11eb-9a37-bb8a65e59f8d.png)

**Additional context**

Webpack 4.44.2.

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack/webpack-cli/issues/2038, title can be misleading, but the problem in one place
