### ISSUE TITLE
can't run webpack serve when installing webpack-cli@4.1

### ISSUE THREAD

**Issue by mihkeleidast** [webpack/webpack-cli#2055]
**Describe the bug**

I've run into multiple issues with 4.2 so I decided to stay on 4.1. However, when I install 4.1 explicitly, I can't run `webpack serve` anymore.

**To Reproduce**

In an empty directory:
1. run `npm init` (default values are fine)
2. run `npm i webpack-cli@4.1 webpack webpack-dev-server`
3. run `npx webpack serve`
4. See error: 
![image](https://user-images.githubusercontent.com/1892091/98413384-34e21080-2082-11eb-9fe0-fdad05914245.png)

**Expected behavior**

`webpack serve` should work when trying to run from an older version.

**Mention other relevant information**
Node v12.18.2
npm v6.14.8 (might matter because of dependency tree resolving? idk)

This may be a non-issue currently if I can upgrade to latest, but it may bite again whenever someone tries to install an older version to downgrade...

**Comment by evilebottnawi** [comment]
Fixed, don't know what we can do here

**Comment by mihkeleidast** [comment]
Was there a specific fix or is it simply not possible to install/use an older version? 🙄

**Comment by evilebottnawi** [comment]
Do not use old version

**Comment by mihkeleidast** [comment]
That does not make any sense at all - noone is going to be able to find out when bugs were introduced when old versions are broken by releasing new ones.

**Comment by evilebottnawi** [comment]
What do you suggest I do here? We had a bug, we fixed it and released the new version

**Comment by mihkeleidast** [comment]
Yeah that was my question, if this was a known bug and is fixed now. I'm rather curious, what the bug was and what fixed it?

**Comment by evilebottnawi** [comment]
@mihkeleidast Do you use monorepos,

**Comment by mihkeleidast** [comment]
Not on the project this happened on - otherwise yes.

**Comment by evilebottnawi** [comment]
It was bug with fields in webpack-cli and bug on webpack side on first run, it was fixed in latest versions

**Comment by mihkeleidast** [comment]
Thanks for the explanation :)
