### ISSUE TITLE
Feature: More user friendly startup message

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#206]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
`Insecure about some of the questions?` are vaguely written, and it would be better to have a more neutral / empathic message on startup.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
A better introduction to the `init-generator`
**If this is a feature request, what is motivation or use case for changing the behavior?**
User Experience 

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

**Comment by sumit-gupta91** [comment]
Hi guys,
I would like to contribute in webpack-cli and I would like to take up this issue.

**Comment by ev1stensberg** [comment]
Awesome @sumit-gupta91 , hit me up if you need help!

**Comment by dhruvdutt** [comment]
@ev1stensberg I took a look at the closed PRs related to this issue. Can I continue the same work with the things you suggested in those PRs?
Please suggest what is needed. I would like to take this up. :hand:

**Comment by ev1stensberg** [comment]
Need to look at the way to avoid #276

**Comment by FadySamirSadek** [comment]
I would like to help work on this , will check closed PRs and follow up from there

**Comment by FadySamirSadek** [comment]
@ev1stensberg since there has been changes in the master branch and no new commits have been added to the V2 branch should I still base my branch on v2 or use master instead ?

**Comment by ev1stensberg** [comment]
Use master

**Comment by FadySamirSadek** [comment]
@ev1stensberg I think this issue was solved at #218 and should be closed , please tell me if there is anything more to be done 😉

**Comment by ev1stensberg** [comment]
It wasn't. Webpack and its 0CJS and that PR collided, so we reverted it
