### ISSUE TITLE
webpack serve --open does not work?!

### ISSUE THREAD

**Issue by martinoppitz** [webpack/webpack-cli#2062]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snitin315** [comment]
please use `webpack serve --open chrome`

**Comment by snitin315** [comment]
`webpack serve --open` will be supported with `webpack-derv-server` version `4`

**Comment by snitin315** [comment]
Duplicate of #2001
