### ISSUE TITLE
within monorepo keep getting [webpack-cli] The command moved into a separate package: @webpack-cli/serve 

### ISSUE THREAD

**Issue by IljaDaderko** [webpack/webpack-cli#2081]
I'm not sure if this is a bug or something else, but on every version after 5.2 I keep getting following error when trying to run serve command:
```
[webpack-cli] The command moved into a separate package: @webpack-cli/serve
```

The command that triggers this is
```
webpack serve --config webpack/development.js
```

CLI asks me if I want to install `@webpack-cli/serve`, I agree to that prompt and install that, but then still get the error. My hunch is that it can be related to monorepos?

My repo structure looks like this
```
packages
 app/
   package.json
package.json
```

I run my commands from root package.json, but all webpack packages are scoped to `app`.

**Comment by evilebottnawi** [comment]
@IljaDaderko Please use the issue template in future, otherwise we will close your issue with reply, respect time of other developers, thanks

**Comment by IljaDaderko** [comment]
@evilebottnawi will do, I wasn't sure if this was a legitimate issue or some change I missed while upgrading webpack version, hence used `[Other]` option.

**Comment by evilebottnawi** [comment]
@IljaDaderko What is version of `npm`? I think you have hoist problem here, and we can't fix it on our side

**Comment by IljaDaderko** [comment]
@evilebottnawi `npm@7.0.9`, but also happens to me on `yarn@1.22.10`. Are you sure this is an upstream issue? This message only started coming up after `webpack@5.2`, prior to that everything worked as expected.

**Comment by evilebottnawi** [comment]
@IljaDaderko Can you run `npm ls webpack-cli` and `npm ls @webpack-cli/serve`?

**Comment by IljaDaderko** [comment]
Sure, here are the outputs @evilebottnawi 

npm ls webpack-cli
```
project@1.0.0 /Users/ilja/Documents/GitHub/project
└─┬ app@1.0.0 -> /Users/ilja/Documents/GitHub/project/packages/app
  └─┬ webpack-cli@4.2.0
    ├─┬ @webpack-cli/info@1.1.0
    │ └── webpack-cli@4.2.0 deduped
    └─┬ @webpack-cli/serve@1.1.0
      └── webpack-cli@4.2.0 deduped
```

npm ls @weebpack-cli/seerve
```
project@1.0.0 /Users/ilja/Documents/GitHub/project
└─┬ app@1.0.0 -> /Users/ilja/Documents/GitHub/project/packages/app
  └─┬ webpack-cli@4.2.0
    └── @webpack-cli/serve@1.1.0
```

**Comment by sibelius** [comment]
I'm getting this error on yarn 1 as well

which webpack-cli version does not have this problem?

**Comment by evilebottnawi** [comment]
@sibelius Do you use monorepos too?

**Comment by sibelius** [comment]
I have a working monorepo using webpack 5

and I have a broken monorepo using webpack 4

**Comment by evilebottnawi** [comment]
@sibelius Is this problem happens only for webpack@4 or webpack@5?

**Comment by sibelius** [comment]
can we make `@webpack-cli/serve` a warning? 

so we can migrate when it is done?

for me only on webpack@4

**Comment by sibelius** [comment]
@webpack-cli/serve@1.1.0
webpack-cli@4.1.0

should I try 4.2.0?

**Comment by evilebottnawi** [comment]
Update `webpack-cli@4.2.0`

**Comment by sibelius** [comment]
`webpack-cli@4.2.0` worked for us

tks

**Comment by IljaDaderko** [comment]
In my case this doesn't work

```
"webpack": "5.4.0",
"webpack-cli": "4.2.0",
```

**Comment by evilebottnawi** [comment]
Investigating the problem

**Comment by evilebottnawi** [comment]
@IljaDaderko updating to `4.2` solve the problem, tests on npm and yarn, please update lock file too
