### ISSUE TITLE
--watch needs timestamp

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack-cli#21]
This isn't really a bug, but more a feature request. I'm not sure if this is the right forum for it?

Please can you add a timestamp to --watch so we can visually inspect if a build took place?

For example, sometimes --watch silently hangs, sometimes I save the wrong file etc. If the code editor and the terminal windows are not always visible at once, being able to glance at the timestamp of the most recent build is useful way to check if things are working.

This is akin to checking the timestamp of an executable to verify that the build succeeded and wrote the file you're expecting it to.

Thank you!

**Moved from https://github.com/webpack/webpack/issues/1499**

**Comment by bebraw** [comment]
This is literally

```javascript
plugins: [
        function() {
            this.plugin('watch-run', function(watching, callback) {
                console.log('Begin compile at ' + new Date());
                callback();
            })
        }
    ]
```

as discussed in the comments.

**Comment by cachvico** [comment]
OP here. Thanks for implementing this guys!

**Comment by ev1stensberg** [comment]
💙💙
