### ISSUE TITLE
Webpack-cli serve options merge wrong

### ISSUE THREAD

**Issue by joacub** [webpack/webpack-cli#2102]
this is that the current version do:
```js
const options = mergeOptions_1.default(cliOptions, devServerOpts);
```
so always override cliOptions into devServerOptions at this time is impossible disable liveReload because comes in cliOptions always true
```js
const options = mergeOptions_1.default(devServerOpts, cliOptions);
```

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by evilebottnawi** [comment]
cli options should be prefered

**Comment by joacub** [comment]
> cli options should be prefered

I know but i never put that option, there is no way for disabled defaulted options which comes in clientoptions var

**Comment by anshumanv** [comment]
@evilebottnawi this is due to the default flag values in dev server v3 which are removed in v4

**Comment by joacub** [comment]
> @evilebottnawi this is due to the default flag values in dev server v3 which are removed in v4

🤔 i have dev server v4 i dont know why the default still there

**Comment by joacub** [comment]
Btw, webpack docs still saying that the default option for liveReload is true

**Comment by anshumanv** [comment]
Seems removed in v4 - https://github.com/webpack/webpack-dev-server/blob/v4/bin/cli-flags.js

Can you verify if you're actually using `webpack-dev-server` v4?

**Comment by joacub** [comment]
> Seems removed in v4 - https://github.com/webpack/webpack-dev-server/blob/v4/bin/cli-flags.js
> 
> Can you verify if you're actually using `webpack-dev-server` v4?

I tested always is true in clientOptions

**Comment by evilebottnawi** [comment]
What is webpack-dev-server version?

**Comment by joacub** [comment]
> What is webpack-dev-server version?

yes you guys are right, Webpack-dev-server is version 3, version 4 is not released yet ?

**Comment by evilebottnawi** [comment]
No, is not released yep, hope, I will do it soon, many issues

**Comment by joacub** [comment]
> No, is not released yep, hope, I will do it soon, many issues

hahaha i imagine, not worries thanks for your work.

i dont know if this is related but react-refresh and hot seems likes is working but never happens the refresh in the browser I have to reload completely, maybe is related idk.

thanks again
