### ISSUE TITLE
webpack serve doesn't detect @webpack-cli/serve on codesandbox anymore

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack-cli#2104]
**Describe the bug**

webpack-cli used to work in codesandox but lately it doesn't detect @webpack-cli/serve and is stuck in this prompt:

![html-webpack-plugin_5_x_alpha_html-loader_-_CodeSandbox](https://user-images.githubusercontent.com/4113649/98947085-0edec500-24f5-11eb-873d-9be2890a7118.png)

**What is the current behavior?**

**To Reproduce**

1. go to https://codesandbox.io/s/html-webpack-plugin-5x-alpha-html-loader-q5cg3?file=/webpack.config.js
2. restart the server
3. wait for it to restart

![html-webpack-plugin_5_x_alpha_html-loader_-_CodeSandbox](https://user-images.githubusercontent.com/4113649/98947254-40f02700-24f5-11eb-85b5-2de1823adf17.png)

**Comment by evilebottnawi** [comment]
Fixed in 4.2

**Comment by evilebottnawi** [comment]
Please always check dependencies

**Comment by jantimon** [comment]
Thank you so much for all your work @evilebottnawi - it works with 4.2.0
