### ISSUE TITLE
Initialized project w/o source file config results in TypeScript compilation error

### ISSUE THREAD

**Issue by jouni-kantola** [webpack/webpack-cli#2106]
**Describe the bug**

After using `webpack-cli@4.2.0`'s init with TypeScript, cannot build boilerplated project directly, as it's missing files to include in TypeScript's `tsconfig.json`.

**What is the current behavior?**

`npx webpack-cli` results in following error(s):
```
# [PROJECT_PATH] is dir where webpack.config.js is
ERROR in [PROJECT_PATH]/node_modules/webpack/lib/javascript/JavascriptParser.js
[tsl] ERROR in [PROJECT_PATH]/node_modules/webpack/lib/javascript/JavascriptParser.js(3308,7)
      TS2578: Unused '@ts-expect-error' directive.
```

**To Reproduce**

1. `npm install webpack-cli @webpack-cli/init webpack --save-dev && npx webpack-cli init`
1. Choose `Typescript` in step `Will you use one of the below JS solutions?`
1. `npx webpack-cli` results in the error described as current behavior

**Expected behavior**

Include entry point in `tsconfig.json`, e.g:
```
"compilerOptions": {
...
},
"files": ["src/index.ts"]
```

**Additional context**

```zsh
$ node -v
v14.13.0


$ cat package.json
{
  "name": "my-webpack-project",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@webpack-cli/init": "^1.0.3",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "terser-webpack-plugin": "^5.0.3",
    "ts-loader": "^8.0.11",
    "typescript": "^4.0.5",
    "webpack": "^5.4.0",
    "webpack-cli": "^4.2.0"
  },
  "description": "My webpack project",
  "scripts": {
    "build": "webpack"
  }
}

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101
```

**Comment by snitin315** [comment]
Thanks for the report. I was able to reproduce it. 
I will push a fix in the near future.
