### ISSUE TITLE
[BUG]: 🐞webpack 4.2.x does not appear to honor `stats` settings in watch mode

### ISSUE THREAD

**Issue by nigelellis** [webpack/webpack-cli#2107]
**Describe the bug**
After bumping from webpack-cli 4.2.0 to 4.2.0, our webpack *watch* build has started to output statistics output despite being disabled via. options.  

**What is the current behavior?**
Our [stats configuration](https://webpack.js.org/configuration/stats/#stats-options) is set up as follows and we purposely disable modules, children, and cached output:
```
{
  cached: false,
  children: false,
  modules: false,
}
```

Webpack-cli is invoked with:
```
ts-node -require tsconfig-paths/register ./node_modules/.bin/webpack-cli -w --config=webpack.config.ts
```

If I revert back to webpack-cli 4.1, the additional verbose output disappears.    I've checked both the release notes and commit diffs for 4.2, and can't find anything there that would explain the issue.   If I pass in `stats: {all: false}` I still get stats output which runs counter to my expectations on the `all=false` setting. 

As best as I can tell, in 4.2 we are no longer processing the `stats` options and maybe picking up defaults.

We're using the following versions -- plugin version don't make a difference:
* webpack: 4.44.2
* webpack-cli: 4.2.0 (reverting to 4.1.0 fixes the issue)
* with plugins: mini-css-extract-plugin, hard-source-webpack-plugin, css-loader, postcss-loader, less-loader, thread-loader, and ts-loader

Is this an expected change in behavior?   If so, how do I revert back to the prior behavior?   I apologize for not getting a standalone repro -- our config is pretty complex and chopping it down will take me quite a bit of time.    Happy to dig into that if needed but thought I'd float this issue out there first for early feedback.   Thanks.

**Expected behavior**

When running --watch under 4.1.0 I see the following output:
```
[hardsource:0747d370] Configuration changed. Building new cache.
[webpack-cli] Compilation starting...
 SMP  ⏱
General output time took 20.6 secs
 SMP  ⏱  Loaders
mini-css-extract-plugin, and
css-loader, and
postcss-loader, and
less-loader took 17.85 secs
  module count = 115
cache-loader, and
thread-loader, and
ts-loader took 17.71 secs
  module count = 1000
css-loader, and
postcss-loader, and
less-loader took 16.81 secs
  module count = 115
modules with no loaders took 15.41 secs
  module count = 1276
[webpack-cli] Compilation finished
[webpack-cli] watching files for updates...
```

When running --watch under 4.2.0, I see the same prelude output but it follows with lots of additional stats output which looks like all stats options are ignored and defaults are picked up:
```
...
  module count = 1276
... <IDENTICAL OUTPUT to 4.1.0 ABOVE>
Hash: d99335498a86cc05cf3a
Version: webpack 4.44.2
Time: 21781ms
Built at: 11/12/2020 2:32:09 PM
                                             Asset       Size            Chunks                         Chunk Names
                  ../server/adminApp.manifest.json  428 bytes                    [emitted]
               admin.e23ade07d3cd70eb3c49.entry.js   13.5 MiB             admin  [emitted] [immutable]  admin
           admin.e23ade07d3cd70eb3c49.entry.js.map   11.7 MiB             admin  [emitted] [dev]        admin
                    admin.fb42b9515943bed6c28e.css    169 KiB             admin  [emitted] [immutable]  admin
                admin.fb42b9515943bed6c28e.css.map    255 KiB             admin  [emitted] [dev]        admin
    vendors~postload.65c899b92f45b7a2cf9a.chunk.js   74.2 KiB  vendors~postload  [emitted] [immutable]  vendors~postload
vendors~postload.65c899b92f45b7a2cf9a.chunk.js.map   75.8 KiB  vendors~postload  [emitted] [dev]        vendors~postload
Entrypoint admin = admin.fb42b9515943bed6c28e.css admin.e23ade07d3cd70eb3c49.entry.js admin.fb42b9515943bed6c28e.css.map admin.e23ade07d3cd70eb3c49.entry.js.map (prefetch: vendors~postload.65c899b92f45b7a2cf9a.chunk.js vendors~postload.65c899b92f45b7a2cf9a.chunk.js.map)
[./modules/browser-admin/base-components/admin_page.tsx] 16.3 KiB {admin} [built]
[./modules/browser-admin/base-components/base.less] 39 bytes {admin} [built]
...
    + 2264 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--5-1!node_modules/postcss-loader/src/index.js??ref--5-2!node_modules/less-loader/dist/cjs.js??ref--5-3!modules/browser-admin/accounts-components/private/account_metadata_view.less:
    Entrypoint mini-css-extract-plugin = *
...
```

**Comment by evilebottnawi** [comment]
Fixed in master, not released yet

**Comment by evilebottnawi** [comment]
Release will be in near future
