### ISSUE TITLE
npx webpack init doesn't work - Could not find a yeoman configuration file (.yo-rc.json). error

### ISSUE THREAD

**Issue by mterczynski** [webpack/webpack-cli#2110]
**Describe the bug**

`npx webpack init` doesn't work - `Could not find a yeoman configuration file (.yo-rc.json).` error

**What is the current behavior?**

I see output

```bash
[webpack-cli]
Could not find a yeoman configuration file (.yo-rc.json).

[webpack-cli]
Please make sure to use 'this.config.set('configuration', this.configuration);' at the end of the generator.       

[webpack-cli] [TypeError: Cannot read property 'nodejs-typescript-template' of undefined]
[webpack-cli] TypeError: Cannot read property 'nodejs-typescript-template' of undefined

[webpack-cli] Your yeoman configuration file (.yo-rc.json) was incorrectly formatted. Deleting it may fix the problem.

[webpack-cli] 
Congratulations! Your new webpack configuration file has been created!

You can now run yarn build to bundle your application!
```

webpack.config.js file is created, but it has only this line as its content

```javascript
module.exports = {}
```

**To Reproduce**

`npx webpack init`, then choose these options:

```bash
? Will your application have multiple bundles? No
? Which will be your application entry point? src/index
? In which folder do you want to store your generated bundles? dist
? Will you use one of the below JS solutions? Typescript
? Will you use one of the below CSS solutions? No
```

**Expected behavior**

No errors in the console, `webpack.config.js` is configured correctly .

**Screenshots**

![image](https://user-images.githubusercontent.com/27309340/99088843-df9b8700-25cc-11eb-9e15-bfeabd61b2a3.png)

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

I use `webpack` 5.4.0 and `webpack-cli` 4.2.0

**Comment by evilebottnawi** [comment]
Answer should be Y/N

**Comment by mterczynski** [comment]
Yes, sorry, my bad. For `Will your application have multiple bundles?` questions there is `y/N` - I've chosen "N" for this one.
Others are "choose one from a list" type of questions.

**Comment by evilebottnawi** [comment]
Anyway we should log error on invalid answer and re ask it again

**Comment by mterczynski** [comment]
My answers weren't invalid, I think. What do you mean?

**Comment by rendall** [comment]
Can confirm this for both Windows 10 and Ubuntu 14.04

**Comment by rendall** [comment]
Interestingly, there is this output. Not sure if it's related, but it mentions `yeoman`:
```
√ Would you like to install @webpack-cli/init? (That will run yarn add -D @webpack-cli/init) (Y/n) · true
yarn add v1.22.5
[1/4] Resolving packages...
warning @webpack-cli/init > @webpack-cli/generators > yeoman-generator > yeoman-environment > npm-api > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by rendall** [comment]
If you select `No` to the question `Will you use one of the below JS solutions?` then an `.yo-rc.json` file is created, but `webpack.config.js` remains `module.exports = {};`

The content of the `.yo-rc.json` file is:
```
{
  "configuration": {
    "config": {
      "configName": "config",
      "topScope": [
        "const path = require('path');",
        "const webpack = require('webpack');",
        "\n",
        "/*\n * SplitChunksPlugin is enabled by default and replaced\n * deprecated CommonsChunkPlugin. It automatically identifies modules which\n * should be splitted of chunk by heuristics using module duplication count and\n * module category (i. e. node_modules). And splits the chunks…\n *\n * It is safe to remove \"splitChunks\" from the generated configuration\n * and was added as an educational example.\n *\n * https://webpack.js.org/plugins/split-chunks-plugin/\n *\n */",
        "const HtmlWebpackPlugin = require('html-webpack-plugin')",
        "\n",
        "/*\n * We've enabled HtmlWebpackPlugin for you! This generates a html\n * page for you when you compile webpack, which will make you start\n * developing and prototyping faster.\n *\n * https://github.com/jantimon/html-webpack-plugin\n *\n */",
        "const workboxPlugin = require('workbox-webpack-plugin');",
        "\n",
        "/*\n * We've enabled TerserPlugin for you! This minifies your app\n * in order to load faster and run less javascript.\n *\n * https://github.com/webpack-contrib/terser-webpack-plugin\n *\n */",
        "const TerserPlugin = require('terser-webpack-plugin');",
        "\n"
      ],
      "webpackOptions": {
        "mode": "'production'",
        "plugins": [
          "new webpack.ProgressPlugin()",
          "new HtmlWebpackPlugin({\n\t\t\t\t\ttemplate: 'index.html'\n\t\t\t\t})",
          "new workboxPlugin.GenerateSW({\n\t\t\t\tswDest: 'sw.js',\n\t\t\t\tclientsClaim: true,\n\t\t\t\tskipWaiting: false,\n\t\t\t})"
        ],
        "module": {
          "rules": []
        },
        "devServer": {
          "open": true
        },
        "optimization": {
          "minimizer": [
            "new TerserPlugin()"
          ],
          "splitChunks": {
            "chunks": "'all'"
          }
        }
      }
    },
    "usingDefaults": true
  }
}

**Comment by goldhand** [comment]
I've been experiencing several issues with webpack-scaffold. Not just this one (though I do get this).

When [specifying scaffold packages](https://www.npmjs.com/package/webpack-scaffold-demo), I consistently get the error:

`TypeError: self.prompt is not a function`

Node: 12.16.1
OSX: 10.14.6
webpack-cli@4.3.1

Also the instructions in the [tutorial](https://webpack.js.org/contribute/writing-a-scaffold/) get the same error.

**Comment by rishabh3112** [comment]
> When specifying scaffold packages, I consistently get the error:
> TypeError: self.prompt is not a function

@goldhand that particular error should be fixed if you create your custom scaffolder using [`webpack-scafold-pwa`](https://github.com/rishabh3112/webpack-scaffold-starter)

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack-cli/issues/2430
