### ISSUE TITLE
webpack.config.js: first parameter changed from v4 to v5

### ISSUE THREAD

**Issue by gimmi** [webpack/webpack-cli#2111]
Take this `webpack.config.js`

```js
module.exports = function (env) {
    console.log('env parameter value: ', env)
}
```

With webpack@4

```
> npm list --depth=0
+-- webpack@4.44.2
+-- webpack-cli@3.3.12
```

The result is this

```
env parameter value:  development
```

Instead, with webpack@5

```
> npm list --depth=0
+-- webpack@5.4.0
+-- webpack-cli@4.2.0
```

The result is this

```
env parameter value:  { development: true }
```

Seems that this is not mentioned in [To v5 from v4](https://webpack.js.org/migrate/5/), it should really be there!

**Comment by martinoppitz** [comment]
Cant reproduce that:

![image](https://user-images.githubusercontent.com/6279703/99205401-bb040280-27b8-11eb-8146-e5eb2fd3ca8a.png)

![image](https://user-images.githubusercontent.com/6279703/99205454-e555c000-27b8-11eb-8da5-cbeb97ea5614.png)

**Comment by evilebottnawi** [comment]
@gimmi Please provide command how you run webpack

**Comment by gimmi** [comment]
This is the relevant part of my `pacjage.json`

```json
{
  "scripts": {
    "watch": "webpack --env development --watch",
    "build": "webpack --env production"
  },
  "devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-react": "^7.12.5",
    "babel-loader": "^8.2.1",
    "css-loader": "^5.0.1",
    "eslint": "^7.13.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-react": "^7.21.5",
    "html-webpack-plugin": "^4.5.0",
    "immer": "^7.0.14",
    "react-split": "^2.0.9",
    "style-loader": "^2.0.0",
    "webpack": "^5.4.0",
    "webpack-cli": "^4.2.0"
  }
}
```

**Comment by evilebottnawi** [comment]
env is always object in webpack@5, it is breaking change, so in this case `production` is boolean argument

**Comment by gimmi** [comment]
Yes my point is that, given that this is a breaking change, maybe it is a good idea to put it somewhere in [To v5 from v4](https://webpack.js.org/migrate/5/)

**Comment by evilebottnawi** [comment]
There are a lot of breaking changes, previously developers do not adding notes about what they changed so I can't collect all breaking changes :disappointed:

**Comment by alexander-akait** [comment]
Sorry, let's close
