### ISSUE TITLE
Pass user (custom) flags to webpack config

### ISSUE THREAD

**Issue by shameleo** [webpack/webpack-cli#2113]
**Is your feature request related to a problem? Please describe.**

With **v3** I was able to pass my custom flags to webpack config like this:

**package.json**
```
'dev': 'webpack -w --eslint-fix'
```
or:
```
$ npm run dev -- --eslint-fix
```
and then get it in config using `argv`
```
module.exports = (env, argv) => ({ ... })
```
I don't know, was it feature or flaw, but it was usefull. Now it causes `Unknown argument: ...` error.

**Describe the solution you'd like**

Maybe some prefix for custom flags which would allow then to pass? It should support both `package.json` and command line scenario and be concise.

**Comment by anshumanv** [comment]
You should use `--env`

https://webpack.js.org/api/cli/#environment-options

**Comment by shameleo** [comment]
Thank you, it works

**Comment by anshumanv** [comment]
Great, closing
