### ISSUE TITLE
Repository tags of each version released

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#212]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
No release tags on the repository

**What is the expected behavior?**
Having release tags to the navigation and the history between versions is more efficient.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Having tags on the repository is helpful if the user want to change between version if they want to replicate some bug. At the moment they need to look for the commit that updates the package.json with the new version of the library. 

It will be also helpful to make a diff between version, so the user can have a better understanding of new features and bug fixes.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
No needed

**Comment by ev1stensberg** [comment]
Totally agree. Intended to be done starting at #207
