### ISSUE TITLE
caching failures with webpack serve when pointing to a specific config file

### ISSUE THREAD

**Issue by sppatel** [webpack/webpack-cli#2121]
# Bug report

**What is the current behavior?**

If you change the name of your webpack configuration file and specify it with `webpack serve --config [filename]` you get caching errors in the console..

```
ℹ ｢wdm｣: Compiled with warnings.
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'webpack.launcher.js' in '/Users/xxx/Projects/xxx/src/shell'
<w> while resolving 'webpack.launcher.js' in /Users/xxx/Projects/xxx/src/shell as file
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Setup a webpack dev configuration where configuration X in extends from another configuration and merged though webpack merge.  (Though i don't think this is absolutely necessary).  Ensure that the configuration has file caching turned on.

```
  cache: {
    name: 'shell',
    type: 'filesystem',
    cacheDirectory: path.resolve(__dirname, '../..', '.cache'),
    buildDependencies: {
      config: [path.resolve(__dirname, 'webpack.common.js'), path.resolve(__filename)],
    },
  },
```

Launch `webpack serve --config webpack.launcher.js`.  This throw the above error. If however, you rename this file to webpack.config.js and run without --config.  It will work.

**What is the expected behavior?**

Should be able to name a webpack configuration file anything I want and point to it with --config when running `webpack serve` and filesystem caching should not be affected.

**Other relevant information:**
webpack version: 5.3.2
Node.js version: v12.19.0
Operating System: OSX
Additional tools:

**Comment by evilebottnawi** [comment]
@anshumanv It is related to `default` cache with the `filesystem` type and adding `buildDependencies`, we should always add absolute path

**Comment by anshumanv** [comment]
Will take a look

**Comment by evilebottnawi** [comment]
WIP

**Comment by sppatel** [comment]
@alexander-akait has this fix been released yet?  If so which version?  I am running the latest and still experiencing the issue.

**Comment by alexander-akait** [comment]
@sppatel not released yet, ETA is today/tomorrow
