### ISSUE TITLE
webpack 5  env is an array not a object

### ISSUE THREAD

**Issue by ziven27** [webpack/webpack-cli#2125]
# Bug report
![image](https://user-images.githubusercontent.com/7261176/99783066-e4c07f00-2b54-11eb-8dd0-d50d12a8be9d.png)

```js
module.exports = env =>{
  console.log('NODE_ENV: ', env.NODE_ENV); // 'local'
  console.log('Production: ', env.production); // true
  console.log('env: ', env); // true
 return {};
};
```

**What is the current behavior?**

the `evn` turn out to be an array but object is expect

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

object is expect

**Other relevant information:**
webpack version:  ^5.4.0
 "webpack-cli": "3.3.12",
Node.js version: v12.16.3
Operating System: 
Additional tools:

**Comment by anshumanv** [comment]
Can you provide webpack-cli version?

**Comment by ziven27** [comment]
> Can you provide webpack-cli version?

 "webpack-cli": "3.3.12"

**Comment by ziven27** [comment]
> Is it an array for a single value too ? `webpack --env production`

it's string for a single value

**Comment by anshumanv** [comment]
Can you try upgrading to latest CLI?

The format you're using now is only supported in old CLI, for v3 you need to do `--env.production --env.NODE_ENV=local`

**Comment by anshumanv** [comment]
Closing, feel free to reopen if the problem persists.

**Comment by hgwood** [comment]
Hello @anshumanv. Using `--env.flag` instead of `--env flag` works. Thanks. Is [this documentation page](https://webpack.js.org/api/cli/#env) obsolete then?

**Comment by anshumanv** [comment]
@hgwood those docs are for CLI v4, maybe you're using v3?

**Comment by hgwood** [comment]
Ah, you're right, my bad. I thought I was using CLI v4, but my node_modules were not up-to-date and v3 was running. Thank you.
