### ISSUE TITLE
[BUG] Remove dist folder from being included on github

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#213]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Right now we are committing the `dist` folder on github.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
We should remove it from being included, i.e `.gitignore`
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

**Comment by ev1stensberg** [comment]
@kingdaro interested?

**Comment by kingdaro** [comment]
No problem, I'll go ahead and knock this one out.

**Comment by kingdaro** [comment]
Should I just commit this one to master? @ev1stensberg

**Comment by ev1stensberg** [comment]
Yep, this one could
