### ISSUE TITLE
Error: Cannot read property 'length' of undefined when running command npm install webpack-dev-server --save-dev

### ISSUE THREAD

**Issue by jordan-brookman** [webpack/webpack-cli#2134]
**Describe the bug**

When I run the command `npm install webpack-dev-server --save-dev` the following error is thrown: `Cannot read property 'length' of undefined`

**What is the current behavior?**

![Screen Shot 2020-11-24 at 14 13 02](https://user-images.githubusercontent.com/62706808/100140634-3a4fa100-2e5f-11eb-889a-bd22f118d693.png)

**To Reproduce**

See above.

**Expected behavior**

Expected to install webpack-dev-server without errors.

**Screenshots**

![Screen Shot 2020-11-24 at 10 56 09](https://user-images.githubusercontent.com/62706808/100118300-b340ff80-2e43-11eb-9f0a-ee40dd669987.png)

System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 986.89 MB / 16.00 GB
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    npm: 7.0.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.198
    Firefox: 83.0
    Safari: 14.0
  Packages:
    webpack: ^5.6.0 => 5.6.0 
    webpack-bundle-analyzer: ^4.1.0 => 4.1.0 
    webpack-cli: ^4.2.0 => 4.2.0 

The following is the contents of `package.json`:

`{
  "name": "fireship",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack",
    "info": "webpack-cli info"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "lodash": "^4.17.20"
  },
  "devDependencies": {
    "css-loader": "^5.0.1",
    "sass": "^1.29.0",
    "sass-loader": "^10.1.0",
    "style-loader": "^2.0.0",
    "webpack": "^5.6.0",
    "webpack-bundle-analyzer": "^4.1.0",
    "webpack-cli": "^4.2.0"
  }`

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please provide reproducible test repo or full stack of error

**Comment by evilebottnawi** [comment]
And it is npm bug, please report them about it
