### ISSUE TITLE
Webpack --json flag fails when doing --watch

### ISSUE THREAD

**Issue by dragonDScript** [webpack/webpack-cli#2138]
# Bug report

**What is the current behavior?**
If the --json flag specified together with the --watch flag, and you save the output to a file by doing > file.json,
```bash
webpack --json --watch > file.json
```
The old file.json will not be overwritten by the new build. Instead, it will be placed below, so there are JSON Syntax errors.

**What is the expected behavior?**
1. The file.json file is overwritten with the webpack build information

**Proposed solution**
There are two:
1. Check if the JSON Syntax is correct.
2. Overwrite file.

**Other relevant information:**
webpack version: 4.44.2 (Also tested in webpack latest version, it behaves the same)
Node.js version: v10.19.0 (Ubuntu), v14.XX.XX (Windows 10)
Operating System: Mixed
Additional tools: Any loader interacts with this feature. This is not needed.

**Comment by alexander-akait** [comment]
No problems with webpack itself herem why you need json in watch?

**Comment by dragonDScript** [comment]
I need to get the hash. Btw, this is webpack stuff because this is a builtin feature.

**Comment by alexander-akait** [comment]
this is webpack-cli stuff, webpack don't have CLI

**Comment by dragonDScript** [comment]
Oh! I thought that webpack had its own CLI. Sorry, I will reopen this in the webpack-cli repository. Thank you for being so fast.

**Comment by dragonDScript** [comment]
Uhm It's in webpack-cli already uhmm....

**Comment by snitin315** [comment]
Can you try - 

`webpack --json=file.json --watch`

**Comment by dragonDScript** [comment]
OK, I'm back with this. Setting --json to =file.json didn't work.

**Comment by alexander-akait** [comment]
@dragonDScript Can you clarify about `OK, I'm back with this. Setting --json to =file.json didn't work. Any file called file.json was created.`?

**Comment by dragonDScript** [comment]
> @dragonDScript Can you clarify about `OK, I'm back with this. Setting --json to =file.json didn't work. Any file called file.json was created.`?

@snitin315 mentioned that I should try to execute `webpack --json=file.json --watch`

**Comment by alexander-akait** [comment]
Yep, doesn't work?

**Comment by dragonDScript** [comment]
Nope.

**Comment by alexander-akait** [comment]
What is problem?

**Comment by dragonDScript** [comment]
--json=file.json flag is not emitting a file called file.json

**Comment by snitin315** [comment]
I will check once locally.

**Comment by dragonDScript** [comment]
@snitin315 Does this work? I will make a sample project asap

**Comment by dragonDScript** [comment]
In my sample project (https://github.com/dragonDScript/webpack-json-flag-error) it's working correctly. Hmmm, this is weird

**Comment by alexander-akait** [comment]
@dragonDScript yep, it should work, maybe you can provide more infomation

**Comment by dragonDScript** [comment]
> @dragonDScript yep, it should work, maybe you can provide more information

I will research myself. Thank you.
