### ISSUE TITLE
Output from `webpack --help` is mangled

### ISSUE THREAD

**Issue by tdammers** [webpack/webpack-cli#2140]
# Bug report

**What is the current behavior?**

Terminal output from `webpack --help` looks mangled:

- Excessive newlines
- Strange column sizing / layout
- Terminal escape codes retained when piping into something that is not a TTY (e.g. `| less`; `| more` works, but presumably due to a happy accident, as terminal escapes are also retained, it just so happens that `more` doesn't break the terminal output when paging such "enriched" text)

A few screenshots showing the problem in various terminal emulators:

gnome-terminal:
![gnome-terminal](https://user-images.githubusercontent.com/1434567/100437138-9c4b1900-30a0-11eb-8ddc-4aab0b482a32.png)

rxvt-unicode:
![urxvt](https://user-images.githubusercontent.com/1434567/100437329-e0d6b480-30a0-11eb-8641-84df203ad86a.png)

konsole:
![konsole](https://user-images.githubusercontent.com/1434567/100437360-e92eef80-30a0-11eb-952b-f29b1dd8a7b8.png)

piping through `less` in gnome-terminal:
![gnome-terminal-less](https://user-images.githubusercontent.com/1434567/100437612-4b87f000-30a1-11eb-917b-af139ac0d3df.png)

The problems persist across terminal emulators, and regardless of shell used.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run any of the following commands in a terminal emulator in a context where `webpack-cli` is available.

- `webpack --help`
- `webpack --help | head -n100`
- `webpack --help | more`
- `webpack --help | less`

**What is the expected behavior?**

- Terminal escapes are only inserted when output is a TTY (or, ideally, if forced via a suitable CLI option)
- Output is formatted sensibly (no excessive newlines, reasonable column widths)

**Other relevant information:**
webpack version:  5.7.0
Node.js version: v15.2.1
Operating System: Debian GNU/Linux 10 (buster)
Additional tools: urxvt, gnome-terminal, konsole, less, more, head, bash, zsh (all installed from Debian repositories)

**Comment by alexander-akait** [comment]
> Terminal escapes are only inserted when output is a TTY (or, ideally, if forced via a suitable CLI option)

We already do it only when TTY enabled

> Output is formatted sensibly (no excessive newlines, reasonable column widths)

And we already do it

**Comment by alexander-akait** [comment]
Please say what you want to see, you have a very thin columns, which is why you get this look

**Comment by tdammers** [comment]
Please take a look at those screenshots.

The `|less` one illustrates how output consumed by something that is not a TTY contains terminal escapes. The same escapes are also present when piping output to `xclip` and then pasting from the clipboard into, say, `leafpad`. So if webpack already checks for TTY output, then that check isn't working.

The others illustrate the "excessive newlines" problem. Text that should be formatted as a block of prose

ends

up

looking

like

this.

Even if this is due to insufficient screen space, the line breaking seems buggy to me, or at least I cannot imagine a situation where you would want to insert a double newline after each word.

Regarding column widths: I don't know what I can do to make columns wider, but IMO it is not unreasonable to expect `--help` output to be readable on a standard 80-column wide terminal (my normal setup is 84 columns when tiled to half a laptop screen). It looks like the left column is much wider than the right, presumably to fit those long option names, and the right column is then squashed to fit in whatever space is left. I don't think it would be useful to try and debug this, but it clearly doesn't look desirable.

Regarding what I would like to see: I'm not very picky, as long as the output is readable. Looking at other programs, the canonical solution seems to be to line-break the right column to the full width of the output. Examples of commonly used programs dumping `--help` to extremely narrow terminals:

rsync:

![rsync-help](https://user-images.githubusercontent.com/1434567/100456855-4cc91500-30c1-11eb-848b-8aa74f4ae025.png)

tar:

![tar-help](https://user-images.githubusercontent.com/1434567/100456882-53578c80-30c1-11eb-8ac5-c684fde2b0c9.png)

gcc:

![gcc-help](https://user-images.githubusercontent.com/1434567/100457074-a7627100-30c1-11eb-8bfe-937fa823ec5a.png)

These aren't great either, but at least they keep things compact, and provide reasonable output given the constraints.

**Comment by snitin315** [comment]
I think we can do -

 `webpack --help` show basic options help

`webpack --help=advance` show advance help will all 250+ options

**Comment by alexander-akait** [comment]
@snitin315 yep, I think we need improve this:
- `webpack --help` show basic + top level core flags (like `target`/etc - i.e. only one word)
- `webpack --help=advance` should all flags

**Comment by alexander-akait** [comment]
> The |less one illustrates how output consumed by something that is not a TTY contains terminal escapes. The same escapes are also present when piping output to xclip and then pasting from the clipboard into, say, leafpad. So if webpack already checks for TTY output, then that check isn't working.

How I can reproducible it?

**Comment by alexander-akait** [comment]
I found it is terminal problem

**Comment by alexander-akait** [comment]
we rely on `process.stdout.isTTY`, so we can't do something here, if it is try it is TTY

**Comment by tdammers** [comment]
> > The |less one illustrates how output consumed by something that is not a TTY contains terminal escapes. The same escapes are also present when piping output to xclip and then pasting from the clipboard into, say, leafpad. So if webpack already checks for TTY output, then that check isn't working.
> 
> How I can reproducible it?

Run `webpack --help | less` on one of the terminals I mentioned, sized to approx. 80 columns wide.

**Comment by alexander-akait** [comment]
@tdammers thanks, I think we will improve this in future

**Comment by tdammers** [comment]
> I found it is terminal problem

That seems unlikely.

None of the other programs I tried have this problem, while webpack does, and consistently so on 4 (!) different terminal emulators (urxvt, xterm, gnome-terminal, konsole).

**Comment by alexander-akait** [comment]
@tdammers maybe you can also provide small example of command where I can see the problem?

**Comment by tdammers** [comment]
> we rely on `process.stdout.isTTY`, so we can't do something here, if it is true it is TTY

Something is clearly wrong though, because even if I send the output into a file (which is not a TTY by any logic), the escapes are still there:

[webpack-help.txt](https://github.com/webpack/webpack-cli/files/5608234/webpack-help.txt)

So either the code doesn't actually use `process.stdout.isTTY`, or the implementation of `process.stdout.isTTY` is incorrect.

**Comment by alexander-akait** [comment]
> So either the code doesn't actually use process.stdout.isTTY, or the implementation of process.stdout.isTTY is incorrect.

Implementation of this from `Node.js`, so we can't do something here, anyway if you provide steps to reproduce I will investigate it deeply and say why it is happens

**Comment by tdammers** [comment]
> > So either the code doesn't actually use process.stdout.isTTY, or the implementation of process.stdout.isTTY is incorrect.
> 
> Implementation of this from `Node.js`, so we can't do something here, anyway if you provide steps to reproduce I will investigate it deeply and say why it is happens

Bit of evidence here:

![istty](https://user-images.githubusercontent.com/1434567/100472155-fc12e580-30db-11eb-87e3-d193b0a1e16d.png)

In other news, `process.stdout.isTTY` is `true` when the script is run directly from a shell, `undefined` when piped through `more` or `head`. I've also tried `less` and `xclip`; in both cases, I get `undefined`. `isTTY` is pretty much working as intended (though I would have expected `false` rather than `undefined`).

**Comment by snitin315** [comment]
WIP

**Comment by alexander-akait** [comment]
@snitin315 not resolved, 

> Terminal escape codes retained when piping into something that is not a TTY (e.g. | less; | more works, but presumably due to a happy accident, as terminal escapes are also retained, it just so happens that more doesn't break the terminal output when paging such "enriched" text)

need solve

**Comment by alexander-akait** [comment]
Fixed in v4.3.0, if you still have problems - feel free to feedback
