### ISSUE TITLE
Unnecessary params of `await cli.run(parsedArgsOpts, flags);` in "/lib/bootstrap.js"

### ISSUE THREAD

**Issue by xiaojingzhao** [webpack/webpack-cli#2164]
**Describe the bug**

Hi, I was reading code recently. I found in ["lib/bootstrap.js" row 68](https://github.com/webpack/webpack-cli/blob/1398295cd8f3d952fb23cd2584459b01f6ba581b/packages/webpack-cli/lib/bootstrap.js#L68)

```js
await cli.run(parsedArgsOpts, flags);
```

It seems that `flags` is unnecessary here? Because in ["webpack-cli.js" row 584,](https://github.com/webpack/webpack-cli/blob/0339a101be852ab6e020c8b814f382b2b06ab18e/packages/webpack-cli/lib/webpack-cli.js#L436) it only accepts one param here:
```js
async run(args) {
        await this.runOptionGroups(args);

        let compiler;

        // ...
}
```

**What is the current behavior?**

passed an unnecessary param to `cli.run`

**To Reproduce**

check the code in  [bootstrap.js](https://github.com/webpack/webpack-cli/blob/1398295cd8f3d952fb23cd2584459b01f6ba581b/packages/webpack-cli/lib/bootstrap.js#L68) and [webpack-cli.js](https://github.com/webpack/webpack-cli/blob/0339a101be852ab6e020c8b814f382b2b06ab18e/packages/webpack-cli/lib/webpack-cli.js#L436)

**Expected behavior**

Maybe only `parsedArgsOpts` here is needed.

**Comment by anshumanv** [comment]
yep, will remove it, thanks for the issue!
