### ISSUE TITLE
[Migrate]: JSdocs for migrate

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#219]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Right now, we do not have JSdocs for migrate, it would be nice!
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
JSdoc on migrate
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

**Comment by dylanonelson** [comment]
@ev1stensberg I'd be happy to help out with this. Will try to submit a PR in the next week.

**Comment by ev1stensberg** [comment]
Cool beans 🍛

**Comment by ev1stensberg** [comment]
closed per #255
