### ISSUE TITLE
Feature: Support --quiet on the command-line

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack-cli#22]
Currently, `webpack --quiet` ignores the files passed, while still outputting to the console:

```
Hash: 6dbc5ab44333d067d673
Version: webpack 1.4.0-beta6
Time: 11ms
```

It would be nice to have the `--quiet` option work as expected, i.e. silence all non-error messages.

**Moved from https://github.com/webpack/webpack/issues/490**

**Comment by DanielaValero** [comment]
There was a PR some time ago in webpack, see webpack/webpack#517

**Comment by georgiosd** [comment]
The `stats` property doesn't seem to get picked up when returning multiple configuration objects.

**Comment by DanielaValero** [comment]
@ev1stensberg, @pksjce what you guys think, should this be part of our roadmap to v1 ?

**Comment by pksjce** [comment]
Yes, the `--quiet` option can be implemented. In the compiler callback, we just need to suppress all ouput.
But fixing `stats` bugs might be harder. Might require changes in webpack core.

**Comment by DanielaValero** [comment]
is somehow the `stats` bug related to the `--quiet` option? The relationship I see is that the `--quiet` silence the `stats`. If this is the only relationship, then I'd say that the `stats` bug should be raised as a separate github issue, so we don't mix two different things

**Comment by bebraw** [comment]
Btw, if you are open to changing naming, consider `--silent`/`-s` to follow npm convention.

**Comment by ev1stensberg** [comment]
We've got `-s --save`, I think. That would need to be changed, dunno if people would like that. I'm open to it though

**Comment by bebraw** [comment]
Ah, yeah. Namespace collisions are tough.

**Comment by ev1stensberg** [comment]
@georgiosd Could you come up with a test repro on the stats and comment it at #84 ?

**Comment by ematipico** [comment]
Feature implemented: `--silent`
