### ISSUE TITLE
.gitignore contains package-lock.json , but it does not exist

### ISSUE THREAD

**Issue by gauravdas014** [webpack/webpack-cli#2216]
## Issue:
.gitignore contains package-lock.json, but it does not exist in the repo. As yarn is being used so there should not be package-lock.json isn't it?

**Comment by alexander-akait** [comment]
No, we don't need package-lock.json because we use yarn.lock

**Comment by gauravdas014** [comment]
@alexander-akait sir, that's what I am saying, we don't need package-lock.json, so this should not be there in .gitignore also, right?

**Comment by snitin315** [comment]
We ignore it to prevent new contributors from accidentally committing it.

**Comment by gauravdas014** [comment]
@snitin315 okay, got it!
