### ISSUE TITLE
Typo in webpack-cli/packages/webpack-cli/bin/cli.js 

### ISSUE THREAD

**Issue by gauravdas014** [webpack/webpack-cli#2221]
`sucessfully` is written instead of `successfully`. 
<br/>
<br/>
![ss](https://user-images.githubusercontent.com/51530678/101642023-805c5580-3a58-11eb-916b-f9dc05ff6872.jpg)

**Comment by snitin315** [comment]
@gauravdas014 do you wanna send a PR fixing it?

**Comment by gauravdas014** [comment]
yes. I would like to send a PR fixing it.

**Comment by snitin315** [comment]
Yep `master`

**Comment by alexander-akait** [comment]
Fixed in master
