### ISSUE TITLE
V2 General Improvements

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#223]
- Right now, there's some bugs with migrate, as well as some transform utility functions are trying to achieve the same thing. Migrate shouldn't have any errors and the utility functions should be refactored and used respectively 
- Scaffolding for `add`, `update` and `remove`

**Comment by jevan0307** [comment]
@ev1stensberg, are `loaders` and `module` the only major issues with `add` command at the moment? I would like to see if I can contribute something to it.

**Comment by ev1stensberg** [comment]
Think theres too much lesser flaws with the add command right now to grab single issues. The architecture needs to be simplified in order to benefit from the contribution.
