### ISSUE TITLE
outputPath is not respected with 4.2.0

### ISSUE THREAD

**Issue by beckerei** [webpack/webpack-cli#2242]
**Describe the bug**

We can server our repostiory against our production build with this config. I did cut some (hopefully useless) information, to make it easier to get.

```js
const devSerer = {
      historyApiFallback: true,
      publicPath: '/',
      disableHostCheck: true,
      host: 'localhost.some-domain.com',
      port: 443,
      inline: true,
      hot: true,
      noInfo: false,
      stats: 'minimal',
      proxy: [
        {
          context: ['/api/',],
          target: 'https://www.some-domain.com'',
          changeOrigin: true,
        },
      ],
    }

const output = {
        filename: '[name].[hash].js',
        chunkFilename: '[name].[hash].chunk.js',
        path: path.join(__dirname, 'dist'),
        publicPath: '/app/',
      },
```

Using HtmlWebpackPlugin with some pretty boring index.ejs file

**What is the current behavior?**

Before 4.2.0 everything work as expected:

Scripts were loaded from the `/app`, index was served from /

Now the html contains

```html
<script src="/app/runtime.4f07461f24ae6827cfbb.js"></script>
```

This returns 404, while accessing just `/runtime.4f07461f24ae6827cfbb.js` works.
So I assume either index is served from the wrong folder, or assets are not put in the correct folder.

Using `publicPath: '/'` does work, but would also effect production builds, which is not desired.

**To Reproduce**

~~

**Expected behavior**

It should work as before.

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

Webpack Version is 4.44.2

**Comment by alexander-akait** [comment]
How you run server?

**Comment by beckerei** [comment]
```
cross-env NODE_ENV=development webpack serve --env=development --progress
```

`corss-env` should not matter

**Comment by alexander-akait** [comment]
Can you try `--public-path /`?

**Comment by beckerei** [comment]
I get `[webpack-cli] Unknown argument: --public-path` regardless of how I pass the `/`

**Comment by alexander-akait** [comment]
Yep, bug, need to fix, as workaround you can set `output.publicPath: '/'` for `serve` command:
```
cross-env NODE_ENV=development WEBPACK_MODE=serve webpack serve --env=development --progress
```

and use `process.env.WEBPACK_MODE` in `webpack.config.js`

**Comment by snitin315** [comment]
> I get `[webpack-cli] Unknown argument: --public-path` regardless of how I pass the `/`

Maybe it's `--output-public-path /`

**Comment by alexander-akait** [comment]
Anyway I think it is fixed in master, I will add tests in near future

**Comment by beckerei** [comment]
`output-public-path` doesn't work either.

> Anyway I think it is fixed in master, I will add tests in near future

But wow, I was not expecting this 🚀 
Let me know if I can help you out, testing a beta release or so.

**Comment by beckerei** [comment]
I checked out the latest release (4.3.0). Our setup works again without any changes.

Thank you.

Despite these tiring times I wish you all the best for next year 🎉

**Comment by alexander-akait** [comment]
Let's keep open, I want to add tests for this case to avoid regressions
