### ISSUE TITLE
webpack-cli init scaffold does not work

### ISSUE THREAD

**Issue by iuryfranky** [webpack/webpack-cli#2247]
I am using yeoman-generator and @webpack-cli/init to scaffold a project , then I got webpack.config.js and .yo-rc.json files , the content of .yo-rc.json is ok, but  webpack.config.js  has only one line 
``` javascript
module.exports = {}; 
```
I found in @webpack-cli\utils\lib\modify-config-helper.js
``` javascript
 // the configuration stored in .yo-rc.json should already be in the correct
 // WebpackScaffoldObject format
 // it is labeled with the name property from the user's package.json, meaning
 // we should simply access that value, rather than iterating through all
  // the configs that are stored in .yo-rc.json
  if (configModule[packageName] && configModule[packageName].configuration) {
         finalConfig = configModule[packageName].configuration; 
   }
```
I think the issue is caused by the scaffold project name != name of the project which use that scaffold project , so I change it to
``` javascript
//if (configModule[packageName] && configModule[packageName].configuration) {
               // finalConfig = configModule[packageName].configuration;
               finalConfig = configModule[Object.keys(configModule)[0]].configuration;
 // }
```
Finally it works as expected
 "yeoman-generator": "4.12.0"
 "webpack-cli": "4.2.0"
 "@webpack-cli/init": "1.0.3",

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please format your issue, it is not readable, respect time of other developers

**Comment by Bilge** [comment]
I have the same problem. Generated file just contains `module.exports = {}`. What even is the point of this command if that's all you get at the end of it? Moreover, the `(Use arrow keys)` prompt just moves the flashing cursor around the console on Windows under mintty. It is not possible to know which menu item is selected.

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack-cli/issues/2430, we do big refactor out `init` command and now it support `template` syntax, it is easy and simple, we will update docs when it will be ready
