### ISSUE TITLE
webpack init  - Offer to install Prettier

### ISSUE THREAD

**Issue by gmarcos87** [webpack/webpack-cli#2253]
**Is your feature request related to a problem? Please describe.**

I have noticed that if one creates a project from scratch and does `webpack init` the message always ends with `"File is not properly formatted because you don't have prettier installed, you can either install it or format it manually"`. 

**Describe the solution you'd like**

Maybe instead of ending that way there could be a previous step where the cli offer to install Prettier in case it is not in package.json

**Describe alternatives you've considered**

I can't think of any other alternative, installing Prettirer by default seems to me too invasive

**Additional context**

```
mkdir wp-prettier
cd wp-prettier
npm init -y
npm install webpack webpack-cli --save-dev
npx webpack init
```

**Comment by alexander-akait** [comment]
I don't think provide extra step for installation of prettier is good idea, we should reduce questions

**Comment by gmarcos87** [comment]
But the message is strange then, because it does not contribute anything, I could say the same about any other package that is not installed. 
It's a simple detail that seems strange to me. I'm happy to continue using webpack :)
Thank you for your work!

**Comment by alexander-akait** [comment]
We can fix message like, webpack.config.js is not formatted due prettier is not installed (maybe better)

**Comment by anshumanv** [comment]
will improve it
