### ISSUE TITLE
Articles mistake in the documentation.

### ISSUE THREAD

**Issue by Creatoon** [webpack/webpack-cli#2256]
**Describe the bug**
If you look at the second line of the screenshot , you can see "the" used before word "issue"

**To Reproduce**

1- Visit https://github.com/webpack/webpack-cli/blob/master/.github/CONTRIBUTING.md#your-first-contribution
2- In the 2nd paragraph you can see the wrong article used before the word "issue"

**Current behavior**

"After you've created ***the***  issue, we will have a look, and provide feedback to your ticket."

**Expected behavior**

"After you've created ***an***  issue, we will have a look, and provide feedback to your ticket."

**Screenshots**

![Screenshot_2020-12-24 webpack webpack-cli](https://user-images.githubusercontent.com/65965202/103040930-e984b280-459a-11eb-88db-72220b1f00b6.png)

**Comment by alexander-akait** [comment]
Avoid creating docs issues, please send a fix

**Comment by Creatoon** [comment]
@alexander-akait Ok sir , sending a fix.
