### ISSUE TITLE
Syntax `webpack <name>=<file>` no longer supported

### ISSUE THREAD

**Issue by scinos** [webpack/webpack-cli#2258]
**Describe the bug**

webpack-cli@4.2.0 doesn't seem to support to pass a pair `<name>=<file>`, despite https://webpack.js.org/api/cli/#without-configuration-file saying it is supported.

**What is the current behavior?**

After upgrading to `4.2.0`, that syntax doesn't work anymore.  `webpack editor=./src/editor.js viewer=./src/viewer.js` will fail with:

```
ERROR in main
Module not found: Error: Can't resolve 'entry=./src/editor.js' in '/Users/sergio/app'

ERROR in main
Module not found: Error: Can't resolve 'entry=./src/view.js' in '/Users/sergio/app'
```

In previous versions (tested with 3.3.12), `webpack editor=./src/editor.js viewer=./src/viewer.js` would create two bundles, `dist/editor.js` and `dist/viewer.js`.

Note that `webpack ./src/editor.js ./src/viewer.js` works, but it will create a single bundle with the content of both entrypoints.

**To Reproduce**

```
echo "console.log(1)" >> 1.js
echo "console.log(2)" >> 2.js
webpack one=./1.js two=./2.js
```

**Expected behavior**

(As documented in https://webpack.js.org/api/cli/#without-configuration-file)

Two bundles, `dist/one.js` and `dist/two.js`, with the contents of `1.js` and `2.js` respectively

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 575.84 MB / 16.00 GB
  Binaries:
    Node: 12.19.1 - ~/.nvm/versions/node/v12.19.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.1/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Safari: 14.0
```

```
webpack-cli 4.2.0
webpack 5.10.3
```

**Comment by alexander-akait** [comment]
It was fixed, you got cached copy of docs (press ctrl + f5), this behavior was removed

```
npx webpack --entry <entry> -o <output-path>
```

/cc @chenxsan Why changes files don't invalidate page?

**Comment by chenxsan** [comment]
@alexander-akait Unfortunately It's how the Cache-First service worker works, the new service worker is still waiting for activation until all opened pages from the webpack.js.org are closed. We have introduced a refresh button in this pull request https://github.com/webpack/webpack.js.org/pull/4287 to work around it. But I guess it could still be annoying. Anyway we can remove the service worker if users don't use offline.

**Comment by alexander-akait** [comment]
@chenxsan Why do not change strategy? For example `stale-while-revalidate`? https://developers.google.com/web/tools/workbox/modules/workbox-strategies

**Comment by chenxsan** [comment]
[Precaching](https://github.com/webpack/webpack.js.org/blob/master/src/sw.js#L10) doesn't support specifying other strategies but Cache First, see https://github.com/GoogleChrome/workbox/issues/1767, otherwise I would obviously prefer Network first strategy when I was migrating offline plugin to workbox. But yes, Cache-first is bad for a documentation site, and that refresh button is just an escape hatch. I've created an issue here https://github.com/webpack/webpack.js.org/issues/4340 to track it.

**Comment by alexander-akait** [comment]
Thanks for help

**Comment by scinos** [comment]
FWIW, after doing a hard refresh, clearing the cache, trying incognito and even a new browser, I still see `If you pass a pair in the form <name>=<request>, you can create an additional entry point.` in the docs.

It is actually in the source, in https://github.com/webpack/webpack.js.org/edit/master/src/content/api/cli.md

**Comment by alexander-akait** [comment]
Please create issue in docs site

**Comment by alexander-akait** [comment]
we can't fix it on our side, it is bug in docs

**Comment by chenxsan** [comment]
@scinos You are right, seems like syntax like `webpack editor=./src/editor.js viewer=./src/viewer.js` to create two bundles respectively is no longer supported in `webpack-cli` 4.

@alexander-akait do we have alternative way to do it under webpack-cli 4? Otherwise we need to remove those texts from the [source file](https://github.com/webpack/webpack.js.org/blob/master/src/content/api/cli.md#:~:text=if%20you%20pass%20a%20pair%20in%20the%20form):

> If you pass a pair in the form `<name>=<request>`, you can create an additional entry point.

**Comment by alexander-akait** [comment]
hm, let's reopen it will be usefull

**Comment by alexander-akait** [comment]
Let's close in favor https://github.com/webpack/webpack-cli/issues/2356, we want to return supporting `webpack ./entry.js` and `webpack entry=./entry.js`

**Comment by saivan** [comment]
I commented this elsewhere, but in the meantime, if anybody runs into this issue, you can try something along the lines of:

```js
class CompilerHooks {
  apply(compiler) {
    // Rewrite the "main" entry point 
    compiler.hooks.entryOption.tap('Entry Rewrite', (context, entry) => {
      // Delete the main entry point and get the entry files
      const entryFiles = entry.main.import
      delete entry.main

      // Add new entry points for each file
      for ( let fileName of entryFiles ) {
        const name = path.parse(fileName).name
        entry[name] = { import: [fileName] }      }
    })
  } 
}
```

Then in your config:

```js
config = {
   plugins: [new CompilerHooks()]
   ...
}
```

You can even add in some environment variables if you want to make this more elaborate 😄
