### ISSUE TITLE
[Discussion] webpack-cli as a module

### ISSUE THREAD

**Issue by sompylasar** [webpack/webpack-cli#226]
If `webpack-cli` adds on top of raw `webpack` some value in the shape of self-contained functions like "add" or "serve", not only arg-passing glue, then maybe it makes sense to make these functions available and importable as a library.

Examples:
- `require('webpack-cli').add(otherArgs)  // -> Promise<WebpackCliAddResult>`
- `require('webpack-cli').serve(otherArgs)  // -> Promise<WebpackCliServerInstance>`.

Alternatives:
- spawn a `webpack` CLI process with the args, parse output.

Pros:
- working in the same memory space: not passing string streams around and having access to the pre-configured Webpack objects.

Cons:
- additional API surface.

Started here https://twitter.com/sompylasar/status/943993394115657728

**Comment by ev1stensberg** [comment]
Hi @sompylasar , we're closing this. We're adding a monorepo later, which will make this a bit better for you, as you can hook up this functionality yourself!
