### ISSUE TITLE
[v4.3.0] can no longer use --progress

### ISSUE THREAD

**Issue by AviVahl** [webpack/webpack-cli#2262]
**Describe the bug**

Starting with v4.3.0, when passing --progress to either `webpack serve` or `webpack-dev-server`, execution fails.

**What is the current behavior?**
```
[webpack-cli] Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'progress'.
```

**To Reproduce**

Run the cli with `--progress`.

**Expected behavior**

Work like previous versions, showing progress of compilation when `--progress` is provided.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

```
 System:
    OS: Linux 5.9 Fedora 33 (Workstation Edition) 33 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 22.56 GB / 31.21 GB
  Binaries:
    Node: 14.15.2 - ~/.nvm/versions/node/v14.15.2/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.2/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.2/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 84.0
  Monorepos:
    Yarn Workspaces: 1.22.10
    Lerna: 3.22.1
  Packages:
    html-webpack-plugin: ^5.0.0-beta.1 => 5.0.0-beta.1 
    webpack: ^5.11.0 => 5.11.0 
    webpack-cli: ^4.3.0 => 4.3.0 
    webpack-dev-server: ^4.0.0-beta.0 => 4.0.0-beta.0 
```

**Comment by AviVahl** [comment]
I just realized that while the previous version did accept `--progress`, it no longer printed the actual progress in console. Not sure if this was the expected behavior.

**Comment by alexander-akait** [comment]
Yep, it was bug, let's fix and do patch release

**Comment by alexander-akait** [comment]
It should work and should output progress

**Comment by alexander-akait** [comment]
Found other problem with `--hot` and twice applied HotModuleReplacement plugin, let's do patch release tomorrow, I want to fix this too
