### ISSUE TITLE
npx webpack --help should not ask user to install webpack-dev-server

### ISSUE THREAD

**Issue by chenxsan** [webpack/webpack-cli#2266]
**Describe the bug**

`npx webpack --help` should not ask user to install `webpack-dev-server`.

**What is the current behavior?**

When I run `npx webpack --help`, it prompts with:

> [webpack-cli] For using this command you need to install: 'webpack-dev-server' package
✖ Would you like to install 'webpack-dev-server' package? (That will run 'yarn add -D webpack-dev-server') (Y/n)

**To Reproduce**

1. `git clone https://github.com/chenxsan/webpack-cli-bug`
2. run `yarn`
3. run `npx webpack --help`

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/1091472/103170905-ecc1bc00-4882-11eb-9fec-9ef412db2f10.png)

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

```
  System:
    OS: macOS 11.1
  Packages:
    webpack: ^5.11.0 => 5.11.0 
    webpack-cli: ^4.3.0 => 4.3.0 
```

**Additional context**

**Comment by alexander-akait** [comment]
Yep, let's fix
