### ISSUE TITLE
CLI init not interactive

### ISSUE THREAD

**Issue by shadowfoxish** [webpack/webpack-cli#2274]
**Describe the bug**
The cli init function is not interactive and immediately exits.

```
PS C:\Code\Frontend> npx webpack-cli init
[webpack-cli] 
i INFO  For more information and a detailed description of each question, have a look at: https://github.com/webpack/webpack-cli/blob/master/INIT.md
[webpack-cli] i INFO  Alternatively, run "webpack(-cli) --help" for usage info

? Will your application have multiple bundles? (y/N) 
PS C:\Code\Frontend>
```
```
    "webpack": "^5.11.1",
    "webpack-bundle-analyzer": "^4.3.0",
    "webpack-cli": "^4.3.0",
    "webpack-dev-server": "^3.11.1"
```

**What is the current behavior?**

When I run npx webpack-cli init, it prints some messages and immediately exits. It is not waiting for my input.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
Can't run `webpack-cli info` directly, `npx webpack-cli info` shown:

PS C:\Code\Frontend> npx webpack-cli info

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 20.88 GB / 31.61 GB
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.66)
    Internet Explorer: 11.0.19041.1
  Packages:
    clean-webpack-plugin: ^3.0.0 => 3.0.0
    copy-webpack-plugin: ^6.0.3 => 6.4.1
    html-webpack-plugin: ^3.2.0 => 3.2.0
    webpack: ^5.11.1 => 5.11.1
    webpack-bundle-analyzer: ^4.3.0 => 4.3.0
    webpack-cli: ^4.3.0 => 4.3.0
    webpack-dev-server: ^3.11.1 => 3.11.1

**Additional context**
I am upgrading a project from webpack 4.43 to 5.11.1 and the CLI has been updated from 3.3.11 to 4.3.0

**Comment by alexander-akait** [comment]
It means you terminal doesn't support interactive

**Comment by shadowfoxish** [comment]
Well that certainly would explain it. Maybe something VSCode didnt take into account.

Works in a standalone powershell. Integrated VS Code terminal didnt. Sorry to bother.
