### ISSUE TITLE
`npx webpack server` asks me to install `server` package

### ISSUE THREAD

**Issue by chenxsan** [webpack/webpack-cli#2277]
**Describe the bug**

I've made a typo when running `npx webpack serve` and it become `npx webpack server`,

```bash
npx webpack server
[webpack-cli] For using this command you need to install: 'server' package
? Would you like to install 'server' package? (That will run 'yarn add -D server') (Y/n) › true
```

This is sort of unexpected in my opinion since `server` is not a command supported by `webpack-cli`, I would expect it to throw an error telling me that `server` command is not supported. Otherwise I might install something else if I don't pay attention to it.

**What is the current behavior?**

**To Reproduce**

1. install the latest `webpack-cli` and `webpack`
2. run `npx webpack server`

**Expected behavior**

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by snitin315** [comment]
Yes need to improve the error reporting here. 

WIP

**Comment by snitin315** [comment]
So, we don't support the `webpack entry.js` syntax anymore. 

/cc @alexander-akait

**Comment by alexander-akait** [comment]
Yes, syntax was removed due misleading
