### ISSUE TITLE
webpack-cli doesn't run on windows

### ISSUE THREAD

**Issue by RobotnickIsrael** [webpack/webpack-cli#230]
latest version (2.0.1)

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
when I do "webpack-cli migrate ./webpack.config.dev.js" or "webpack-cli -v" I get an error
message not related to the fuction itself:

> module.js:472
>     throw err;
>     ^
> 
> Error: Cannot find module 'webpack/lib/ErrorHelp
>     at Function.Module._resolveFilename (module.
>     at Function.Module._load (module.js:418:25)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\Users\tc34792\AppD
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)

It's important to add I just did "npm install -g webpack-cli", and it installed version 2.0.1

**If the current behavior is a bug, please provide the steps to reproduce.**

run either "webpack-cli migrate ./webpack.config.dev.js" or "webpack-cli -v"

**What is the expected behavior?**
the cli to give it's version or run.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
nodeJS 7.7.3 (X64), npm 4.1.2. Windows 7 64bit.

**Comment by ematipico** [comment]
I tried to run `webpack-cli -v` and it worked

**Comment by kumarharsh** [comment]
Not working for me too. Windows 10, Node 8.5.0

**Comment by ev1stensberg** [comment]
@kumarharsh same error?

**Comment by kumarharsh** [comment]
Yup.

```
[master +1 ~2 -2 !]> webpack-cli init
module.js:529
    throw err;
    ^

Error: Cannot find module 'webpack/lib/ErrorHelpers'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\kumar\AppData\Local\Yarn\config\global\node_modules\webpack-cli\bin\webpack.js:11:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by ev1stensberg** [comment]
Hi @kumarharsh and @RobotnickIsrael , this is fixed in https://github.com/webpack/webpack-cli/commit/9f195c9620fafd7ed793c61c8af757d519f32d87 , install the patch using `npm install -g webpack-cli@2.0.2`, and if you have any other issues, don't hesitate to put up an issue! Thanks for posting this one!

**Comment by somil-northout** [comment]
I am getting same issue with webpack-cli@3.0.8.
