### ISSUE TITLE
@webpack-cli/serve version 1.2.1 seems to have removed all command line options supported by 1.2.0?

### ISSUE THREAD

**Issue by starpit** [webpack/webpack-cli#2314]
**Describe the bug**

With 1.2.0, I can run `webpack serve --progress` or `webpack serve --config my/webpack.config.js`. Neither of these options work in 1.2.1.

**What is the current behavior?**
```sh
error: unknown option '--progress'
```

**To Reproduce**

1) install 1.2.0, type `npx webpack serve --help`, and see lots of options
2) install 1.2.1, type the same, and see none of those options

**Expected behavior**

Patch releases shouldn't introduce breaking changes like this. More so: what is the advised remedy for using these options?

**Screenshots**

n/a

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

```
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 898.71 MB / 16.00 GB
  Binaries:
    Node: 12.20.1 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Safari: 14.0.1
```

**Additional context**

n/a

**Comment by snitin315** [comment]
Works for me. Make sure you have `webpack-dev-server` installed.

**Comment by starpit** [comment]
Below I am showing 1.2.1 (first section) versus 1.2.0 (second section). Observe how the output of `webpack serve -h` for 1.2.1 lacks any of the options shown in `webpack serve -h` for 1.2.0.

# With @webpack/serve@1.2.1

```sh
$ npm init -y && npm install webpack@5.11.1 webpack-dev-server@3.11.0 webpack-cli@4.3.0
...
$ npm list @webpack-cli/serve
yo1@1.0.0 /Users/nickm/tmp/yo1
└─┬ webpack-cli@4.3.0
  └── @webpack-cli/serve@1.2.1 
$ npx webpack serve -h
Usage: webpack serve|s [options]

Run the webpack dev server.

Global options:
  --color               Enable colors on console.
  --no-color            Disable colors on console.
  -v, --version         Output the version number of 'webpack', 'webpack-cli'
                        and 'webpack-dev-server' and commands.
  -h, --help [verbose]  Display help for commands and options.

To see list of all supported commands and options run 'webpack --help=verbose'.

Webpack documentation: https://webpack.js.org/.
CLI documentation: https://webpack.js.org/api/cli/.
Made with ♥ by the webpack team.
```

# With @webpack-cli/serve@1.2.0
$ npm init -y && npm install webpack@5.11.1 webpack-dev-server@3.11.0 webpack-cli@4.3.0 @webpack-cli/serve@1.2.0
...
$ npm list @webpack-cli/serve
tmp@1.0.0 /Users/nickm/tmp
├── @webpack-cli/serve@1.2.0 
└─┬ webpack-cli@4.3.0
  └── @webpack-cli/serve@1.2.0  deduped
$ npx webpack serve -h
Usage: webpack serve|s [options]

Run the webpack dev server.

Options:
  -c, --config <value>        Provide path to a webpack configuration file e.g.
                              ./webpack.config.js.
  --config-name <value>       Name of the configuration to use.
  -m, --merge                 Merge two or more configurations using
                              'webpack-merge'.
  --env <value>               Environment passed to the configuration when it
                              is a function.
  --progress [value]          Print compilation progress during build.
  -j, --json [value]          Prints result as JSON or store it in a file.
  -d, --devtool <value>       Determine source maps to use.
  --no-devtool                Do not generate source maps.
  --entry <value>             The entry point(s) of your application e.g.
                              ./src/main.js.
  --mode <value>              Defines the mode to pass to webpack.
  --name <value>              Name of the configuration. Used when loading
                              multiple configurations.
  -o, --output-path <value>   Output location of the file generated by webpack
                              e.g. ./dist/.
  --stats [value]             It instructs webpack on how to treat the stats
                              e.g. verbose.
  --no-stats                  Disable stats output.
  -t, --target <value>        Sets the build target e.g. node.
  -w, --watch                 Watch for files changes.
  --no-watch                  Do not watch for file changes.
  --watch-options-stdin       Stop watching when stdin stream has ended.
  --no-watch-options-stdin    Negative 'watch-options-stdin' option.
  --bonjour                   
  --lazy                      
  --liveReload                 (default: true)
  --serveIndex                 (default: true)
  --inline                     (default: true)
  --progress                  
  --hot-only                  
  --stdin                     
  --open <value>              
  --useLocalIp                
  --open-page <value>         
  --client-log-level <value>   (default: "info")
  --https                     
  --http2                     
  --key <value>               
  --cert <value>              
  --cacert <value>            
  --pfx <value>               
  --pfx-passphrase <value>    
  --content-base <value>      
  --watch-content-base        
  --history-api-fallback      
  --compress                  
  --port <value>              
  --disable-host-check        
  --socket <value>            
  --public <value>            
  --host <value>              
  --allowed-hosts <value>

Global options:
  --color               Enable colors on console.
  --no-color            Disable colors on console.
  -v, --version         Output the version number of 'webpack', 'webpack-cli'
                        and 'webpack-dev-server' and commands.
  -h, --help [verbose]  Display help for commands and options.

To see list of all supported commands and options run 'webpack --help=verbose'.

Webpack documentation: https://webpack.js.org/.
CLI documentation: https://webpack.js.org/api/cli/.
Made with ♥ by the webpack team.
```

**Comment by snitin315** [comment]
>$ npm init -y && npm install webpack@5.11.1 webpack-dev-server@3.11.0 webpack-cli@4.3.0
...
$ npm list @webpack-cli/serve
yo1@1.0.0 /Users/starpit/tmp/yo1
└─┬ webpack-cli@4.3.0
  └── @webpack-cli/serve@1.2.1 


webpack-dev-server wasn't installed here. as can be seen in the dependencies graph. Check the output of `webpack version`.
try installing `webpack-dev-server` separately. -> `npm install webpack-dev-server`

**Comment by alexander-akait** [comment]
Reinstall deps, double check global packages, avoid `@webpack-cli/serve@1.2.0` installation directly, you don't need this

**Comment by starpit** [comment]
Howdy! Thanks for the help.

### webpack version

```sh
$ npx webpack version
webpack 5.11.1
webpack-cli 4.3.0
webpack-dev-server 3.11.0
```

### Global packages

I just checked, and there is nothing webpack related in /usr/local/lib/node_modules

### re: avoiding direct installation

I would love to, and, up until the release of 1.2.1, we did not directly install it. You can see from my first example that I did not directly install `@webpack-cli/serve`. I only did so in the second example to highlight the difference in the output of `webpack serve --help` of 1.2.0 versus 1.2.1.

### re: installing webpack-dev-server

You should see from my examples above that, in both cases, I installed webpack-dev-server.

**Comment by alexander-akait** [comment]
Still not work? Update `webpack-dev-server` to `3.11.1`

**Comment by starpit** [comment]
Aha! By using webpack-dev-server 3.11.1 and webpack-cli 4.3.1, the problem seems to be resolved. The problem we had was we didn't want to bump anything, we simply re-ran `npm install`, and some floating dependence on your side picked up `@webpack-cli/serve@1.2.1`, without a corresponding update to either `webpack-dev-server` or `webpack-cli`.

**Comment by alexander-akait** [comment]
Only fixes was in `https://github.com/webpack/webpack-dev-server/commits/v3.11.1`, you still had something old in your dependencies, packages are compatibility

> Perhaps these packages should lock to eachother better?

No, it was big problem for future updates

**Comment by starpit** [comment]
I did not, I simply re-ran `npm install` and what used to work no longer worked. This is presumably because some floating dependence on your side forces `@webpack-cli/serve@1.2.1` despite our package-lock's request to install `webpack-dev-server@3.11.0`. The command lines above I think made this pretty clear. You can try it yourself, and I have done so on multiple systems, all to the same effect (i.e. `webpack serve -h` does not work)

```sh
 npm init -y && npm install webpack@5.11.1 webpack-dev-server@3.11.0 webpack-cli@4.3.0
```

Anyway, I have a resolution, and now know to be wary of webpack version issues in the future. Thanks for the help!
