### ISSUE TITLE
webpack ./src/main.js -o ./dist/bundle.js 报错

### ISSUE THREAD

**Issue by gyjcode** [webpack/webpack-cli#2322]
E:\MyCode\webpack-study>webpack ./src/main.js -o ./dist/bundle.js
[webpack-cli] Unknown command './src/main.js'
[webpack-cli] Run 'webpack --help' to see available commands and options

**Comment by snitin315** [comment]
Use - `webpack --entry ./src/main.js -o ./dist/bundle.js`

**Comment by gyjcode** [comment]
Thanks

**Comment by fregante** [comment]
Why was this changed? `webpack index.js` has worked since the beginning and now my builds are breaking with an error that can't be found anywhere online. 

Could you at least provide some meaningful errors when you introduce breaking changes in the most simple of usages?

```
❯ webpack --version
webpack 5.14.0
webpack-cli 4.3.1

❯ webpack index.js
[webpack-cli] Unknown command 'index.js'
[webpack-cli] Run 'webpack --help' to see available commands and options
```

**Comment by snitin315** [comment]
It was difficult to differentiate if the user was providing an entry or a command.

For example `webpack server` , since the actual command is `serve` cli would have considered it as an entry point.
