### ISSUE TITLE
Error thrown when aborting a mirgration

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#233]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Install `webpack-cli`
2. Run a command, in this case `webpack-cli migrate webpack.config.js`
3. When the cli asks if you are sure about some change, press **n**
4. When the migration is aborted, the cli throws an error

```bash
$ npx webpack-cli migrate webpack.config.diamond.dev.js
 √ Reading webpack config
 √ Migrating config from v1 to v2
+             debug: true,
? Are you sure these changes are fine? No
✖ Migration aborted
✖ ︎Migration aborted due to some errors
TypeError: Cannot read property 'confirmValidation' of undefined
    at inquirer.prompt.then.then.answer (C:\Users\zkuazc7\dev\diamond\web\src\diamond\web\static_files\node_modules\webpack-cli\dist\commands\migrate.js:121:16)
```
**What is the expected behavior?**
It should not throw an error in the console

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Windows 7 64bit, Node 6.10.2

**Comment by ev1stensberg** [comment]
@ematipico could you fix this? A matter of navigating to the migrate file and do a console log on your repo

**Comment by ematipico** [comment]
Sure I can fix it

**Comment by ev1stensberg** [comment]
https://github.com/webpack/webpack-cli/blob/master/lib/commands/migrate.js#L89-L150
