### ISSUE TITLE
[FEATURE REQUEST]: A way to know if the webpack CLI call has failed or succeeded

### ISSUE THREAD

**Issue by cbdeveloper** [webpack/webpack-cli#2344]
**Is your feature request related to a problem? Please describe.**

I have a `deploy.sh` script file where one of the steps is to call `webpack --config webpack.prod.js`

The next step is to actually deploy the build. But I'd like to stop the deploy process if the `webpack` build call has failed.

**Describe the solution you'd like**

Is there any possibility of returning something from the CLI to make it possible to know if the webpack run has been successful or failed? Like:

```
BUILD_RESULT="$(webpack --config webpack.prod.js)"

// ANY STRING THAT MIGHT BE USEFULL TO KNOW IF ANY ERROR HAS BEEN THROWN
```

Or maybe a `--checkErrors` CLI flag that instead of actually building the files, might return a `boolean` for errors. What do you think? Is this even remotely possible?

I've noticed that the script continues if when `webpack` fails.

Any other solutions/comments will be appreciated.

**Comment by anshumanv** [comment]
I think you can rely on the exit code of the CLI process and figure out it failed or succeeded - https://github.com/webpack/webpack-cli#exit-codes-and-their-meanings

**Comment by alexander-akait** [comment]
Please use exit codes:
- 0 - fine
- 1 - errors
- 2 - errors from CLI

But don't forget you can get warnings, my recommendation here to use `stats` from webpack, you can use `--json` flag to save this in file and check `errors` and `warnings` properties on empty

**Comment by cbdeveloper** [comment]
Thank you. How can I use these `exit codes`?

This is what I got logged from the following code:

```
BUILD_RESULT="$(cross-env NODE_ENV=production webpack --config webpack.prod.js)"
echo $BUILD_RESULT
```

```
Hash: 26bf6fxae38aa6q5af6e2ddbdb4 
Version: webpack 4.44.2 
Time: 13593ms 
Built at: 01/12/2021 12:00:18 PM 
Asset Size Chunks Chunk Names 
app.90dxa.js 370 KiB 0 [emitted] [immutable] [big] 
// OTHER PACKAGES / CHUNKS
npm.firebase-auth.39e99.js 
npm.firebase-firestore.06248.js 
npm.firebase-storage.4d697.js 
npm.react-dom.e7050.js 
npm.firebase-webchannel.1077e.js 
npm.reduxjs.9b30c.js vendors~app.6bf51.js 
app.90dec.js WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure 
to lazy load some parts of your application. For more info visit 
https://webpack.js.org/guides/code-splitting/ 
Child HtmlWebpackCompiler: 1 asset Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0 [MlNL] 
./node_modules/html-webpack-plugin/lib/loader.js!./src/app.html 1.57 KiB {0} [built]
```

Should the `exit code` be in there?

Also, how could I use `stats` to solve this? Maybe adding `--stats-errors` and `--stats-warnings` to log specifically those properties? Does the `default` setting for the `stats` include those properties?

**Comment by alexander-akait** [comment]
> Should the exit code be in there?

`echo $?` returns exit code from previously process 

> Also, how could I use stats to solve this? Maybe adding --stats-errors and --stats-warnings to log specifically those properties? Does the default setting for the stats include those properties?

No new options, it is unnecessary, please read my answer you can use the `webpack --json stats.json` options and parse a JSON file using `JSON.parse` and check `errors` and `warnings`
