### ISSUE TITLE
Add "Did you mean '--entry index.js'?"

### ISSUE THREAD

**Issue by fregante** [webpack/webpack-cli#2356]
**Is your feature request related to a problem? Please describe.**

The simplest usage stopped working in v4 and the error is meaningless

```
❯ webpack --version
webpack 5.14.0
webpack-cli 4.3.1

❯ webpack index.js
[webpack-cli] Unknown command 'index.js'
[webpack-cli] Run 'webpack --help' to see available commands and options
```

**Describe the solution you'd like**

Tell me how to fix it rather than having to Google my way out of cryptic error messages.

```diff
  ❯ webpack index.js
  [webpack-cli] Unknown command 'index.js'
+ [webpack-cli] Did you mean '--entry index.js'?
  [webpack-cli] Run 'webpack --help' to see available commands and options
```

**Additional context**

People having issues: 
- https://github.com/webpack/webpack-cli/issues/2322
- https://stackoverflow.com/q/65606265/288906

**Comment by snitin315** [comment]
As I mentioned in https://github.com/webpack/webpack-cli/issues/2322#issuecomment-760776701 , It is difficult to differentiate between an invalid command and an entry point. 
Earlier the logic was very hacky.

**Comment by snitin315** [comment]
But I think we can do something like follow -

for
`webpack index.js` 

```js
if (isFileExists('invalid')) { 
 logger.error('Did you mean '--entry index.js'?')
} else { 
  // current behaviour
}

**Comment by alexander-akait** [comment]
hm, maybe we can do, I will think about it

**Comment by alexander-akait** [comment]
I am WIP on old syntax (will be in the next patch release) - 
- `webpack ./entry.js` 
- `webpack entry=./entry.js`

**Comment by alexander-akait** [comment]
We return: `webpack ./entry.js`, `webpack entry=./entry.js` will be in future, need some improvements

**Comment by saivan** [comment]
I had code that depended on `webpack entry=./entry.js`, is there an alternative way to achieve this now (without having to write a webpack config file)?

**Comment by anshumanv** [comment]
Tried it and it seems to work for me, does it not work for you? 

![image](https://user-images.githubusercontent.com/21009455/108086420-5b114680-709c-11eb-9636-1a8c3f5879f5.png)

**Comment by saivan** [comment]
Sorry to be clear, i'd want to set a different name like: `webpack hello=./hello.js second=./second.js`. I have no way to set the name of the package by the looks of things

**Comment by saivan** [comment]
Another strange thing, is that providing multiple entry points always sets the `name` field to `main` (I don't think I set that anywhere). Is that expected behaviour?

**Comment by alexander-akait** [comment]
`webpack hello=./hello.js second=./second.js` is not supported, you need configuration for it, or we should improve it on webpack side

**Comment by saivan** [comment]
Well in the meantime, if anybody runs into this issue, you can try something along the lines of:

```js
class CompilerHooks {
  apply(compiler) {
    // Rewrite the "main" entry point 
    compiler.hooks.entryOption.tap('Entry Rewrite', (context, entry) => {
      // Delete the main entry point and get the entry files
      const entryFiles = entry.main.import
      delete entry.main

      // Add new entry points for each file
      for ( let fileName of entryFiles ) {
        const name = path.parse(fileName).name
        entry[name] = { import: [fileName] }      }
    })
  } 
}
```

Then in your config:

```js
config = {
   plugins: [new CompilerHooks()]
   ...
}
```

You can even add in some environment variables if you want to make this more elaborate 😄

**Comment by alexander-akait** [comment]
If you need `webpack --name=./foo.js --other=./bar.js` we can implement this, but we need improve it on webpack side
