### ISSUE TITLE
Global webpack-cli should work without webpack installed

### ISSUE THREAD

**Issue by grgur** [webpack/webpack-cli#236]
### Here's what I did:
1. No global npm packages installed (never liked that, really)
2. `npm -g i webpack-cli`
3. Executed `webpack-cli` from an empty directory

### Observed:
* `Cannot find module` error

```bash
module.js:538
    throw err;
    ^

Error: Cannot find module 'webpack/lib/Stats.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at processOptions (/usr/local/lib/node_modules/webpack-cli/bin/webpack.js:253:31)
    at yargs.parse (/usr/local/lib/node_modules/webpack-cli/bin/webpack.js:455:3)
    at Object.parse (/usr/local/lib/node_modules/webpack-cli/node_modules/yargs/yargs.js:539:18)
    at /usr/local/lib/node_modules/webpack-cli/bin/webpack.js:192:8
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack-cli/bin/webpack.js:457:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
```

### Expected:
* Webpack's usual output such as

```bash
(node:75139) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Hash: e51fce300e49c2258eca
Version: webpack 4.0.0-alpha.3
Time: 38ms

WARNING in configuration
The 'mode' option has not been set. Set 'mode' option to 'development' or 'production' to enable defaults for this enviroment.

ERROR in Entry module not found: Error: Can't resolve './src' in '/Users/grgur/Projects/oss/test'
```

* After I installed webpack globally with `npm -g i webpack`, it worked fine. Even with webpack 3.x.

### Environment
* macOS High Sierra
* node v8.9.1
* yarn 1.3.2
* npm 5.5.1
* **NODE_PATH** includes `usr/local/lib/node_modules`

**Comment by ev1stensberg** [comment]
Thanks for the report @grgur ! Suspected this would happen. @sokra any ideas on how to avoid it being circular while still having `webpack` as  a dependency? I've seen the tapable warnings too, perhaps that was fixed in `alpha.4`. If that's the case, I'm bumping the dependencies

**Comment by sokra** [comment]
I guess it's not unexpected that webpack-cli build doesn't work without webpack installed. I guess `webpack init` should still work and install webpack as local dependency.

An improved error message would be nice. Something like: "webpack was not found. Run 'webpack init' to create a new project."

**Comment by ev1stensberg** [comment]
@sokra `webpack init` and those features work, but running the build doesn't. Should we ask if the user wants to install webpack first if it's not installed globally/locally when they want to build?

**Comment by sokra** [comment]
That would be great. I could imagine these options, but feel free to implement it different:

* Initialize a new project in the current folder `webpack init`
* Install webpack locally with yarn `yarn add -D webpack webpack-cli@^${package.version}`
  (when `yarn.lock` present)
* Install webpack locally with npm `npm install --dev webpack webpack-cli@^${package.version}`
  (when `package-lock.json` present)
* Install webpack globally with yarn `yarn global add webpack`
* Install webpack globally with npm `npm install -g webpack`

Note: local installation should also install webpack-cli in the same major version. It basically fixes the versions for this project.

**Comment by grgur** [comment]
I noticed that [bin/webpack.js](https://github.com/webpack/webpack-cli/blob/master/bin/webpack.js#L11) uses `resolve-cwd`. 

So, the weird part is that `resolveCwd.silent("webpack")` will detect webpack as one of the installed dependencies (`/usr/local/lib/node_modules/webpack-cli/bin/webpack.js`). Obviously, node doesn't agree as `require` can't find it.

If I replace `resolveCwd.silent` with `require.resolve("webpack")`  then I get a proper message back. I guess that's a way to figure out if help message should be printed as @sokra suggested.

Let me know if I'm on the right path here. Would love to help out.

Here's the snippet I used for this:

```js

function detectModule(module) {
  try {
    return require.resolve(module);
  } catch (e) {
    return null;
  }
}

function isModuleInstalled(module) {
  const isInstalled = detectModule(module);
  //const isInstalled = resolveCwd.silent(module);
  const color = isInstalled ? "\x1b[32m" : "\x1b[31m";
  const message = `${module} is ${isInstalled ? 'INSTALLED' : 'NOT installed'}`;
  const location = isInstalled ? `here: ${isInstalled}` : '';
  const reset = "\x1b[0m";

  console.log(color, message, location, reset);
}

isModuleInstalled("webpack");
isModuleInstalled("flow-bin"); // Something I'm positive exists
isModuleInstalled("foo"); // I want this to fail
```

![image](https://user-images.githubusercontent.com/733074/34642173-06ed8950-f30f-11e7-82bd-a99f45e6ae4b.png)

**Comment by grgur** [comment]
Here's another thing: [_local CLI replace global one_](https://github.com/webpack/webpack-cli/blob/master/bin/webpack.js#L13) will fail to do that, really. It will do do opposite.

```javascript
// Local version replace global one
var localCLI = resolveCwd.silent("webpack-cli/bin/webpack");
if (localCLI && localCLI !== __filename) {
  require(localCLI);
  return;
}
```

### Steps to reproduce:
1. Clone this repo
2. install `webpack-cli` globally. 
3. Edit `/usr/local/lib/node_modules/webpack-cli/bin/webpack.js` and add a simple console.log such as `console.log("\x1b[34m", "I am global webpack-cli. Did someone call for me?", "\x1b[0m");`
4. run `bin/webpack-cli` from the repo. You should see the message from step 3.

**Comment by ev1stensberg** [comment]
Linked to #299 , fixing this in next minor version

**Comment by grgur** [comment]
Thanks @ev1stensberg
