### ISSUE TITLE
NODE_ENV not set on process.env

### ISSUE THREAD

**Issue by okonet** [webpack/webpack-cli#2362]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Currently, `mode` only sets the value for `NODE_ENV` in the `DefinePlugin` but not changes the `process.env.NODE_ENV`. 

For example, Babel depends on this env variable and when used with `webpack --mode=production` it will still run in `development` mode.

**If the current behavior is a bug, please provide the steps to reproduce.**

Running `webpack --silent --mode=production && echo $NODE_ENV`

This will NOT print anything.

Run `NODE_ENV=production && webpack --silent --mode=production && echo $NODE_ENV`

This will print `production`

**What is the expected behavior?**

Running `webpack --silent --mode=production && echo $NODE_ENV` should print `production`

**Comment by alexander-akait** [comment]
I think we should look how other tools do it, maybe we just need improve our docs
