### ISSUE TITLE
[webpack-cli] Error: Cannot find module 'C:\Users\s\d\app\package.json'

### ISSUE THREAD

**Issue by sumitchd** [webpack/webpack-cli#2377]
[webpack-cli] Error: Cannot find module 'C:\Users\s\d\app\package.json'
Require stack:
- C:\Users\s\d\app\webpack5-stucture\config\paths.js
- C:\Users\s\d\app\webpack5-stucture\webpack.prod.js
- C:\Users\s\d\app\webpack.config.js
- C:\Users\s\d\app\node_modules\webpack-cli\lib\groups\ConfigGroup.js
- C:\Users\s\d\app\node_modules\webpack-cli\lib\webpack-cli.js
- C:\Users\s\d\app\node_modules\webpack-cli\lib\bootstrap.js
- C:\Users\s\d\app\webpack5-stucture\node_modules\bin\cli.js
- C:\Users\s\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\import-local\index.js
- C:\Users\s\AppData\Roaming\npm\node_modules\webpack-cli\bin\cli.js
- C:\Users\s\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js

Getting above error while trying to bundle my code
  "webpack": "5.1.0",
    "webpack-cli": "4.0.0",
    "webpack-dev-server": "3.11.0",
    "webpack-merge": "5.7.3"

**Comment by Itsaadarsh** [comment]
If you're using webpack-cli 4, try to change from webpack-dev-server --open to webpack serve.

Example:

`"serve": "webpack serve --config config/webpack.dev.js --progress --profile --watch --content-base src/"`
You might want also check this [comment ](https://github.com/webpack/webpack-dev-server/issues/2029#issuecomment-707196728)on GitHub:

NPM package.json scripts are a convenient and useful means to run locally installed binaries without having to be concerned about their full paths. Simply define a script as such:

For webpack-cli 3.x:

"scripts": { "start:dev": "webpack-dev-server" }

For webpack-cli 4.x:

"scripts": { "start:dev": "webpack serve" }

**Comment by alexander-akait** [comment]
Bug in your `C:\Users\s\d\app\webpack5-stucture\config\paths.js` file, we can't help here
