### ISSUE TITLE
Add back --output-filename param

### ISSUE THREAD

**Issue by clyfe** [webpack/webpack-cli#2385]
Older versions had the `--output-filename` param.
Current one doesn't, and that breaks [downstream tools that were using it](https://github.com/bhauman/figwheel-main/issues/278).

Can this be added back?

**Comment by alexander-akait** [comment]
No, it can't be returned, you have `--output-path` and `--output-filename`, it is breaking change

**Comment by clyfe** [comment]
I have `--output-filename`? Is not in the docs [here](https://webpack.js.org/api/cli/).

**Comment by snitin315** [comment]
Check help output - `webpack --help=verbose`

https://github.com/webpack/webpack-cli/blob/master/OPTIONS.md
