### ISSUE TITLE
'webpack serve' command fails after dependency updates

### ISSUE THREAD

**Issue by cemalettin-simsoft** [webpack/webpack-cli#2422]
**Describe the bug**

After recent dependency updates, webpack cli gives me this error.

```
$ export SERVER_URL=${SERVER_URL:-'http://localhost:8080'} DEV_PORT=${DEV_PORT:-3000} ; NODE_ENV=development webpack serve --config config/webpack.client.dev.js
[webpack-cli] TypeError: cli.isValidationError is not a function
    at Command.<anonymous> (/home/user/Desktop/someFolder/client/node_modules/@webpack-cli/serve/lib/index.js:96:25)
error Command failed with exit code 2.
```

which points me to the this code snippet

```
            catch (error) {
                if (cli.isValidationError(error)) {
                    logger.error(error.message);
                }
                else {
                    logger.error(error);
                }
                process.exit(2);
            }

```

**What is the current behavior?**
Cannot find the reference for the `isValidationError` function
`**TypeError: cli.isValidationError is not a function**`

**To Reproduce**
Start the dev-server after recent updates

**Expected behavior**

Webpack dev-server should start successfully.

**Screenshot of the dependency updates**

![dep_updates_of_webpack-cli](https://user-images.githubusercontent.com/69463668/107185936-5f7e9500-69f4-11eb-8e42-89618927e756.png)

**Comment by anshumanv** [comment]
Checking

**Comment by anshumanv** [comment]
You need to upgrade your webpack-cli too

**Comment by cemalettin-simsoft** [comment]
will try thanks

**Comment by cemalettin-simsoft** [comment]
Yes, after webpack-cli@4.5.0, it works :tada:

**Comment by anshumanv** [comment]
Great, closing
