### ISSUE TITLE
Create a subcategory on medium for the cli

### ISSUE THREAD

**Issue by fokusferit** [webpack/webpack-cli#246]
As discussed in our last cli meeting @TheLarkInn provided us the opportunity to have a subcategory (?) on medium so we can release future blogposts / series there. 

Thanks for supporting it Sean 🤗 !

**Comment by ematipico** [comment]
@fokusferit I believe this is now done?

**Comment by fokusferit** [comment]
Oh yeah, I think we can close this now.
