### ISSUE TITLE
Custom args passed to webpack does not work anymore with webpack 5

### ISSUE THREAD

**Issue by lk77** [webpack/webpack-cli#2462]
Hello,

i have an issue when updating to webpack 5,
it seems that custom args does not work anymore

```
const args = require('minimist')(process.argv.slice(2));

console.log(args.custom);

module.exports = {
     [...]
}
```

**What is the current behavior?**

When i run :
```
node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=production webpack --config webpack.config.js --custom=test
```
i got
```
[webpack-cli] Error: Unknown option '--custom=test'
[webpack-cli] Run 'webpack --help' to see available commands and options
```

**To Reproduce**

Add custom args to webpack command

**Expected behavior**

Webpack ignores unknown commands and proceeds as normal. With webpack 4 i used to pass a lot of args via the command line, and i could see those flags in the webpack.config.js file without issues.

```
> webpack-cli info


  System:
    OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Xeon(R) CPU E3-1225 V2 @ 3.20GHz
    Memory: 2.82 GB / 15.61 GB
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.12.1 - /usr/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 85.0.1
  Packages:
    clean-webpack-plugin: ^3.0.0 => 3.0.0 
    copy-webpack-plugin: ^7.0.0 => 7.0.0 
    html-webpack-plugin: ^4.5.2 => 4.5.2 
    karma-webpack: github:lk77/karma-webpack => 5.0.0 
    save-remote-file-webpack-plugin: github:nystudio107/save-remote-file-webpack-plugin#develop => 1.1.0 
    webpack: ^5.23.0 => 5.23.0 
    webpack-bundle-analyzer: ^4.4.0 => 4.4.0 
    webpack-cli: ^4.5.0 => 4.5.0 
    webpack-dev-server: ^3.11.2 => 3.11.2 
    webpack-version-file-plugin: ^0.4.0 => 0.4.0 
  Global Packages:
    webpack: 5.21.2
```

thanks

**Comment by lk77** [comment]
I find out  than i can do :

```
node node_modules/cross-env/src/bin/cross-env.js NODE_ENV=production webpack --config webpack.config.js --env --custom=test
```

and it works, it's a little bit longer, since i'm using npm run i'm force to type
```
-- --env --custom=test
```
everytime, it's less straightforward that it used to be

**Comment by snitin315** [comment]
With the latest `webpack-cli` version we have [`--node-env`](https://webpack.js.org/api/cli/#node_env), So you don't need to use `cross-env` anymore.

So you can change your script to:

`webpack --config webpack.config.js  --node-env production --env --custom=test`

Since `webpack.config.js` is default config you can also omit `--config webpack.config.js`

**Comment by lk77** [comment]
ok, thanks !

i will change that it will be shorter
