### ISSUE TITLE
[Docs]: Update README and Contributing guidelines

### ISSUE THREAD

**Issue by fokusferit** [webpack/webpack-cli#247]
Updated list of things I will cover:

- [x] Migrate documentation
- [ ] CLI descriptions at webpack.js.org and in the CLI should be more descriptive
- [x] README in all the package folders for each package
- [ ] InIt documentation at webpack.js.org
- [ ]  Documentation and Contribution guide
- [ ] Explaination about publishing and the `next`/`develop` branch
- [ ] Explain empty params code style

**Comment by ev1stensberg** [comment]
For the contribution guides, it should be split into sections like: do you want to make an easy contribution or an advanced one. At the start, we could have a small summary, and maybe split it up into a menu with pointers to different guides. One could be tests, another AST et.at

**Comment by dhruvdutt** [comment]
@ev1stensberg Please add "help wanted", "Good First Contribution" tags.

**Comment by ev1stensberg** [comment]
This is an maintainer issue, cause we need to make sure that the structure and documentation reflects how we want people to contribute. Discussed this in a meeting, @fokusferit can give you the link

**Comment by ev1stensberg** [comment]
@fokusferit any update? 💯

**Comment by ev1stensberg** [comment]
Moving #450 here

**Comment by fokusferit** [comment]
I'm updating the initial comment, and create a checklist, so that I it's easier to reference to PR's for each task.

**Comment by rishabh3112** [comment]
@ev1stensberg I would like to work on Init documentation first.

**Comment by ev1stensberg** [comment]
Go for it!

**Comment by rishabh3112** [comment]
@ev1stensberg check #547 for init documentation

**Comment by ev1stensberg** [comment]
Any update here lads?

**Comment by fokusferit** [comment]
THis weekend I have planned to focus! It's scheduled!

**Comment by ev1stensberg** [comment]
Hmu if you need help @fokusferit

**Comment by rishabh3112** [comment]
@ev1stensberg having a documentation website is much better as it will serve the cause quicker.
If you agree to same I am happy to build a solution for this :D

**Comment by fokusferit** [comment]
Docs page is webpack.js.org so stuff needs to go there 😅

**Comment by rishabh3112** [comment]
Yeah but I couldn't find the docs for `webpack-cli` there.

**Comment by fokusferit** [comment]
Exactly. This is something this task should tackle. 
We can collaborate on this, as I start with that topic and we could share tasks. Are you

**Comment by rishabh3112** [comment]
https://cli.angular.io
Angular CLI has its own too ;)

**Comment by rishabh3112** [comment]
@fokusferit we will be doing this at https://webpack.js.org or a standalone?

**Comment by fokusferit** [comment]
@rishabh3112 they have it but in our case I think the CLI is an integral part so having them all in one place makes more sense & referencing to the CLI in that doc's will increase visibility :)

**Comment by chaytanyasinha** [comment]
@evenstensberg  May I work on this?

**Comment by chaytanyasinha** [comment]
@evenstensberg May I work on this?

**Comment by snitin315** [comment]
@chaytanyasinha Sure , go ahead.
