### ISSUE TITLE
yarn bootstrap command is not found.

### ISSUE THREAD

**Issue by sumukhah** [webpack/webpack-cli#2472]
**Describe the bug**
running `yarn bootstrap` resulting in `error Command "bootstrap" not found.`. 

**What is the current behavior?**
resulting in error `error Command "bootstrap" not found.`

**To Reproduce**
* clone the repo
* run yarn install
* run `yarn bootstrap`

**Expected behavior**
Bootstrap all the submodules before building for the first time

**Screenshots**
<img width="601" alt="Screenshot 2021-03-01 at 6 53 10 PM" src="https://user-images.githubusercontent.com/23723464/109503711-9a8a5a80-7ac0-11eb-9774-9a5f59a85cc4.png">

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
node version: 12.14
**Additional context**

I am following contribution [guideline](https://github.com/webpack/webpack-cli/blob/master/.github/CONTRIBUTING.md).

**Comment by snitin315** [comment]
I see the `bootstrap` script is not present in `package.json` anymore. I am looking into it.

**Comment by alexander-akait** [comment]
You can run lerna bootstrap, no need command for this

**Comment by snitin315** [comment]
Yes, run `yarn lerna bootstrap` or `lerna bootstrap` (if `lerna` is available globally)
