### ISSUE TITLE
Remove local fork of Yeoman

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#248]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
The `cli` uses a local fork of yeoman generator

**If the current behavior is a bug, please provide the steps to reproduce.**

It works as expected but npm will install the local fork from github, which _**won't work if the user is behind a corporate proxy or they use a package manager like Artifactory**_

**What is the expected behavior?**
Install all the deps from npm

Something important that I want to highlight is that `webpack v4` will have a dependency from the `cli`, which means that if a user will try to update `webpack`, they won't be able to run some commands because yeoman won't be installed. I think  this is something that should be fixed before webpack v4 will be officially released. 
As I work in a company where they have a corporate proxy, they won't allow an installation from github because it's not a package manager like npm, What if we would do a PR to `yeoman` repository with the changes made inside the local fork?

@ev1stensberg what's your opinion about this topic?

**Comment by ev1stensberg** [comment]
I'll need to have a discussion with the yeoman team before we can do anything. It's already an issue on this, so close that one or this.

**Comment by ematipico** [comment]
What suits you best. We can track the progress of the task on the other issue. Closing as duplicate
