### ISSUE TITLE
Add info-verbosity into json schema

### ISSUE THREAD

**Issue by EugeneHlushko** [webpack/webpack-cli#249]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**
info-verbosity enum range is set within the code

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
info-verbosity enum is set in the schema, so there is no validation for it outside of validateOptions
**If this is a feature request, what is motivation or use case for changing the behavior?**
We are adding this option before json schema landed, but PR is there and should go in soon.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

Work can be started when #240 lands into master

**Comment by abiduzz420** [comment]
I shall take this up and subscribe to #242 PR, accordingly work on this issue.

**Comment by ev1stensberg** [comment]
Nice!

**Comment by ev1stensberg** [comment]
Here to help if you need anything :)

**Comment by EugeneHlushko** [comment]
On the other hand, looking again at the code @ev1stensberg 
i think that we cannot move this to webpackConfigurationSchema as it is not part of the `options` but actually a part of outputOptions. Having another validation step for output options maybe and a separate json file? but in that case it will duplicate information from these rows: https://github.com/webpack/webpack-cli/blob/a15807bdd1fb2a9759b7b22545dfdddb799cb212/bin/webpack.js#L65-L197

Sorry for late reply @abiduzz420 i would like to finish my code so i will work on this issue.

**Comment by ev1stensberg** [comment]
Separate configuration file is not good, would prefer it to be compact.

**Comment by EugeneHlushko** [comment]
In that case it should be out of outputOptions and go to options which gets validated against the schema. Any thoughts or objections?
cc @sokra @ev1stensberg

**Comment by ev1stensberg** [comment]
Send a PR, I'll review to see if its a nice thing to have in there 👍
