### ISSUE TITLE
test: add smoketests for missing subpackages

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack-cli#2493]
**Is your feature request related to a problem? Please describe.**
Currently we are not testing behaviour when sub packages are missing. I added one in #2482 and I think should be added for other packages.

**Describe the solution you'd like**
Same as mentioned above.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by alexander-akait** [comment]
Yes, PR welcome

**Comment by snitin315** [comment]
I'm writing one for missing `webpack-bundle-analyzer`.

**Comment by alexander-akait** [comment]
@rishabh3112 What tests do we need more?

**Comment by rishabh3112** [comment]
We are done, all optional deps are covered now.
