### ISSUE TITLE
convert-args signature contains unused parameters

### ISSUE THREAD

**Issue by shellscape** [webpack/webpack-cli#250]
**Do you want to request a *feature* or report a *bug*?**

Code cleanup, API change

**What is the current behavior?**

n/a 

**What is the expected behavior?**

n/a

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

https://github.com/webpack/webpack-cli/blob/master/bin/convert-argv.js#L6

contains two unused parameters; `yargs` and `convertOptions`. Both should be removed and that API signature removed in favor of `...args` and intelligent checking for arguments passed (eg. `argv` can be at `0` or `1` for `convert-args`.

webpack-contrib's ESLint config would have thrown an error for this. I'd highly recommend adopting it's use for this repo.

**Comment by sendilkumarn** [comment]
the spread operator is not supported in node4. Guess we have to wait until Apr 30 to change this.

**Comment by shellscape** [comment]
@sendilkumarn webpack@4 is node6+ as are all new major versions of webpack org modules.

**Comment by ematipico** [comment]
Yes we can safely use the spread operator now in `webpack-cli`. We already dropped node v4
