### ISSUE TITLE
`webpack serve --help` output showing all negative flags

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#2529]
**Describe the bug**

`webpack serve --help` output showing all negative flags

**What is the current behavior?**
all negative flags are being printed.

**To Reproduce**

`webpack serve --help`

**Expected behavior**
should print these flags in verbose mode only.

**Screenshots**
<img width="1266" alt="Screenshot 2021-03-20 at 4 54 13 PM" src="https://user-images.githubusercontent.com/46647141/111868044-bdac7980-899d-11eb-8a47-218e8e2a7f78.png">

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

OS - macOS

**Additional context**

**Comment by alexander-akait** [comment]
WIP
