### ISSUE TITLE
[FEATURE]: Option to switch between versions of webpack

### ISSUE THREAD

**Issue by cdrini** [webpack/webpack-cli#2551]
I'm working on a Vue 2 project, which needs webpack v4 deep in its internals. It seems unlikely I'll be able to update any time soon. However for a new entry point, I'd like to use v5. I was able to install both v4 and v5 using package.json npm aliases:

```json
"webpack": "^4.0.0",
"webpack5": "npm:webpack@^5.28.0",
"webpack-cli": "^4.5.0"
```

It would be wonderful if I could somehow configure `webpack-cli` to use `webpack5` some of the time.

**Describe the solution you'd like**

An environment variable seems like an ok option? Something like: `WEBPACK_PACKAGE=webpack5 npx webpack version`. A wepback-cli option itself could also work, but seems more difficult to implement.

**Describe alternatives you've considered**

- I tried splitting off the new entry point into its own directory, but they have some shared code, so not really an option. The only other option is using v4 exclusively.
- I tried modifying this line: https://github.com/webpack/webpack-cli/blob/6fb1215c8ac82e88ee85861e987b476af47acc61/packages/webpack-cli/lib/webpack-cli.js#L12 to say `this.webpack = require(process.env.WEBPACK_PACKAGE || 'webpack');`, and that did the thing!

**Additional context**

**Comment by anshumanv** [comment]
The approach looks good but ideally, it would be best if tools migrate to webpack 5 instead

/cc @alexander-akait what do you think?

**Comment by alexander-akait** [comment]
Make sense, PR welcome

**Comment by snitin315** [comment]
i will send a PR

**Comment by cdrini** [comment]
Awesome! Thank you @snitin315 @alexander-akait @anshumanv ! That was some lightning fast turn around :)

**Comment by cdrini** [comment]
And it's released and usable in under a week! Y'all are awesome!
