### ISSUE TITLE
configuration validation : strict "Promise" instanceof validation

### ISSUE THREAD

**Issue by jbottigliero** [webpack/webpack-cli#258]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
webpack/webpack-cli#240 introduces validation which causes `Promise` based configurations to pass due to `instanceof Function` being `true`.

**What is the expected behavior?**
At the point the validation runs, the configuration can never be _just_ a `Function`, it's expected to be an object, an array of objects, or a `Promise`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Provide stricter validation schema.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

The main concern with adding the above is that it requires webpack/webpack#6430.

The `ajv-keywords` package does not support `"instanceof": "Promise"` in versions `<3.1.0`, which has a `peerDependency` of `ajv@^6.0.0`.

An alternative to updating the package versions would be to add `Promise` as a "custom" constructor [(outlined here)](https://github.com/epoberezkin/ajv-keywords/tree/v2.1.1#instanceof), but this would still have to be implemented in `webpack/webpack` based `ajv` being configured in core, and not directly exposed.

**Comment by jbottigliero** [comment]
I have a branch ready with this change that I will PR once webpack/webpack#6430 is part of a tagged release.

**Comment by ev1stensberg** [comment]
Sounds good

**Comment by dhruvdutt** [comment]
webpack [4.0.0](https://github.com/webpack/webpack/releases/tag/v4.0.0) is out. :fire: 

@jbottigliero Can we make the PR now?

**Comment by jbottigliero** [comment]
@dhruvdutt – opened #298, cheers!

**Comment by jbottigliero** [comment]
#298 was merged to `master` – closing.
