### ISSUE TITLE
[BUG]:  TypeError: this.program.configureOutput is not a function

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#2598]
**Describe the bug**

When I install webpack-cli I get  `TypeError: this.program.configureOutput is not a function`.
**What is the current behavior?**
See above

**To Reproduce**

1. Install webpack-cli `npm install -g webpack-cli`
2. Run `webpack-cli`

**Expected behavior**

A compilation or the help command is shown.

**Screenshots**
<img width="562" alt="Screen Shot 2021-04-06 at 02 06 16" src="https://user-images.githubusercontent.com/16735925/113640871-b0b9a680-967c-11eb-9913-11e3bb3c09fd.png">

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
N/A

**Additional context**

node v.10.21.0

Darwin xxx xxx Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; xxx/RELEASE_X86_64 x86_64

**Comment by evenstensberg** [comment]
We should output an error if webpack isn't installed.

**Comment by snitin315** [comment]
We already do that https://github.com/webpack/webpack-cli/blob/31d0aba5518cc9cca57513fc3c1147cfb7eaf703/packages/webpack-cli/bin/cli.js#L24

**Comment by rishabh3112** [comment]
We also have smoketests in place for missing webpack. Can you share reproducible repo for the same?

**Comment by evenstensberg** [comment]
I just showed you the steps to reproduce

**Comment by alexander-akait** [comment]
Not related to webpack-cli, you have global installed old version of commander.js, we can't fix it on our side, this is how it works `require`

**Comment by alexander-akait** [comment]
You can look at our code and see it

**Comment by evenstensberg** [comment]
forgot to build actually
