### ISSUE TITLE
[Feature]: Rename init to create

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#2599]
**Is your feature request related to a problem? Please describe.**

Init isn't a very good name for creating/scaffolding new configurations.

**Describe the solution you'd like**

Rename `webpack-cli` init to `webpack-cli create`

**Describe alternatives you've considered**

Nothing

**Additional context**

N/A

**Comment by alexander-akait** [comment]
It is breaking change, we can apply alias

**Comment by snitin315** [comment]
Yes alias will be good. I can send a PR for same.

**Comment by alexander-akait** [comment]
Also let's add `new` alias, to be honestly, `webpack new` and `webpack new --template react` is the best name for this

**Comment by snitin315** [comment]
Yeah `new` suits better.
