### ISSUE TITLE
Error: Unknown option '--info'

### ISSUE THREAD

**Issue by real-shigurepoi** [webpack/webpack-cli#2606]
**Describe the bug**

get error  `Error: Unknown option '--info'`  when try to start dev server with script 
`webpack serve --config webpack.config.js --mode development --progress --info false`

**Dependences**
```
"dependencies": {
  "react": "^17.0.2",
  "react-dom": "^17.0.2",
  "react-router-dom": "^5.2.0"
},
"devDependencies": {
  "@babel/core": "^7.13.14",
  "@babel/preset-react": "^7.13.13",
  "babel-loader": "^8.2.2",
  "eslint": "^7.23.0",
  "html-webpack-plugin": "^5.3.1",
  "webpack": "^5.30.0",
  "webpack-cli": "^4.6.0",
  "webpack-dev-server": "^3.11.2"
}
```
**Versions**
node 14.16.0
yarn 1.22.5

**Comment by snitin315** [comment]
We don't have any `--info` flag with the latest version. You need to change your script to -

`webpack serve --config webpack.config.js --mode development --progress`

To see a list of available commands and options run `webpack --help`.

**Comment by real-shigurepoi** [comment]
ok , but this option can be found in webpack doc, this may be an enhancement.

**Comment by snitin315** [comment]
> ok , but this option can be found in webpack doc, this may be an enhancement.

Need update docs, can you share the link where you find it?
