### ISSUE TITLE
Webpack Generators should allow paths instead of NPM/Yarn

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#262]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running `webpack init myPackage` requires it to be published on npm. 
**If the current behavior is a bug, please provide the steps to reproduce.**
Run `webpack init someUnPublishedPackage`

**What is the expected behavior?**
We should support relative paths to initalize projects. This makes it easier for authors to test their packages and people that are using it to use their local ones without publishing.

**If this is a feature request, what is motivation or use case for changing the behavior?**
NA
**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
NA

**Comment by dylanonelson** [comment]
I'd like to take a crack at this.

**Comment by EugeneHlushko** [comment]
In that case @ev1stensberg can you assign the issue to @dylanonelson so its transparent for others
