### ISSUE TITLE
webpack-cli/bin/config-yargs' not found 

### ISSUE THREAD

**Issue by Juniad9421** [webpack/webpack-cli#2664]
**Describe the bug**

**What is the current behavior?**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by anshumanv** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please use latest webpack-cli

**Comment by Juniad9421** [comment]
My Project Specification are 
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "live-server": "^1.2.1",
    "webpack-cli": "^4.6.0"
    "@babel/core": "^7.13.16",
    "@babel/preset-env": "^7.13.15",
    "babel-loader": "^8.2.2",
    "webpack": "^5.35.1",
    "webpack-dev-server": "^3.11.2"




/****************************************/

             ERROR BELOW
/***************************************/

> test_boiler@1.0.0 dev-server
> webpack-dev-server --mode development

node:internal/modules/cjs/loader:943
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- F:\Web Development\JS\Test_Boiler\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.Module._load (node:internal/modules/cjs/loader:773:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (F:\Web Development\JS\Test_Boiler\node_modules\webpack-dev-server\bin\webpack-dev-server.js:65:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'F:\\Web Development\\JS\\Test_Boiler\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}





/*********************************************************************************/ 

Here I found some file confliction to access file from CLI 
Actually, I compare these changes to previous version
and found 


In Latest Version 
![Current CLI config-yargs js file -- not exist in CLI fooder]
(https://user-images.githubusercontent.com/44174808/115985839-22737900-a5c7-11eb-8cba-10925d8abd08.png)

In Previous Version 
![Privious CLI config-yargs js file](https://user-images.githubusercontent.com/44174808/115985899-5189ea80-a5c7-11eb-855a-931a9a54fd94.png)





Resolve these file path access to "webpack-cli/bin/config-yargs.js"

**Comment by anshumanv** [comment]
Follow https://github.com/webpack/webpack-cli/issues/1948

what command do you use to run dev-server? use `webpack serve`

**Comment by Juniad9421** [comment]
> 
> 
> Follow #1948
> 
> what command do you use to run dev-server? use `webpack serve`

I used this command for webpack
dev-server : 'webpack-dev-server'

**Comment by anshumanv** [comment]
use `webpack serve`

**Comment by anshumanv** [comment]
As mentioned in docs

**Comment by Juniad9421** [comment]
But 
dev-server : 'webpack serve'
rsolve the broblem thanks
