### ISSUE TITLE
ProgressPlugin is not a constructor

### ISSUE THREAD

**Issue by ganapativs** [webpack/webpack-cli#267]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using webpack 4.0.0-beta.1 and webpack-cli 2.0.5.
webpack-cli is throwing
`ProgressPlugin is not a constructor`
https://github.com/webpack/webpack-cli/blob/94ac6dbbc50027184c6b32aa496b8ba3157ff0dc/bin/webpack.js#L442

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
shouldn't
```
const ProgressPlugin = require("webpack").ProcessPlugin;
```
be
```
const ProgressPlugin = require("webpack").ProgressPlugin;
```
Or am I missing something?

**Comment by ev1stensberg** [comment]
Hi, fixed now, sorry. 

We had some conflicts with rebasing against the old webpack w.r.t dependencies earlier, but it should be fixed now, just pushed a patch (`v.2.0.6`). Thank you so much for reporting the problem, it would be super awesome if you'd post an issue like you just did, if you find another bug like this or anything that you might think is a bug 👍 Have a nice Wednesday!

**Comment by ganapativs** [comment]
@ev1stensberg Sure, Thanks 😀
