### ISSUE TITLE
Convert the codebase to Typescript

### ISSUE THREAD

**Issue by khushal87** [webpack/webpack-cli#2685]
**Is your feature request related to a problem? Please describe.**
A major part of the codebase is in Javascript currently. If we migrate it to Typescript this will enable new possibilities and make the codebase more clear with stricter type checking and readable code.

**Describe the solution you'd like**
I would like to convert the codebase to typescript.

**Describe alternatives you've considered**
None, for now.

**Additional context**
I would like to have feedback from the community and ask if I can proceed to work on it.

**Comment by khushal87** [comment]
I would like to start with the `scripts` directory.

**Comment by alexander-akait** [comment]
PR welcome

**Comment by khushal87** [comment]
@alexander-akait I am working on it and soon will raise a PR. Just one doubt, you want all at once or I can proceed directory-wise?

**Comment by anshumanv** [comment]
You can also help in https://github.com/webpack/webpack-cli/pull/2686

**Comment by anshumanv** [comment]
Also, I feel there's no real benefit of changing `scripts` to TS as they are mostly used by us or on CI

**Comment by khushal87** [comment]
Okay @anshumanv Which directory can I start with, so that there isn't any conflict? I see you have already done a good amount of migration.

**Comment by evenstensberg** [comment]
This will make it harder for new contribitors to start contributing FYI

**Comment by alexander-akait** [comment]
We still need ts, as minimum as JSDocs

**Comment by akash-joshi** [comment]
Is this issue still up for grabs? If yes, can the Typescript conversion be carried out incrementally?

There's discussions to be had around the various settings in `tsconfig.json` as well, but I guess that can be done when there's a PR introducing one to the codebase.

**Comment by taranek** [comment]
@alexander-akait  Is this still relevant? Is there anything else we want to add types to? 🤔

**Comment by alexander-akait** [comment]
We can move our tests to ts, but I don't think it makes much sense like I said before.

**Comment by snitin315** [comment]
I think tests are fine in JS. We can close this issue.
