### ISSUE TITLE
Consider splitting the CLI and transformations

### ISSUE THREAD

**Issue by rynclark** [webpack/webpack-cli#269]
**What is the current behavior?**

Now that webpack 4 requires the CLI, which in return has a dependency on `jscodeshift`, this means everyone get's a copy of `babel-register` and all the other plugins that it needs.

Ideally this should be split out as not everyone who uses the CLI needs to transform the code.

It also causes issues when trying to use the babel-loader 8.x with babel 7.x, as `jscodeshift` uses babel 6.x.

**If the current behavior is a bug, please provide the steps to reproduce.**

Install `webpack@next` and the `webpack-cli`. Check your `node_modules`.

**What is the expected behavior?**

Split out the code transformation from the CLI, so all users don't have to have a copy of (possibly the incorrect version of) babel with every webpack install.

- `node` 8.4.0
- `macOS` High Sierra 
- `npm` 5.6.0
- `webpack` 4.0.0-beta.1
- `webpack-cli` 2.0.6

**Comment by rynclark** [comment]
I think splitting it out into `webpack-cli-yeoman` would be good. That could either then be the command if used with yeoman, or add a `--yeoman` flag (or auto detection) that will check for the separate npm package.

**Comment by ev1stensberg** [comment]
In for this, this issue would be in relation to the monorepo strategy

**Comment by shellscape** [comment]
Make the package solid first. Worry about constructing a monorepo later. I vote 👍 for this (and suggest the same is needed for many of CLI's feature sets)

**Comment by cvkline** [comment]
jscodeshift also brings in babel-preset-es2015 which is deprecated in favor of babel-preset-env, as well as nomnom, which is also deprecated. I also vote 👍🏻 on this.

**Comment by ev1stensberg** [comment]
That's on Facebook, not us. The warning will still be there

**Comment by cvkline** [comment]
I guess I didn't phrase it right… I didn't mean to imply that it was something you could fix. Sorry! I just meant to echo support for the original request that that package doesn't look to have very good deps and that might cause issues for some, hence the suggestion to split out that transformation functionality from the webpack-cli basics.

**Comment by rynclark** [comment]
Is `webpack-cli migrate` even used much anymore? v1 to v2 transformation, we're on v4 now..

**Comment by ev1stensberg** [comment]
https://twitter.com/_kud/status/968481905392914432

**Comment by sendilkumarn** [comment]
one more reason for monorepo 👍 😉

**Comment by ev1stensberg** [comment]
#261
