### ISSUE TITLE
Empty Module.exports created with webpack-cli init

### ISSUE THREAD

**Issue by wangtoday** [webpack/webpack-cli#271]
Hi Guys, 

I was trying to use webpack-cli to generate the webpack.config.js file.  I follwed the stpes blow:

1.  In a empty folder,  run **npm init** first.
2.  run **webpack-cli init**
3.  fill with the below answers.

>  ? Will your application have multiple bundles? **No**
? Which module will be the first to enter the application? [example: './src/index'] **index.js**
? Which folder will your generated bundles be in? [default: dist]: **dist**
? Are you going to use this in production? **Yes**
? Will you be using ES2015? **Yes**
? Will you use one of the below CSS solutions? **LESS**
? If you want to bundle your CSS files, what will you name the bundle? (press enter to skip) **stylesheet.min.css**
? Name your 'webpack.[name].js?' [default: 'prod']: **config**

However, once it done, I got a webpack.config.js file without any description in the Module.export ,
```

const webpack = require('webpack');
const path = require('path');

/*
 * We've enabled UglifyJSPlugin for you! This minifies your app
 * in order to load faster and run less javascript.
 *
 * https://github.com/webpack-contrib/uglifyjs-webpack-plugin
 *
 */

const UglifyJSPlugin = require('uglifyjs-webpack-plugin');

/*
 * We've enabled ExtractTextPlugin for you. This allows your app to
 * use css modules that will be moved into a separate CSS file instead of inside
 * one of your module entries!
 *
 * https://github.com/webpack-contrib/extract-text-webpack-plugin
 *
 */

const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {};
```

I thought there should be some basic configuration setting inside the module.exports, but it just return a empty obj.  I followed by [Getting started with the NEW webpack cli](https://www.youtube.com/watch?v=mE9IvFzXDFc&list=PLw5h0DiJ-9PDnVL1s-Y3HLWK8FYaCK8-e). Thought somethins is not correct with my output of webpackconfig.js, but can not figure where is wrong. 

Sorry, I am new to webpack.

**Comment by ev1stensberg** [comment]
Thanks for submitting an issue, will check it out! Which version are you using?

**Comment by abtExp** [comment]
Faced The Same Issue : 
 Webpack-cli : 2.0.4 
webpack : 3.11.0

**Comment by ev1stensberg** [comment]
Could you guys upgrade to `webpack-cli 2.0.6` ?

**Comment by wangtoday** [comment]
Hi @ev1stensberg ,

Just update the version to 2.0.6.


> ? Will your application have multiple bundles? No
> ? Which module will be the first to enter the application? [example: './src/index'] index.js
> ? Which folder will your generated bundles be in? [default: dist]: dist
> ? Are you going to use this in production? Yes
> ? Will you be using ES2015? Yes
> ? Will you use one of the below CSS solutions? SASS
> ? If you want to bundle your CSS files, what will you name the bundle? (press enter to skip)
> ? Name your 'webpack.[name].js?' [default: 'prod']: webpack.config.js

> yarn add v0.27.5
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> warning fsevents@1.1.3: The platform "win32" is incompatible with this module.
> info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...
> warning "less-loader@4.0.5" has incorrect peer dependency "less@^2.3.1".
> [4/4] Building fresh packages...
> success Saved 10 new dependencies.
> ├─ babel-core@6.26.0
> ├─ babel-loader@7.1.2
> ├─ babel-preset-env@1.6.1
> ├─ css-loader@0.28.9
> ├─ extract-text-webpack-plugin@3.0.2
> ├─ node-sass@4.7.2
> ├─ sass-loader@6.0.6
> ├─ style-loader@0.20.2
> ├─ uglifyjs-webpack-plugin@1.2.0
> └─ webpack@3.11.0
> Done in 6.91s.

Still have an empty module.export, 

`module.export = {}`

**Comment by abtExp** [comment]
Yep, 2.0.6 also produces empty exports

**Comment by ev1stensberg** [comment]
Gotcha, checking out later. Thanks for reporting!

**Comment by jevan0307** [comment]
Hi, I have the same problem.
May I send a PR for this issue?

**Comment by ev1stensberg** [comment]
Go ahead!
