### ISSUE TITLE
Config option to listen unix-socket instead of port for dev-server

### ISSUE THREAD

**Issue by findoff** [webpack/webpack-cli#2752]
**Is your feature request related to a problem? Please describe.**

At first i was create this issue at https://github.com/webpack/webpack-dev-server/issues/3308
As described at https://webpack-v3.jsx.app/configuration/dev-server/#devserver-socket unix socket can be listen unix-sockets with `devServer: {socket}`, but with webpack-dev-server@4 it's does't work.

As i can find socket option belongs to dev-server and dropped at 4th version.

**Describe the solution you'd like**

I was think it's problem related to dev-server, but redirected here.

**Describe alternatives you've considered**

Now i resolve this issue by replacing webpack-cli + simple-configuration with own express app what uses dev and hot middleware directly without dev-server.

**Additional context**

About my use case
Thick dev-server with many users
Any user can create socket's at own specified folder
Nginx automatically serves static from folder and not found from sockets over https with wildcard certifaicate
_PROJECT_-_USER_.dev-server.example.com => /home/_USER_/sockets/_PROJECT_.sock
Also it's uses different socket name for proxy `/api` to backend app, but it unrelated to this issue

It's gives way to don't do any actions to serve new or test project from user folder.
Every project have https on standard port and easy semantic name.
Dev's have no requirements to local machine and can easly and instantly show own version to other.
No local accessed app ports gives way to use POSIX permission to restrict access between different devs. (nginx uses project named auth basic file from user folder)
Just nginx and permission without external programs gives zero-cost reasonable isolation and high control to any dev without special requirements with just a copy&paste folder. (without socket option it's requires additional code or manual actions from every dev)

**Comment by alexander-akait** [comment]
:+1: 

hmm, I looked at the code that we have before, I think we will return it in the next few days, it's not difficult

**Comment by politsin** [comment]
subscribe

**Comment by alexander-akait** [comment]
Sorry for small delay https://github.com/webpack/webpack-dev-server/pull/3479/, after merge I will update our logic here and all will be work
