### ISSUE TITLE
Add the ability to pick a package manager of choice while scaffolding

### ISSUE THREAD

**Issue by jamesgeorge007** [webpack/webpack-cli#2768]
**Is your feature request related to a problem? Please describe.**
Currently, there isn't any way to specify a package manager of choice while generating the boilerplate (`init` | `loader` | `plugin`).

https://github.com/webpack/webpack-cli/blob/060268b770c9623e457afc849e3933364914951d/packages/generators/src/init-generator.ts#L103

https://github.com/webpack/webpack-cli/blob/060268b770c9623e457afc849e3933364914951d/packages/webpack-cli/lib/utils/get-package-manager.js#L15-L31

With the current approach, `npm` is always chosen if creating a new project in an empty directory.

**Describe the solution you'd like**
It'd be nice to have a prompt that shows up with the available installers so that one can go ahead with the preferred package manager.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by alexander-akait** [comment]
Yep, PR welcome
