### ISSUE TITLE
writeToDisk doesn't work with multiple targets

### ISSUE THREAD

**Issue by Timmmm** [webpack/webpack-cli#2771]
webpack version: 4.43.0
webpack-cli version: 3.3.11
webpack-dev-server version: 3.11.0
Node.js version: 14.0.0
Operating System: MacOS 10.14.6

- [x] This is a **bug**

If you have a webpack.config.js that exports multiple targets, e.g:

    module.exports = [rendererConfig, mainConfig];

And you set this in one of them:

```
  devServer: {
    writeToDisk: true,
  },
```

Then no files are written to disk - the behaviour is identical to not setting it. If you add that setting to both targets then it correctly writes everything out to disk. But I would have expected that you can set that option in different targets separately.

### Expected Behavior

It should write files to disk.

### Actual Behavior

It does not write files to disk.

### For Bugs; How can we reproduce the behavior?

Run `webpack-dev-server` with multiple targets, only one of which has `writeToDisk` set.

**Comment by alexander-akait** [comment]
@webpack/cli-team we need to allow set `devServer: false`, so we should fix it firstly here https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json#L346, i.e. `enum: [false]`

**Comment by snitin315** [comment]
On it 👍

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack-cli/issues/2408
