### ISSUE TITLE
Feature: Document what `smoketests` folder does

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#2778]
**Is your feature request related to a problem? Please describe.**

For less confusion, documenting the `smoketests` folder would be nice. Add a README and document how to run smoketests and how it is structured. 

**Describe the solution you'd like**

A README that documents the smoketests run by the CLI.

**Describe alternatives you've considered**
N/A

**Additional context**

N/A

**Comment by alexander-akait** [comment]
`smoketests` is smoke tests, why we need document it? I find it superfluous

**Comment by evenstensberg** [comment]
It's easier to know what happens and good for documenting in case new developers want to know

**Comment by rushikeshadhav** [comment]
Hey, Can I contribute. I would really love to contribute. This will be my first contribution to this project.
I need some beginner friendly issues to contribute to. It would be really great if I can.
Thank you.

**Comment by dollar22** [comment]
going for it assigned it to me

**Comment by dollar22** [comment]
@snitin315 How i will able to know I'm doing changes is right or wrong like in website i can clearly see what i'm doing but how i will know in cli

**Comment by snitin315** [comment]
You can run existing tests and add mkre test cases as per your changes to check if everything is working as expected. Read CONTRIBUTING.md for moreinformation.

**Comment by dollar22** [comment]
@snitin315 ok thanks bro

**Comment by dollar22** [comment]
@snitin315 where i have to add doc about smoketests is it in webpack.js.org

**Comment by snitin315** [comment]
I don't think if we need docs for it. Simply, these are just tests.

/cc @webpack/cli-team

**Comment by rishabh3112** [comment]
Yup, not needed. We can close this one.
