### ISSUE TITLE
Enhancement: Move flags to its own files and import them

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#2780]
**Is your feature request related to a problem? Please describe.**

Right now, flags are inline in `lwebpack-cli.js` and it is no need to have it there.

**Describe the solution you'd like**
Modularize the options to their own files and import them.

**Describe alternatives you've considered**

N/A

**Additional context**

https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/lib/webpack-cli.js#L401-L676

to its own file and import them.

**Comment by alexander-akait** [comment]
Thanks, no need

**Comment by evenstensberg** [comment]
Why? It's better for performance in node

**Comment by alexander-akait** [comment]
How? Extra `require` requires fs call, each fs call reduce perf, we can use memorize here, but there is no point do it

**Comment by evenstensberg** [comment]
it makes it more readable, and we can have it as a top-scope prop insted?

**Comment by alexander-akait** [comment]
@evenstensberg Why we need this? It is internal, code is readable right now, I don't see any problems here
