### ISSUE TITLE
Yarn is a Needless Dependency

### ISSUE THREAD

**Issue by shellscape** [webpack/webpack-cli#280]
**Do you want to request a *feature* or report a *bug*?**

Neither. An architectural issue.

**What is the current behavior?**

Contribution to this repo _requires_ `yarn` and is an unnecessary blocker. More importantly, installation of `npm` dependencies immediately after cloning to this repo throws an error if the user does not have `yarn` installed globally. This is counter-intuitive behavior.

**What is the expected behavior?**

The repo should clone, and `npm install` should function without error and without `yarn` installed.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Webpack and it's official packages should be packager agnostic. There's absolutely no need for `yarn` as an additional dependency as none of the yarn-specific feature sets are being utilized by the repo. As Node ships with `npm`, everyone is guaranteed to have it installed. While using `yarn` as an individually preferred packager should not be a blocker, and while the repo should function using `yarn` on one's machine, it should not be a hard, global dependency for this module.  Note that `webpack` proper nor any of the modules in the `webpack` org require `yarn`.

Combing through the commits which add yarn to the package.json scripts, there appears to be no related information as to why this was done and seems to be an arbitrary change. As none of the yarn-specific features (eg. workspaces) are being used, and there is no information documented as to why this change was made, this appears to simply be a poor architectural choice. I would like to submit a PR to revert to using `npm`.

**Comment by ev1stensberg** [comment]
#302

**Comment by shellscape** [comment]
well done @ev1stensberg 👏
