### ISSUE TITLE
[webpack-cli] Error: Unknown option '--build-delimiter'

### ISSUE THREAD

**Issue by AlonsoK28** [webpack/webpack-cli#2803]
**Describe the bug**

`Output options` command `--build-delimiter` doesn't works into `webpack-cli@4.7.2` according to documentation https://v4.webpack.js.org/api/cli/#output-options

**What is the current behavior?**

When add `--build-delimiter` to `webpack-cli ` params gets following error 

```
[webpack-cli] Error: Unknown option '--build-delimiter'
[webpack-cli] Run 'webpack --help' to see available commands and options
```

**To Reproduce**

Add `--build-delimiter` to `webpack-cli` params for example  

```
webpack --config my-webpack-config.js --watch --progress --build-delimiter
```

**Expected behavior**

`webpack-cli` outputs the delimiter correctly according to documentation https://v4.webpack.js.org/api/cli/#output-options

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

```
// package.json
...
"scripts": {
    "start": "webpack --config my-webpack-config.js --watch --progress --build-delimiter",
  },
...
```

**Additional context**

I dont know if this options still valid in `latest webpack 4` but if not please remove from documentation and add a options because this is user-friendly feedback for developers when `webpack-cli` emmit a new compilation

**Comment by anshumanv** [comment]
Yep, that option, unfortunately, doesn't exist in CLI v4, I think this can be achieved using a simple plugin? 

/cc @alexander-akait

**Comment by alexander-akait** [comment]
@AlonsoK28 What is use case for `--build-delimiter`? Yep, it will be implement using custom plugin

**Comment by alexander-akait** [comment]
But it is angular CLI output, and webpack already write `compiled success` at the end

**Comment by AlonsoK28** [comment]
> But it is angular CLI output, and webpack already write `compiled success` at the end

I fully agree with you

I'm just giving an example of a use case for `--build-delimiter` as you asked me 🙂🙂🙂🙂

**Comment by evenstensberg** [comment]
We should support this, makes the CLI more customizable

**Comment by alexander-akait** [comment]
You can do it using plugins, why we need to have it built-in?

**Comment by alexander-akait** [comment]
Let's close, please create custom plugin for this, we already print `compiled success` or compiled with errors/compiler with warning, it is enough for 99% cases, I don't see good reasons add it by default
