### ISSUE TITLE
feature: add init templates for popular webpack use cases

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack-cli#2832]
**Is your feature request related to a problem? Please describe.**
We recently updated the init architecture. This makes it easier to add template for initializing new projects.

**Describe the solution you'd like**
Here are few high priority ones:
- [ ] React/Preact
- [ ] Vue
- [ ] Svelte
- [ ] Node

Feel free to add more suggestions below 😄 

**Describe alternatives you've considered**
N/A

**Additional context**
#2430

**Comment by rishabh3112** [comment]
Will be doing the React/Preact first!

**Comment by jamesgeorge007** [comment]
Hi @rishabh3112, I'd love to join forces. Can I take up Svelte?

**Comment by alexander-akait** [comment]
Yes, feel free to send any PR

**Comment by rishabh3112** [comment]
@jamesgeorge007 sure, thank you for helping out! Sorry for late reply, was busy with other stuffs and I missed this issue some how.

**Comment by rishabh3112** [comment]
bump
