### ISSUE TITLE
TypeError loading webpack.config.js in ESM project with node v16.6

### ISSUE THREAD

**Issue by olizilla** [webpack/webpack-cli#2864]
I think this change https://github.com/nodejs/node/pull/39175 in node 16.6 means the webpack.config.js is loading is broken for ESM projects.

Our CI started failing once node 16.6 got rolled out with:

```console
$ npm run build

> @web3-storage/api@3.1.1 build
> webpack

TypeError: String.prototype.startsWith called on null or undefined
    at startsWith (<anonymous>)
    at node:internal/errors:811:19
    at Array.filter (<anonymous>)
    at node:internal/errors:809:16
    at prepareStackTrace (node:internal/errors:96:12)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:38)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

Setting `WEBPACK_CLI_FORCE_LOAD_ESM_CONFIG=true` fixed it, but it seems like a workaround.

see: https://github.com/webpack/webpack-cli/blob/a660ffcbeb2807bce1554f787297e697464abd59/packages/webpack-cli/lib/webpack-cli.js#L50-L51
see: https://github.com/nodejs/node/pull/39175
see: https://github.com/nodejs/node/commit/e2a6399be742f53103474d9fc1e56fadf7f90ccc#r54198959

**Comment by olizilla** [comment]
reported in: https://github.com/nodejs/node/commit/e2a6399be742f53103474d9fc1e56fadf7f90ccc#r54198959

add your +1 on this comment to vote to fast track the fix https://github.com/nodejs/node/pull/39593#issuecomment-890049715

**Comment by olizilla** [comment]
it's already landed! Noice!

**Comment by alexander-akait** [comment]
Fixed in Node.js
