### ISSUE TITLE
Deprecation warning of dep of our deps

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#287]
**Do you want to request a *feature* or report a *bug*?**
Deprecation warning

**What is the current behavior?**
`warning webpack-cli > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.`

**If the current behavior is a bug, please provide the steps to reproduce.**
Install the cli

**What is the expected behavior?**
No deprecation notices

Just noticed the deprecation of the package `nomnom` which is a `dependency` of the package `jscodeshift` which is heavily used by the cli. Should we take action and check with the facebook guys if they plan or want help to finding an alternative?

**Comment by dhruvdutt** [comment]
I've made a [PR](https://github.com/facebook/jscodeshift/pull/240) to jscodeshift to replace the deprecated package with an [active fork](https://github.com/GerHobbelt/nomnom).

**Comment by ematipico** [comment]
Thanks @dhruvdutt ! Let's hope it's going to get merged soon

**Comment by EvHaus** [comment]
Why not simply move `jscodeshift` to `devDependencies` instead. Is it really needed for production use?

**Comment by ematipico** [comment]
Yeah we use to manipulate the AST! It's at the core of the migration feature :)

**Comment by vladshcherbin** [comment]
This warning are really scary, especially the last ones:

![screen shot 2018-03-19 at 11 24 46](https://user-images.githubusercontent.com/6711845/37584905-43c87056-2b68-11e8-9932-ee3addc56b75.png)

Would be really great to get read of them 🙏

**Comment by ev1stensberg** [comment]
@vladshcherbin this is on jscodeshift, they're delaying, hopefully it will be gone soon.

**Comment by ev1stensberg** [comment]
Nothing more we can do. We're removing some redundancies when new version is published, but ultimately this is on jscodeshift.

**Comment by edmorley** [comment]
> Nothing more we can do. We're removing some redundancies when new version is published, but ultimately this is on jscodeshift.

To save others looking for it too - the relevant PR is:
facebook/jscodeshift/pull/247
