### ISSUE TITLE
[Feature]: Increase memory with a flag / Support Node Flags

### ISSUE THREAD

**Issue by damianobarbati** [webpack/webpack-cli#289]
Could `webpack-cli` handle the memory limit increase with a flag?

Right now we have to manually use:
```node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js```

A simple flag would be very nice instead:
```webpack --increase-memory 4096```

Or multiple custom node options like:
```webpack --node.increase-memory 4096 --node.trace-deprecation --node.experimental-modules```

**Comment by PlayMa256** [comment]
I'm down to grab this, but i'm not really sure where do i add the flags.
Is this similar to [this](https://github.com/webpack/webpack-cli/blob/master/bin/convert-argv.js#L29)?

**Comment by montogeek** [comment]
@PlayMa256 No, it is part of the process args, not process environment variables

**Comment by montogeek** [comment]
You could do something like `argv["max_old_space_size"] = 4096` somewhere.
I believe this shouldn't be part of webpack, it should be handled by the user.

**Comment by PlayMa256** [comment]
I expressed myself in a wrong way, sorry for that.
I understand it's not a process args, but i meant to do this the same way that the production mode is handled.
Anyways. You answered my question!
Thank you @montogeek

**Comment by PlayMa256** [comment]
I was having a look how to implement those flags, and i've reached a fork road. I'm not able to override node flag options when a process already started, so i was thinking... spawning a child process passing down v8 flags would be a cumbersome idea or is there a way (i actually dont know any...) to update v8 flags when a process already started?

What do you all think?

**Comment by ev1stensberg** [comment]
Getting back to you on this. This might not be possible without invoking `node ./path/to/webpack`

**Comment by PlayMa256** [comment]
is there a way to run a single test only? A single binary test?

**Comment by ematipico** [comment]
Not at the moment :(

**Comment by ev1stensberg** [comment]
This impl can be used with #15 . We keep track of pId and restart a process once it's done ( I think )

**Comment by damianobarbati** [comment]
Can npx used to accomplish the result? i.e: `npx -n=' --max_old_space_size=4096'`
Not sure how to inspect max memory limit for current process in js.

**Comment by evenstensberg** [comment]
Yes if npm supports injection of args. We cannot use this as a fix to us, as the flags needs to be supported by default not by running npx
