### ISSUE TITLE
Error: Cannot find module '@webpack-cli/serve/lib/startDevServer'

### ISSUE THREAD

**Issue by timoaudi** [webpack/webpack-cli#2895]
**Describe the bug**

Since the release of webpack-cli 4.8.0 we get the error below.

**What is the current behavior?**

When running the CLI we get:
```
Error: Cannot find module '@webpack-cli/serve/lib/startDevServer'
```

**Reason**

When `@webpack-cli/serve@1.5.2` was upgraded from 1.5.1 `startDevServer.ts` was deleted which is why the file is not found: https://github.com/webpack/webpack-cli/compare/@webpack-cli/serve@1.5.1...@webpack-cli/serve@1.5.2

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please fill out all fields, I can't help you, I will reopen when you do it.

Also check `@webpack-cli/serve` should not be installed directly

**Comment by jaipresto** [comment]
Hey @alexander-akait . You've introduced a breaking change in a fix. Is it documented somewhere that @webpack-cli/serve should not be installed directly?

**Comment by jaipresto** [comment]
There is not multiple versions installed. We were using `@webpack-cli/serve/lib/startDevServer` directly.

**Comment by alexander-akait** [comment]
You should not use `@webpack-cli/serve/lib/startDevServer` directly, it is internal

**Comment by jaipresto** [comment]
I think what you are saying is that I should not install `@webpack-cli/serve` directly but I can install `@webpack-cli/serve ` directly but I should not use `@webpack-cli/serve/lib/startDevServer ` directly.

**Comment by alexander-akait** [comment]
We don't have public API for usage, so using something from `@webpack-cli/serve/path/to/file` is not safe and never was safe
