### ISSUE TITLE
Feature: Init transformations

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack-cli#29]
**Do you want to request a *feature* or report a *bug*?**
Feature - `webpack --init` should kickstart a volley of inquirer questions. Each of the questions will be backed by a transformer. Each transformer will be transforming a single AST. When the end of questions is reached, the AST will be pretty printed to source code of the webpack config.

**What is the current behavior?**
Does not exist

**If the current behavior is a bug, please provide the steps to reproduce.**
Does not exist

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
Initial development

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

WIP - project structure for the same.

**Comment by DanielaValero** [comment]
We should also add here an explicit task to run a validation of the generated config, so we ensure that everything is going to work fine for the user.

Also, would be nice when we could optionally generate webpack 1 and/or webpack 2 configs

**Comment by ev1stensberg** [comment]
I think this is resolved of #105 , reopen if needed.
