### ISSUE TITLE
configuration has an unknown property '_assetEmittingPreviousFiles'

### ISSUE THREAD

**Issue by LechLee** [webpack/webpack-cli#2902]
**Describe the bug**

Hi, im hitting 'configuration has an unknown property '_assetEmittingPreviousFiles' when running webpack serve

**What is the current behavior?**

I suspect the issue is with **@webpack-cli/serve** version 1.5.2
as i have reverted to version 1.5.1 at package-lock.json and is working fine

**To Reproduce**
package.json:
`
{
  "name": "webpack",
  "version": "1.0.0",
  "description": "A webpack config",
  "main": "index.js",
  "scripts": {
    "start": "webpack serve"
  },
  "devDependencies": {
    "webpack": "^5.28.0",
    "webpack-cli": "4.7.2",
    "webpack-dev-server": "4.0.0-beta.2"
  }
}

`
webpack.config.js:
`
const path = require('path')

module.exports = {
	entry: {
		main: './src/js/index.js',
		styles: './src/css/main.css',
	},
	output: {
		path: path.join(__dirname, 'public'),
		filename: '[name].[contenthash].js',
	},
	plugins: [],
}

`

**Expected behavior**

able to run webpack server

**Screenshots**
![Screenshot 2021-08-18 at 3 07 49 PM](https://user-images.githubusercontent.com/10540170/129854103-c5a5c883-198a-4b9f-acbd-fba849055435.png)

**Comment by snitin315** [comment]
Please try with `webpack-dev-server@4.0.0-rc.1` and webpack-cli 4.8.0

**Comment by LechLee** [comment]
> Please try with webpack-dev-server@4.0.0-rc.1 and webpack-cli 4.8.0

This is working

**Comment by echarles** [comment]
> Please try with webpack-dev-server@4.0.0-rc.1 and webpack-cli 4.8.0

This is working also for me. Thx!
