### ISSUE TITLE
Option --allowed-hosts all incorrectly parsed that lead to ignoring it by Server

### ISSUE THREAD

**Issue by maksimr** [webpack/webpack-cli#2909]
STR:
- `node@v14.15.3`
-  Install webpack-dev-server`npm install --save-dev webpack webpack-dev-server webpack-cli @webpack-cli/serve`
- Run `webpack serve --mode development --allowed-hosts all`

ER:  `allowedHosts: 'all'`
AR: `allowedHosts: ['all']`

This lead to [ignoring this option by Server](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L1516-L1518)

And visual error `Invalid Host header`

package.json
```json
{
  "main": "src/jindex.js",
  "scripts": {
    "test": "webpack serve --mode development --allowed-hosts all"
  },
  "devDependencies": {
    "@webpack-cli/serve": "^1.5.2",
    "webpack": "^5.51.1",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^4.0.0"
  }
}
```

**Comment by anshumanv** [comment]
You don't need `@webpack-cli/serve` in your deps can you try removing that and try? we normalize the option [https://github.com/webpack/webpack-dev-server/blob/f563d1d13eed75744cca2911878352581afa6a03/lib/Server.js#L198](https://github.com/webpack/webpack-dev-server/blob/f563d1d13eed75744cca2911878352581afa6a03/lib/Server.js#L198) so it shouldn't have been \`\['all'\]\`

**Comment by maksimr** [comment]
@anshumanv result the same without serve as dep.  normalize in Server.js normalize string to array but here we have a case when `allowedHosts` passed as array with string  only one string`all` and server expect that `all` would not be in the array.

This option converted to array here - https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/lib/webpack-cli.js#L317
And set to passed Server options object [here](https://github.com/tj/commander.js/blob/master/lib/command.js#L550) in the commander lib

**Comment by anshumanv** [comment]
Thanks for the investigation, yep it's an issue

I'll fix it :crossed\_fingers:

**Comment by anshumanv** [comment]
I've done a potential fix [here](https://github.com/webpack/webpack-dev-server/pull/3720), I'll wait for feedback from @alexander-akait to validate the fix and then get it merged :+1:
