### ISSUE TITLE
webpack-cli init command error

### ISSUE THREAD

**Issue by dhruvdutt** [webpack/webpack-cli#291]
**webpack-cli version**

Latest tree. (2.0.9) Using symlink.

**What is the current behavior?**

Using `webpack-cli init` with mostly default recommended options.

![screenshot_20180227_032131](https://user-images.githubusercontent.com/5961873/36697566-7481ea48-1b6d-11e8-992b-407afc920115.png)

After all dependencies are installed, I get this error:

![image](https://user-images.githubusercontent.com/5961873/36697623-a31b13d4-1b6d-11e8-892a-f70de0bd532d.png)

Generated package.json

![image](https://user-images.githubusercontent.com/5961873/36697704-dabb0df8-1b6d-11e8-8494-a02291fc195c.png)

**Steps to reproduce**
```bash
mkdir test-dir && cd test-dir;
mkdir src && touch src/index.js;
webpack-cli init
```

**What is the expected behavior?**

`webpack-cli init` should run and create a webpack project with a config file.

**Comment by SolarLiner** [comment]
Can confirm on Ubuntu 17.10 - webpack-cli fails at the last moment with the same error.

Makes webpack-cli useless to me :man_shrugging:

**Comment by ev1stensberg** [comment]
I'll have a look at this tomorrow, our fork isn't cooperating :(

**Comment by kawasako** [comment]
Hi. I also experienced this problem. In my opinion, maybe, this change is the cause. https://github.com/webpack/webpack-cli/commit/0b4269c7eb25c61908cf2aa56b23eb017036dd28#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Since yoeman-environment refers to youeman-generator, I think that behavior has changed with this change.

**Comment by dhruvdutt** [comment]
@kawasako `yeoman-environment` [doesn't](https://github.com/yeoman/environment/blob/master/package.json) have any [peerDependency](https://nodejs.org/en/blog/npm/peer-dependencies/) for `yeoman-generator` so there aren't any issues with namespacing.

**Comment by kawasako** [comment]
@dhruvdutt your right. (I'm sorry) I studied further in detail, The real cause is that `webpack-fork-yeoman-generator` is published from master branch. There is no implementation of `getArgument` here. https://github.com/ev1stensberg/generator/blob/master/package.json#L2

**Comment by dhruvdutt** [comment]
@kawasako Yeah, I think that could be an issue as well.
Can you try my PR #294 or [branch](https://github.com/dhruvdutt/webpack-cli/tree/fix%2Fyeoman) locally and test if it's working? I don't think we need a separately published fork if this one works.

**Comment by kawasako** [comment]
@dhruvdutt I tested it. It seems to work well about `webpack-cli init`.

**Comment by dhruvdutt** [comment]
Awesome. :rocket:

**Comment by williamnerdy** [comment]
I have the same problem

**Comment by justerest** [comment]
I have the same problem

**Comment by dhruvdutt** [comment]
@ev1stensberg The `init` command is broken on our latest published version. :cry: 

Can you please test and review #294 or else we will have to find some other fix.

**Comment by justerest** [comment]
it fixs the problem but I just use v2.0.7 now

**Comment by ev1stensberg** [comment]
`webpack-cli v.2.0.10` should fix this. Publishing in a few hours

**Comment by dhruvdutt** [comment]
[`2.0.10`](https://www.npmjs.com/package/webpack-cli) is released with the fix. :fire:

@SolarLiner @kawasako @williamnerdy @justerest 
Please test and let us know if you still have any issues. :100:
