### ISSUE TITLE
filesystem cache corruption on SIGINT

### ISSUE THREAD

**Issue by AprilArcus** [webpack/webpack-cli#2918]
If webpack-cli is terminated by SIGINT while writing to the filesystem cache (e.g. in watch mode during an incremental rebuild of a project with large external source maps), the filesystem cache will be corrupted and must be erased before webpack will build again.

webpack-cli should [hook `SIGINT`](https://nodejs.org/api/process.html#process_signal_events) and await a clean exit from [compiler.close](https://webpack.js.org/api/node/#compiler-instance).

Note that the child processes spawned by e.g. `fork-ts-checker-webpack-plugin` or `thread-loader` will hear SIGINT from the parent process, so they'll need to be isolated by spawning the compiler into a detached child process.

**Comment by snitin315** [comment]
I will fix it.

**Comment by snitin315** [comment]
It should be added here, right?

https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/lib/webpack-cli.js#L2057

```js
      process.on("SIGINT", () => {
        compiler.close();
      });
```

**Comment by alexander-akait** [comment]
Here https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/lib/webpack-cli.js#L2029

**Comment by alexander-akait** [comment]
Here https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/lib/webpack-cli.js#L2122 and also here https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/lib/webpack-cli.js#L2135

**Comment by AprilArcus** [comment]
Don't lock

**Comment by alexander-akait** [comment]
Sorry for long fix :disappointed:
