### ISSUE TITLE
Cannot find sibling packages when using npm workspaces

### ISSUE THREAD

**Issue by codyebberson** [webpack/webpack-cli#2922]
_(Probably low priority, but documenting for anyone else who encounters it)_

When using [npm workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces), `webpack-cli` does not recognize when sibling projects are not equally hoisted.

For example:
```
root
 +- node_modules
     +- webpack-cli
 +- packages
     +- project1
     +- project2
         +- node_modules
             +- webpack
             +- webpack-dev-server
```

Current behavior: The output of `webpack serve` is:

```
[webpack-cli] For using 'serve' command you need to install: 'webpack-dev-server' package
[webpack-cli] Would you like to install 'webpack-dev-server' package? (That will run 'npm install -D webpack-dev-server') (Y/n)
```

Expected behavior:  `webpack serve` recognizes the folder structure and is able to find `webpack-dev-server`.

There is a simple workaround, to add all webpack dependencies to the root package.json.

I believe the bug is in [package-exists.js](https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/lib/utils/package-exists.js):

```javascript
function packageExists(packageName) {
  if (process.versions.pnp) {
    return true;
  }

  let dir = __dirname;

  do {
    try {
      if (fs.statSync(path.join(dir, "node_modules", packageName)).isDirectory()) {
        return true;
      }
    } catch (_error) {
      // Nothing
    }
  } while (dir !== (dir = path.dirname(dir)));

  return false;
}
```

The method assumes `__dirname` is the start directory and walks upward.  That assumption is incorrect.

System details:

```
$ npm --version
7.20.3

$ node --version
v16.6.1

$ npx webpack-cli info

  System:
    OS: Windows 10 10.0.19043
    CPU: (20) x64 Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
    Memory: 18.27 GB / 31.91 GB
  Binaries:
    Node: 16.6.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.20.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.78)
    Internet Explorer: 11.0.19041.906
  Packages:
    webpack: 5.51.1 => 5.51.1
    webpack-cli: 4.8.0 => 4.8.0
    webpack-dev-server: 4.0.0 => 4.0.0
```

**Comment by alexander-akait** [comment]
Please open an issue in `npm`, we use `require`/`import()`, no magic here

**Comment by alexander-akait** [comment]
oh, my mistake, I see the problem

**Comment by rishabh3112** [comment]
`process.cwd()` seems to be a valid assumption on first glance. Will work on to fix this.

**Comment by alexander-akait** [comment]
@codyebberson What is place where you run `webpack serve`?

**Comment by codyebberson** [comment]
@alexander-akait In the example above, it would be in `packages/project2`.

Using `process.cwd()` should fix that case, but might break the opposite case (i.e., from the root directory, running `npm run dev --workspace packages/project2`).

**Comment by alexander-akait** [comment]
@codyebberson 

> In the example above, it would be in packages/project2.

expected, even `require`/`import` will not work with this, you need move all deps on top level and install each webpack-dev-server/webpack-cli/webpack in each package

Example:

**node_modules/package/index.js**

```js
const anotherPackage = require('another-package');
```

`another-package` should be in `node_modules`, not in `packages/project2/node_modules/another-package`

**Comment by codyebberson** [comment]
> you need move all deps on top level

Yes, as mentioned, that is what I did, and it solved the problem.  The "fix" to this might simply be documentation.  

My reason for filing the bug was that I received the error message "For using 'serve' command you need to install: 'webpack-dev-server' package", even though I already had `webpack-dev-server` installed in that project.  That's confusing.  

> or install each webpack-dev-server/webpack-cli/webpack in each package

This option is more tricky.  In my specific example, it was a transitive dependency that hoisted `webpack-cli`.  But, because the transitive dependency used a different version of `webpack`, it was *not* hoisted.  

It might just be easier and cleaner to recommend moving all webpack related deps to top level.

> expected, even `require`/`import` will not work with this

In my case, did not use `require` or `import`.  I was only using the command line utilities.

**Comment by alexander-akait** [comment]
@codyebberson 

> In my case, did not use require or import. I was only using the command line utilities.

But this logic emulate `require`/`import`, I want to say it works as expected

**Comment by alexander-akait** [comment]
Tested right now:
- `npm run serve --workspace packages/project2` works fine (`"serve": "webpack server"` on `package.json`)
- go to `packages/project2` and run `npm run serve` works fine (`"serve": "webpack server"` on `package.json`)
- go to `packages/project2` and run `webpack serve` works fine (`"serve": "webpack server"` on `package.json`)

npm doesn't install deps on package level, they are hoisted to top `node_modules`, so `__dirname` works fine and always found `webpack-dev-server` and `webpack`, check it - go to `node_modules` and you should found `node_modules/webpack`, `node_modules/webpack-cli`/`node_modules/webpack-dev-server`, you may have accidentally installed dependencies at the package level (I think `npm` should warn about that), I tried it with fresh repo and all works fine, even more, our logic based on Node.js logic, look at here https://github.com/nodejs/node/blob/master/lib/internal/modules/cjs/loader.js#L701 and https://github.com/nodejs/node/blob/master/lib/internal/modules/cjs/loader.js#L870, so I can't reproduce even...

Feel free to feedback or please create example of a problem

**Comment by beaucollins** [comment]
In fact, `webpack info` finds the `webpack-dev-server` just fine.

```
npx -w packages/web_app webpack info

  System:
    OS: Linux 5.10 Alpine Linux
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.17 GB / 7.77 GB
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.24.0 - /usr/local/bin/npm
  Packages:
    webpack-dev-server: ^4.3.1 => 4.3.1 
```

`webpack-cli` shouldn't try to implement it's own special algorithm for resolving packages.
