### ISSUE TITLE
This happens when I use `npx webpack init`. I worked around it by doing `./node_modules/bin/webpack init`.

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack-cli#2944]
This happens when I use `npx webpack init`. I worked around it by doing `./node_modules/bin/webpack init`.

_Originally posted by @volkanunsal in https://github.com/webpack/webpack-cli/issues/191#issuecomment-916912387_

**Comment by alexander-akait** [comment]
Just run `npx webpack init` on new package

**Comment by alexander-akait** [comment]
@webpack/cli-team we need to rename `@webpack-cli/init` to `create-webpack-app` package, also it should work without `webpack-cli` itself, i.e. we should move `commander` and other API inside `create-webpack-app` package also fix docs everywhere, because `npx webpack init` and `npx webpack-cli` doesn't work

**Comment by anshumanv** [comment]
On it

**Comment by alexander-akait** [comment]
Still valid

**Comment by rishabh3112** [comment]
It's been two months now, so I am taking this up.

**Comment by rishabh3112** [comment]
WIP: https://github.com/webpack/webpack-cli/pull/3036

**Comment by adriancuadrado** [comment]
Any progress on this?

**Comment by abrehan2** [comment]
Hello Sir @snitin315,

I bring with me extensive expertise in full-stack development and open-source contributions, including the publication of my own npm packages. I am eager to tackle some starter bugs; could you kindly point me in the right direction? ;)

Best regards,
Rehan

**Comment by snitin315** [comment]
@MysteryHawk17 @abrehan2 Let's use Discord for introductions & questions and avoid commenting on issues.

**Comment by abrehan2** [comment]
> @MysteryHawk17 @abrehan2 Let's use Discord for introductions & questions and avoid commenting on issues.

Sure! Can you please share the link?

**Comment by MysteryHawk17** [comment]
@snitin315 please share the discord link to connect

**Comment by samrudh3125** [comment]
@snitin315 please share the dicord connect link

**Comment by urizennnn** [comment]
Hello guys I would love to work on this topic as it seems quite intuitive. Here are my questions on this , what are the targeted languages for this  like the main languages one would like to create a boiler code for and also if there should be an other option if the developer just wants to create something else but still use the webpack bundler

**Comment by c6z3h** [comment]
@samrudh3125 I tried clicking on the discord link but it seems expired or have no permission, is there an updated link maybe?

**Comment by urizennnn** [comment]
> @samrudh3125 I tried clicking on the discord link but it seems expired or have no permission, is there an updated link maybe?

You can use this link to join https://discord.gg/emmqK9eAyx
