### ISSUE TITLE
webpack-cli init does not find webpack

### ISSUE THREAD

**Issue by wernert** [webpack/webpack-cli#2952]
**Describe the bug**

webpack-cli does not find installed webpack

**What is the current behavior?**

**To Reproduce**

make a new folder
_npm init_ + accept defaults
_npx webpack-cli init_

![image](https://user-images.githubusercontent.com/4059844/133448072-14ff9111-89fd-4a09-a112-9004c49182b2.png)

Also after multiple runs where webpack is clearly installed from before the same error occurs
Same on powershell and git bash
same error also on run _npx webpack-cli info_

OS: windows 10 home
node v14.15.5
npm 6.14.11

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack-cli/issues/2944
