### ISSUE TITLE
Migrate to new API in Colorette 2.0.x

### ISSUE THREAD

**Issue by kibertoad** [webpack/webpack-cli#2955]
Currently webpack-cli relies on modifying global state, which potentially results in affecting other parts of the code that might rely on Colorette as well.

**Describe the solution you'd like**

https://github.com/jorgebucaran/colorette/issues/70

**Additional context**

You can see how we migrated pino-pretty to a new API here: https://github.com/pinojs/pino-pretty/pull/230

**Comment by alexander-akait** [comment]
PR welcome, should not be hard to migrate

**Comment by kibertoad** [comment]
On it.

**Comment by ai** [comment]
If you do not want to add `createColors` call (`colorette` new API requires this call, exports like `red` do not have color auto-detection anymore) you can use [`nanocolors`](https://github.com/ai/nanocolors).

The same 0 dependencies, same `colorette 1.x` API, better loading time ([benchmark](https://github.com/ai/nanocolors#benchmarks)). `nanocolors` will be used in PostCSS, Autoprefixer, and Browserslist if you want to sync tools and reduce `node_modules` size a little.

**Comment by alexander-akait** [comment]
Yep, sounds good too

**Comment by ai** [comment]
I can prepare PR tomorrow to compare code changes
