### ISSUE TITLE
devServerFlags missing in webpack-dev-server. 

### ISSUE THREAD

**Issue by Pranay365** [webpack/webpack-cli#2967]
**Describe the bug**

 I have a build script in my package.json file to server my front-end with webpack-dev-server.
"scripts": {  "build": "webpack serve --open" }
  When I run the npm run build command it throws the error devServerFlags is not iterable in the file webpack-cli/bin/serve. Actually the "devServerFlags" is not present in webpack-dev-server/bin/cli-flags. So the require('webpack-dev-server/bin/cli-flags').devServerFlags will return undefined and hence not iterable.

**What is the current behavior?**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please paste the results of `npx webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by jasperkuperus** [comment]
If you happen to walk into this error like I did, you've probably updated your `webpack-dev-server` dependency and forgot to update your `webpack-cli` dependency. Updating `webpack-cli` as well solved this for me.
