### ISSUE TITLE
Unknown --env option on Webpack 5 and Webpack-cli 4

### ISSUE THREAD

**Issue by Slava96** [webpack/webpack-cli#2973]
I am using webpack from Gradle build on my Kotlin multiplatform project. When I try to run it as part of my build, my webpack task failed with error.
Before I am using Webpack version 4.44.1, Node version 12.16.1, webpack-cli 3.3.12

`
[webpack-cli] Error: Unknown option '--env ENV=LOCAL '
[webpack-cli] Run 'webpack --help' to see available commands and options
` 
I found webpack command that performed:
`
C:\...\nodejs\node-v14.15.5-win-x64\node.exe C:\...\node_modules\webpack\bin\webpack.js --env ENV=LOCAL --config C:\...\webpack.config.js
`
Why --env is not work? Because documentation says that Webpack supports it.

Versions:
**Node** - 14.15.5
**Webpack** - 5.35.0
**Webpack-cli** - 4.6.0
**Webpack-dev-server** -  4.0.0-beta.2

**Comment by snitin315** [comment]
--env works for me. Please provide a repo to reproduce the error. Also try installing tge latest version of webpack-cli and webpack-dev-server.

**Comment by Slava96** [comment]
https://github.com/Slava96/kmm-test
I have this repository

**Comment by alexander-akait** [comment]
Invalid usage https://github.com/Slava96/kmm-test/blob/master/build.gradle.kts#L114, separate it

**Comment by Slava96** [comment]
Don't understand. Separate it?

**Comment by alexander-akait** [comment]
Yes, each argument should be separately, error message - `--env ENV=LOCAL ` say about it
