### ISSUE TITLE
Feature: Migrate current webpack cli from webpack to webpack-cli

### ISSUE THREAD

**Issue by DanielaValero** [webpack/webpack-cli#30]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The cli options from webpack exist in our repo, but have not been yet adapted to our new code design.

**What is the expected behavior?**
* All the webpack cli options are functional and tested in webpack-cli
* The code is adapted to the webpack-cli code design

**If this is a feature request, what is motivation or use case for changing the behavior?**
In order to have a unified place where to find all the cli options of webpack, all the webpack cli commands should belong to the webpack-cli repo

Relates to: #25

**Comment by ev1stensberg** [comment]
>The cli options from webpack exist in our repo, but have not been yet adapted to our new code design.

Elaborate some more please.

**Comment by ev1stensberg** [comment]
Fixed in #40 I assume, bugfixes left.
