### ISSUE TITLE
Web fails if it doesn't recognize my package manager

### ISSUE THREAD

**Issue by pauldraper** [webpack/webpack-cli#3044]
**Describe the bug**

**What is the current behavior?**

If I don't have an executable on by PATH that is npm, yarn, or pnpm with a suitable `--version` flag, webpack cli complete fails.

**To Reproduce**

Install webpack.

Remove npm, yarn, and pnpm from PATH if necessary.

Run `webpack --config webpack.config.js`.

**Expected behavior**

I expected webpack to not fail.

**Screenshots**

```
[webpack-cli] No package manager found.
```

**Additional context**

I'm really curious why webpack needs to interact with my package manager.

**Comment by alexander-akait** [comment]
It needs for other commands, why you don't have package manager? You need more complex setup for webpack to avoid problems

**Comment by pauldraper** [comment]
I have a package manager, it's just not npm, yarn, or pnpm.

This world has many, many package managers.

**Comment by alexander-akait** [comment]
Make sense, I will look at the problem

**Comment by alexander-akait** [comment]
@pauldraper Can you provide version of `webpack-cli`, it looks like it was fixed in https://github.com/webpack/webpack-cli/releases/tag/webpack-cli%404.9.0, I can't reproduce thje problem locally

**Comment by pauldraper** [comment]
Thanks for fast response. I am using 4.9.0.

I have discovered there are some other conditions necessary. Namely, the baby-module-resolution in `checkPackageExists` has to fail:

```
  checkPackageExists(packageName) {
    if (process.versions.pnp) {
      return true;
    }

    let dir = __dirname;

    do {
      try {
        if (fs.statSync(path.join(dir, "node_modules", packageName)).isDirectory()) {
          return true;
        }
      } catch (_error) {
        // Nothing
      }
    } while (dir !== (dir = path.dirname(dir)));

    return false;
  }
```

Looks like someone even added an exception for those PnP weirdos.

There are a couple of ways this can fail. One is anybody mucking with Node.js internals, like PnP does. Another is for modules found in NODE_PATH differently than webpack-cli.

----

I would suggest two changes:

1. `checkPackageExists` should use `require.resolve`. (Unless webpack is loading ES modules....require.resolve doesn't work for those, but AFAIK it isn't.)

2. The output of `doInstall` should return something useful like `dependency X not found` regardless of whether it recognizes the available package managers.

**Comment by alexander-akait** [comment]
> checkPackageExists should simply use require.resolve. (Unless webpack is loading ES modules....require.resolve doesn't work for those, but AFAIK it isn't.) That would even remove the need for the PnP check.

Sorry, it is impossible, due bug in Node.js

Please provide reproducible test repo, we even run this code when you run webpack command

**Comment by willtrking** [comment]
I'm running into this problem as well. In our case we're using a pretty custom setup in a Bazel monorepo.

I'm currently hacking around this with a post-install patch to webpack-cli. It would be nice if there was an environment variable or something we could use to set this to the proper path.

**Comment by alexander-akait** [comment]
@willtrking Please read my message above, we don't run nothing special for package managers when you run `webpack`/`webpack build`/`webpack serve`/etc so you should not get this problem, check your version

**Comment by pauldraper** [comment]
Any command with dependencies runs `checkPackageExists`, including `webpack build`.

https://github.com/webpack/webpack-cli/blob/6a9aac99665f0d2f2f0c58c757c6befbc7734c8f/packages/webpack-cli/lib/webpack-cli.js#L929

---

I ran into this because I am mucking with require.resolve/Module._resolveFilename, and this check accesses the file system directly.

My workaround is to fake the existence of PnP (causing Webpack to abort the check entirely).

*skip-package-check.js*

```
Object.defineProperty(process.versions, "pnp", {
  get() {
    if (new Error().stack.includes("checkPackageExists")) {
      return "bazel";
    }
    return undefined;
  },
});
```

Then add `-r skip-package-check` to Node.js options.

**Comment by willtrking** [comment]
Hey @alexander-akait thanks for the info! You're correct, in my case the error was being thrown because webpack-cli wasn't able to resolve webpack, which was an issue specific to our setup. Fixed that + removed the postinstall patch and all is well

**Comment by alexander-akait** [comment]
@pauldraper 

> Any command with dependencies runs checkPackageExists, including webpack build.

But we don't run `checkPackageExists` for `webpack build`, all commands are lazy loaded and executed only when you specify them and run.

I am really can't reproduce your problem, I tried - docker without any package managers and it still work without any problems. Can you provide steps to reproduce?

**Comment by pauldraper** [comment]
While I think I could repro it, I think this is uncommon, and I now understand how this works better.
