### ISSUE TITLE
Many devDependencies listed as dependencies

### ISSUE THREAD

**Issue by billyjanitsch** [webpack/webpack-cli#306]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Many devDependencies of this project are listed as dependencies in package.json such as [prettier](https://github.com/webpack/webpack-cli/blob/3aabdf473b79dcd2238291fee961851df7f6a7cd/package.json#L102) and [codecov](https://github.com/webpack/webpack-cli/blob/3aabdf473b79dcd2238291fee961851df7f6a7cd/package.json#L84). This causes them to be installed when a user installs webpack-cli.

There are also some dependencies that don't appear to be used at all, such as [global](https://github.com/webpack/webpack-cli/blob/3aabdf473b79dcd2238291fee961851df7f6a7cd/package.json#L89).

If a dependency isn't needed at runtime, it shouldn't be listed in dependencies. 

**What is the expected behavior?**

Only the dependencies necessary to run webpack-cli are installed alongside it.

**If this is a feature request, what is motivation or use case for changing the behavior?**

webpack-cli is currently a _huge_ install (~66mb). It would be nice to cut down on the dependencies it requires, especially since this project is now required to interact with webpack via CLI.

**Comment by olore** [comment]
Relatedly (?) the inclusion of the following is erroring on my build servers because of proxy issues and what not.

```
 "yeoman-generator": "github:ev1stensberg/generator#Feature-getArgument"
```

Is there a plan to get this into a published npm package soon? Can I help? /ping @ev1stensberg

**Comment by ematipico** [comment]
About the local fork, we have an open issue here #161 

About the dependencies, it would be nice to have a PR. It shouldn't be too difficult. Help is appreciated!

**Comment by olore** [comment]
Thanks @ematipico. Not sure how I missed that one.

Looks like there is already a PR for the dependencies from @billyjanitsch https://github.com/webpack/webpack-cli/issues/309
