### ISSUE TITLE
Documentation shows incorrect options for webpack serve

### ISSUE THREAD

**Issue by fires3as0n** [webpack/webpack-cli#3083]
**Describe the bug**
Documentation here https://github.com/webpack/webpack-cli/blob/master/SERVE-OPTIONS-v4.md says that to disable live reload you should use --no-live-reload flag but webpack server refuses to accept it.

**What is the current behavior?**
Error: Unknown option '--no-live-reload'

**To Reproduce**
Execute the command
`webpack serve --no-live-reload`

**Expected behavior**
Webpack dev server should accept the argument provided in the documentation and disable live reload

**Comment by snitin315** [comment]
What is your webpack-dev-server version?

**Comment by fires3as0n** [comment]
```
"webpack": "^5.0.0",
 "webpack-cli": "^4.7.2",
 "webpack-dev-server": "^3.11.2"
```
I have checked documentation for v3 at:  https://github.com/webpack/webpack-cli/blob/master/SERVE-OPTIONS-v3.md
And it says that for v3 flag should be --liveReload instead
It does not crash when using this flag but still with or without it it still auto realods, thus not working as well.
