### ISSUE TITLE
Git repository missing v2.0.5 through v2.0.10 tags

### ISSUE THREAD

**Issue by andersk** [webpack/webpack-cli#310]
The latest Git tag here is v2.0.4. I believe the following tags belong at

* v2.0.5 94ac6dbbc50027184c6b32aa496b8ba3157ff0dc
* v2.0.6 4333088e5f224a5987263ad0d01580c045327696
* v2.0.7 81a9f1ee0ac3c42931e20cd51470fe1f4c17c9be or a1652699a418a4ca2b69b263842d3ba045ac535b
* v2.0.8 94069128585d49241857dbf7353523be0acec266
* v2.0.9 4cf5e172d65eed39acc5da6b9bfd6dd3db8923f9
* v2.0.10 7dedf2e40e6c9a3f084a0834aa2039f2d1c0e678

**Comment by ematipico** [comment]
Will take care of it by the end of the day!

**Comment by ev1stensberg** [comment]
awesome, thank you so much @ematipico :heart:

**Comment by ematipico** [comment]
This is now done!

**Comment by ev1stensberg** [comment]
Awesome work @ematipico ❤️
