### ISSUE TITLE
Sub depencency probably removed. Install fails.

### ISSUE THREAD

**Issue by JonWallsten** [webpack/webpack-cli#311]
I'm trying to update webpack-cli from 2.0.9 -> 2.0.10.
PS C:\Users\me\repo\web-app-angular> npm install webpack webpack-cli
npm ERR! code E404
npm ERR! 404 Not Found: @sindresorhus/is@^0.7.0

npm i @sindresorhus/is
npm ERR! code E404
npm ERR! 404 Not Found: @sindresorhus/is@latest

Can someone else check if it's actually missing or if "it doesn't work on my machine"

**Comment by ev1stensberg** [comment]
Can you print the entire stack trace which is not (if) confidential?

**Comment by dhruvdutt** [comment]
Can you print full error log or maybe link the repo? It is unclear from this what is happening.

**Comment by JonWallsten** [comment]
Sure, hang on!

**Comment by montogeek** [comment]
Post your package.json as well please

**Comment by ev1stensberg** [comment]
Not needed, stack trace is enough

**Comment by montogeek** [comment]
2.0.9 does not exists, neither 2.0.10.
But they will later today https://github.com/webpack/webpack-cli/issues/310

**Comment by JonWallsten** [comment]
It's just the git tags missing, not the packages I assume?

**Comment by dhruvdutt** [comment]
GitHub tags don't matter. The library is published on [npm registry](https://www.npmjs.com/package/webpack-cli).

**Comment by JonWallsten** [comment]
I am however stuck on this now:
```
fetchMetadata: sill resolveWithNewModule webpack-cli@2.0.10 checking installable status
``` 
Something is fishy

**Comment by dhruvdutt** [comment]
It would be very convenient to debug if you can make a small zip with minimal things or list steps to reproduce this issue.

**Comment by JonWallsten** [comment]
It doesn't work for my colleague either. So I guess it's our network and/or artifactory. I've tried against both registry.npmjs.org with proxy and our internal artifactory without proxy. I have installed a lot of other modules. Might be a coincident that it was this package that fails. I'll let you guys now as soon as I get home so I can try it outside of the company network.

**Comment by dhruvdutt** [comment]
You can try switching to [mirrors of npm registry](https://docs.npmjs.com/misc/registry#description) and see which works for you.
You can ping the mirrors to check and switch to it inside your npm config.

**Comment by JonWallsten** [comment]
It's just getting worse and worse. Tried the mirror: 
```
pm install webpack-cli@2.0.10
npm ERR! code E401
npm ERR! 404 401 Unauthorized: webpack-cli@2.0.10
```

**Comment by dhruvdutt** [comment]
Make sure you're using **public** mirrors. Use the ones listed in the official [npm docs](https://docs.npmjs.com/misc/registry#description) and not any other private ones which might need authorization.

Double check which is currently active `npm config get registry`.

You can always do `ping registry.npmjs.org` or `ping skimdb.npmjs.com` to check which responds for your network.

If all of this doesn't work then most likely there's some issue specific to your network which might be blocking it. Can you confirm if this is also happening with `webpack-cli` or all packages?

**Comment by JonWallsten** [comment]
It's seems rather random. I'll go ahead and close this. It's obviusly our network. Probably a coincidence that it pointed to webpack-cli.

**Comment by JonWallsten** [comment]
@ev1stensberg 
FYI: after removing package-lock.json I got stuck on a different package. And after a while I finally got an error message:
```
npm ERR! Error while executing:
npm ERR! C:\Users\jway52\AppData\Local\Programs\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/ev1stensberg/generator.git
npm ERR!
npm ERR! ssh: connect to host github.com port 22: Connection timed out
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128 
```

**Comment by JonWallsten** [comment]
So I guess the upgrade to 2.0.10 was the issue after all:
https://github.com/webpack/webpack-cli/commit/514a695be2fcd0b5502f48ab7694293de3c148c5
Is it possible to add the this without messing up for us behind corp firewalls?
`"yeoman-generator": "github:ev1stensberg/generator#Feature-getArgument"´

**Comment by dhruvdutt** [comment]
@JonWallsten I'm not sure if this would help but can you add `--verbose` flag while installing `webpack-cli` and show the output?

Seems like this issue is happening only when behind a proxy, and we might need to publish the fork on npm seperately or remove the fork entirely. Related issue #161

**Comment by JonWallsten** [comment]
I actually solved it a few moments ago.
The proxy I added in the _global git config_ didn't help. Not the proxy in the _.npmrc_ file either. 
What did work however was to add _http_proxy_ and _https_proxy_ as system variables on my local machine. I guess running _git_ through _npm_ happens to slip in between proxy settings.

**Comment by dhruvdutt** [comment]
Interesting. What values did you set for `http_proxy` and `https_proxy` system variables?

Also, can you please close this issue for now? We're already discussing the proxy and fork issue at #161

**Comment by JonWallsten** [comment]
Our corporate proxy servers. I'm just baffled it didn't work with both .npmrc and git config already using them. They are also set under my LAN settings. Still I had to set as system variables. Seems a bit redundant!

**Comment by lgallindo** [comment]
I'm getting a similar error today (error that wasn't there last week), how can I check the availability of a package@version in a mirror by hand (without npm) to check if the error is in my end somehow?

**Comment by ev1stensberg** [comment]
Could you link the stack trace you're getting?

**Comment by lgallindo** [comment]
Ok, I'm on Windows 8.1, just reinstalled the latest nodejs from the official site.

```
C:\>npm --version
5.6.0
C:\>npm ls
C:\
`-- (empty)
c:\npm view connect
npm ERR! code E404
npm ERR! 404 Not Found: connect
npm ERR! 404
npm ERR! 404  'connect' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\******\AppData\Roaming\npm-cache\_logs\2018-05-07T18_40_26_578Z-debug.log
```

This happens for any package, and also for the "install" command. At first I was trying to install webpack-cli.

**Comment by ev1stensberg** [comment]
I don't think this is related to webpack-cli. We don't have a dependency named `connect`, how does your package.json look?
