### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by yang-mengyue** [webpack/webpack-cli#3138]
node: 14.15.4
webpack-cli: 4.9.2

Execute a js file that imports other modules with import, package it and report an error
![@Q9~C{}U A~IV_DD%992ABY](https://user-images.githubusercontent.com/78328465/154457061-d9982354-2778-44a0-9e57-03386f4c2432.png)

When webpack is 4.2.0 can be packed normally。

**Comment by yang-mengyue** [comment]
How to use the latest webpack-cli normally？Thank you！

**Comment by alexander-akait** [comment]
You can't use `import` in commonjs files, there are not problems with webpack, use `.mjs` extension or set `type: "module"` in `package.json`
