### ISSUE TITLE
Smoketests are flaky on CI

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack-cli#3152]
**Describe the bug**

Flaky smoke tests. 

**What is the current behavior?**

Sometimes pass sometimes fail on CI.

**To Reproduce**

- [Fail](https://github.com/webpack/webpack-cli/runs/5354308786?check_suite_focus=true)
- [Pass](https://github.com/webpack/webpack-cli/runs/5369390976?check_suite_focus=true)
- [Pass](https://github.com/webpack/webpack-cli/actions/runs/1892497779)
- [Fail](https://github.com/webpack/webpack-cli/actions/runs/1892491583)

**Expected behavior**

Should not fail randomly.

**Screenshots**
NA

**Please paste the results of `npx webpack-cli info` here, and mention other relevant information**

CI environment.

**Additional context**

Seems specific to windows CI only.

**Comment by alexander-akait** [comment]
Feel free to send a PR
