### ISSUE TITLE
Required git?

### ISSUE THREAD

**Issue by sam-s4s** [webpack/webpack-cli#318]
I'm very confused right now.

Firstly - all I need to do is provide a path to webpack... `webpack --config demo/webpack.config.js`. So it seems very silly that in order to do that I need to install a whole other package for webpack.

Secondly - I can't even install webpack-cli, because it requires git to be installed on my machine (and all of my company's other dev boxed and build boxes, which is not possible).

a) why does webpack-cli require git to be installed at all? This seems like a very bad decision. We have a large pipeline, and no other packages require git to be installed - including webpack itself.

b) the fact that it requires git to be installed is not mentioned anywhere - until npm install throws an error. If this project has such a strange requirement, it should be mentioned in bold text right at the top of the documentation.

Any help or explanations would be greatly appreciated. Thanks!

**Comment by kingdaro** [comment]
[It looks like one of the dependencies is a local fork from git.](https://github.com/webpack/webpack-cli/blob/44517fd28041c671dc2486d062386b7d1f6bbaf1/package.json#L111) If we can, would we be able to resolve the issue after removing this, @ev1stensberg ?

**Comment by ematipico** [comment]
Yeah exactly, you need `webpack-cli` package installed

**Comment by ev1stensberg** [comment]
#323
