### ISSUE TITLE
Webpack init trying to use unsupported extract-text-webpack-plugin

### ISSUE THREAD

**Issue by chrispickford** [webpack/webpack-cli#320]
**Type:** Bug

**What is the current behavior?**

Repro steps here: https://stackoverflow.com/questions/49172495/webpack-init-trying-to-use-unsupported-extract-text-webpack-plugin

 1. `dotnew new web`
 2. `yarn init`
 3. `yarn add --dev webpack webpack-cli`
 4. `webpack init`
 5. `webpack`

*Displays the following error message:*

> (node:19320) DeprecationWarning: Tapable.plugin is deprecated. Use new
> API on '.hooks' instead
> D:\SRC\MISC\WebpackTest\node_modules\webpack\lib\Chunk.js:460
>                 throw new Error(
>                 ^
> 
> Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by
> instanceof Entrypoint instead
>     at Chunk.get (D:\SRC\MISC\WebpackTest\node_modules\webpack\lib\Chunk.js:460:9)
>     at D:\SRC\MISC\WebpackTest\node_modules\extract-text-webpack-plugin\dist\index.js:176:48
>     at Array.forEach (<anonymous>)
>     at D:\SRC\MISC\WebpackTest\node_modules\extract-text-webpack-plugin\dist\index.js:171:18
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\SRC\MISC\WebpackTest\node_modules\tapable\lib\HookCodeFactory.js:24:12),
> <anonymous>:7:1)
>     at AsyncSeriesHook.lazyCompileHook [as _callAsync] (D:\SRC\MISC\WebpackTest\node_modules\tapable\lib\Hook.js:35:21)
>     at Compilation.seal (D:\SRC\MISC\WebpackTest\node_modules\webpack\lib\Compilation.js:881:27)
>     at hooks.make.callAsync.err (D:\SRC\MISC\WebpackTest\node_modules\webpack\lib\Compiler.js:464:17)
>     at _err0 (eval at create (D:\SRC\MISC\WebpackTest\node_modules\tapable\lib\HookCodeFactory.js:24:12),
> <anonymous>:11:1)
>     at _addModuleChain (D:\SRC\MISC\WebpackTest\node_modules\webpack\lib\Compilation.js:749:12)
>     at processModuleDependencies.err (D:\SRC\MISC\WebpackTest\node_modules\webpack\lib\Compilation.js:688:9)
>     at process._tickCallback (internal/process/next_tick.js:150:11)

**What is the expected behavior?**

A freshly initialised project configuration should not throw errors upon build.

**Comment by jamsoft** [comment]
I can confirm that I've reproduced this issue.

**Comment by montogeek** [comment]
We need to use the new version, I could pick this one

**Comment by ev1stensberg** [comment]
yes

**Comment by ev1stensberg** [comment]
Fixed in #323
