### ISSUE TITLE
init command shoult use `src/index.js` as entry module by default

### ISSUE THREAD

**Issue by montogeek** [webpack/webpack-cli#321]
Feature

**What is the current behavior?**
`init` command does not provide a default value for entry module.
```
👉  ./node_modules/.bin/webpack init

ℹ INFO For more information and a detailed description of each question, have a look at https://github.com/webpack/webpack-cli/blob/master/INIT.md
ℹ INFO Alternatively, run `webpack(-cli) --help` for usage info.

? Will your application have multiple bundles? No
? Which module will be the first to enter the application? [example: './src/index']
>> Please specify an answer!
```

**What is the expected behavior?**

`init` command should provide a default value `src/index.js` as entry module following webpack itself approach to zero configuration

**Comment by dhruvdutt** [comment]
Can we discuss this over #315 as it's quite related?

**Comment by ev1stensberg** [comment]
Actually we can leave it blank by default, as 0CJS can handle it

**Comment by ev1stensberg** [comment]
Just want to add that prompting that default is `src/index` is good to make sure users understand we're actually setting defaults.

**Comment by vijaykrishnavanshi** [comment]
Made a PR with this change.

**Comment by vijaykrishnavanshi** [comment]
Doing same for multiple bundle case also would be a good idea. 
Thoughts?

**Comment by EugeneHlushko** [comment]
I am not sure you want to add something that is already default, i actually omited it in one of my PR earlier: https://github.com/webpack/webpack-cli/pull/356/files#diff-1b2b84fcd9935ef62f04b2ffd905d2c6R86
