### ISSUE TITLE
Feature Request: Swap from Lerna to another monorepo tool

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#3227]
**Is your feature request related to a problem? Please describe.**

Lerna is depreciated, so maybe we should swap to another monorepo tool.

- https://github.com/lerna/lerna

**Describe the solution you'd like**

Something like [Nx](https://nx.dev/), pnpm workspaces

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by alexander-akait** [comment]
We can use built-in workspace feature in npm/yarn and avoid extra packages

**Comment by alexander-akait** [comment]
I think we can close it, because lerna is not deprecated anymore
