### ISSUE TITLE
Documentation: Revise README 

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#327]
**What is the current behavior?**
The `README.md` says:
>>  For the time being, it is backwards-compatible with the CLI included in webpack itself.

The old CLI is removed in webpack, so that's inconsistent.

**What is the expected behavior?**
You can either revise the comment to say that the old CLI arguments is kept, or remove the line (preferable).

## Important

**This ticket is limited to first-time contributors only**

**Comment by dhruvdutt** [comment]
I would have qualified a couple of weeks ago. :smile: 
@Symphoria you wanna crack this up?

**Comment by bitpshr** [comment]
Happened to be looking at the <kbd>[Good First Contribution](https://github.com/webpack/webpack-cli/labels/Good%20First%20Contribution)</kbd> label a few minutes after this issue was created, so I grabbed it.
