### ISSUE TITLE
webpack-cli is 78 mb large package with transitive dependencies

### ISSUE THREAD

**Issue by ankurk91** [webpack/webpack-cli#330]
Hi,

Just upgraded to webpack v4.x and came to know that also need to install `webpack-cli`.
Then i see a big increment on `node_modules` size on hard disk.

See screenshot -
![screenshot from 2018-03-10 11 38 48](https://user-images.githubusercontent.com/6111524/37238973-f12d182c-2457-11e8-8105-79dd3b18f277.png)

Combining webpack 4 + cli takes around 100 mb compared to 33 mb in webpack 3.x

### Platform info
* elementary OS 0.4.1 Loki x64
* node 9.5.0 
* npm 5.6
* yarn 1.5.1
* webpack 4.1.1
* webpack-cli 2.0.11

**Comment by ev1stensberg** [comment]
See #261 for work on this. Discussion over there 👍
