### ISSUE TITLE
init command creates invalid config with multiple bundles

### ISSUE THREAD

**Issue by jevan0307** [webpack/webpack-cli#331]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
When "webpack-cli init" creates config with multiple bundles, the location you input for the entry files are not outputted as string literals in the config and causes error.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
$ webpack-cli init

.... skip

? Will your application have multiple bundles? Yes
? Type the names you want for your modules (entry files), separated by comma [example: 'app,vendor'] a,b
? What is the location of "a"? [example: "./src/a"] ./src/a
? What is the location of "b"? [example: "./src/b"] ./src/b
? Which folder will your generated bundles be in? [default: dist]: dist
? Are you going to use this in production? No
? Will you be using ES2015? No
? Will you use one of the below CSS solutions? SASS
? If you want to bundle your CSS files, what will you name the bundle? (press enter to ski p)
? Name your 'webpack.[name].js?' [default: 'config']: multi
.... skip

Congratulations! Your new webpack configuration file has been created!

WARNING: Could not apply prettier to D:\repo\test\webpack.multi.js due validation error, but the file has been created
```

There is a warning indicates that the created code has a validation error, and here is the output:
```
...
module.exports = {
  entry: {
    a: ./src/a.js,        // <------- it should be a string literal
    b: ./src/b.js        // <------- it should be a string literal
  },

  output: {
    filename: '[name].[chunkhash].js',
    chunkFilename: '[name].[chunkhash].js',
    path: path.resolve(__dirname, 'dist')
  },

  module: {
    rules: [{
      test: {},

      use: [{
        loader: 'style-loader'
      }, {
        loader: 'css-loader'
      }, {
        loader: 'sass-loader'
      }]
    }]
  },

  plugins: [new UglifyJSPlugin()]
}
```

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
webpack-cli v2.0.11

**Comment by ev1stensberg** [comment]
You can pass it whatever you'd like, look at the example provided.

**Comment by dhruvdutt** [comment]
You'll need to use quotes in the answer explicitly.

As an enhancement, we could also do it if the quotes are not present.
@ev1stensberg, should we add this to #315?

**Comment by ev1stensberg** [comment]
With quotes = string, without = function or whatever, so we can't change that.

**Comment by jevan0307** [comment]
Yes, but only single quote is valid and it is not what the example hint us.
I am wondering why to make it different from how we create with single entry.

**Comment by ev1stensberg** [comment]
It does. "example" is a quote, yes? It's how the ast transform is built up, we can't parse functions if we parse them as functions. See: https://github.com/ev1stensberg/webpack-addons-demo#important-with-string-values-you-need-to-wrap-your-strings-once-again-this-is-because-we-can-declare-some-other-functionality-using-only---while--mystring--resolves-to-a-string
