### ISSUE TITLE
new option to terminate with non-zero code if builded with warnings

### ISSUE THREAD

**Issue by vankop** [webpack/webpack-cli#3315]
**Is your feature request related to a problem? Please describe.**

related to https://github.com/webpack/webpack/issues/15960#issuecomment-1168468320

**Describe the solution you'd like**

One possible solution could be - add an option to terminate process with non-zero code if any warning exist. e.g. `--strict` option ( `false` by default )

**Describe alternatives you've considered**

**Additional context**

**Comment by vankop** [comment]
@alexander-akait any other "naming" ideas?

**Comment by sokra** [comment]
`--disallow-warnings` `--strict-warnings` `--fail-on-warnings`?

**Comment by snitin315** [comment]
I like --fail-on-warnings

**Comment by alexander-akait** [comment]
`--fail-on-warnings` :+1:

**Comment by rishabh3112** [comment]
Yeah, `--fail-on-warnings` is sounds good.
