### ISSUE TITLE
eslint not found

### ISSUE THREAD

**Issue by dtle82** [webpack/webpack-cli#3319]
**Describe the bug**

When trying to install webpack-cli i'm getting this error for eslint not found because someone published a bad package.  How can we force it to download the older version?

**What is the current behavior?**

**To Reproduce**

npm i webpack-cli

**Expected behavior**

RUN npm install -g webpack-cli webpack:
#29 3.215 npm ERR! code E404
#29 3.218 npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz
#29 3.218 npm ERR! 404 
#29 3.218 npm ERR! 404  '@types/eslint@*' is not in the npm registry.
#29 3.218 npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
#29 3.218 npm ERR! 404 It was specified as a dependency of '@types/eslint-scope'
#29 3.219 npm ERR! 404 
#29 3.219 npm ERR! 404 Note that you can also install from a
#29 3.219 npm ERR! 404 tarball, folder, http url, or git url.
#29 3.224 
#29 3.224 npm ERR! A complete log of this run can be found in:
#29 3.224 npm ERR!     /root/.npm/_logs/2022-06-30T20_45_37_981Z-debug.log

**Screenshots**

**Additional context**

**Comment by alexander-akait** [comment]
Just regenerate lock file and send a PR
