### ISSUE TITLE
Discussion: adding envinfo to webpack-cli and ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by tabrindle** [webpack/webpack-cli#334]
Currently the issue template has the following:

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

And yet many issues ignore this or format it differently, because it takes time and effort to get all those versions. Making issues easy to write up and resolve is very important in a high traffic repo like webpack.

I'd like to update the issue_template with [envinfo](https://github.com/tabrindle/envinfo) so we can get all of this in one terminal command: 

`npx envinfo --preset webpack` 

```
  System:
    OS: macOS High Sierra 10.13
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 8.9.4
    Yarn: 1.3.2
    npm: 5.6.0
  npmPackages:
    webpack:
      wanted: ^3.11.0
      installed: 3.11.0
  npmGlobalPackages:
    webpack-cli: 2.0.11
```

envinfo is flexible and can request a number of different things - including browsers, and can return the data in multiple formats like yaml, markdown and json - and copy directly to the clipboard.

Ill make a PR if you like the idea - but mostly want to know what route you want to take. We could white label this inside of webpack-cli so that it can be a command like `webpack-cli diagnostics` or `webpack-cli envinfo`. This is the approach that react-native and expo uses. Or, other projects like jest and styled-components just use `npx envinfo` directly. Up to you!

**Comment by ev1stensberg** [comment]
Agree
