### ISSUE TITLE
Error: Unknown option '--profile'

### ISSUE THREAD

**Issue by harmeet-kr** [webpack/webpack-cli#3368]
I recently upgraded the webpack cli version from 3.3.11 to 4.10.0
When I run webpack with profiling option, 
`webpack --profile --json > stats.json`

I get the below error:
```
[webpack-cli] Error: Unknown option '--profile'
[webpack-cli] Run 'webpack --help' to see available commands and options
error Command failed with exit code 2.
```

but from what I can see in https://github.com/webpack/webpack-cli/blob/master/OPTIONS.md, --profile is a valid flag.
Has this flag been removed in v4?

**Comment by snitin315** [comment]
`--profile` was removed in favor of `--progress=profile`.

Also you dont need to paas it with json anymore. You should update ypur command as `webpack --json=stats.json`

**Comment by alexander-akait** [comment]
Answered, feel free to feedback
