### ISSUE TITLE
[webpack-cli] SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by kulkarnipradnyas** [webpack/webpack-cli#3381]
**Describe the bug**
  Script:  "start:local": "webpack serve --config ./webpack.config.js --env env=local",
  "webpack": "^5.51.1",
   "webpack-cli": "^4.8.0",
   "webpack-dev-server": "^4.10.0",

**What is the current behavior?**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please paste the results of `npx webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by snitin315** [comment]
Please provide steps to reproduce.
