### ISSUE TITLE
init abandoned?

### ISSUE THREAD

**Issue by Coachonko** [webpack/webpack-cli#3382]
Hi, is the init script abandoned? I have initialized a project with it but the generated configuration does not even match the website's documentation at all. Is the init script generating configurations that are compatible with webpack 5 but written in an older-version way?

Further, when generating a commonJS config, the syntax uses the ES include syntax which breaks the initialized project

**Comment by snitin315** [comment]
@Coachonko Can you provide steps to reproduce?

**Comment by snitin315** [comment]
No response. Hence closing.
