### ISSUE TITLE
Output configuration through option/flags

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#3395]
**Is your feature request related to a problem? Please describe.**

As webpack configurations grow, and abstractions on top of `webpack.config.js` increases, it would be nice to output how the config looks, and what the end configuration will be, possibly through a CLI flag.

**Describe the solution you'd like**

A flag that outputs the configuration file.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by snitin315** [comment]
Jest and typescript provides a `--showConfig` flag.

**Comment by alexander-akait** [comment]
bump

**Comment by alexander-akait** [comment]
Let's close in favor of https://github.com/webpack/webpack-cli/issues/3537, because `webpack config` should do it
