### ISSUE TITLE
Scoping: current Webpack CLI migration

### ISSUE THREAD

**Issue by kenwheeler** [webpack/webpack-cli#34]
Lets use this ticket to discuss the scope of migrating existing Webpack CLI migration

TODO: 

- [ ]  Agreed upon high level scope points go here

**Comment by ev1stensberg** [comment]
Could you elaborate a bit more in the ticket @kenwheeler ?

**Comment by DanielaValero** [comment]
As I see it here, the next steps would be:

1. Make a list of the currently available cli features
2. Check what the current code design is, what libraries are being used, and which functionalities lack of tests.
3. Integrate it into the cli `lib/`
4. Decide if we want/need to refactor the code.

**Comment by ev1stensberg** [comment]
Closed, I think we're even on what we're doing and that we should refactor `bin` with some better user experience later.
