### ISSUE TITLE
webpack-cli init command - wrong babel configuration generation

### ISSUE THREAD

**Issue by Pavel-Durov** [webpack/webpack-cli#343]
**Reproduction Steps:**
1. Install webpack + webpack-cli 
```
$ npm i webpack -D
$ npm i webpack-cli -D
```
2. Run webpack-cli init
`webpack-cli init
`
3. Enter the following configurations:
> ? Will your application have multiple bundles? No
> ? Which module will be the first to enter the application? [example: './src/index'] ./index.js
> ? Which folder will your generated bundles be in? [default: dist]: 
> ? Are you going to use this in production? No
> ? Will you be using ES2015? Yes
> ? Will you use one of the below CSS solutions? No
> ? If you want to bundle your CSS files, what will you name the bundle? (press enter to skip) 
> ? Name your 'webpack.[name].js?' [default: 'config']: 

4. Run webpack:
`$ webpack
`

5. Observe cli error:
> .../node_modules/webpack/lib/RuleSet.js:188
> 				throw new Error(RuleSet.buildErrorMessage(condition, error));
> 				^
> Error: Excepted condition but got [object Object] in {
>   "test": {},
>   "include": "undefined",
>   "exclude": {}
> }
>     at Function.normalizeRule (/Users/paveldurov/git-repos/temp/node_modules/webpack/lib/RuleSet.js:188:11)
>     at rules.map (/Users/paveldurov/git-repos/temp/node_modules/webpack/lib/RuleSet.js:110:20)
>     at Array.map (<anonymous>)
>     at Function.normalizeRules...
> 
> 

**Reason:**
Invalid babel configuration:
> {
> 				test: {},
> 				exclude: /node_modules/,
> 				loader: 'babel-loader',
> 				options: {
> 					presets: ['env']
> 				}
> }
> 

**Solution:**
change `test: {} ` to `test: /\.js$/`
as stated in babel-loader documentation.

**What is the expected behavior?**
Webpack bundle runs without error

versions:
```
node -v: v8.9.4
npm -v: 5.6.0
webpack -v:  4.1.1
webpack-cli -v: 2.0.11

**Comment by ev1stensberg** [comment]
Yes, saw that myself, I'll have a look at it!

**Comment by ev1stensberg** [comment]
`webpack-cli@2.0.12`
