### ISSUE TITLE
Documentation: Flesh out, improve and rearrange documentation

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#3444]
**Is your feature request related to a problem? Please describe.**

In our package documentation, we need to improve the documentation by:

1) Remove or refurbish old documentation of things like the generators. For instance, the update generator is unneeded.

**Describe the solution you'd like**

A PR that goes through all the markdown files and removes obsolete and redundant documentation. 

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by CatherineKiiru** [comment]
Hello Even, I'd like to work on this issue. What it resolved?

**Comment by ashutosh887** [comment]
I'd like to work on this

**Comment by lalitkumawat1m** [comment]
Hi @evenstensberg,
I would like to fix this issue, can I please get assigned to it?
