### ISSUE TITLE
The `useLocalIp` option is not work as expected.

### ISSUE THREAD

**Issue by fengyuanchen** [webpack/webpack-cli#345]
**Do you want to request a *feature* or report a *bug*?**

- A **bug** if I understand right.

**What is the current behavior?**

When set the `useLocalIp` option, it can open the local ip in browser, but got error: `This site can’t be reached`.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. The local IP is `192.168.0.101` (example).
2. Set the `useLocalIp` option: `webpack-dev-server --mode development --hot --open --useLocalIp`
3. Open `192.168.0.101:8080` in browser
4. Got error:
   ```
   This site can’t be reached
   192.168.0.101 refused to connect.
   ```
5. If I open `127.0.0.1:8080` or `localhost:8080`, it works fine.

**What is the expected behavior?**

Can reach the site when use local IP.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

**Comment by ev1stensberg** [comment]
@shellscape

**Comment by shellscape** [comment]
@ev1stensberg sorry man, I haven't maintained WDS in 4 months now.

**Comment by fengyuanchen** [comment]
Sorry, I will close this and open a new one on `webpack-dev-server` project.
