### ISSUE TITLE
[webpack-cli] Error: Unknown option '--node-env'

### ISSUE THREAD

**Issue by codelegant** [webpack/webpack-cli#3494]
**Describe the bug**

```
// package.json
“scripts”: {
    "start": "webpack serve --node-env=development --progress",
}，
“dependencies”: {
    "webpack": "^5.74.0",
    "webpack-cli": "^5.0.0",
    "webpack-dev-server": "^4.10.0"
}
```
run `npm start` in bash then error.

**What is the current behavior?**

```
[webpack-cli] Error: Unknown option '--node-env'
[webpack-cli] Run 'webpack --help' to see available commands and options
```

**To Reproduce**

**Expected behavior**
Work without error

**Screenshots**

![image](https://user-images.githubusercontent.com/12785928/202400207-8b6360fc-d62e-4f6b-a1ea-9febccbee0a5.png)

**Please paste the results of `npx webpack-cli info` here, and mention other relevant information**
```
  System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz
    Memory: 7.31 GB / 31.74 GB
  Binaries:
    Node: 16.15.1 - ~\.nvm\versions\node\v16.15.1\bin\node.EXE
    npm: 8.11.0 - ~\.nvm\versions\node\v16.15.1\bin\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.42)
    Internet Explorer: 11.0.22621.1
  Packages:
    css-loader: ^6.7.1 => 6.7.2
    fork-ts-checker-webpack-plugin: ^7.2.11 => 7.2.13
    html-webpack-plugin: ^5.5.0 => 5.5.0
    less-loader: ^11.0.0 => 11.1.0
    style-loader: ^3.3.1 => 3.3.1
    thread-loader: ^3.0.4 => 3.0.4
    ts-loader: ^9.3.1 => 9.4.1
    vue-loader: ^17.0.0 => 17.0.1
    webpack: ^5.74.0 => 5.75.0
    webpack-cli: ^5.0.0 => 5.0.0
    webpack-dev-server: ^4.10.0 => 4.11.1
```
**Additional context**

**Comment by snitin315** [comment]
@codelegant We have renamed it to `--define-process-env-node-env`. You can find it in [the changelog ](https://github.com/webpack/webpack-cli/blob/master/CHANGELOG.md#500-2022-11-17). Please update your script as:

```js
"start": "webpack serve --define-process-env-node-env=development --progress",
````

**Comment by codelegant** [comment]
Thanks, but the webpack doc not update https://webpack.js.org/api/cli#node-env

**Comment by codelegant** [comment]
> @codelegant We have renamed it to `--define-process-env-node-env`. You can find it in [the changelog ](https://github.com/webpack/webpack-cli/blob/master/CHANGELOG.md#500-2022-11-17). Please update your script as:
> 
> ```js
> "start": "webpack serve --define-process-env-node-env=development --progress",
> ```

Thanks, but the webpack doc not update https://webpack.js.org/api/cli#node-env

**Comment by snitin315** [comment]
@codelegant Thanks for the heads up,  I'll update the docs by today/tomorrow.
