### ISSUE TITLE
webpack-cli is always install not success

### ISSUE THREAD

**Issue by Rinx-1** [webpack/webpack-cli#3595]
C:\Users\GTB>webpack -v
CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "yarn" to install the CLI via "yarn add -D webpack-cli".
Do you want to install 'webpack-cli' (yes/no): yes
Installing 'webpack-cli' (running 'yarn add -D webpack-cli')...
yarn add v1.22.19
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "webpack-cli > @webpack-cli/configtest@2.0.1" has unmet peer dependency "webpack@5.x.x".
warning "webpack-cli > @webpack-cli/info@2.0.1" has unmet peer dependency "webpack@5.x.x".
warning "webpack-cli > @webpack-cli/serve@2.0.1" has unmet peer dependency "webpack@5.x.x".
warning " > webpack-cli@5.0.1" has unmet peer dependency "webpack@5.x.x".
[4/4] Building fresh packages...
warning No license field
success Saved 1 new dependency.
info Direct dependencies
└─ webpack-cli@5.0.1
info All dependencies
└─ webpack-cli@5.0.1
Done in 1.54s.
Error: Cannot find module 'webpack-cli/package.json'
Require stack:
- D:\React-test\React-0\my-app\node_modules\webpack\bin\webpack.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at runCli (D:\React-test\React-0\my-app\node_modules\webpack\bin\webpack.js:65:26)
    at D:\React-test\React-0\my-app\node_modules\webpack\bin\webpack.js:154:5
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\React-test\\React-0\\my-app\\node_modules\\webpack\\bin\\webpack.js'
  ]
}

C:\Users\GTB>webpack -v
CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "yarn" to install the CLI via "yarn add -D webpack-cli".
Do you want to install 'webpack-cli' (yes/no): no
You need to install 'webpack-cli' to use webpack via CLI.
You can also install the CLI manually.

C:\Users\GTB>npm install -g cnpm -registry=https://registry.npm.taobao.org
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

added 404 packages in 13s

11 packages are looking for funding
  run `npm fund` for details

C:\Users\GTB>cnpm -v
cnpm@9.0.1 (C:\Users\GTB\AppData\Roaming\npm\node_modules\cnpm\lib\parse_argv.js)
npm@8.19.3 (C:\Users\GTB\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\index.js)
node@18.13.0 (C:\Program Files\nodejs\node.exe)
npminstall@7.4.1 (C:\Users\GTB\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\index.js)
prefix=C:\Users\GTB\AppData\Roaming\npm
win32 x64 10.0.19045
registry=https://registry.npmmirror.com

C:\Users\GTB>webpack -v
CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "yarn" to install the CLI via "yarn add -D webpack-cli".
Do you want to install 'webpack-cli' (yes/no): no
You need to install 'webpack-cli' to use webpack via CLI.
You can also install the CLI manually.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please check you don't have globally and locally installed version they can overlap and it can be a problem, feel free to feedback and please use the issue template in future
