### ISSUE TITLE
webpack -p spams with Uglify warning noise

### ISSUE THREAD

**Issue by hillscottc** [webpack/webpack-cli#36]
I understand that the `-p` options has no way of suppressing underlying warnings. That's a pain. I'm seeing hundreds of lines of noise as Uglify generates warnings for every line of every third-party dependency in the project. This makes `webpack -p` not a good option for me, when otherwise its working well and saving me some work. I hope this gets looked at.

https://github.com/webpack/webpack/issues/2352#issuecomment-274279180

**Comment by ev1stensberg** [comment]
This is relative to #22 , we are discussing this internally, I'll keep you posted on that issue thread. Thanks for submitting, but remember to use the template given! If you want help on fixing this in `webpack.config.js`, I can help you with that, but seems like that has been sorted out in where the issue originated from.
