### ISSUE TITLE
ProgressPlugin support for MultiCompiler

### ISSUE THREAD

**Issue by mems** [webpack/webpack-cli#3604]
**Is your feature request related to a problem? Please describe.**

Progression is not reliable when used with webpack command line and a multi compilation.

[`ProgressPlugin` support it](https://github.com/webpack/webpack/blob/4b4ca3bb53f36a5b8fc6bc1bd976ed7af161bd80/lib/ProgressPlugin.js#L150-L151), but it's related to how this plugin is injected in the configuration.

An instance of the plugin is [created automatically for each compiler](https://github.com/webpack/webpack-cli/blob/37bf3afae1dc4b69e4316b0e3627da806b867d6e/packages/webpack-cli/src/plugins/cli-plugin.ts#L31-L33) when `CLIPlugin` (which is [added to each config](https://github.com/webpack/webpack-cli/blob/37bf3afae1dc4b69e4316b0e3627da806b867d6e/packages/webpack-cli/src/webpack-cli.ts#L2164-L2171)) is [applied to the compiler](https://github.com/webpack/webpack-cli/blob/37bf3afae1dc4b69e4316b0e3627da806b867d6e/packages/webpack-cli/src/plugins/cli-plugin.ts#L104-L106).

The problem is the `ProgressPlugin` [will never applied](https://github.com/webpack/webpack-cli/blob/37bf3afae1dc4b69e4316b0e3627da806b867d6e/packages/webpack-cli/src/webpack-cli.ts#L2322) with a `MultiCompiler` to [configure correctly progress computation](https://github.com/webpack/webpack/blob/4b4ca3bb53f36a5b8fc6bc1bd976ed7af161bd80/lib/ProgressPlugin.js#L143-L155).

**Describe the solution you'd like**

I think there is 2 possible solutions:

1. `Compiler` provide access to it's parent compiler / root compiler (compiler tree) like `MultiCompiler` [does to it's children compilers](https://github.com/webpack/webpack/blob/4b4ca3bb53f36a5b8fc6bc1bd976ed7af161bd80/lib/MultiCompiler.js#L74).
2. `webpack-cli` configure `ProgressPlugin` at the same level it handle watch option:
	```ts
	// In https://github.com/webpack/webpack-cli/blob/37bf3afae1dc4b69e4316b0e3627da806b867d6e/packages/webpack-cli/src/webpack-cli.ts#L2241C3-L2341
	class WebpackCLI implements IWebpackCLI {
	  // ...
	  async runWebpack(options: WebpackRunOptions, isWatchCommand: boolean): Promise<void> {
	    let compiler: Compiler | MultiCompiler;
	    //...
	    compiler = await this.createCompiler(options as WebpackDevServerOptions, callback);
	    //...
	    // See https://webpack.js.org/plugins/progress-plugin/#:~:text=we%20recommend%20using%20percentby%3A%20'entries'
	    new ProgressPlugin(({ percentBy: 'entries' })).apply(compiler);
	    //...
	    if (isWatch(compiler) && this.needWatchStdin(compiler)) {
	      // ...
	    }
	  }
	}
	```

**Describe alternatives you've considered**

The workaround I use in `webpack.config.js`, is a `ProgressPlugin` monkey patch:

```js
const createProgressPlugin = createProgressPluginFactory();

export default [
  {
    // ...config 1
    plugins: [
      createProgressPlugin(),
      //...
    ]
  },
  {
    // ...config 2
    plugins: [
      createProgressPlugin(),
      //...
    ]
  },
  //...
];

function createProgressPluginFactory() {
  /** @type {[number, ...string[]][]} */
  const states = [];

  return () => {
    const idx = states.length;
    states.push([0]);

    const instance = new ProgressPlugin({ percentBy: 'entries' });
    const _applyOnCompiler = instance._applyOnCompiler.bind(instance);
    instance._applyOnCompiler = (compiler, handler) => {
      // From https://github.com/webpack/webpack/blob/4b4ca3bb53f36a5b8fc6bc1bd976ed7af161bd80/lib/ProgressPlugin.js#L167-L172
      _applyOnCompiler(compiler, (p, msg, ...args) => {
        states[idx] = [p, msg, ...args];
        let sum = 0;
        for (const [p] of states) sum += p;
        handler(sum / states.length, `[${idx}] ${msg}`, ...args);
      });
    };
    return instance;
  };
}
```

**Additional context**

Screen capture of the progress output for 5 configurations that show uneven progress:

https://user-images.githubusercontent.com/729275/216970448-f79bfdb6-933a-46a1-8f89-cfeedbba2672.mov

Screen capture of the progress output for 5 configurations with workaround (expected result):

https://user-images.githubusercontent.com/729275/216983633-8f00eeb8-4bee-46e1-a195-e52b34a234a7.mov

**Comment by alexander-akait** [comment]
I want to say it is more bug than a feature request, do you want to send a PR?

**Comment by alexander-akait** [comment]
Let's use the second solution and remove the logic from CLI plugin, i.e.

```js
if (Array.isArray(compiler)) {
  new ProgressPlugin(({ percentBy: 'entries' })).apply(compiler);
} else {
  // Logic from WebpackCLIPlugin
}

```

**Comment by alexander-akait** [comment]
@webpack/cli-team Does anyone want to implement this, very easy task :smile:

**Comment by snitin315** [comment]
I'll send a PR.
