### ISSUE TITLE
`webpack` without config fails

### ISSUE THREAD

**Issue by Legends** [webpack/webpack-cli#361]
**Do you want to request a *feature* or report a *bug*?**

Bug in API or Docs [(referenced SO issue)](https://stackoverflow.com/questions/49377170/module-not-found-error-cant-resolve-hello-bundle-js-in-d-webpackdemo)

**What is the current behavior?**

The [documentation](https://webpack.js.org/api/cli/#usage-without-config-file) says: 

> webpack src/index.js dist/bundle.js

We do: `webpack ./hello.js   hello.bundle.js`

**But we get:**
ERROR in multi ./hello.js hello.bundle.js Module not found: Error: Can't resolve 'hello.bundle.js'

**Now, when you do:**
`webpack ./hello.js -o hello.bundle.js`

This will generate a `hello.bundle.js`.

**Now when you execute:**

`webpack ./hello.js hello.bundle.js`  (again like the first time without `-o` flag)

It will work. But it will not work if the output bundle does not already exist!

**If the current behavior is a bug, please provide the steps to reproduce.**

[Here is a sample gist](https://github.com/Legends/wbpack-cli-bug)

**What is the expected behavior?**
Correct docs or fixed api

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

Win 10 x64, node v8.10.0, npm 5.7.1

**Comment by montogeek** [comment]
What if you remove `./` from the entry?

**Comment by Legends** [comment]
It's not a resolution error. The result is the same if I remove `./`. It's a small and simple gist. Try it out..

**Comment by Legends** [comment]
When downloading/cloning the gist, you have to try it this way, after installing deps:

1. `webpack ./hello.js hello.bundle.js` <-- fails
2. `webpack hello.js -o hello.bundle.js` <-- succeeds and generates hello.bundle.js
3. `webpack ./hello.js hello.bundle.js` <-- succeeds
4. Now delete `hello.bundle.js` created in step 2 and repeat step 3
    `webpack ./hello.js hello.bundle.js`  <-- fails, it expects the output file to be present

**Comment by montogeek** [comment]
Yes, looks like it is not longer supported to pass entry separated by a space, it is clearly a documentation dsync, because CLI clearly says you have to pass `-o`: https://github.com/webpack/webpack-cli/blob/master/bin/webpack.js#L55

I will update webpack docs

**Comment by montogeek** [comment]
Relevant PR https://github.com/webpack/webpack-cli/pull/227

**Comment by Legends** [comment]
Merged...
