### ISSUE TITLE
Tests: Use NPM CI for Tests

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#367]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

In our tests ( `appveyor` and `travis` ), we're using npm and not npm ci.

**If the current behavior is a bug, please provide the steps to reproduce.**

[NPM CI](https://docs.npmjs.com/cli/ci) is a version of npm that runs on the CI ( faster ), which will increase feedback loop. 

## These are the files you are most likely to revise:

- https://github.com/webpack/webpack-cli/blob/master/.appveyor.yml
- https://github.com/webpack/webpack-cli/blob/master/.travis.yml

## Relevant Resources

- https://medium.com/@tomastrajan/how-to-speed-up-continuous-integration-build-with-new-npm-ci-and-package-lock-json-7647f91751a
- http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable
- http://blog.npmjs.org/post/171139955345/v570

**What is the expected behavior?**

Faster builds on integration, unit and relevant tests.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Performance

## Important

**This issue is reserved for first time contributors.**

Happy hacking 🎉

**Comment by FadySamirSadek** [comment]
I would love to pick this one up

**Comment by ematipico** [comment]
Can be closed
