### ISSUE TITLE
Fix: Make the Parser more Functional

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#37]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Current behaviour is that the Parser is having an imperative approach to the first `--init` command.

**What is the expected behavior?**

The expected behaviour is that we should make `lib/parser` more functional to be reused together with the inquirer prompt. This allows us to reuse code, save some space and write elegant, performant code without compromising. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

Improvement / Performance / Readability / Good Manners

**Comment by DanielaValero** [comment]
Hi @ev1stensberg, do you mean here 'functional' as of Functional Programming ?

**Comment by ev1stensberg** [comment]
@DanielaValero Yes, that was the intent.

**Comment by ev1stensberg** [comment]
#59
