### ISSUE TITLE
Question: --jsonForString flag to get json that can be used in jsonToString without ignoring --display options

### ISSUE THREAD

**Issue by jkanczler** [webpack/webpack-cli#370]
**Do you want to request a *feature* or report a *bug*?**
I would like to request a new feature.

**What is the current behavior?**
In case of `--json` and `--display "none"` flags, the modules are written out into the JSON.

**What is the expected behavior?**
Add a `--jsonForString` flag, that won't ignore any display options.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I just would like to use the JSON to collect errors and warnings, after that I would like to use the Stats.jsonToString static to write the result out to console.

**Comment by ematipico** [comment]
Is the feature still valid? Noticed that the linked issue has been closed

**Comment by jkanczler** [comment]
Maybe or maybe not. In case of the `--json --display "none"` arguments, the modules are included into the JSON output. But in case of the `--json --display "minimal"` arguments, just the count of the modules. What's the intention behind it? For me, in case of the webpack-vsts-extension (it's a Visual Studio Team Services extension that can execute the webpack-cli and log useful things in the build summary screen), I have to check for the `--display` flag to remove the modules manually from the JSON output in case of "none". It's a valid workaround for me, but it could be useful, if somehow we can pass the JSON output to `Stats.jsonToString` without any manipulation and it can be the same as running the webpack-cli without `--json` flag. Does it make sense?

**Comment by ev1stensberg** [comment]
@jkanczler As far as I've understood this is about the precedence of args, so if you provide a flag, the flag is responsible for its task, not any other. Could you give me a repro?

**Comment by jkanczler** [comment]
https://github.com/jkanczler/webpack-cli-display-options.git

```
yarn install
yarn build-display-none
yarn build-display-minimal
```

Basically:
```
yarn build-display-none
yarn run v1.6.0
$ webpack --json --display none
{
  "errors": [],
  "warnings": [
    "configuration\nThe 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.\nYou can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/"
  ],
  "modules": [
    {
      "id": 0,
      "identifier": "C:\\W\\Playground\\webpack-cli-display-options\\src\\index.js",
      "name": "./src/index.js",
      "index": 0,
      "index2": 0,
      "size": 23,
      "cacheable": true,
      "built": true,
      "optional": false,
      "prefetched": false,
      "chunks": [
        0
      ],
      "issuer": null,
      "issuerId": null,
      "issuerName": null,
      "issuerPath": null,
      "failed": false,
      "errors": 0,
      "warnings": 0
    }
  ],
  "filteredModules": 0
}
Done in 1.92s.
```

and with minimal:
```
yarn build-display-minimal
yarn run v1.6.0
$ webpack --json --display minimal
{
  "errors": [],
  "warnings": [
    "configuration\nThe 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.\nYou can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/"
  ],
  "modules": [],
  "filteredModules": 1
}
Done in 1.91s.
```

As you can see, with --json and --display minimal you'll get less information as with --json --display none arguments.

**Comment by ev1stensberg** [comment]
Thanks!

**Comment by evenstensberg** [comment]
I don't think we will implement this, but it's feedback for stats @sokra , and maybe something that could be done api wise through stats.

**Comment by sokra** [comment]
`Stats.jsonToString` is removed in webpack 5 anyway.

`preset: "none"` should no longer include modules
