### ISSUE TITLE
Running npx webpack-cli --force still ask questions...

### ISSUE THREAD

**Issue by carvalholuigi25** [webpack/webpack-cli#3719]
**Describe the bug**

Hello. 

When, i try to run the command: ```npx webpack-cli init --force``` after installed webpack setup and dependencies, it still shows the ask questions. 

![image](https://user-images.githubusercontent.com/102177155/230588214-c3937ea5-3c85-4c7a-b386-2a2606f08284.png)

Versions: 

Node: 16.20.0
NPM: 8.19.4
Webpack:  5.78.0
Operating System: Windows 11 Home 22H2 (22621.1413)

**What is the current behavior?**

The current behavior is still showing the ask questions after using the command in above.

**To Reproduce**

1º - mkdir myproj && cd myproj
2º - npm init -y 
3º - npm install -D @webpack-cli/generators
4º - npm install --save-dev webpack webpack-cli
5º - npx webpack-cli init --force

Note: I followed these guides: 
[Installation of webpack](https://webpack.js.org/guides/installation.js.org/guides/installation)
[webpack-cli init](https://github.com/webpack/webpack-cli/blob/master/packages/generators/INIT.md)

**Expected behavior**

The expected behavior should be getting no questions, passing with default answers and skip through to installation. It should be like this:

![image](https://user-images.githubusercontent.com/102177155/230590265-1d46bc1a-671e-4577-911c-6a8e11b50258.png)

**Screenshots**

1º:

![image](https://user-images.githubusercontent.com/102177155/230588515-a479d738-285d-4d67-a35a-fd41620bf8fc.png)

```mkdir myproj && cd myproj```

2º: 

![image](https://user-images.githubusercontent.com/102177155/230588600-3c78d076-db93-4a16-8ae6-9fa7786fc8b5.png)

```npm init -y```

3º: 

![image](https://user-images.githubusercontent.com/102177155/230588867-5ef0ea32-07e8-4135-a34f-b6c70f704b07.png)

```npm install -D @webpack-cli/generators```

4º: 

![image](https://user-images.githubusercontent.com/102177155/230589038-b0b7c3d6-1134-4e62-bcfe-5908b864b6b0.png)

```npm install --save-dev webpack webpack-cli```

5º:

![image](https://user-images.githubusercontent.com/102177155/230589217-493a6ad8-fe98-4a3a-bbfc-2b752dbec116.png)

```npx webpack-cli init --force```

**Please paste the results of `npx webpack-cli info` here, and mention other relevant information**

![image](https://user-images.githubusercontent.com/102177155/230592529-38753b74-b394-4de7-be05-37e5dff4bfda.png)

**Comment by alexander-akait** [comment]
Sound like a bug

/cc @webpack/cli-team Somebody can check it?

**Comment by snitin315** [comment]
Yes I was able to reproduce it. We also have tests for --force. Need to check why this is happening.
