### ISSUE TITLE
Webpack bundling emits "require" statements in the distribution file

### ISSUE THREAD

**Issue by tal-rofe** [webpack/webpack-cli#3728]
I have a TypeScript project, and I use Webpack to bundle the code to single JavaScript file. I'm using **ESM** only. When I try to run the distribution file by running: `node ./dist/index.js` I get this error:
```
const external_minimist_namespaceObject = require("minimist");
                                          ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

Indeed, I configured `"type": "module"` in the `package.json` file.
I have this script to run the Webpack: `"dist": "node --loader ts-node/esm node_modules/webpack-cli/bin/cli.js -c ./webpack.config.ts",` in my `package.json` file.

This is my `webpack.config.ts` file:
```ts
import path from 'node:path';
import fs from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import webpack from 'webpack';
import nodeExternals from 'webpack-node-externals';
import TsconfigPathsPlugin from 'tsconfig-paths-webpack-plugin';
import WebpackShellPluginNext from 'webpack-shell-plugin-next';

const packageJsonData = await fs.readFile('package.json', 'utf-8');
const packageJsonObject = JSON.parse(packageJsonData);
const version = packageJsonObject.version;

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const configuration: webpack.Configuration = {
	context: __dirname,
	mode: 'production',
	target: 'node',
	entry: './src/index.ts',
	// * https://stackoverflow.com/questions/48673408/should-javascript-npm-packages-be-minified
	optimization: { minimize: false },
	externals: [nodeExternals({ modulesDir: path.join(__dirname, 'node_modules') })],
	experiments: { outputModule: true },
	module: {
		rules: [
			{
				test: /\.ts$/,
				use: [
					{
						loader: 'ts-loader',
						options: { configFile: 'tsconfig.build.json' },
					},
				],
				exclude: /node_modules/,
			},
		],
	},
	plugins: [
		new WebpackShellPluginNext({
			onBuildStart: {
				scripts: ['rimraf dist'],
				blocking: true,
			},
			safe: true,
		}),
		new webpack.DefinePlugin({
			__PACKAGE_VERSION__: JSON.stringify(version),
		}),
	],
	resolve: {
		extensions: ['.ts'],
		plugins: [
			new TsconfigPathsPlugin({
				configFile: './tsconfig.base.json',
				extensions: ['.ts'],
			}),
		],
	},
	output: {
		filename: 'index.js',
		path: path.resolve(__dirname, 'dist'),
		library: { type: 'module' },
		chunkFormat: 'module',
	},
};

export default configuration;
```

And this is my `tsconfig.base.json` file which is the important one:
```json
{
	"extends": "./tsconfig.paths.json",
	"compilerOptions": {
		"target": "ES2018",
		"module": "ESNext",
		"moduleResolution": "bundler",
		"noEmit": true,
		"baseUrl": "./",
		"allowJs": false,
		"skipLibCheck": true,
		"strict": true,
		"forceConsistentCasingInFileNames": true,
		"esModuleInterop": true,
		"resolveJsonModule": true,
		"isolatedModules": true,
		"incremental": true,
		"removeComments": true,
		"allowUnreachableCode": false,
		"allowUnusedLabels": false,
		"alwaysStrict": true,
		"noFallthroughCasesInSwitch": true,
		"noImplicitAny": true,
		"noImplicitOverride": true,
		"noImplicitReturns": true,
		"noImplicitThis": true,
		"noPropertyAccessFromIndexSignature": true,
		"noUncheckedIndexedAccess": true,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"typeRoots": ["./node_modules/@types", "./@types"]
	}
}
```

Webpack completes successfully, but I cannot run the distribution file with NodeJS (`node ./dist/index.js`). Why does the distribution file contain `require` statements instead of `import` to successfully run with `ESM`?

**Comment by tal-rofe** [comment]
> @tal-rofe Due this `externals: [nodeExternals({ modulesDir: path.join(__dirname, 'node_modules') })]`, you say webpack to use commonjs externals, but your code in ESM, we should improve error reporting here, you need setup this https://github.com/liady/webpack-node-externals#optionsimporttype-commonjs on `module` or `import`

So I should set something like this: `	externals: [nodeExternals({ modulesDir: path.join(__dirname, 'node_modules'), importType: '' })],`

But what should I set? cannot set `module` or `import`

**Comment by alexander-akait** [comment]
I reccommend to use:
```
externals: [nodeExternals({ modulesDir: path.join(__dirname, 'node_modules'), importType: 'import' })]

**Comment by tal-rofe** [comment]
> I reccommend to use:
> 
> ```
> externals: [nodeExternals({ modulesDir: path.join(__dirname, 'node_modules'), importType: 'import' })]
> ```

`'import'` cannot be set: 
`        importType?: 'var' | 'this' | 'commonjs' | 'amd' | 'umd' | ImportTypeCallback | undefined;`

**Comment by alexander-akait** [comment]
In this case try to use ImportTypeCallback, we can't fix it in another projects, sorry

There is an example https://github.com/liady/webpack-node-externals#optionsimporttype-commonjs, jsut replace `amd` on `import`

**Comment by tal-rofe** [comment]
> In this case try to use ImportTypeCallback, we can't fix it in another projects, sorry
> 
> 
> 
> There is an example https://github.com/liady/webpack-node-externals#optionsimporttype-commonjs, jsut replace `amd` on `import`

Thank you. It resolved the issue
