### ISSUE TITLE
init command should create config with mini-css-extract-plugin

### ISSUE THREAD

**Issue by jevan0307** [webpack/webpack-cli#374]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The init command creates config with `extract-text-webpack-plugin` to extract CSS into separate files when used in production. However, it should use `mini-css-extract-plugin` since ETWP no longer supports `webpack@4`.

**What is the expected behavior?**
Use `mini-css-extract-plugin` instead of  `extract-text-webpack-plugin` in generated config file.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Supporting the new `MiniCssExtractPlugin`.

**Comment by ev1stensberg** [comment]
#373
