### ISSUE TITLE
Webpack examples

### ISSUE THREAD

**Issue by Legends** [webpack/webpack-cli#378]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

- missing module: uri-js
- Argument: mode, Given: "none", Choices: "development", "production"

**If the current behavior is a bug, please provide the steps to reproduce.**

In order to run the webpack examples I need to link webpack-cli.
```
git clone ..webpack-cli
yarn install
yarn link
```

```
cd local/webpack/repo
yarn link webpack-cli
yarn build:examples  --> missing module `uri-js`
```

**webpack-cli repo**^
Have to install `uri-js` to make it work.
`yarn add uri-js --dev`

**webpack-repo**
`yarn build:examples`
Build runs and fails at example `source-maps`:
`--> Argument: mode, Given: "none", Choices: "development", "production"`

[Referencing existing/merged PR](https://github.com/webpack/webpack-cli/pull/278)

**What is the expected behavior?**
Run the examples without any error.

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**
webpack-cli 2.0.14
webpack "4.5.0",
Win10 x64^

```
 System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
  Binaries:
    Node: 8.10.0
    Yarn: 1.5.1
    npm: 5.8.0
  Browsers: {}
  npmPackages:
    i18n-webpack-plugin:
      wanted: ^1.0.0
      installed: 1.0.0
    uglifyjs-webpack-plugin:
      wanted: ^1.2.4
      installed: 1.2.4
    webpack-dev-middleware:
      wanted: ^1.9.0
      installed: 1.12.2
    webpack-sources:
      wanted: ^1.0.1
      installed: 1.1.0
  npmGlobalPackages:
    webpack-cli: 2.0.14
```

**Comment by Legends** [comment]
@ematipico @sokra 
This [PR](https://github.com/webpack/webpack-cli/pull/278) from sokra was merged, but is not part of master anymore?

Is it possible to remerge it?

**Comment by Legends** [comment]
Btw. `code-splitted-css-bundle` example is empty, means only a readme.md exists...

**Comment by ematipico** [comment]
We must have had some problems with other PR. You can make I PR to restore it if you can

**Comment by Legends** [comment]
It's a little effort to merge it back again, but it would be good to know why it was deleted... any open issue?

**Comment by ematipico** [comment]
Looking at the history of the file, it looks like we lost that commit. I am going to restore it and make a PR from that branch
