### ISSUE TITLE
Feedback and ideas to CLI

### ISSUE THREAD

**Issue by aight8** [webpack/webpack-cli#38]
I want to leave my thoughts about webpack's CLI especially.
It's well known that webpack's config can be difficult to master because there are a lot of options and gears. (The most are somehow CLI relevant, but I wrote down everything otherwise I forget it)

1. The current webpack integrated CLI have now an integrated config validator which is worth so much, but because webpack configs are often generated, It were good when you can summarize the effective used configuration in a human readable manner. **update:** Keep in mind the CLI parameters, too. It's difficult to understand the validate webpack configuration which it will produce.
A json dump it's not really a solution because the json can be really mess.

2. Some configuration keys in the webpack config are only for CLI. Like devServer, stats etc. This can be really confusing to. Maybe this could be a documentation improvement.

3. There are lot of articles, boilerplates etc. which describe which configuration improvements can used for browser/node - development/production. I really miss that a helper cli which explain your configuration and give tips based on your intents. btw: The webpack doc. should document much more with a practical orientation. "You should use this if... and ... and ... - not use this if...". List advantages and disadvantages (performance/data security affects) too. This whole "cli doctor" could be a part of the CLI too.

4. The native webpack CLI command should really implement a way to output how much time the different loaders/plugins/resolvers have consumed. This is fundamental to understand, especially before you can find bottlenecks and build up a good and fast development environment. This point is more basic than point 3. - this outputs just a performance summary, point 4. analyze your config more deeply - and it must not run the build.

5. Resolver debugging regarding to this: https://github.com/webpack/webpack/issues/3466#issuecomment-269003425

**Comment by DanielaValero** [comment]
Hi @aight8 thanks for sharing! We'll have a look at your ideas and integrate them where possible/makes sense to our roadmap

**Comment by TheLarkInn** [comment]
This seems like a `webpack-describe` or a feature which describes what each process is doing in an understandable fashion. I think for this to be possible however requires a lot of core infra (that I'm frankly okay with). We'd want to have some sort of meta information that can describe each process that is occuring and then feed these events to the cli in some fashion.

**Comment by ev1stensberg** [comment]
@aight8  I recommend you to try out this awesome tool by @shellscape 
 https://medium.com/webpack/webpacks-new-cli-hotness-d6a2063168a8

**Comment by shellscape** [comment]
@aight8 our colleague @ev1stensberg is correct, `webpack-command` implements nearly all of your requests
