### ISSUE TITLE
Update transformation: bannerPlugin

### ISSUE THREAD

**Issue by bitpshr** [webpack/webpack-cli#382]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The current transformation supports migrating a webpack configuration from `v1` to `v2`. 

**What is the expected behavior?**
The transformation should support migrating a webpack configuration from `v3` to `v4`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
After [some discussion](https://github.com/webpack/webpack-cli/issues/373) the decision was made to update our migration transformations to actively support migrating only from the previous version to the current version, which currently means `v3 - v4`. Migrating older versions such as `v1` or `v2` will no longer be supported.

This feature request is to update the `bannerPlugin` transformation accordingly.

**Comment by ematipico** [comment]
Is this changed from webpack 3 to 4? I don't think so

**Comment by PlayMa256** [comment]
@ematipico Nop, it is not from v3 to v4. 
[This](https://github.com/webpack/webpack/blob/fde018300aa52262c384e937c408d5dd97d62951/test/configCases/plugins/banner-plugin/webpack.config.js#L15) example was updated a long time ago. Seems that this is from v1->v2.
