### ISSUE TITLE
while calling remote app getting [object object] i used webpack when i open separate it's work fine but when open in host app and call remote app getting error [object object]

### ISSUE THREAD

**Issue by Arsalan1only** [webpack/webpack-cli#3827]
**Describe the bug**

**What is the current behavior?**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please paste the results of `npx webpack-cli info` here, and mention other relevant information**

**Additional context**

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
