### ISSUE TITLE
webpack-dev-server doesn't work with installed webpack and webpack-cli in the parent folder

### ISSUE THREAD

**Issue by dominikj111** [webpack/webpack-cli#3830]
### Actual Behavior

Installation of the `webpack-dev-server` in the `child-app` folder causes installation of the `webpack` in same folder as it depends on it, even the `webpack` is already installed in the `parent-app` folder.

If dependency is not found in the `child-app`, the node will search parent folder automatically as stated here:
[modules_loading_from_node_modules_folders](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders)

On the other hand, installation of the `webpack-cli` (also installed in `parent-app`) is not triggered.

In the `child-app`, commands
`./node_modules/.bin/webpack serve --mode development`
`../node_modules/.bin/webpack serve --mode development`
ending with same result (I would to point, that `webpack-dev-server` is already installed):
```
[webpack-cli] For using 'serve' command you need to install: 'webpack-dev-server' package.
[webpack-cli] Would you like to install 'webpack-dev-server' package? (That will run 'npm install -D webpack-dev-server') (Y/n)
```
After confirm that, we get:
```
up to date, audited 277 packages in 1s

33 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[webpack-cli] You need to install 'webpack-dev-server' for running 'webpack serve'.
Error: Cannot find module 'webpack-dev-server'
Require stack:
- /usr/src/app/node_modules/@webpack-cli/serve/lib/index.js
- /usr/src/app/node_modules/webpack-cli/lib/webpack-cli.js
- /usr/src/app/node_modules/webpack-cli/lib/bootstrap.js
- /usr/src/app/node_modules/webpack-cli/bin/cli.js
- /usr/src/app/child-app/node_modules/webpack/bin/webpack.js
```

To solve this problem, I need to install `webpack-cli` in the `child-app` folder
`npm i webpack-cli`
once finished, the
`./node_modules/.bin/webpack serve --mode development`
works as expected.

Another solution without installing the `webpack-cli` is to set the `NODE_PATH`, so command
`NODE_PATH="$NODE_PATH:/usr/src/app/child-app/node_modules" ./node_modules/.bin/webpack serve --mode development`
will serve as expected also.

### Expected Behavior

I think that `webpack` and `webpack-cli` should not be installed in the `child-app` node_modules at all, but they should by used from the parent folder.

Also installation of the `webpack-dev-server` should not install `webpack` dependency automatically, the responsibility lies on developer (same for the `webpack-cli` what is correct).
In fact, after inspecting both `node_module` folders, I saw plenty intersections.
And I don't understand why we need these duplicates if they are available in the parent's `node_module` / `NODE_PATH`.

### How Do We Reproduce?

1. do folder called **parent-app** with this structure where `package.json` files are default (generated by `npm init`)
```
parent-app
├── child-app
│   ├── package.json
│   ├── public
│   │   └── index.html
│   └── src
│       └── index.js
└── package.json
```
content of **index.html**:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  </head>
  <body>
    <div id="rootNode" />
    <script src="/main.js"></script>
  </body>
</html>
```
content of **index.js**:
```
const rootNode = document.getElementById("rootNode");
rootNode.innerHTML = "<div>This is the content rendered by js</div>";
```

2. in the `parent-app` install `webpack` and `webpack-cli` and then in the `child-app` install `webpack-dev-server`
It is handy to use docker environment upon the folder:
`docker run -it --rm -v $(pwd):/usr/src/app -w /usr/src/app -p 8080:8080 node:latest /bin/bash`

### Results of `npx webpack-cli info`

 System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 18.01 GB / 19.55 GB
  Binaries:
    Node: 20.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.6 - /usr/local/bin/npm
  Packages `parent-app`:
    webpack: ^5.85.0 => 5.85.0
    webpack-cli: ^5.1.1 => 5.1.1
  Packages `child-app`:
    webpack-dev-server: ^4.15.0 => 4.15.0

**Comment by alexander-akait** [comment]
It is a limitation you should have webpack-cli on the same level on webpack-dev-server

**Comment by dominikj111** [comment]
I understand that there may be some limits. So if it is meant to work like this it is ok, but I would expect some level of consistency at least in case where `webpack` is installed automatically when running `npm i webpack-dev-server`, but `webpack-cli` doesn't .

**Comment by dominikj111** [comment]
Aha, I see your point now @alexander-akait so wouldn't be better to install all dependencies (+ `webpack-cli` in my case) automatically or maybe even better, just throw an error with meaningful message and do not install anything, because this is more educative for developers I think. Also I'm thinking about `webpack-dev-server` as additional thing/plugin, so it doesn't make sense to install anythig if I'm going to use plugin. It is like because I want to install some Wordpress plugin, the Wordpress will install automatically as a plugin dependecy, this seems to me oposite direction of thinking.

**Comment by alexander-akait** [comment]
@dominikj111 It is not related to webpack-dev-server, there is a logic and answer why it doesn't work https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/src/webpack-cli.ts#L140, no magic, we can't do what you want and no one package can do it - you can't `require`/`import` package on  the `parent` level and awating loading it from `child`, sorry

Webpack-dev-server is not full featured CLI, it is just a runner for `webpack-cli`

**Comment by dominikj111** [comment]
@alexander-akait I just don't understand why. 
And you wrote the apposite direction I'm talking about in this issue. I want to install package in the parent and then I want to `require`/`import` in the child.
And that really works, I just install `express` in the parent and then I did `require` in the child and in the child I ran `node index.js` and it works.

If I'm wrong, just explain why and we close this issue without resolving it. But from my perspective it is a buggy behavior even there is not problem with running it, but the architecture self I suppose.

**Comment by alexander-akait** [comment]
Shortly :
- you run `webpack serve`
- when you use `webpack serve`,` webpack` try to run `webpack-cli`, because webpack itself doesn't have CLI https://github.com/webpack/webpack/blob/main/bin/webpack.js#L106
- `webpack-cli` in the parent directory
- `webpack-cli` is running with the `serve` command and `webpack-cli` try to find `webpack-dev-server`
- `webpack-cli` can't find `webpack-dev-server` because - looking at the current `node_modules` directory and up to the top until it will be found https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/src/webpack-cli.ts#L140, like `require` and `import` works
- because `webpack-dev-server` in the child directory we can't find it

> Another solution without installing the webpack-cli is to set the NODE_PATH, so command
NODE_PATH="$NODE_PATH:/usr/src/app/child-app/node_modules" ./node_modules/.bin/webpack serve --mode development
will serve as expected also.

It is not a workaround, it is a valid solution

**Comment by dominikj111** [comment]
Ah, I see the whole picture now ... because I'm running `webpack` which is in the parent, it doesn't know about the `webpack-dev-server`. Sorry it is quite obvious.

Well, I would to point that on my local `NODE_PATH` is empty by default and to have `webpack-dev-server` in child and the rest in parent I need to locate both `node_modules` folders.

```
NODE_PATH="$NODE_PATH:/Users/*****/my/development/parent-app/child-app/node_modules:/Users/*****/my/development/parent-app/node_modules" npm run serve:dev
```
for reference.

**Comment by ThiagoSuchi** [comment]
Hello, I'm facing the same error but I couldn't solve it with the step by step you showed, my error is this: > agenda-de-contatos@1.0.0 start
> webpack serves --hot

[webpack-cli] You need to install 'webpack-dev-server' for running 'webpack serve'.
Error: Cannot find module 'webpack-dev-server/package.json'
Require stack:
- /home/guilherme/Área de Trabalho/Projeto-Agenda-de-contatos/node_modules/@webpack-cli/serve/lib/index.js
- /home/guilherme/Área de Trabalho/Projeto-Agenda-de-contatos/node_modules/webpack-cli/lib/webpack-cli.js
- /home/guilherme/Área de Trabalho/Projeto-Agenda-de-contatos/node_modules/webpack-cli/lib/bootstrap.js
- /home/guilherme/Área de Trabalho/Projeto-Agenda-de-contatos/node_modules/webpack-cli/bin/cli.js
- /home/guilherme/Área de Trabalho/Projeto-Agenda-de-contatos/node_modules/webpack/bin/webpack.js

**Comment by ThiagoSuchi** [comment]
I have everything installed correctly and it still doesn't work

**Comment by dominikj111** [comment]
Hello @ThiagoSuchi my issue was mainly related to the project structure. So if you have standalone project, you are facing different issue I think.
If you facing the structural issue as I was, if you install all webpack stuff on same level, you should be good to go.
I may try if you'll share the project

**Comment by ThiagoSuchi** [comment]
You can look without any problems, here is my project: https://github.com/ThiagoSuchi/Agenda-de-Contatos

**Comment by dominikj111** [comment]
@ThiagoSuchi are on discord or skype? I did some changes in the project, but I think there can by more to discuss.

**Comment by ThiagoSuchi** [comment]
Brother, I'm Brazilian, and I don't speak English, I'm sending messages here with the help of Google Translate

**Comment by ThiagoSuchi** [comment]
But if the webpack problem is too difficult to solve, let it go, it's very likely that if I can't solve it I'll readapt the project to run in another way.

**Comment by dominikj111** [comment]
@ThiagoSuchi that is ok, I'll not bother you with calls :) ... I'm from Czech btw
It is easy to solve, I had to add just my own webpack configuration, so I'm not sure if it is same as yours (as it is gitignored). And I can send you back the working project, I don't want to lost time with pull requests

**Comment by ThiagoSuchi** [comment]
Hmm I understand, wow, that's okay, thank you brother, thanks for your attention! Regarding the issue of calling on discord, it's not a problem, it's just that I don't know any English at all, just the basics that Brazilians learn at school, I'm also studying English because I know that the programming area requires a lot of speaking English, kk

**Comment by dominikj111** [comment]
@ThiagoSuchi 
https://discord.gg/eAEK8Tzc
