### ISSUE TITLE
Accept `undefined` and `null` in `plugins` array

### ISSUE THREAD

**Issue by silverwind** [webpack/webpack-cli#3836]
**Is your feature request related to a problem? Please describe.**

To conditionally add plugins, `&&` syntax is useful and this works in vite as well:

```js
export default {plugins: [condition && SomePlugin()]}
```

It errors because the schema is too strict:

```
[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.plugins[4] should be one of these:
   object { apply, … } | function
   -> Plugin of type object or instanceof Function.
   Details:
    * configuration.plugins[4] should be an object:
      object { apply, … }
      -> Plugin instance.
    * configuration.plugins[4] should be an instance of function.
      -> Function acting as plugin.
```

**Describe the solution you'd like**

Accept `undefined` and `null` values in `plugins` array, and just ignore them.

**Describe alternatives you've considered**

This works, but is clumsy:

```js
export default {plugins: [condition && SomePlugin()].filter(Boolean)}
```

**Comment by alexander-akait** [comment]
I think we need improve this on the webpack side, because you can pass options without webpack-cli, feel free to send a PR

**Comment by silverwind** [comment]
[I tried](https://github.com/webpack/webpack/pull/17329) but then I gave up.

**Comment by hardfist** [comment]
webpack side seems more ideal，otherwise all webpack cli have to reimplement the same logic here
