### ISSUE TITLE
Update transformation: removeDeprecatedPlugins

### ISSUE THREAD

**Issue by bitpshr** [webpack/webpack-cli#386]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The current transformation supports migrating a webpack configuration from `v1` to `v2`. 

**What is the expected behavior?**
The transformation should support migrating a webpack configuration from `v3` to `v4`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
After [some discussion](https://github.com/webpack/webpack-cli/issues/373) the decision was made to update our migration transformations to actively support migrating only from the previous version to the current version, which currently means `v3 - v4`. Migrating older versions such as `v1` or `v2` will no longer be supported.

This feature request is to update the `removeDeprecatedPlugins` transformation accordingly.

**Comment by PlayMa256** [comment]
Plugins to be removed: 
- [ ] webpack.optimize.CommonsChunkPlugin
- [ ] webpack.optimize.UglifyJsPlugin (which is done by #401 )

**Comment by ematipico** [comment]
* `CommonsChunkPlugin` is not deprecated but it's been changed in favor of `splitChunks`, which is covered already in another PR
* not deprecated but changed

I don't think we have plugins have been totally removed.

**Comment by PlayMa256** [comment]
Yep, if forgot we have a PR open for split chunks too. I just updated my comment. We can close this i guess
