### ISSUE TITLE
Update transformation: resolve

### ISSUE THREAD

**Issue by bitpshr** [webpack/webpack-cli#388]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The current transformation supports migrating a webpack configuration from `v1` to `v2`. 

**What is the expected behavior?**
The transformation should support migrating a webpack configuration from `v3` to `v4`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
After [some discussion](https://github.com/webpack/webpack-cli/issues/373) the decision was made to update our migration transformations to actively support migrating only from the previous version to the current version, which currently means `v3 - v4`. Migrating older versions such as `v1` or `v2` will no longer be supported.

This feature request is to update the `resolve` transformation accordingly.

**Comment by PlayMa256** [comment]
This is for v2->v3, which is also present in [here](https://webpack.js.org/migrate/3/#resolve-root-resolve-fallback-resolve-modulesdirectories). Issue can be closed. Also, folder can be deleted (?)

**Comment by bitpshr** [comment]
PR submitted for the removal of this transformation.
