### ISSUE TITLE
@webpack-cli/generators@3.0.7 has some deprecated NPM modules

### ISSUE THREAD

**Issue by stein2nd** [webpack/webpack-cli#3891]
**Describe the bug**

npm WARN deprecated debuglog@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

**What is the current behavior?**

**To Reproduce**

1. ncu
2. ncu -u
3. npm install

**Expected behavior**

**Screenshots**
![image](https://github.com/WordPress/gutenberg/assets/531628/73f89ae1-ee6b-4dde-b9cc-ce9fdde1d212)

![image](https://github.com/WordPress/gutenberg/assets/531628/ee83d7c4-c6b7-4763-82c0-c036eed8caa1)

![image](https://github.com/WordPress/gutenberg/assets/531628/fdd5a3ee-79e8-4872-87fc-20cfbb8eb596)

**Please paste the results of `npx webpack-cli info` here, and mention other relevant information**

## System:
 - OS: macOS 13.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 285.12 MB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 20.5.0 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 9.8.0 - ~/.nodebrew/current/bin/npm
## npmPackages:
 - @webpack-cli/generators: ^3.0.7 => 3.0.7

**Additional context**

**Comment by alexander-akait** [comment]
Also:
- https://github.com/webpack/webpack-cli/issues/3891
- https://github.com/webpack/webpack-cli/issues/3892

**Comment by stein2nd** [comment]
After upgrading to @wordpress/scripts@26.11.0, we have confirmed that issue https://github.com/WordPress/gutenberg/issues/53553 has been successfully resolved, but issue https://github.com/WordPress/gutenberg/issues/53552 continues to occur.

Does this mean that this is happening because @webpack-cli/generators is not fixing its own deprecated issues with "debuglog", "readdir-scoped-modules", and "@npmcli/move-file"?

**Comment by evenstensberg** [comment]
Update cli version to more than v3 (your current)
