### ISSUE TITLE
@npmcli/move-file: This functionality has been moved to @npmcli/fs

### ISSUE THREAD

**Issue by stein2nd** [webpack/webpack-cli#3893]
**Describe the bug**
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

The following is the result of executing "npm ls @npmcli/move-file":
![image](https://github.com/webpack/webpack-cli/assets/531628/8c665564-89ca-4750-8d71-440a79cc59db)

**What is the current behavior?**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please paste the results of `npx webpack-cli info` here, and mention other relevant information**
## System:
 - OS: macOS 13.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 285.12 MB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 20.5.0 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 9.8.0 - ~/.nodebrew/current/bin/npm
## npmPackages:
 - @webpack-cli/generators: ^3.0.7 => 3.0.7 

**Additional context**

**Comment by alexander-akait** [comment]
Let's union such issues into one https://github.com/webpack/webpack-cli/issues/3892
