### ISSUE TITLE
[Feature] Read the types of mode available from webpack

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#391]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
At the moment the available type of `--mode` are hardcoded

**What is the desired behavior?**
The `cli` should retrieve/read the available type of `--mode` from `webpack`

**If this is a feature request, what is motivation or use case for changing the behavior?**
To make the `cli` less hardcoded and flexible

**Comment by PlayMa256** [comment]
I can do that. They are found at the schemas file, right? I found them there, just want to make sure it is the right place.

**Comment by PlayMa256** [comment]
I'm just restesting another pr, i will do that!
