### ISSUE TITLE
Feature: Migrate should move CommonsChunkPlugin to SplitChunksPlugin

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#393]
**Do you want to request a *feature* or report a *bug*?**
Feature. 

**What is the current behavior?**
At the moment migrate does nothing when it encounters `CommonsChunkPlugin` 

**What is the expected behavior?**
It should migrate to `SplitChunksPlugin`

**If this is a feature request, what is motivation or use case for changing the behavior?**
`CommonsChunkPlugin` is now deprecated in `webpack` v4 and migrate, as its objective, should opt in in favor of `SplitChunksPlugin`

**Comment by dhruvdutt** [comment]
I can pick this up. :hand:

**Comment by ematipico** [comment]
Great! That was quick

**Comment by ematipico** [comment]
No, just changing the name is not enough. It's a complete different section of the configuration

https://webpack.js.org/plugins/split-chunks-plugin/#optimization-splitchunks

**Comment by montogeek** [comment]
@dhruvdutt First change is its name, second step is play a lot with all its options until it fits CCP behaviour, if you discover something new share it on webpack.js.org docs!

**Comment by PlayMa256** [comment]
@ematipico this was already merged #399 , we can close
