### ISSUE TITLE
[Feature] Migrate should move NamedModulesPlugin to optimizations.namedModules

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#394]
**Do you want to request a *feature* or report a *bug*?**
Feature. 

**What is the current behavior?**
At the moment migrate does nothing when it encounters `NamedModulesPlugin ` 

**What is the expected behavior?**
It should migrate to optimizations.namedModules

**If this is a feature request, what is motivation or use case for changing the behavior?**
`NamedModulesPlugin` is now changed in `webpack` v4 and migrate, as its objective, should add a flag inside the optimizations object

**Comment by bitpshr** [comment]
I'll take this one.
