### ISSUE TITLE
[Feature] Migrate should move NoEmitOnErrorsPlugin to optimizations.noEmitOnErrors

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#395]
**Do you want to request a *feature* or report a *bug*?**
Feature. 

**What is the current behavior?**
At the moment migrate does nothing when it encounters `NoEmitOnErrorsPlugin ` 

**What is the expected behavior?**
It should migrate to optimizations.noEmitOnErrors

**If this is a feature request, what is motivation or use case for changing the behavior?**
`NoEmitOnErrorsPlugin ` is now changed in `webpack` v4 and migrate, as its objective, should add a flag inside the optimizations object

**Comment by bitpshr** [comment]
I can take this since I've been working on the migrate code for #390.
