### ISSUE TITLE
Webpack CLI  - Define features and tasks of the package

### ISSUE THREAD

**Issue by DanielaValero** [webpack/webpack-cli#4]
We are at the moment setting up most of the groundwork of the project. In order to move forward we need to define the set of features and tasks that the project needs.

In the slack channel we have agreed that we would like to work with a TDD approach. Therefore setting up the TDD would be the first step.

Also, most of the conversation about the features, is being held at the webpack repo in this issue webpack/webpack#3466

So far, the lists of tasks would be:
- [x] Setup contributing guidelines: This includes also defining the workflow of the project. Status: done, see #3 
- [x] Set TDD tooling. Status: On Going, See #5 
- [ ] Set a project with the 'user stories' of the features the project will have

**Comment by hulkish** [comment]
Definitely some things I think where this could be super useful.:

1. Lightweight / Shallow scaffolding (similar npm init/git init):
```
~/my/project$ webpack-cli init

This utility will walk you through creating a webpack.config.js file.
It only covers the most common items, and tries to guess sensible defaults.

Press ^C at any time to quit.
target runtime: <node|browser>
entry file: (app/index.js)
output directory: (dist)
module rules: 
  Idea: maybe implement a full on 
  wizard-like workflow? (potential rabbit hole!)
  1. test patterns: /\.jsx?/
    uses: babel-loader (maybe make suggestions here?)
  2. test patterns (..etc)
do you want to generate a setup file for test runners? (require.context etc)
```

2. Shorthand help shortcuts to specific configuration docs:
```
~/my/project$ webpack-cli docs <config property>
```

* Example values: 
  * resolve:modules
  * module:rules
  * output

* Example usage:
 ```
 ~/my/project$ webpack-cli docs output

 The top-level output key contains set of options instructing 
 webpack on how and where it should output your bundles, 
 assets and anything else you bundle or load with webpack

   - chunkFilename                           <shorthand desc>
   - crossOriginLoading                      <shorthand desc>
   - devtoolFallbackModuleFilenameTemplate   <shorthand desc>
   - devtoolLineToLine                       <shorthand desc>
   - devtoolModuleFilenameTemplate           <shorthand desc>
   - filename                                <shorthand desc>
   - hotUpdateChunkFilename                  <shorthand desc>
   - hotUpdateFunction                       <shorthand desc>
   - hotUpdateMainFilename                   <shorthand desc>
   - jsonpFunction                           <shorthand desc>
   - library                                 <shorthand desc>
   - libraryTarget                           <shorthand desc>
   - path                                    <shorthand desc>
   - pathinfo                                <shorthand desc>
   - publicPath                              <shorthand desc>
   - sourceMapFilename                       <shorthand desc>
   - sourcePrefix                            <shorthand desc>
   - umdNamedDefine                          <shorthand desc>
 ```
    
...I have a lot more I'm kind of excited to add to this list lol.. but these are first that come to mind.

**Comment by ev1stensberg** [comment]
- https://www.npmjs.com/package/inquirer-test
- https://github.com/facebook/jest/blob/master/examples/manual_mocks/__tests__/FileSummarizer-test.js
- https://dmitriiabramov.github.io/jest-cheatsheet/index.html
- https://github.com/SBoudrias/Inquirer.js/tree/master/test
- https://glebbahmutov.com/blog/unit-testing-cli-programs/

**Comment by DanielaValero** [comment]
Here a sumarized list of the on going discussion about the feaures of this package.

## List of suggested features

* Transform a webpack configuration v.1.x to v.2.x
* Create boilerplate setup with customizable implementation
* Add loaders and similar "high-level" features such as entry points / loaders - test loaders configuration (i.e. from an entry point, list files being tested by loader X)
* init - create an empty configuration (similar to npm init or git init)
* setups - create predefined configurations and some files (similar to Yeoman)
* validator - use the built in validation
* hints - recommend non-used features/plugins


### More detailed description of the suggested features
Original comment here: https://github.com/webpack/webpack/issues/3466#issuecomment-266711191

`init`

A way to build a basic webpack configuration. Exactly like webpack-init. We need to cover the following.

* Add entry point and output path.
* Add prewritten configs to add babel support, css/scss/less support, hmr and so on.
* Allow to add DEV and PROD configurations.
* This should build an annotated webpack configuration file.

`add <setup-name>`

Adds prewritten config setup to add new loaders, plugins

`generate <plugin|loader|setup> <options>`

Like ember generate where it can add scaffold for the user to fill up functionality.

`<multiple config options> --save <config-name>`

Save the working config options to the existing webpack config file or create a new config file. Need also an override to rewrite configs.

`validate <config-name>`

Validate existing configuration using webpack's schema validator, give meaningful error messages. Nice to have would be to give helpful improvement hints.

`help <option>`

Kickass help with elaborate examples.

### List of similar initiatives
https://github.com/webpack/webpack/issues/3466#issuecomment-266677349


### Example commands
`$ webpack init --basic | --code-split | --loader=<loader>`


### List of open questions
https://github.com/webpack/webpack/issues/3466#issuecomment-266836772

**Comment by ev1stensberg** [comment]
For the init solution we can prompt this from [Mink](https://github.com/ev1stensberg/mink). Install it, use `npm link` and run `mink -u` or other flags to see example output and interface.

**Comment by carlos-** [comment]
@DanielaValero, the list lgtm. I would prioritize them as you suggested.

I understand `webpack` and `webpack-cli` are in different repositories / npm packages. But in your example command `webpack-cli` is executed as `webpack --init`. How can this be? will `webpack` package require `webpack-cli`? or is it a typo? 

I agree documentation will be also very important, so people do not get confused.

**Comment by ev1stensberg** [comment]
@carlos- It's going to be `webpack <options>` , executing with `webpack-cli` is just development.

**Comment by hulkish** [comment]
@ev1stensberg tbh, I think mink kind of takes it a little further than what makes sense for `webpack-cli`, specifically the parts where it involves exterior library support as part of the generator routine (`react-redux`, for ex).

I think there's value in keeping the idea of `webpack-cli init` just a simple straight forward config initializer.

**Comment by ev1stensberg** [comment]
@hulkish Oh, yeah that's going to be included, but old naming is preserved. We're adding `init` and  `migrate`. If you run `webpack --init react` you should get a webpack config with react support!

**Comment by ev1stensberg** [comment]
What I meant with Mink is that we could reuse some of the interface implementation. It's too broad trying to support all libraries in 1 project, that's why it's best to have an implementation similar to yeoman, but we can look at Mink for implementation insight.

**Comment by hulkish** [comment]
@ev1stensberg agreed, I think maybe allowing for an options like `--post-processor react-webpack-config-processor` (for example) would be great.

**Comment by ev1stensberg** [comment]
We've discussed inline options, could be better to have that as a question in inquirer instead. Else, there should/is going to be an opportunity to create an own package where you'd get that added.

**Comment by hulkish** [comment]
I don't really know where I can fit in on this... but I'd love to help - point me in the direciton! @ev1stensberg @DanielaValero

**Comment by ev1stensberg** [comment]
Send a message to @pksjce , maybe she has some acorn stuff she needs help with!

**Comment by DanielaValero** [comment]
Hello @hulkish 

We are at the moment setting some ground work, and organizing the features, roadmap, etc. Once we've nailed it, and have the groundwork in place, there will be more clear tasks that you or anyone can pick up to help out.

Greetings

**Comment by DanielaValero** [comment]
Will close now as we have already a github issue per feature. We will add in the first stage apart from the options to the compiler, an `init` and a `migrate` tasks.

All the rest: `add <setup-name>`, `generate  <plugin|loader|setup> <options>` and `help <option>`, will be discussed and added after the first version is in place.
