### ISSUE TITLE
Add support for tsimp TS loader

### ISSUE THREAD

**Issue by wojtekmaj** [webpack/webpack-cli#4025]
**Is your feature request related to a problem? Please describe.**

I would like to replace ts-node with tsimp, but when I try to replace

```
    "build": "NODE_ENV=production NODE_OPTIONS='--loader ts-node/esm' webpack",
```

with

```
    "build": "NODE_ENV=production NODE_OPTIONS='--import tsimp/import' webpack",
```

I'm met with the following error:

```
[webpack-cli] Unable load '/Users/wmaj/Projekty/Rewardo/web/webpack.config.ts'
[webpack-cli] Unable to use specified module loaders for ".ts".
[webpack-cli] Cannot find module 'ts-node/register' from '/Users/wmaj/Projekty/Rewardo/web'
[webpack-cli] Cannot find module 'sucrase/register/ts' from '/Users/wmaj/Projekty/Rewardo/web'
[webpack-cli] Cannot find module '@babel/register' from '/Users/wmaj/Projekty/Rewardo/web'
[webpack-cli] Cannot find module 'esbuild-register/dist/node' from '/Users/wmaj/Projekty/Rewardo/web'
[webpack-cli] Cannot find module '@swc/register' from '/Users/wmaj/Projekty/Rewardo/web'
[webpack-cli] Please install one of them
```

**Describe the solution you'd like**

Add tsimp to the list of allowed TS module loaders

**Describe alternatives you've considered**

🤷‍♂️

**Comment by alexander-akait** [comment]
`NODE_ENV=production NODE_OPTIONS='--loader=tsimp/loader' webpack` works fine for me locally without any problem, expect experimental message, check your enviroment, looks like you don't have installed `tsimp` 

Here docs - https://github.com/tapjs/tsimp?tab=readme-ov-file#usage, supported ESM `--import` is still under experiments 

Close due https://github.com/webpack/webpack-cli/issues/3905

Feel free to feedback

**Comment by wojtekmaj** [comment]
@alexander-akait First thing I've tried. Unfortunately, this does not work.

```
[webpack-cli] Unable load '/app/webpack.config.ts'
[webpack-cli] Unable to use specified module loaders for ".ts".
[webpack-cli] Cannot find module 'ts-node/register' from '/app'
[webpack-cli] Cannot find module 'sucrase/register/ts' from '/app'
[webpack-cli] Cannot find module '@babel/register' from '/app'
[webpack-cli] Cannot find module 'esbuild-register/dist/node' from '/app'
[webpack-cli] Cannot find module '@swc/register' from '/app'
[webpack-cli] Please install one of them
```

**Comment by alexander-akait** [comment]
@wojtekmaj strange, maybe you can create a reproducible repo? Because it works locally for me, also please check your version

**Comment by wojtekmaj** [comment]
There is absolutely nothing unusual about my setup. Here's my minimal repro repo:

[web.zip](https://github.com/webpack/webpack-cli/files/13846455/web.zip)

However, I believe the key is that you may have one of the listed packages ('ts-node/register', 'sucrase/register/ts', '@babel/register', 'esbuild-register/dist/node', '@swc/register') installed alongside tsimp, causing the error not to appear.

**Comment by alexander-akait** [comment]
I see the problem, right now you can use:
```
"scripts": {
    "build": "WEBPACK_CLI_FORCE_LOAD_ESM_CONFIG=1 NODE_ENV=production NODE_OPTIONS='--import tsimp/import' webpack --disable-interpret"
},
```

Anyway you still have some problems with ts/babel configuration.

Using `--disable-interpret` you will disable built-in behaviour and using `WEBPACK_CLI_FORCE_LOAD_ESM_CONFIG` you are saing to load configuration as ESM.

Feel free to feedback

**Comment by alexander-akait** [comment]
Anyway in future we will improve it and you will need less extra code to run it, we are waiting `interpret` developers, also we need support `--import` syntax on the `interpret` side (right now only `register` is working)
