### ISSUE TITLE
[Feature]: Init command's splitChunks caching group generation per provided entry

### ISSUE THREAD

**Issue by EugeneHlushko** [webpack/webpack-cli#404]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**
it doesnt output caching group per entry provided

**If the current behavior is a bug, please provide the steps to reproduce.**
after #356 is merged
use `webpack-cli init` and provide multiple entries
Observe splitChunks plugin declaration doesnt add caching group per entry

**What is the expected behavior?**
splitChunks caching groups added per entry

**If this is a feature request, what is motivation or use case for changing the behavior?**
TBD @ev1stensberg 

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**

*NOTE*
When trying to initally set up regexp generation i bumped into a case where user might provide two entries from within same directory when doing simple config generations e.g. for entries user types:
`homepage,blog`

and for entry paths:
```
./src/homepage
./src/blog
```

In this case regexp for catching files in splitChunks will be the same for both entries if entries are
```
./src/homepage.js
./src/blog.js
```

and not directories with a nested `index.js` file.
```
./src/homepage/index.js
./src/blog/index.js
```

**Comment by ematipico** [comment]
We've ready to proceed with this one now

**Comment by bitpshr** [comment]
Is this still a relevant feature? If so, I'd be happy to take it on with a bit of clarification. Is the intention to define a `cacheGroups` entry for each configured `entry` point? Should this behavior be opt-in, or should it be the default when initializing a new project?

**Comment by ev1stensberg** [comment]
yes, @EugeneHlushko could you elaborate some more? 📦

**Comment by bitpshr** [comment]
Cool, thanks. I'll take this one.

**Comment by EugeneHlushko** [comment]
Yeah its pretty much relevant. As @ev1stensberg we think that it should be default for multiple entries. The catch here is described in the issue description, if entries are .js files in one dir, everything will fall under the same caching group, needs a thought.

**Comment by dhruvdutt** [comment]
Sure! Would try to finish over the weekend.

**Comment by evilebottnawi** [comment]
bump
