### ISSUE TITLE
webpack-cli should remove yeoman file at the end of the installation

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#411]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
`cli` doesn't remove the yeomen file

**If the current behavior is a bug, please provide the steps to reproduce.**

* `webpack-cli init`
* answer all the questions
* wait for yarn/npm to install
* notice the yeomen file 

**What is the expected behavior?**
It should remove it

**Comment by ev1stensberg** [comment]
I don't think that **we need to remove it**. Imagine if user wants to do the init command again, then it would save us time to save the `.yo-rc` config

**Comment by ematipico** [comment]
@dhruvdutt because some people (like myself) would like to have a config for development and config for production. Shouldn't we notify the user somehow about what's that file about, at least?

**Comment by buoyantair** [comment]
I'm willing to take this issue :D , from what I just read, it looks like the goal is a bit unsure.. like should we fix or should we warn the user? :3

**Comment by sendilkumarn** [comment]
I also don't want to remove it. It is extremely helpful in many ways. Let us have it

**Comment by ematipico** [comment]
We should update the documentation so
