### ISSUE TITLE
webpack-cli wants `@swc/register` but it is deprecated for `@swc-node/register`

### ISSUE THREAD

**Issue by vergilfromadyen** [webpack/webpack-cli#4129]
**Describe the bug**

**What is the current behavior?**

[This block of logic](https://github.com/webpack/webpack-cli/blob/ebddcafd5865667665e2970d93fc196bc01084fa/packages/webpack-cli/src/webpack-cli.ts#L1804-L1838) sometimes leads to the following error when `@swc-node/register` is used:

```
[webpack-cli] Unable load '/path/to/webpack.config.ts'
[webpack-cli] Unable to use specified module loaders for ".ts".
[webpack-cli] Cannot find module 'ts-node/register' from '/Users/vergil/adyen-main/frontend/apps/dummy'
[webpack-cli] Cannot find module 'sucrase/register/ts' from '/Users/vergil/adyen-main/frontend/apps/dummy'
[webpack-cli] Cannot find module '@babel/register' from '/Users/vergil/adyen-main/frontend/apps/dummy'
[webpack-cli] Cannot find module 'esbuild-register/dist/node' from '/Users/vergil/adyen-main/frontend/apps/dummy'
[webpack-cli] Cannot find module '@swc/register' from '/Users/vergil/adyen-main/frontend/apps/dummy'
[webpack-cli] Please install one of them
```

The error occurs because the `interpret` dependency supports `@swc/register` and not `@swc-node/register`.

**Expected behavior**

`webpack-cli` can use `@swc-node/register`

**Additional context**

I understand the issue occurs because of a dependency to the `interpret` package, but it leads to webpack-cli depending on deprecated packages.

**Comment by alexander-akait** [comment]
Please open an issue in `interpret`, we can't fix it here, sorry, partially closed in favor https://github.com/webpack/webpack-cli/issues/3905, because we want to move this functions inside webpack-cli to fix such problems faster
