### ISSUE TITLE
--help output showing subcommands with `--` prefix

### ISSUE THREAD

**Issue by rossipedia** [webpack/webpack-cli#413]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Webpack's `--help` flag shows the following options:

```
Initialization:
  --init             Initializes a new webpack configuration or loads a
                     addon if specified                                [boolean]
  --migrate          Migrate your webpack configuration from webpack 1 to
                     webpack 2                                         [boolean]
  --add              Adds a webpack component to your configuration file
                                                                       [boolean]
  --generate-loader  Generates a new webpack loader project            [boolean]
  --generate-plugin  Generates a new webpack plugin project            [boolean]
```

The bug is that they're prefixed with `--`, which is not how they're intended to be invoked:

```
$ webpack --init
...
ERROR in Entry module not found: Error: Can't resolve './src' in '/home/bryan/scratch'

$ webpack init
i INFO For more information and a detailed description of each question, have a look at https://github.com/webpack/webpack-cli/blob/master/INIT.md
i INFO Alternatively, run `webpack(-cli) --help` for usage info.

? Will your application have multiple bundles? (Y/n)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

See previous

**What is the expected behavior?**

Help output should show sub-commands without the `--` prefix.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**

```
λ webpack-cli  info

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-3970X CPU @ 3.50GHz
  Binaries:
    Node: 9.11.1
    Yarn: 1.6.0
    npm: 5.6.0
  Browsers: {}
  npmPackages:
    webpack:
      wanted: ^4.6.0
      installed: 4.6.0
    webpack-cli:
      wanted: ^2.0.15
      installed: 2.0.15
```

**Comment by rossipedia** [comment]
I believe this is an issue with yargs, actually. I ran into it recently on a non-webpack project. I'll see about getting a minimal repro and file an issue over on their repo.

**Comment by ematipico** [comment]
Have you also tried with migrate? To me, it looks like the script is working

**Comment by rossipedia** [comment]
The bug isn't with the scripts _themeselves_, it's a problem with the `--help` output being incorrect. (Running with `webpack --migrate` doesn't work, but with `webpack migrate` does).

**Comment by bitpshr** [comment]
I'm taking a look into this one if @ematipico isn't already.

**Comment by ematipico** [comment]
@bitpshr yes sure, go ahead!

**Comment by PlayMa256** [comment]
I could not execute `--init` either, it goes straight to the compilation process. This is actually a "docs" problem since user will try to do that and won't be able to. This can be fixed using the `command` api from `yargs`, [this](https://prnt.sc/j8ysn9) is the result i was able to get.

if @bitpshr could not find a better solution, i guess i could open a pr with this one.

**Comment by ev1stensberg** [comment]
https://medium.com/webpack/announcing-the-new-webpack-cli-75ce1d9b8663 @PlayMa256 intentional

**Comment by ev1stensberg** [comment]
We should strip the dashes

**Comment by PlayMa256** [comment]
Interesting @ev1stensberg, by using the `command` api, would'nt that be much clear to the end user since the first thing someone always do is `--help` on a cli? Or do we prefer "flags" only?

**Comment by rossipedia** [comment]
I think that's going to be difficult to do, as the help output is generated by `yargs`.

IMO [these](https://github.com/webpack/webpack-cli/blob/master/bin/config-yargs.js#L18-L36) should be implemented using `yargs.command()`, instead of `yargs.option()`, as they _are_ commands, logically.

**Comment by PlayMa256** [comment]
I agree with @rossipedia , other than that we are just doing "workarounds", aren't we?

**Comment by ematipico** [comment]
It totally makes sense!
