### ISSUE TITLE
process.loadEnvFile(); fails to load

### ISSUE THREAD

**Issue by Anoerak** [webpack/webpack-cli#4134]
**Describe the bug**

**What is the current behavior?**

When launching webpack (`npm run build`),webpack-cli fails to load the webpack config because of the node `process.loadEnvFile()`.
TypeError: process.loadEnvFile is not a function

**To Reproduce**

Create a basic webpack.js config file, add `process.loadEnvFile();`in order to load your .env (place the .env at the root of your project).

**Expected behavior**

`webpack 5.90.2 compiled successfully in 3195 ms`

**Screenshots**

![Screenshot 2024-04-03 at 18 24 42](https://github.com/webpack/webpack-cli/assets/79709673/bc124077-c459-4d66-97f1-56e8b5c6c30c)

![Screenshot 2024-04-03 at 18 22 02](https://github.com/webpack/webpack-cli/assets/79709673/1865f344-7323-490e-a398-aacf559b027f)

**Please paste the results of `npx webpack-cli info` here, and mention other relevant information**
  System:
    OS: macOS 14.4.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 59.36 MB / 18.00 GB
  Binaries:
    Node: 21.6.2 - ~/.nvm/versions/node/v21.6.2/bin/node
    npm: 10.4.0 - ~/.nvm/versions/node/v21.6.2/bin/npm
  Browsers:
    Chrome: 123.0.6312.87
    Safari: 17.4.1
    Safari Technology Preview: 17.4
  Packages:
    babel-loader: * => 9.1.3
    css-loader: ^6.10.0 => 6.10.0
    postcss-loader: ^8.1.0 => 8.1.0
    sass-loader: ^14.1.0 => 14.1.0
    source-map-loader: ^5.0.0 => 5.0.0
    style-loader: ^3.3.4 => 3.3.4
    webpack: ^5 => 5.90.2
    webpack-cli: ^5.1.4 => 5.1.4
    webpack-merge: ^5.10.0 => 5.10.0
    webpack-notifier: ^1.13.0 => 1.15.0

**Additional context**

**Comment by alexander-akait** [comment]
Sorry, not related to webpack-cli, we don't have such API

**Comment by alexander-akait** [comment]
It is still under development, I don't reccomend to use it right now https://nodejs.org/api/process.html#processloadenvfilepath or please enable it using `node` CLI
