### ISSUE TITLE
[@webpack-cli/generators] Some internal modules has unmet peer dependency.

### ISSUE THREAD

**Issue by stein2nd** [webpack/webpack-cli#4178]
For verification, I temporarily modernised package.json by running 'ncu' and 'ncu -u' under the ‘@webpack-cli/generators’ installation folder.
![©typesyeoman-generator](https://github.com/webpack/webpack-cli/assets/531628/8e6114c5-35fd-47d0-aa01-fe16b6a718f0)

When 'yarn install' was executed, an 'unmet peer dependency' warning for an internal module was displayed.
![Pasted Graphic 4](https://github.com/webpack/webpack-cli/assets/531628/6b206f11-a168-4481-84e0-3824187edfeb)

Some modules that appeared as 'unmet peer dependency' warnings were installed with 'yarn add'.

This was attempted to resolve the deprecated warnings listed below.

> npm warn deprecated inflight@1.0.6:
> This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
![Pasted Graphic 7](https://github.com/webpack/webpack-cli/assets/531628/0b83d4b6-0102-4ce6-aa26-713ad2148312)

> npm warn deprecated read-package-json@6.0.4:
> This package is no longer supported. Please use @npmcli/package-json instead.
![Pasted Graphic 6](https://github.com/webpack/webpack-cli/assets/531628/fd89deb5-67bb-4d77-af11-61d662a47413)

> npm warn deprecated npmlog@5.0.1:
> This package is no longer supported.
![Pasted Graphic 15](https://github.com/webpack/webpack-cli/assets/531628/cb6b1261-246f-438b-bd33-8a824d9a8e70)

> npm warn deprecated npmlog@6.0.2:
> This package is no longer supported.
![Pasted Graphic 14](https://github.com/webpack/webpack-cli/assets/531628/9887109a-3be2-4058-a640-1938065159ce)

> npm warn deprecated @npmcli/move-file@1.1.2:
> This functionality has been moved to @npmcli/fs
![Pasted Graphic 17](https://github.com/webpack/webpack-cli/assets/531628/5c81727f-5d66-4bf5-ad35-a69897e1e6de)

> npm warn deprecated @npmcli/move-file@2.0.1:
> This functionality has been moved to @npmcli/fs
![Pasted Graphic 16](https://github.com/webpack/webpack-cli/assets/531628/59aecd58-fe61-4412-aa2c-495df8906d38)

> npm warn deprecated are-we-there-yet@2.0.0:
> This package is no longer supported.
![Pasted Graphic 13](https://github.com/webpack/webpack-cli/assets/531628/22f20931-5b7a-49a1-a727-d18a24c305dd)

> npm warn deprecated are-we-there-yet@3.0.1:
> This package is no longer supported.
![Pasted Graphic 12](https://github.com/webpack/webpack-cli/assets/531628/5e593980-93d8-4efe-a1b4-21f2960572ef)

> npm warn deprecated gauge@3.0.2:
> This package is no longer supported.
![Pasted Graphic 11](https://github.com/webpack/webpack-cli/assets/531628/76c45871-75c3-481a-aa44-037580cf9887)

> npm warn deprecated gauge@4.0.4:
> This package is no longer supported.
![Pasted Graphic 10](https://github.com/webpack/webpack-cli/assets/531628/80d75f2d-8208-44c1-8379-2831950854e8)

> npm warn deprecated glob@7.2.3:
> Glob versions prior to v9 are no longer supported
![Pasted Graphic 7](https://github.com/webpack/webpack-cli/assets/531628/c35dda46-4d9a-4f1f-9da3-0005921f9be6)

> npm warn deprecated glob@8.1.0:
> Glob versions prior to v9 are no longer supported
![npm-registry-fetch@12 0 2](https://github.com/webpack/webpack-cli/assets/531628/1b4121da-acd2-4ca9-8913-9a308ef801c3)

> npm warn deprecated rimraf@3.0.2:
> Rimraf versions prior to v4 are no longer supported
![yeoman-environment@3 19 3](https://github.com/webpack/webpack-cli/assets/531628/455cc113-ddb8-4aa1-a303-59a038a3cc8b)

> npm warn deprecated debuglog@1.0.1:
> Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
![Pasted Graphic 9](https://github.com/webpack/webpack-cli/assets/531628/a26df892-980b-4a9a-8768-33e588607455)

> npm warn deprecated readdir-scoped-modules@1.1.0:
> This functionality has been moved to @npmcli/fs
![Pasted Graphic 8](https://github.com/webpack/webpack-cli/assets/531628/a870ea42-4025-4b9f-83fb-5917d24adff6)

## System:
 - OS: macOS 14.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 274.02 MB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 22.2.0 - ~/.nodebrew/current/bin/node
 - Yarn: 1.22.22 - /usr/local/bin/yarn
 - npm: 10.8.1 - ~/.nodebrew/current/bin/npm
## npmPackages:
 - @types/inquirer: ^9.0.7 => 9.0.7 
 - @types/yeoman-generator: ^5.2.14 => 5.2.14 
 - @yeoman/types: ^1.2.0 => 1.2.0 
 - mem-fs: ^4.1.0 => 4.1.0 
 - webpack: ^5.91.0 => 5.91.0 
 - webpack-cli: ^5.1.4 => 5.1.4 
 - yeoman-environment: ^4.4.0 => 4.4.0 
 - yeoman-generator: ^7.2.0 => 7.2.0

**Comment by evenstensberg** [comment]
We're removing a lot of these deps once Create Webpack App is done this summer.

**Comment by wilyJ80** [comment]
> We're removing a lot of these deps once Create Webpack App is done this summer.

@evenstensberg may I know what Create Webpack App is? Sorry, didn't find any info about it. I'd love to know. I'm absolutely enjoying this world of JS bundling.

**Comment by evenstensberg** [comment]
It's a generator/scaffolding tool for webpack. Generates basic front end builds with react, typescript et.al
