### ISSUE TITLE
Possible regression webpack-cli@2.1.0

### ISSUE THREAD

**Issue by brunoscopelliti** [webpack/webpack-cli#419]
**Do you want to request a *feature* or report a *bug*?** BUG

**What is the current behavior?**

Webpack just does nothing.
It just doesn't execute the config file.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
console.log("Ok?")

const path = require("path");

module.exports = {
  entry: "./src/index.js",
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "index.js"
  }
};
```

**What is the expected behavior?**

See the log in console, and assets in the dist folder.

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**

Nothing is logged in console; neither the "Ok?" log.
I've tested on windows 10.

**Comment by ev1stensberg** [comment]
Maybe related to #413 PR, I've rebased, give it some minutes and a new version will be published. All tests were green, a bit strange. Let's see in some minutes

**Comment by brunoscopelliti** [comment]
Take the time you need.

**Comment by iernie** [comment]
2.1.1 still doesn't work for me. Multiple node-instances are spun up every second until process is killed.

I forgot to add I'm running Windows 10 with node 10 and npm 6

**Comment by andreujuanc** [comment]
Same here.

**2.0.15:** OK
**2.1.0:** Stuck
**2.1.1:** Stuck

Win10, npm 5.3, node 8.3

**Comment by ev1stensberg** [comment]
Alright, let's try `2.1.2`

**Comment by iernie** [comment]
`2.1.2` works for me! 👍

**Comment by ev1stensberg** [comment]
Sweet :100: , sorry for the inconvenience!

**Comment by andreujuanc** [comment]
Works!   🏹  😛
