### ISSUE TITLE
Question: Test for TTY Context before printing progress

### ISSUE THREAD

**Issue by melloc01** [webpack/webpack-cli#420]
**Do you want to request a *feature* or report a *bug*?**
Improvement

**What is the current behavior?**
Outputs progress on non-TTY contexts, generating loads of ouput

**If the current behavior is a bug, please provide the steps to reproduce.**
1. `webpack --progress` in a non-TTY context

**What is the expected behavior?**
To not print progress. There's a node api for TTY: https://nodejs.org/api/tty.html

**If this is a feature request, what is motivation or use case for changing the behavior?**
CI output gets bloated with process output.

**Comment by ev1stensberg** [comment]
Have you tried setting env variables for `supports-color`? https://github.com/chalk/supports-color/blob/master/test.js#L156-L160

**Comment by ev1stensberg** [comment]
Fixed at #452
