### ISSUE TITLE
Feature: create normal package.json

### ISSUE THREAD

**Issue by DanielRuf** [webpack/webpack-cli#426]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**
Currently there is just a lock file generated but not a normal package.json.
It would be helpful to create one if none exists.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
A package.json should be generated if needed.

**If this is a feature request, what is motivation or use case for changing the behavior?**
`webpack init` should init a whole project if wanted and also generate package.json.

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**

```shell
  System:
    OS: macOS High Sierra 10.13.4
    CPU: x64 Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
  Binaries:
    Node: 8.9.0
    Yarn: Not Found
    npm: 6.0.0
  Browsers:
    Chrome: 66.0.3359.139
    Firefox: Not Found
    Safari: 11.1
  npmGlobalPackages:
    webpack-cli: 2.1.2
```

**Comment by ev1stensberg** [comment]
I don't think that's our intention, webpack-cli init is supposed to be an extension of other tools. You should run `npm init` then the init command from the cli.

**Comment by ev1stensberg** [comment]
Maybe, submit a PR, it's a good first contribution!
