### ISSUE TITLE
getting nre on validation of schema

### ISSUE THREAD

**Issue by catesandrew** [webpack/webpack-cli#4289]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `webpack-cli@3.3.0` for the project I'm working on.

I was getting error over NRE from length array that's non existy from validateSchema response. fix was to check truthy of retval first

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/webpack-cli/bin/convert-argv.js b/node_modules/webpack-cli/bin/convert-argv.js
index c5fc62f..6535289 100644
--- a/node_modules/webpack-cli/bin/convert-argv.js
+++ b/node_modules/webpack-cli/bin/convert-argv.js
@@ -136,7 +136,7 @@ module.exports = function(...args) {
 
 	function processConfiguredOptions(options) {
 		const webpackConfigurationValidationErrors = validateSchema(webpackConfigurationSchema, options);
-		if (webpackConfigurationValidationErrors.length) {
+    if (webpackConfigurationValidationErrors && webpackConfigurationValidationErrors.length) {
 			const error = new WebpackOptionsValidationError(webpackConfigurationValidationErrors);
 			console.error(error.message, `\nReceived: ${typeof options} : ${JSON.stringify(options, null, 2)}`);
 			process.exit(-1); // eslint-disable-line
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by alexander-akait** [comment]
`webpack-cli@3.3.0` is outdated and I highly recommend updating the package to the latest version, thank you
