### ISSUE TITLE
Scoping: What properties to include when running --init

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#43]
#### Agenda: 

Discuss what to transform and scaffold for all use cases. With other words: discuss what goes to the parser via `webpackOptions` or to the transform we have. This is so we can better know what to expect from an inquirer prompt, relative to #42

**Comment by TheLarkInn** [comment]
I think we should provide some sort of sane ENV separation for Dev and Prod environments. At the least separate composable configurations that enforce best practices like using production versions of vue angular and react.

**Comment by lcxfs1991** [comment]
has the project started? Any thing I can help here?

**Comment by ev1stensberg** [comment]
We generally need feedback from prospective users in #42 , and if you wanna contribute there's an open issue at #63 👍

**Comment by ev1stensberg** [comment]
Closed, #42 is now active.
