### ISSUE TITLE
[Init] the command should add the chosen libs into devDep

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#431]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
The init command add the chosen libraries inside the dependencies section of the package.json

**If the current behavior is a bug, please provide the steps to reproduce.**

* Run the init command 
* Answer few questions, make sure to choose something like sass loader, for instance
* Check the package.json

**What is the expected behavior?**
It should add them inside the devDependencies of the package.json

**Comment by ev1stensberg** [comment]
it's already happening though? https://github.com/webpack/webpack-cli/blob/master/lib/generators/init-generator.js#L413

**Comment by ematipico** [comment]
I tried the package on a project and I saw that the dependencies were installed in the wrong section

**Comment by ematipico** [comment]
I ran it through the cli itself.

**Comment by ev1stensberg** [comment]
I'm able to reproduce this, so yeah, let's fix it
