### ISSUE TITLE
Fix: Improve tests at tests/__tests__/parser/validate.test.js at feature/parser

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#44]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

We're performing the actual function call that will throw an error and we simplify the testing of it. You should mock this function instead.

**If the current behavior is a bug, please provide the steps to reproduce.**
replace `expect(object.toString()).toContain('TypeError:')` with what is under.

![skjermbilde 2017-01-27 kl 19 47 01](https://cloud.githubusercontent.com/assets/16735925/22383277/6a903336-e4c9-11e6-9ace-c04e4a06302d.png)

**What is the expected behavior?**

It should output the exact error message instead of an invalid regexp.

**Comment by joshuacolvin** [comment]
I can work on this

**Comment by ev1stensberg** [comment]
Great! The tests aren't well written, so any work on this are greatly appreciated. Keep in mind that the PR is towards the branch `feature/parser`

**Comment by ev1stensberg** [comment]
@joshuacolvin Doing some breaking changes on the branch, you should wait until monday to avoid getting conflicts and failed tests!

**Comment by joshuacolvin** [comment]
@ev1stensberg Thanks! I will wait until monday.

**Comment by ev1stensberg** [comment]
Okay, looks like this is stable until friday. Is there any knowledge/input you need from me before you start @joshuacolvin ?

**Comment by joshuacolvin** [comment]
@ev1stensberg I plan to dig into this tonight so I will let you know. Thanks!

**Comment by ev1stensberg** [comment]
@joshuacolvin Keep me posted!

**Comment by joshuacolvin** [comment]
Sorry I misread what needed to be done here. I am still willing to help with some guidance. 

Just to clarify: the `validateAddons` function needs to be mocked? What is the preferred way to mock functions with jest? Also, should `expect()` be updated to match the error message instead of using `.contains()`?

Any guidance would be appreciated! Feeling a little in over my head.

**Comment by ev1stensberg** [comment]
I'll push a commit for what needs to be done later today. If you see a flag with `TODO`, there's a brief section about what needs to be done. Remove this once done ( this is under ´tests` )

**Comment by joshuacolvin** [comment]
Thanks!

**Comment by ev1stensberg** [comment]
@joshuacolvin Sorry, been running out of time lately. We're having a meeting tomorrow, I'll put it up by then 💯  

Thanks for the help by the way! 👍

**Comment by joshuacolvin** [comment]
No worries! Thanks for the update!

**Comment by ev1stensberg** [comment]
https://github.com/webpack/webpack-cli/tree/feature/parser PR goes to this branch, lemme know if you need anything from me. You have dozens of room for play/experiment 👍

**Comment by ev1stensberg** [comment]
Handing this over to @alistairjcbrown . Evidently the entire folder should be moved as from #35

**Comment by joshuacolvin** [comment]
Thanks for the update!

**Comment by ev1stensberg** [comment]
#59
