### ISSUE TITLE
Feature: Show page results of webpack-scaffolds

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#449]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when there's no place I can find scaffolds.

**Describe the solution you'd like**
It would be nice with a page at `webpack.js.org` that shows us all the `webpack-addons`.

**Additional context**
Note that `webpack-addons` is soon to be renamed to `webpack-scaffold`.

**Comment by sendilkumarn** [comment]
There is already a `webpack-scaffold` available.

**Comment by sendilkumarn** [comment]
Btn I like this idea and yes it is frustrating.

**Comment by ev1stensberg** [comment]
Moved to https://github.com/webpack/webpack.js.org/issues/2168
