### ISSUE TITLE
Add yarn.lock to .gitignore or add yarn's lock file in project

### ISSUE THREAD

**Issue by nveenjain** [webpack/webpack-cli#454]
**Is your feature request related to a problem? Please describe.**
Since we are using yarn in webpack for most of parts (everywhere we setup using simple `yarn` command). When anyone run `yarn`, additional lock file is added to project, which shouldn't be done everytime anyone run 'yarn'.. We can either ignore 'package-lock' as it is generated by npm and keep only yarn.lock in our project directory or we can ignore 'yarn.lock' and  keep only 'package-lock.json' in directory..
**Describe the solution you'd like**
Add yarn.lock to .gitignore or a better thing would be to add package-lock.json to .gitignore since most of our developers use yarn anyway..
I can send a PR, once i get opinion on which file to ignore and which to keep.

**Comment by ev1stensberg** [comment]
Closed per #455
