### ISSUE TITLE
Bug: `--display-entrypoints=false` does not hide entries

### ISSUE THREAD

**Issue by sfger** [webpack/webpack-cli#463]
**Describe the bug**

 `webpack --watch --progress --display-error-details --hide-modules=true --display-chunks=false --display-entrypoints=false` is not work as expected

**What is the current behavior?**

No matter true or false when I give a value of --display-entrypoints, the entrypoints in  the stdout output always shows!  

**To Reproduce**
1. find a project use webpack-cli and open it in the cmd
2. Input the order: webpack --watch --progress --display-error-details --hide-modules=true --display-chunks=false --display-entrypoints=false
3. See the stdout output

**Expected behavior**
--display-entrypoints=false : the entrypoints do not shows

**Screenshots**
![image](https://user-images.githubusercontent.com/2604977/40461180-ab25af22-5f3c-11e8-8af7-e9355bc70c64.png)

**Please paste the results of `webpack-cli info` here, and mention other relevant information*

**Additional context**
I debuged the code in bin/webpack.js:
just change the code from:
				ifArg("display-entrypoints", function(bool) {
					if (bool) outputOptions.entrypoints = true;
				});
to:
				ifArg("display-entrypoints", function(bool) {
					outputOptions.entrypoints = !!bool;
				})
It will work well:)

**Comment by ev1stensberg** [comment]
Could you submit a PR?
