### ISSUE TITLE
Bug: Init command creates invalid config, the entry field is wrong

### ISSUE THREAD

**Issue by senyaak** [webpack/webpack-cli#468]
**Describe the bug**

The init command create incorrect js file. The property 'entry' contains plain string.

**What is the current behavior?**

the entry filed is like this `entry: ./foo/bar`
instead to be like this `entry: './foo/bar'`

**To Reproduce**
```webpack init```
`n`
`[default]`
`[default]`
`Y`
`Y`
`[any]`
`[skip]`
`[default]`
we get `WARNING: Could not apply prettier to webpack.prod.js due validation error, but the file has been created`

**Expected behavior**
entry should contain a string literal

Version: webpack 4.9.1

**Comment by senyaak** [comment]
UDP: if you use default entry point - `Which module will be the first to enter the application? [default: ./src/index] `  - entry will become `entry: 0`

**Comment by ematipico** [comment]
Hi @senyaak , could you please tell us which version of `webpack-cli` you use?

**Comment by senyaak** [comment]
I use last available in npm - 2.1.4

**Comment by ematipico** [comment]
Just investigated and followed how you answered to the questions. Since you chose the defaults, webpack-cli doesn't add the `entry` inside the configuration because it uses the webpack defaults. Maybe the answers that you gave were different?

**Comment by senyaak** [comment]
I tried to use default(then I got `entry: 0`) and I tried to use some path(f.e. `./foo` - then I got `entry: ./foo`)

**Comment by ev1stensberg** [comment]
This is fixed in "webpack-cli@next"
