### ISSUE TITLE
Feature [--migrate]: Validate the generated webpack 2 configuration.

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack-cli#48]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The generated webpack 2 config needs to be validated with the webpack schema.

**If this is a feature request, what is motivation or use case for changing the behavior?**
This feature needs to be present for basic hygeine

**Comment by ev1stensberg** [comment]
@pksjce Working with webpack schema at parser now, could give you feedback on what I'm thinking of it once I'm done.

**Comment by ev1stensberg** [comment]
Resolved in #99
