### ISSUE TITLE
Missing release notes / changelog for 3.x

### ISSUE THREAD

**Issue by robcresswell** [webpack/webpack-cli#489]
There are no entries in the Releases tab or `CHANGELOG` for version `3.x`. Any chance of some details in there so we can figure out what the breaking change was?

**Comment by ev1stensberg** [comment]
HI, have a look at my comment here: https://github.com/webpack/webpack-cli/pull/448#issuecomment-394172842

**Comment by robcresswell** [comment]
```
There's no breaking changes if you're using webpack without any features like init migrate etc.
```

Sorry for my stupidity, but this seems a little vague; if you are using `init` or `migrate`, what has changed? This isn't documented anywhere. It might be worth adding something to the Releases page too, so you don't have others constantly opening issues asking for changelogs.

**Comment by ev1stensberg** [comment]
If you read the blog post, there's a more elaborating writing there

**Comment by robcresswell** [comment]
I appreciate that, but can we not just stick to the usual formats like release notes and changelogs? Parsing those is one thing, hunting for "some blog post" every time a JS lib posts a breaking change is kinda excessive, IMO. In the current state, it's just not explained in the repo unless you try and understand the code.

**Comment by ev1stensberg** [comment]
Yep, will do that. Thanks for the explaination and elaboration @robcresswell

**Comment by robcresswell** [comment]
Thanks @ev1stensberg, I really appreciate that

**Comment by jeffbyrnes** [comment]
Looks like we’re still missing changelog entries for v3.0.0; I ran into a situation where I wanted to see if I should upgrade, and finally landed here, leading me to the other issue & the blog post.

**Comment by ev1stensberg** [comment]
My bad, I’ll draft a release when I get the time

**Comment by ev1stensberg** [comment]
Here's the release https://github.com/webpack/webpack-cli/releases/tag/v3.0.0. We used a auto-commiter and publisher in early v.3 and we had some trouble with versioning. Sorry for the inconvinience

**Comment by jeffbyrnes** [comment]
Thanks @evenstensberg! All good; versioning is hard, and auto-versioning harder still.

**Comment by evenstensberg** [comment]
Yep and people we’rent happy about having to update their dependencies that often. Send me a message if you have any additonal questions!
