### ISSUE TITLE
Feature [--migrate]: Enhance the diff output after migrate command is run

### ISSUE THREAD

**Issue by pksjce** [webpack/webpack-cli#49]
**Do you want to request a *feature* or report a *bug*?**
Feature enhancement

**What is the current behavior?**
Currently we are showing some basic diffs between the original config and the new webpack2 config created for the approval of user.

**What is the expected behavior?**
We would like to enhance this to state the reason for each of the change. This could guide the user to nuances of the change made and explain concisely what exactly the transformations did.

**If this is a feature request, what is motivation or use case for changing the behavior?**
This is educational and makes the migration more reasonable

**Comment by ev1stensberg** [comment]
I think diff output has been implemented, reopen if not
