### ISSUE TITLE
CHANGELOG out of sync with release

### ISSUE THREAD

**Issue by sebastianhaeni** [webpack/webpack-cli#495]
**CHANGELOG out of sync with release**

The [CHANGELOG](https://github.com/webpack/webpack-cli/blob/master/CHANGELOG.md) is out of sync with the released version.

* Please update the changelog.
* Or if you wish to not update the changelog, delete it and instead add change logs to the release on GitHub.

As of now, I have no clue what changed in version 3.0.0 without looking at the commits. Or am I missing something?

And then there's the confusion about what version actually got released since the version in `package.json` says `0.0.8`.

Please clarify in your docs.

**Comment by ematipico** [comment]
Will do

**Comment by ev1stensberg** [comment]
Any update on this?

**Comment by ematipico** [comment]
The changelog command doesn't work as expected so I don't know how to proceed

**Comment by ev1stensberg** [comment]
Okay let me have a look later today

**Comment by ev1stensberg** [comment]
Fixed in #512 . Keep in mind that version numbers are from the next branch so they are not accurate. Nonetheless, the commits are there. Sorry for the inconvenience!
