### ISSUE TITLE
Discussion: How to depend from webpack and publish the cli to be used in webpack

### ISSUE THREAD

**Issue by DanielaValero** [webpack/webpack-cli#53]
**Motivation:**
Make a plan to be able to use code from `webpack`, such as the validation or the schema, and at the same time publish the `webpack-cli` to`npm` so the project can be imported in `webpack`, so is a built in functionality.

**Problem:**
When we add `webpack` in our dependencies, and later on, `webpack` adds us as a dependency, we would get to the circular dependency problem.

How could we avoid this issue? 

Should we have the validation and schema published as a separate package, which can be consumed by `webpack` and `webpack-cli` without generating a circular dependency problem?

**Comment by okonet** [comment]
I think webpack-cli will have webpack as a dependency or am I wrong?

**Comment by DanielaValero** [comment]
Yes, this way we can consume the validation and schema from webpack.

But after we are finished, the core team wants to have webpack-cli as a dependency, to run all the cli features built-in.

**Comment by ev1stensberg** [comment]
>Yes, this way we can consume the validation and schema from webpack.

That's not true. We need to make tweaks to the schema and validation in the future. Would be better of to depend on it from our own file.

**Comment by okonet** [comment]
I think schemas should be shared across repos and be under SemVer. In this case we can always pin a proper dependency in case of such tweaks. We can use webpack as monorepo and still have multiple packages published from it. See how Jest does it. Or we could extract them to a separate repo (which might make more sense TBH if we want to promote these for IDE and text editor creators).

**Comment by DanielaValero** [comment]
I'd tend to agree on the separate repos idea.

Also we need to consume the validation

**Comment by ev1stensberg** [comment]
Used as dependency for now, core team considering to be used as peerDep.
