### ISSUE TITLE
[CI] Travis doesn't kick any build

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#530]
**Describe the bug**
Travis is not kicking any build 

**What is the current behavior?**
PRs are not checked though CI

**To Reproduce**
Just open a PR

**Expected behavior**
It should run and show it inside the checks

**Screenshots**
N/A

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
N/A

**Additional context**
N/A

**Comment by ev1stensberg** [comment]
I'll enable it again.
