### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by IzaGz** [webpack/webpack-cli#542]
```
./node_modules/webpack-cli/bin/webpack.js migrate webpack.config.js 
? Migration output path not specified. Do you want to use your existing webpack configuration? Yes
 ✔ Reading webpack config
 ❯ Migrating config to newest version
   ✔ loadersTransform
   ✔ resolveTransform
   ✔ removeJsonLoaderTransform
   ✖ uglifyJsPluginTransform
     → Cannot read property 'length' of null
     loaderOptionsPluginTransform
     bannerPluginTransform
     extractTextPluginTransform
     noEmitOnErrorsPluginTransform
     removeDeprecatedPluginsTransform

 ✖ ︎Migration aborted due to some errors: 

{ TypeError: Cannot read property 'length' of null
    at NodePath.rootNode.find.forEach.node (/Users/z/project/node_modules/webpack-cli/lib/utils/ast-utils.js:78:16)
    at __paths.forEach (/Users/z/project/node_modules/jscodeshift/src/Collection.js:76:36)
    at Array.forEach (native)
    at Collection.forEach (/Users/z/project/node_modules/jscodeshift/src/Collection.js:75:18)
    at findPluginsArrayAndRemoveIfEmpty (/Users/z/project/node_modules/webpack-cli/lib/utils/ast-utils.js:71:58)
    at module.exports (/Users/z/project/node_modules/webpack-cli/lib/migrate/uglifyJsPlugin/uglifyJsPlugin.js:120:2)
    at Timeout.err [as _onTimeout] (/Users/z/project/node_modules/webpack-cli/lib/migrate/index.js:37:13)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
  context: 

```

**Comment by ev1stensberg** [comment]
Hi @IzaGz , could you use the issue template that is provided next time? Which version are you on?

**Comment by ev1stensberg** [comment]
Moved to #541

**Comment by ev1stensberg** [comment]
Could you move to the latest version? It should be no problem for you

**Comment by IzaGz** [comment]
@ev1stensberg  i use webpack 2 i am migrating from webpack 1 to 2
i see this library for migrationg from 1 to 2 only. But why i see this error?
`webpack-cli@2.1.5 requires a peer of webpack@^4.0.0 but none was installed.`

**Comment by ev1stensberg** [comment]
What happens if you run the newest version? Any errors? Ignore those warnings for now

**Comment by ev1stensberg** [comment]
Try `v.3.2` and up. Just upgrade to the latest, that's the easiest way to get the error gone.

**Comment by IzaGz** [comment]
@ev1stensberg  but where can i found the list of versions? in the  https://github.com/webpack/webpack-cli/releases page only  3.0.8 last
i tried npm i -S webpack-cli@latest - I thought this will install the latest version...
How could i now the real latest version?

**Comment by ev1stensberg** [comment]
`npm uninstall webpack-cli && npm install --save-dev webpack-cli@latest`

**Comment by IzaGz** [comment]
@ev1stensberg it installs 3.0.8 version

**Comment by ev1stensberg** [comment]
Could you check with version is the latest one in Npm? Try to install rhat. There's no breaking things CLI wise for you to be stuck at updating the dependency

**Comment by mayanksingh0821** [comment]
Issue is still present with webpack-cli 3.1.2, why is this issue closed?

**Comment by ematipico** [comment]
File a new issue please. The source of the problem could be different
