### ISSUE TITLE
--output-library does not accept arrays

### ISSUE THREAD

**Issue by Hoten** [webpack/webpack-cli#557]
**Describe the bug**

Unable to pass an array-value to `--output-library`.

```
webpack --output-library-target window --output-library key1 key2 ./src/main.js
webpack --output-library-target window --output-library key1 --output-library key2 ./src/main.js
```

At least one of these formats should pass `["key1", "key2"]` to the `output.library` option. However, only one value can be passed.

**What is the current behavior?**

output is currently something like
```
window.key2=...
```

**Expected behavior**

should be
```
window.key1=window.key1||{},window.key1.key2=...
```

**Comment by Hoten** [comment]
By the way, yargs does support this: https://github.com/yargs/yargs/pull/164

**Comment by ev1stensberg** [comment]
Seems like a easy fix. Do you mind sending a PR?

**Comment by Hoten** [comment]
I've forked and gave it a shot. It's not really clear how to even build the project. I'm afraid I'll just be using a workaround (which is to just define this value in the config file directly).
