### ISSUE TITLE
When in watch mode, pressing Enter should force a rebuild

### ISSUE THREAD

**Issue by jktravis** [webpack/webpack-cli#563]
**Is your feature request related to a problem? Please describe.**
Sometimes, webpack either rebuilds too fast, or I'm generally unsure if it has finished rebuilding (maybe I missed a notification from webpack-notifier). And I just want to force a rebuild. Now, I presume the only thing I can do is stop and restart the watch.

**Describe the solution you'd like**
Something similar to Jest's watch mode (but without all the options.) Mostly, I just want to be able to press Enter and it rebuild. 

**Describe alternatives you've considered**
Just stopping and restarting.

**Additional context**
no additional context

**Comment by ematipico** [comment]
I usually re save a file a new build runs. Same thing with Jest

**Comment by jktravis** [comment]
With Jest, I can press enter to trigger a new test run. I mean, it's fine without it I guess.

**Comment by ev1stensberg** [comment]
Working on a similar feature @jktravis , probably in early beta within 3 weeks.

**Comment by evenstensberg** [comment]
Moved to #586
