### ISSUE TITLE
bug: require(...).default is not a function

### ISSUE THREAD

**Issue by huixisheng** [webpack/webpack-cli#572]
**Describe the bug**

`package.json` with content 

```
...
  "devDependencies": {
    "@webpack-cli/generate-plugin": "0.0.8",
    "@webpack-cli/init": "^0.1.0",
    "@webpack-cli/migrate": "^0.1.0",
    "webpack": "^4.17.1",
    "webpack-cli": "^3.1.0"
  },
...
```

**What is the current behavior?**

```
TypeError: require(...).default is not a function
    at promptForInstallation (/Users/huixisheng/x/lab/webpack/webpack-plugin-demo/node_modules/webpack-cli/bin/prompt-command.js:108:30)
    at /Users/huixisheng/x/lab/webpack/webpack-plugin-demo/node_modules/webpack-cli/bin/cli.js:45:37
    at Object.<anonymous> (/Users/huixisheng/x/lab/webpack/webpack-plugin-demo/node_modules/webpack-cli/bin/cli.js:530:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**To Reproduce**

1. npx webpack-cli generate-plugin
2. vi remote default
```
	} else {
		require(pathForCmd)(...args); // eslint-disable-line
	}
```

**Expected behavior**

only  my-webpack-plugin create.

**Screenshots**

![image](https://user-images.githubusercontent.com/1518967/44596785-19232480-a800-11e8-8867-a71c99a09b8c.png)

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 8.11.1 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 54.0
    Safari: 11.1.2
  npmPackages:
    webpack: ^4.17.1 => 4.17.1 
    webpack-cli: ^3.1.0 => 3.1.0 
    webpack-defaults: ^2.3.0 => 2.3.0 
  npmGlobalPackages:
    webpack-cli: 3.1.0
    webpack: 4.17.1
```

**Additional context**
Add any other context about the problem here like linking to an similar issue you might think is the cause.

**Comment by ev1stensberg** [comment]
@dhruvdutt do you mind fixing this?

**Comment by dhruvdutt** [comment]
This is happening because you have older version of `"@webpack-cli/generate-plugin": "0.0.8"` which is incompatible with the current version of `webpack-cli`.

Can you please upgrade to latest version `0.1.0` of `@webpack-cli/generate-plugin`?

**Comment by huixisheng** [comment]
I try to install  `@webpack-cli/generate-plugin@0.1.0`. but Can't find package `@webpack-cli/generate-plugin@^0.1.0`.

![image](https://user-images.githubusercontent.com/1518967/44616926-2128a600-a88c-11e8-8eaf-5ee15eee0ae0.png)

![image](https://user-images.githubusercontent.com/1518967/44616929-4c12fa00-a88c-11e8-98ac-7a3b62f90758.png)

I will do with `npm cache verify`,  `yarn cache clean ` in the process.

**Comment by ematipico** [comment]
https://www.npmjs.com/package/@webpack-cli/generate-loader

It looks like it's there. Are you hitting the correct registry?

**Comment by ev1stensberg** [comment]
Seems like we might need to support China ( Tabao ) as well. Makes sense?

**Comment by ematipico** [comment]
Yes

**Comment by dhruvdutt** [comment]
@huixisheng We're identified and resolved the issue. We'll soon release a new version with the fix.

**Comment by huixisheng** [comment]
👍

but will do scripts webpack-defaults, it's default config ?

```
npm WARN deprecated @types/commander@2.12.2: This is a stub types definition for commander (https://github.com/tj/commander.js). commander provides its own type definitions, so you don't need @types/commander installed!

> webpack-defaults@2.3.0 postinstall /Users/huixisheng/x/lab/webpack/webpack-plugin-demo/node_modules/webpack-defaults
> node lib/post_install.js
```

**Comment by ev1stensberg** [comment]
Could you elaborate @huixisheng ?

**Comment by huixisheng** [comment]
The generated files are all redundant except `my-webpack-plugin` folder ?

![image](https://user-images.githubusercontent.com/1518967/45007141-faf2cb00-b02e-11e8-90c1-0c7042298de7.png)

**Comment by ev1stensberg** [comment]
I don't think I understand your question. Are you trying to run webpack-defaults and you are wondering if it is ok to run it through webpack-cli?

**Comment by duzy** [comment]
I came across the same issue, this is properly a fix:

``` js
	} else {
          let p = require(pathForCmd), c = p[packages];
          if (typeof c === 'function') {
            c(...args);
          } else if (typeof p.default === 'function') {
	    p.default(...args); // eslint-disable-line
          }
	}
```

which replaced the original (`prompt-command.js`):

``` js
	} else {
          require(pathForCmd).default(...args); // eslint-disable-line
	}
```

**Comment by ev1stensberg** [comment]
Maybe you can do a PR to fix this? That would be great 🤗😍

**Comment by duzy** [comment]
> Maybe you can do a PR to fix this? That would be great

https://github.com/webpack/webpack-cli/compare/master...duzy:patch-1

https://github.com/webpack/webpack-cli/pull/589
