### ISSUE TITLE
[Feature]: Implement api for reporters and implement `stylish` reporter

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack-cli#575]
**Is your feature request related to a problem? Please describe.**

Implement api for `reporter` to allow people choose webpack output.

**Describe the solution you'd like**

Just add option `--reporter [name]`/`--reporter path/to/reporter.js`.

Also have built-in reporters, example `standard` (maybe best name) and `stylish`.

**Describe alternatives you've considered**

Now we have only https://github.com/webpack-contrib/webpack-stylish as plugin. It is bad solution, reporters should be part of `webpack-cli`.

**Additional context**

Link on https://github.com/webpack-contrib/webpack-stylish

In near future i will archived `webpack-stylish` and `webpack-command` repos to avoid misleading.

**Comment by ev1stensberg** [comment]
Setting this as a high priority. Doing this after new CLI is out. Plan is to use webpack stylish as a default reporter.

**Comment by dhruvdutt** [comment]
@ev1stensberg Can you please update #87 if this has been moved?

**Comment by ematipico** [comment]
We risk to lose track of what we need to address. 

Let's close this is only if completed or the umbrella issue has been updated.

Thanks.

**Comment by ev1stensberg** [comment]
ok

**Comment by evenstensberg** [comment]
@hulkish has some nice ideas here

**Comment by anshumanv** [comment]
@EugeneHlushko can you please provide your input on this? 😄

**Comment by evenstensberg** [comment]
We can combine this with webpack-logger?

**Comment by misterdev** [comment]
Some work on this has been done [here](https://github.com/misterdev/webpack-reporter-plugin)

**Comment by evenstensberg** [comment]
Need to add reporter flag

**Comment by evenstensberg** [comment]
This is done, we need to add a flag to add reporter to the config, other than that, we're jazz 🎼

**Comment by hemal7735** [comment]
> This is done, we need to add a flag in the CLI to add reporter to the config, other than that, we're jazz 🎼

@evenstensberg how are taking forward given that we have a `reporter` added. I can pick up if you provide a little bit of guidance.

**Comment by evenstensberg** [comment]
Add the plugin if the flag is present, that's it

**Comment by hemal7735** [comment]
@evenstensberg can you elaborate please?

**Comment by evenstensberg** [comment]
So to add this feature you will need to:

1) Check if a flag named `--output-reporter` is present
2) If so, add the reporter plugin to a configuration


You will need to add the flag to `cli-flags.js`

**Comment by snitin315** [comment]
@evenstensberg  working on this one.

**Comment by snitin315** [comment]
> If so, add the reporter plugin to a configuration

can anyone provide me the link to the reporter plugin?

It's not listed here [https://webpack.js.org/plugins/](https://webpack.js.org/plugins/)

**Comment by misterdev** [comment]
@snitin315 This is probably the plugin you are looking for https://github.com/misterdev/webpack-reporter-plugin

**Comment by marcofugaro** [comment]
wtf, how is this highly requested feature being closed

**Comment by alexander-akait** [comment]
Fixed for `webpack@5`, you can use hooks to customize stats output, example of default plugin https://github.com/webpack/webpack/blob/master/lib/stats/DefaultStatsPrinterPlugin.js, also stats was refactored for webpack@5 and looks good, anyway if you have ideas how we can improve it better, please open an issue in webpack repo

**Comment by lonix1** [comment]
I arrived here from the [`webpack-stylish` repo](https://github.com/webpack-contrib/webpack-stylish), which was deprecated as the reporter was added to the cli.

But I can't find how to enable it :smile: 

How do I get the same as the stylish plugin:

<img src="https://raw.githubusercontent.com/webpack-contrib/webpack-stylish/master/assets/screenshot.png"/>

**Comment by marcofugaro** [comment]
@alexander-akait there is no documentation at all on how to use the `DefaultStatsPrinterPlugin`. 

The webpack output is nowhere near the webpack-stylish one, and there is no documentation on how to achieve what users like @lonix1 want.

**Comment by alexander-akait** [comment]
@marcofugaro default webpack v5 output is like `stylish`, why do you need modify output

**Comment by marcofugaro** [comment]
This does not look anything like the `stylish` screenshot a couple of comments above.

![image](https://user-images.githubusercontent.com/7217420/108201254-df58dd80-711f-11eb-8cf3-65cf643acb12.png)

Please provide a way for users to get that kind of output as it was in `webpack-stylish`.

**Comment by alexander-akait** [comment]
It is improve stylish - assets with size + flags + entry points + version and time

**Comment by lonix1** [comment]
I fail to see how the new report is better than the old report, but maybe it's just me! :smile:

@marcofugaro or anyone else: Do you know how to get a pretty report like before?

**Comment by marcofugaro** [comment]
> but maybe it's just me!

It's not just you.

> Do you know how to get a pretty report like before?

You have to disable the default webpack output with `stats: false` and then you have to do your custom logging relying on the hooks exposed by the [event-hooks-webpack-plugin](https://github.com/cascornelissen/event-hooks-webpack-plugin).

**Comment by lonix1** [comment]
> You have to disable the default webpack output with `stats: false` and then you have to do your custom logging relying on the hooks exposed by the event-hooks-webpack-plugin

So basically: reinvent the wheel or use the new report ;-)
