### ISSUE TITLE
Bug: No types declarations of packages

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack-cli#577]
**Describe the bug**
Couldn't import packages in typescript file

**What is the current behavior?**
After importing `webpack-scaffold` in a typescript file.
I cant use any of its prompt functions like `Confirm` , `Input`, etc. as it doesn't have any types declaration 

**Expected behavior**
Being able to import packages and use its functions and other methods

**Screenshots**
![untitled](https://user-images.githubusercontent.com/15812317/44983987-ce8c6f80-af98-11e8-86eb-fd91848543f5.png)

**Additional context**
simple fix is to set `"declaration": true` in `ts-config.json` file under complierOptions  and add folllowing in `package.json`
```json
types: '<filename>.d.ts'
```
refers: sendilkumarn/webpack-scaffold-pwa#59

**Comment by ematipico** [comment]
Fixed in #578

**Comment by rishabh3112** [comment]
When will this ship to npm @ematipico?

**Comment by ev1stensberg** [comment]
If emanuelle has write access to npm he can do it now
