### ISSUE TITLE
[Feature]: webpack interactive command

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#586]
**Is your feature request related to a problem? Please describe.**
As apart of the new CLI, one thing that would be nice to have is a `webpack interactive` command. This way, users that are in the middle of a git rebase or want to pause compilation by any means, can do that. In addition, it would be nice to have a interactive terminal where you can specify watch mode, what files to compile and such.

**Describe the solution you'd like**
Implement a functional interactive CLI first, look at how [`jest watch`](https://jestjs.io/docs/en/cli.html#running-from-the-command-line) is doing this.

![skjermbilde 2018-09-15 kl 10 15 23](https://user-images.githubusercontent.com/16735925/45584235-58f59d00-b8d0-11e8-887b-38b7a18e4316.png)
 
The features that should be available would be:

• m: filter modules
• p: pause watching (i. e. when doing git actions)
• r: reload configuration and restart webpack
• c: clear cache and recompile
• e: explore mode to interactively walk the module/chunk graph to find out why a module is included
• w: select a module and print out why it's included
• q: quit

**Describe alternatives you've considered**
N/A

**Additional context**

This PR should go against the branch #527 is pointed towards. Feel free to reach out to any of the CLI members to get assistance in implementing this!

The only thing left to do, is to implement the logic for the command, which should be done as a method [here](https://github.com/webpack/webpack-cli/blob/refactor-bin-folder/lib/commands/internal.js#L1)

Happy hacking! 💙

**Comment by Rohanhacker** [comment]
can I work on this ? This will be my first contribution to webpack cli

**Comment by ev1stensberg** [comment]
Gladly!

**Comment by Rohanhacker** [comment]
@ev1stensberg thanks

**Comment by ev1stensberg** [comment]
Yes, but you should be able to do the commands as mentioned in the issue. No, these options are new, so you'll have to experiment a bit yourself!

**Comment by LakshSingla** [comment]
@ev1stensberg Is this issue closed or is there any way I can contribute towards it ?

**Comment by LakshSingla** [comment]
@ev1stensberg `lib/webpack-cli.js` uses `internal.js` but passes arguments in the constructor (which is not yet implemented in `internal.js`). I am presuming that `internal.js` is WIP. Should I implement the `constructor` in `internal.js`? Also many tests currently fail. Is that part any of my concern, or should I write my own tests for the `interactive` command.

**Comment by LakshSingla** [comment]
@ev1stensberg Alright thanks!! So heres the course of action I will take 
 - [ ] Create a new NPM package in `/packages` under the name `@webpack-cli/interactive`
 - [ ] Implement the logic for an interactive prompt 
 - [ ] Implement the logic for functions present in the prompt. 
I understand that the logic corresponding to `p (pause)` and `q (quit)` would have to be wriitten by me. Also, corresponding to `r (reload)` would be implemented by the core `webpack-cli` and would not require much task. I will begin with these and hit you up as I progress regarding the other features to be developed.

**Comment by LakshSingla** [comment]
@ev1stensberg For asynchronously reading the data from the `stdin` should I use an external npm package like `linebyline(former 'readline')` or `readline` npm package ( provided in Node v10 ). Any other package suggestion is also welcomed.
If we have single character keycodes for actions, we can implement it in react-native style, by using rawmode of `process.stdin` and `readline` module to add `keypress` event listener to `process.stdin`.

**Comment by LakshSingla** [comment]
#### UPDATE: 
 - I have implemented `react-native` like interface for the `interactive` command wherein pressing a single character would register it and process the output. The `interactive` passes the CLI arguments it takes directly to the `webpack` command being executed via `child_process` module. I will use `chalk` to colorize the output and possibly `inquirer` for tasks such as walking the module graph etc.
#### ISSUES: 
 - The ouput from the `webpack` command is not colorized when I invoke it using `spawn:child_process` function in Node. Is there any workaround for this. I am looking into `spawn` and `webpack` documentation to see the reason why this is happening.

**Comment by ematipico** [comment]
Try go give a try to `execa`, package to handle child processes. We introduced in one of the PRs and maybe it could help you solving your issue

**Comment by LakshSingla** [comment]
@ematipico Currently the issue I am facing is with `--watch`. On subsequent builds, the `stdout` from the childprocess is blurted out to the parent's `stdout`, irrespective of `pipe` or `inherit`.

**Comment by IshaanDesai45** [comment]
@LakshSingla did using 'execa' solved the problem for u?? because I am facing a similar situation

**Comment by IshaanDesai45** [comment]
@evenstensberg @ematipico for the clear cache mode, do I have to clear the entire cache available at that point or just the build cache that includes the files in the memory in watch mode.
because if we clear the entire the cache, the recompilation would take more time because it will neither have resolver's cache nor the build cache. So build time would be approx equal to initial build.
And for the reload mode , I am having trouble figuring out how webpack access or processes the webpack-config file, can you guys help??

**Comment by anshumanv** [comment]
bump

**Comment by rishabh3112** [comment]
bump

**Comment by harish-sethuraman** [comment]
bump

**Comment by alexander-akait** [comment]
@webpack/cli-team Let's close, I guess we'll never work on it, also it didn't gain enough popularity, other bundlers don't use it, and I think having two output modes is not a good idea, we better focus on one and will continue improve it
