### ISSUE TITLE
Feature: End to End Tests

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#587]
**Is your feature request related to a problem? Please describe.**
We do not have a good test setup written yet. It would be nice to have a end2end test setup for webpack-cli.

**Describe the solution you'd like**
1. Consuming a docker container
2. Run a lot of tests that produce output
3. Check validity of those

**Describe alternatives you've considered**
N/A

**Additional context**
You could look at how yarn does E2E for inspiration: https://github.com/yarnpkg/yarn/tree/master/end_to_end_tests

Happy hacking! 💚

**Comment by AjayPoshak** [comment]
@ev1stensberg Do you have any idea on how to test prompts?  I have started with `init`, but facing difficulty to find a way to test prompts.

**Comment by ev1stensberg** [comment]
I think inquirer has an issue open if you google it

**Comment by evenstensberg** [comment]
I think this is not needed when we have a rigid testing system with /bintestcases.
