### ISSUE TITLE
Feature: Smoketests

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#588]
**Is your feature request related to a problem? Please describe.**
It would be nice to have smoketests to ensure that configurations we produce are valid. These smoketests should be designed to stress the library, to make sure that we are producing valid configurations with various of configuration options.

**Describe the solution you'd like**
A smoketest implementation that produces a webpack configuration, boots up a local server and tests the configuration on an `index.html` page, making sure it is valid. Look at `lighthouse` on how they have their infrastructure set up. 
https://github.com/GoogleChrome/lighthouse/blob/master/package.json#L26

**Describe alternatives you've considered**
N/A

**Additional context**

Happy hacking! ❤️

**Comment by bismarkhenao** [comment]
Hi @evenstensberg can I work on this, It would be my first contribution to webpack 👍

**Comment by evenstensberg** [comment]
Go ahead! Thank you so much ☺️

**Comment by pranshuchittora** [comment]
@evenstensberg Can I work on this issue if it's still open?

**Comment by evenstensberg** [comment]
Yes

**Comment by pranshuchittora** [comment]
Need help, How to setup local server for the testing of the configurations.

**Comment by evenstensberg** [comment]
https://github.com/GoogleChrome/lighthouse/blob/master/package.json#L23
