### ISSUE TITLE
Ench: Consider removing either appveyor or travis over Azure

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#590]
**What is the current behavior?**
Right now we have 3 CI's. Awesome thing to have, but is it really needed?

**If the current behavior is a bug, please provide the steps to reproduce.**
Look at PR and see all the CI's running.

**What is the expected behavior?**
1 less CI service

**If this is a feature request, what is motivation or use case for changing the behavior?**
Maintenance 

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**
N/A

**Comment by ematipico** [comment]
Appveyor is not needed, we can remove it from my point of view. 
Do travis supports CI on Windows OS?

**Comment by ev1stensberg** [comment]
It should

**Comment by dhruvdutt** [comment]
@ematipico Can we close this? Also, can you please check my above comment?

**Comment by ematipico** [comment]
Well, we still have two CIs. We should narrow down to only one. 
I read that Azure doesn't support caching and they are still working on that. On the other hand Azure supports Windows while Travis doesn't. Thoughts? 

I think Windows is needed on a CLI environment

**Comment by ematipico** [comment]
I've tried to re run a build on Azure and it didn't work. Not good atm

**Comment by ev1stensberg** [comment]
Okay. Can you take a look at it Emanuelle? That would be really 👏🏽

**Comment by ev1stensberg** [comment]
Azure seems to be running windows though? What's the bug?
