### ISSUE TITLE
Fail building the project: Cannot find multiple modules 

### ISSUE THREAD

**Issue by EvsChen** [webpack/webpack-cli#591]
I'm new to webpack-cli and clone this project to build locally.

**Describe the bug**

I follow the instruction in CONTIBUTING.md and run the following. 

```bash
yarn install 
yarn link 
yarn link webpack-cli
```
Everything works well and no errors.

Then I run `yarn test` to make sure everything is installed well. Then the `TS2307 error: Cannot find module` comes out.

**What is the current behavior?**

I just paste some of the first missing modules here, but the list is a lot longer.
```bash
> webpack-cli@3.1.0 build /Users/chenshenyue/webpack-cli
> tsc

packages/add/index.ts:1:30 - error TS2307: Cannot find module '@webpack-cli/generators/add-generator'.

1 import defaultGenerator from "@webpack-cli/generators/add-generator";
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


packages/add/index.ts:2:32 - error TS2307: Cannot find module '@webpack-cli/utils/modify-config-helper'.

2 import modifyConfigHelper from "@webpack-cli/utils/modify-config-helper";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


packages/generate-loader/index.ts:1:29 - error TS2307: Cannot find module '@webpack-cli/generators/loader-generator'.

1 import LoaderGenerator from "@webpack-cli/generators/loader-generator";
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


packages/generate-loader/index.ts:2:25 - error TS2307: Cannot find module 'yeoman-environment'.

2 import * as yeoman from "yeoman-environment";
```

**To Reproduce**
Just follow the CONTIBUTING guide to setup the project using yarn as I listed before.

**Additional context**
node version: 8.12.0
yarn version: 1.7.0
npm version: 6.4.1

**Comment by ematipico** [comment]
Hi!

In order to build the project you have to run the bootstrap command as well. We use lerna to orchestrate the packages

**Comment by EvsChen** [comment]
Thanks a lot @ematipico ! That's the missing piece I'm looking for. Would it be better to mention it in the CONTRIBUTING.md?  Otherwise it seems misleading for newcomers.

**Comment by ematipico** [comment]
Totally legit! Feel free to send a PR if you want :)

**Comment by ev1stensberg** [comment]
CC @fokusferit https://github.com/webpack/webpack-cli/issues/591#issuecomment-421777568

**Comment by EvsChen** [comment]
Sure. I'll send a PR for this.

**Comment by EvsChen** [comment]
I used the wrong email to commit so I reopen another one. The cla bot informs me that I have to sign the CLA first. But the link it gives doesn't work. 
https://cla.js.foundation/webpack/webpack-cli?pullRequest=597

**Comment by ematipico** [comment]
It does work for me

**Comment by EvsChen** [comment]
Don't know why it fails. I use some proxy and it finally works. Could you please help to review my PR? @ematipico
