### ISSUE TITLE
Move cli inside its own package [core]

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#593]
**Is your feature request related to a problem? Please describe.**
Now that the project uses lerna, the core cli should be moved inside its own package, maybe called `@webpack-cli/core`

This is will help us also during committing messages like. We have a plugin that will force us to have the string inside the parenthesis as  the name of the packages handled by lerna

```
chore(core)
cli(add)
```

**Describe the solution you'd like**
This project will be a direct dependency of the main project, so it will be directly installed when people will install `webpack-cli`

**Describe alternatives you've considered**
I think this can be done during during the refactoring of the bin folder or straight after

**Additional context**
N/A

**Comment by ev1stensberg** [comment]
I don't think that we should, but leaving it up for discussion

**Comment by ev1stensberg** [comment]
Read the typescript issue and what concerns are raised there

**Comment by ematipico** [comment]
I'd like to keep typescript outside of the scope of this proposal. I'd like to understand your concerns about this proposal and the reasons

**Comment by ev1stensberg** [comment]
Path lookup with webpack and local imports, the need of having to install the main logic as a dependency before using it are my highest ones.

**Comment by ematipico** [comment]
> install the main logic as a dependency before using it

In my proposal I said that this package will be a direct dependency of the main webpack-cli project. So in our main `package.json` will have

```json
"chalk: "x.x.x" 
"@webpack-cli/core": "3.1.0"
```

> local imports

Local import will be kept inside `cli.js`

> Path lookup with webpack 

How is it handled now that it cannot be done by another file inside another folder?

**Comment by evenstensberg** [comment]
No real traction here, I think we should have the main cli as it is, people will get less confused when installing.
