### ISSUE TITLE
Error when compiling with only cli options in webpack-cli 2

### ISSUE THREAD

**Issue by wheresrhys** [webpack/webpack-cli#608]
**Describe the bug**

This is now erroring despite no code changes related to the build. As far as I can see it started happening in the last 2 days. There is no config file; only cli options are used.
```
webpack --mode development \
	--output-library fetchMock \
	--entry ./es5/client.js \
	--output-filename ./es5/client-bundle.js
/Users/wheresrhys/Projects/fetch-mock/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/wheresrhys/Projects/fetch-mock/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /Users/wheresrhys/Projects/fetch-mock/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/Users/wheresrhys/Projects/fetch-mock/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
make: *** [bundle] Error 1
```

**What is the current behavior?**

Throws the error as above. 

**To Reproduce**
1. `git clone https://github.com/wheresrhys/fetch-mock.git`
2. `g checkout b1b363e`
2. `npm install`
3. `make transpile bundle`

**Expected behavior**
Previously built the bundle successfully

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
```
$ webpack-cli info
Promise { <pending> }
```

**Comment by ev1stensberg** [comment]
update to the newest version

**Comment by ematipico** [comment]
Duplicate of #607

**Comment by wheresrhys** [comment]
Shouldn't you put some notice in the readme/install logs saying webpack-cli 2 is unsupported?

**Comment by ev1stensberg** [comment]
Normal behavior would be to upgrade, no?

**Comment by ematipico** [comment]
It's written in the `webpack` changelog

https://github.com/webpack/webpack/releases/tag/v4.20.0

**Comment by wheresrhys** [comment]
IMHO introducing an incompatibility problem between two tools that are so closely coupled could do with a more easily discoverable notice than a changelog, such as a more informative error. I'd be happy to submit a PR inserting such a notice if you think it's worth it

**Comment by ematipico** [comment]
Totally true. We are already planning on how to show this kind of information. Feel free to open an issue or a PR if you want!
