### ISSUE TITLE
Feature: GUI for webpack-cli

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack-cli#617]
**Is your feature request related to a problem? Please describe.**
A GUI for `webpack-cli` which can be used to 
- [ ] Add `loaders`, `plugins` from npm directly
- [ ] Remove configurations
- [ ] Edit configurations
- [ ] Visualize stats in graphs
- [ ] Create new configurations
- [ ] Watch for changes in watch mode
- [ ] Support `webpack serve`
- [ ] Visualize diff between modules when added or removed

**Describe the solution you'd like**
Inspired by `vue-cli ui`
**Describe alternatives you've considered**

**Additional context**

**Comment by ev1stensberg** [comment]
I think a gui for webpack in general would do

**Comment by rishabh3112** [comment]
Yeah @ev1stensberg that would be way more awesome,
We can also reuse the packages in `webpack-cli` like `add`, `remove`, etc to have that implemented I think 🤔

**Comment by ev1stensberg** [comment]
Yup

**Comment by renatoagds** [comment]
@ev1stensberg Looks good! I'll start working on this.

**Comment by ev1stensberg** [comment]
Awesome, thank you so much! 💙 start working on a fork and link me where you are working from and I'll give you feedback along the way ⚜️

**Comment by renatoagds** [comment]
@ev1stensberg perfect!! I'll do a v1 and reach you for feedback.

**Comment by ev1stensberg** [comment]
Sounds good 👏🏽

**Comment by LakshSingla** [comment]
I would also like to contribute to this issue, how should I go about it. Also which portion of UI should I take up?

**Comment by LakshSingla** [comment]
@rishabh3112 Thanks for swift response. I propose creating an Express based server which will run locally, and serve the frontend to the localhost and use a library like shelljs on the backend part of it to run the commands in the webpack directory. Have I interpreted the meaning of creating those endpoints correctly? @renatoagds How do you propose of doing this? I will be happy to adopt to that too.

**Comment by LakshSingla** [comment]
@rishabh3112 @ev1stensberg For the `webpack init` command, I suggest as the user enters his/her choice regarding different options (entry, output, module.rules etc), which are asked in `weback init` interactive mode, we create a dummy webpack config file and pass it to the `webpack init --config`. In case user fails to provide one we provide some defaults. I am unable to find a workaround for providing these defaults to webpack without creating a config file. Are there any command line parameters I can pass to the command so that it doesnot go into the interactive mode and gets all the required options it needs?

**Comment by renatoagds** [comment]
@LakshSingla hey! so, my idea is the same as yours, I started the boilerplate in my branch here: https://github.com/renatoagds/webpack-cli/tree/webpack-gui ... the next step will be create the initial screen to execute the `init` command, reproducing the same questions that we have in the CLI command. I probably will do that today. I'll be happy if you take a look in my branch and give your opinion. 👍

**Comment by LakshSingla** [comment]
@renatoagds Sure thing man. After you complete the initial draft, we can contribute together on different issues regarding UI. I suggest we decide upon a styling library ( like Materialize or Bootstrap ) to speed up the development of core logic. @ev1stensberg @rishabh3112 Suggestions ?

**Comment by LakshSingla** [comment]
@renatoagds If you don't mind, should I start working on the initial features of the GUI? Then we could work together later on more advanced ones? I will pickup from where you left.

**Comment by ematipico** [comment]
If everyone agrees, we could have an upstream branch and you could make PRs against that branch.

We can create an issue with the detailed list of the things to do/done. What do you think?

**Comment by renatoagds** [comment]
@ematipico agreed with you, I think we need to organize what we gonna do, so everyone could help. @LakshSingla let's do what @ematipico suggest first, so we do not work in the same thing, since we're in a pretty different timezone, we will crash our jobs. About the style, I was thinking to use `material-ui`(https://material-ui.com/).

**Comment by rishabh3112** [comment]
Well upstream branch for this is great 😀 @ematipico.
We can track this issue only as another issue for same will not be suitable I think.
I have setup up basic structure with express and typescript for this. I can PR it and we can work on that. Thoughts @renatoagds and @LakshSingla ?

**Comment by ematipico** [comment]
I created the upstream breanch `webpack-cli-ui`. All the PRs regarding this project should go against that branch

**Comment by ev1stensberg** [comment]
Sounds like you all have it under control. Create that PR for visibility and we'll come up with feedback. I'd propose to write it in JS first and then we can discuss rolling it over to TS if this is an external package ( which I think it should be ). So summed short:

1. PR
2. Create todo
3. Communicate to split tasks
4. Finish logic
5. Rewrite to TS

**Comment by ematipico** [comment]
Feel free to discuss here if you prefer https://github.com/webpack/webpack-cli/issues/647

**Comment by ev1stensberg** [comment]
Well I think it might be easier to take it gradually to avoid errors, but feel free to do TS straight away. In that case, this should be moved to a seperate package named ‘ui’

**Comment by himanshuc3** [comment]
I would also love to get in on ```webpack-cli ui```. Has it started or yet to be scaffolded? More the people, faster the feature integration I guess.

**Comment by rishabh3112** [comment]
Sure, @himanshuc3.
Currently foundation is in process. We would be starting actual development soon.

**Comment by sohailrajdev97** [comment]
@evenstensberg. I would like to contribute to this. May I know the current status and progress on this feature request.

**Comment by evenstensberg** [comment]
We're currently setting up infrastructure for the UI/GUI feature and we are thinking about design. Could you have a look at https://github.com/webpack/webpack-cli/issues/654 ?

**Comment by manishupadhyaya** [comment]
@evenstensberg. I would also like to contribute something to this. I can implement design to code. So any suggestions on how can I help?

**Comment by evenstensberg** [comment]
We have a PR open for the ui feature. You could check that out

**Comment by chaharnishant11** [comment]
I would like to work on this!
can you please suggest me where should I start from?

**Comment by anshumanv** [comment]
Hey @chaharnishant11 to give you a quick overview, we're presently setting up the server which will serve the frontend, so we're presently writing endpoints which will help ui run commands, you check out the open PRs and help with creating the endpoints, for the UI we're still discussing the design by taking feedback from everyone, would be cool if you can add in your suggestions as well! 😄

**Comment by chaharnishant11** [comment]
@anshumanv okay sir! definitely

**Comment by apoorv1997** [comment]
@anshumanv sir, I would like to work on building the frontend, can you tell me from where do i begin?

**Comment by anshumanv** [comment]
Hey @amitport we're still in the process of finalizing the UI before actually starting any solid work, would be awesome if you can design some prototypes, provide feedback and compare some existing solutions and see if you can come up with something which solves our problem. 😄

**Comment by amitport** [comment]
@anshumanv, I'm pretty sure you refer to someone else

**Comment by evenstensberg** [comment]
Re-opening this in CLI until there's an official repo for webpack UI

**Comment by alexander-akait** [comment]
Please create repo `webpack UI` and open an issue there, all we can create here is a command `webpack ui` and run your package, when it will be great feel free to open an issue and I will help, no need to keep it here, sorry

**Comment by alexander-akait** [comment]
webpack-cli !== webpac-ui, it is different thinkhs

**Comment by Mint-6263** [comment]
Ok:blush:

**Comment by Mint-6263** [comment]
@evenstensberg

**Comment by rishabh3112** [comment]
bump
