### ISSUE TITLE
DOCS: contributing setup: rimraf dep needed before running npm bootstrap

### ISSUE THREAD

**Issue by manu-chroma** [webpack/webpack-cli#619]
**Describe the bug**
**What is the current behavior?**

If the user does not have ``rimraf`` installed before running ``npm bootstrap``, 
``sh: 1: rimraf: not found`` error is thrown. 

This dependency should be specified in https://github.com/webpack/webpack-cli/blob/master/CONTRIBUTING.md.

**Comment by ev1stensberg** [comment]
You will need to do npm install first of all. Docs points that out. Hmu if you need help setting yourself up 🙏💙

**Comment by manu-chroma** [comment]
@ev1stensberg it is not clearly mentioned in: https://github.com/webpack/webpack-cli/blob/master/CONTRIBUTING.md#setup. That is why the confusion.
