### ISSUE TITLE
Deprecate --optimize-minimize in favour of --mode production

### ISSUE THREAD

**Issue by edmorley** [webpack/webpack-cli#624]
**Is your feature request related to a problem? Please describe.**
I've seen end users continue to use `--optimize-minimize` with webpack 4, since they weren't aware of the newer/superior `--mode production`, and then get confused why they are seeing "`mode` is not set" warnings.

**Describe the solution you'd like**
Start by showing a deprecation warning for `--optimize-minimize`, then at some point later remove it entirely.

**Describe alternatives you've considered**
Not showing a deprecation warning.

**Additional context**
Example accidental `--optimize-minimize` use:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/158#issuecomment-425938987

**Comment by evenstensberg** [comment]
We're removing this in the new webpack cli version that is out later this year fyi
