### ISSUE TITLE
Bug: Installing fails with "lerna: command not found"

### ISSUE THREAD

**Issue by gwylim** [webpack/webpack-cli#629]
**Describe the bug**

Running `npm install` in a project depending on webpack-cli fails with `lerna: command not found`.

**To Reproduce**
```
mkdir test && cd test
npm init
npm add webpack/webpack-cli
```

**What is the current behavior?**

```
[gwylim@gwylim test]$ npm install

> webpack-cli@3.1.2 postinstall /home/gwylim/test/node_modules/webpack-cli
> lerna bootstrap

sh: lerna: command not found
npm WARN webpack-cli@3.1.2 requires a peer of webpack@^4.x.x but none is installed. You must install peer dependencies yourself.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.
npm WARN test@1.0.0 No license field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! webpack-cli@3.1.2 postinstall: `lerna bootstrap`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the webpack-cli@3.1.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gwylim/.npm/_logs/2018-10-05T19_24_36_020Z-debug.log
```

**Additional context**
This seems to be related to https://github.com/webpack/webpack-cli/commit/415084913204d206579a5fc7d5dbc2f88555da31, since `npm install` is no longer run before `lerna bootstrap`. It works as expected if that commit is reverted.

My machine is running Arch Linux with npm version 5.6.0. This only seems to occur on linux from what we've observed.

**Comment by ev1stensberg** [comment]
Can you try to do npm install without the prod flag?

**Comment by gwylim** [comment]
Yes, that works when running `npm install` in webpack-cli, but the main bug here is that adding webpack-cli as a dependency of another package doesn't work. When you run `npm add webpack/webpack-cli` in another package, it doesn't install the dev dependencies of webpack-cli.

**Comment by ev1stensberg** [comment]
that's intended. When adding the CLI it should be used to compile webpack, not developing it locally

**Comment by gwylim** [comment]
Sorry, maybe I haven't explained it well or I've misunderstood something. If I create a minimal npm package with the following package.json, it results in the above error when running `npm install`. Is it a bug or expected behavior? If it's expected, then what's wrong with my package.json?:

```
{
  "name": "test",
  "version": "1.0.0",
  "devDependencies": {
    "webpack-cli": "webpack/webpack-cli"
  }
}
```

**Comment by gwylim** [comment]
Ok, I've edited the description to hopefully be more clear about the actual issue.

**Comment by ematipico** [comment]
I see that you are linking the cli internally. But if you don't run the npm install, it won't find any package. In fact lerna is not installed hence you get that error.

We could improve the documentation

**Comment by ev1stensberg** [comment]
@gwylim did it solve your issue?

**Comment by ev1stensberg** [comment]
Closing as inactive until there’s any objections
