### ISSUE TITLE
Tests: Try not using mocks on utility functions

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#63]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Right not we are testing our tests in many of the test files. This is due that the entire module is circular ( might be hard to isolate the tests ). However we can drag out some of the utility functions from the build instead of mocking those, such as `validateAddons`. 

**What is the expected behavior?**

Some of the utility functions/isolated modules are not being manually mocked but imported directly.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Test improvements

**Comment by abhiaiyer91** [comment]
Hi! I'd like to help on this issue! could you give me some more detail of what you'd like done?

**Comment by ev1stensberg** [comment]
Hey @abhiaiyer91 ! Thank you so much for reaching out! We want to use the real functions for most of the time, so perhaps some sort of E-E test or using `jest.fn` would be great. If you want to know how to do this, I recommend looking at the tests in the Yarn source code. I can put up a list of which modules that needs a refresh, if you want me to?

**Comment by abhiaiyer91** [comment]
@ev1nstensberg thanks for getting back to me! If you could kinda guide me through this first contribution that would be great!!

**Comment by ev1stensberg** [comment]
@abhiaiyer91 I'll put up a branch for you and everything you need on the github side, with comments on where you should get involved. I'll put up a small google docs for you with some useful sources for your PR and what it should include. This is a great opportunity for you to get to know the internals FWIW :) Have you read our wiki on the parser? This PR is majorly related to that

**Comment by abhiaiyer91** [comment]
@ev1stensberg Awesome! Im super excited! I will read the parser wiki today!

**Comment by ev1stensberg** [comment]
Sweet! Here's the [link](https://github.com/webpack/webpack-cli/wiki/Init-Feature-Design-Overview)! If you need anything from me while you're doing the PR, feel free to reach out at Twitter or here! I'm a bit busy right now, but I'll put up the branch and get you started by tomorrow morning (GMT + 1 here) :)

**Comment by ev1stensberg** [comment]
Here's the [document](https://docs.google.com/document/d/1Cz1iLt89Of0n_79e8aj8tOrx9ghS4O_G6AF4jsRXySA/edit?usp=sharing), good luck & thanks!

**Comment by ev1stensberg** [comment]
Old, resolved and probably going to be brought up again in another context.
