### ISSUE TITLE
[Documentation] Webpack-scaffold documentation and guides

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#667]
**Is your feature request related to a problem? Please describe.**
Currently, there's few ways to get to know how to create a webpack-scaffold. After `webpack-ui` is done, this is going to implemented as a bootstrapping system onto the UI. It would be nice to make documentation more accessible so that users can create their own pre-configured configurations.

**Describe the solution you'd like**
We should make documentation pages at webpack.js.org for creating your own scaffolds.

**Describe alternatives you've considered**
N/A
**Additional context**
This PR should be directed towards https://github.com/webpack/webpack.js.org

**Comment by pranshuchittora** [comment]
@evenstensberg  I would like to work on this issue. This would be my first contribution to webpack.
Is this the correct [reference](https://github.com/webpack/webpack-cli/blob/master/SCAFFOLDING.md#webpack-scaffold-yourpackage)

**Comment by evenstensberg** [comment]
This needs to be added at webpack.js.org

**Comment by pranshuchittora** [comment]
I think the [this doc](https://github.com/webpack/webpack-cli/blob/master/SCAFFOLDING.md#webpack-scaffold-yourpackage) should be implemented in webpack.js.org?

Am I going the right way? @evenstensberg

**Comment by evenstensberg** [comment]
No, its own section under the docs page at the webpack.js.org repository

**Comment by theaayush8999** [comment]
@evenstensberg This scaffold doc-guide will go under webpack-cli section or it will be a new page/section?

**Comment by evenstensberg** [comment]
https://github.com/webpack/webpack.js.org

**Comment by pranshuchittora** [comment]
### Progress so far
- Added the `scaffolding.md` to Guides

![Screenshot from 2019-03-11 13-37-26](https://user-images.githubusercontent.com/32242596/54109920-01129b80-4406-11e9-9cf0-f739cad59e03.png)

### Roadblocks
- eslint throwing error on the code

![Screenshot from 2019-03-11 13-58-53](https://user-images.githubusercontent.com/32242596/54109942-138cd500-4406-11e9-9cd0-09f63188ab20.png)

**Comment by evenstensberg** [comment]
I think we need to flesh this out.

**Comment by pranshuchittora** [comment]
@evenstensberg all the issues have been fixed. https://github.com/webpack/webpack.js.org/pull/2860
Pls review the PR

**Comment by pranshuchittora** [comment]
@evenstensberg is it necessary to run linting on the markdown's code snippets because sometimes we are forced to bloat the required code in order to make it syntactically perfect

#### Example

Let's say I want to write just a method of a class, eslint throws an error & to make it fix you are required to wrap it inside a class definition.

The code below is not valid :point_down: 
```js
constructor(){
    //Do something
}
```
This is valid :point_down:
```js
class Unwanted{
    constructor(){
            // Do something
    }
}
```

https://github.com/webpack/webpack.js.org/blob/ee984f747870f17111944f47fed23fae97c56381/.eslintrc#L25

**Comment by strongSoda** [comment]
@evenstensberg If it's not done can I work on this?

**Comment by evenstensberg** [comment]
A live demo would be great, youtube or smth like that

**Comment by strongSoda** [comment]
On it.

**Comment by pranshuchittora** [comment]
@evenstensberg  shall we close this?

**Comment by karanb1** [comment]
@evenstensberg I would like to work on this issue. Please can you guide me how to proceed and what all changes need to me made.

**Comment by Cronus1007** [comment]
@evenstensberg I would like to work on this issue.

**Comment by evenstensberg** [comment]
Feel free

**Comment by Cronus1007** [comment]
@evenstensberg  Sir can you please guide me how to proceed?

**Comment by evilebottnawi** [comment]
webpack-scaffold will be union with `generators` project, so we can close it
