### ISSUE TITLE
[Documentation] Webpack-scaffold Overview

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#668]
**Is your feature request related to a problem? Please describe.**
It would be nice with an overview of current scaffolds at https://github.com/webpack/webpack.js.org. 
**Describe the solution you'd like**
A search page at https://github.com/webpack/webpack.js.org where we use Agnolia to search current `webpack-scaffold-name`'s.

**Describe alternatives you've considered**
N/A

**Additional context**
This PR should go towards https://github.com/webpack/webpack.js.org

**Comment by hemal7735** [comment]
@evenstensberg can we get more information regarding what is expected here? Maybe some example would help.

**Comment by evenstensberg** [comment]
Yes. Add Agnolia to search for webpack scaffolds. A WIP PR is up here: 

https://github.com/webpack/webpack.js.org/pull/2171

CC @haroenv

**Comment by Haroenv** [comment]
How are the webpack-scaffolds recognisable on npm, a keyword?

**Comment by evenstensberg** [comment]
They are prefixed with `webpack-scaffold`

**Comment by Haroenv** [comment]
A PR can be made here

https://github.com/algolia/npm-search/blob/c7b4fd9f60e64588e9c2cdab2990185d253ba6d1/src/formatPkg.js#L207-L230

so that it can be filtered effectively. Once that is done, I can create a search API key for webpack

**Comment by evenstensberg** [comment]
@Haroenv 

Is this right? https://github.com/algolia/npm-search/pull/296

A correct name would be: `webpack-scaffold-yolo`

**Comment by Haroenv** [comment]
It's right if you want to enforce the keyword, I'm not sure if you want to though

**Comment by evenstensberg** [comment]
No, removing nwo

**Comment by Haroenv** [comment]
```
appId: OFCNCOG2CU
apiKey: 77db8c6516725ef60b8a60223155f7ad
indexName: npm-search
filters: computedKeywords:webpack-scaffold
```

All information is now kept updated.

Here's an example with React InstantSearch: 
[![Edit react-instantsearch-app](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8nk1p91l5l?module=%2Fsrc%2FApp.js)

**Comment by rishabh3112** [comment]
cc @evenstensberg

**Comment by snitin315** [comment]
Bump

**Comment by evilebottnawi** [comment]
webpack-scaffold will be union with `generators` project, so we can close it
