### ISSUE TITLE
[UI] Option to Install a webpack-scaffold in UI

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#669]
**Is your feature request related to a problem? Please describe.**
When using `webpack ui` we should be able to use a `webpack-scaffold` and download a pre-configured configuration.

**Describe the solution you'd like**
Clicking a button to have a configuration set up

**Describe alternatives you've considered**
N/A

**Additional context**
In order for this to fully function programatically we can either ask the prompts at the UI website itself or we can adjust webpack-scaffolds to have an option to auto-set default parameters.

**Comment by siddhant1** [comment]
Can I work on this?

**Comment by evenstensberg** [comment]
Yes!!

**Comment by siddhant1** [comment]
Thanks! Will start today

**Comment by evenstensberg** [comment]
Great, hmu if you have any questions!

**Comment by anshumanv** [comment]
👍 for the prompt on the UI, why not provide a flag like `--default` to use the default config to auto-set default params, on the UI we'll provide an option to the user to add a scaffold or just click on a default config? Have any other approach in mind? 

Providing both will be great imo

**Comment by evenstensberg** [comment]
No flags with this. Just a website that is clean and does this

**Comment by silent-lad** [comment]
I am very interested to work on this , I saw the todo board for the same is closed now. Any tips in where to start from? @evenstensberg
