### ISSUE TITLE
select No for "Will you use one of the below CSS solutions" selects SASS

### ISSUE THREAD

**Issue by hansifer** [webpack/webpack-cli#673]
**Describe the bug**

when running `npx webpack-cli init` and answering the questions, using arrow keys to select **No**, then hitting enter results in the wizard selecting the **SASS** option.

**What is the current behavior?**

when running `npx webpack-cli init` and answering the questions, using arrow keys to select **No**, then hitting enter results in the wizard selecting the **SASS** option.

**To Reproduce**

1. run `npx webpack-cli init`
2. when answering `Will you use one of the below CSS solutions?`, select No and hit enter
3. observe that SASS is selected instead of no css solution.

**Expected behavior**

No css solution selected instead of SASS.

**Screenshots**

N/A

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

 System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    npm: 5.3.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    uglifyjs-webpack-plugin: ^2.0.1 => 2.0.1
    webpack: ^4.24.0 => 4.24.0
    webpack-cli: ^3.1.2 => 3.1.2

**Additional context**

N/A

**Comment by dhruvdutt** [comment]
<img width="499" alt="screenshot 2018-11-04 at 1 16 54 pm" src="https://user-images.githubusercontent.com/5961873/47961592-0add5a00-e034-11e8-84c7-87b97953c7d9.png">

I followed the steps for reproducing, it works fine for me. Option "No" is getting selected.

Can you please make a gif or something to reproduce the issue?

**Comment by ematipico** [comment]
I think the issue is that by selecting No, the final config has SASS but instead it should not have nothing

**Comment by dhruvdutt** [comment]
@ematipico Checked that as well. The final config doesn't contain SASS. Can you try if you can reproduce the issue?

**Comment by evenstensberg** [comment]
@dhruvdutt you can reproduce this locally yourself

**Comment by hansifer** [comment]
Any suggestions on how to capture a gif or video of my screen without the
use of paid software on Windows?

**Comment by dhruvdutt** [comment]
Try [Captura](https://github.com/MathewSachin/Captura) or [ShareX](https://github.com/ShareX/ShareX).

**Comment by hansifer** [comment]
This is what I see prior to selecting the css solution. The cursor is after "No" and using up/down arrow keys simply moves the cursor up/down (to item "selection" is apparent).

![webpack-cli-bug](https://user-images.githubusercontent.com/1163334/47966522-92b16d00-e010-11e8-9e56-f57b5867c555.png)

This is what I see after I hit enter when the cursor is next to "No". Explicitly typing "No" before hitting enter has the same effect.

![webpack-cli-bug-2](https://user-images.githubusercontent.com/1163334/47966544-ea4fd880-e010-11e8-8bc1-547f2a357257.png)

**Comment by dhruvdutt** [comment]
This seems to be some issue with [Inquirer's `List`](https://github.com/SBoudrias/Inquirer.js#list---type-list). We use this to show the prompt. I'm not able to reproduce this on macOS.

If you can try to run the [`List`](https://github.com/SBoudrias/Inquirer.js/blob/master/packages/inquirer/examples/list.js) example from [Inquirer's official samples](https://github.com/SBoudrias/Inquirer.js#examples) and reproduce it, that would contribute a lot in tracing the issue. 🤗 

Also, can you mention your Node version as well?

**Comment by dhruvdutt** [comment]
Can you try with the default standard command prompt of Windows?

**Comment by hansifer** [comment]
> Can you try with the default standard command prompt of Windows?

It works fine with Windows' native command prompt and PowerShell.

**Comment by dhruvdutt** [comment]
Seems like there are some issues of Inquirer with git bash.
References: [#266](https://github.com/SBoudrias/Inquirer.js/issues/266), [#303](https://github.com/SBoudrias/Inquirer.js/issues/303), [#507](https://github.com/SBoudrias/Inquirer.js/issues/570).
