### ISSUE TITLE
[BUG] : webpack-cli does not honor webpack-config file passed as param

### ISSUE THREAD

**Issue by hemal7735** [webpack/webpack-cli#679]
**Describe the bug**

**What is the current behavior?**

I have used webpack, however this is the first time I'm using webpack-cli.

**To Reproduce**
1. create webpack-config file `webpack.foo.js`
2. use command `npx webpack-cli remove webpack.foo.js`
3. It throws the error --> 
**ERROR webpack.config.js** not found. Please specify a valid path to your webpack config like `$ webpack-cli remove webpack.dev.js`

**Expected behavior**
1. It should honor the file supplied by the CLI, instead always searching for `webpack.config.js`
2. Current error is completely misleading. It can be improvised. The error could be : `ERROR [passed filename] not found. Please specify a valid path to your webpack config like ...`

**Debugging Info**
1. [modify-config-helper](https://github.com/webpack/webpack-cli/blob/master/packages/utils/modify-config-helper.ts#L44) takes param configFile, which defaults to [webpack.config.js](https://github.com/webpack/webpack-cli/blob/master/packages/utils/modify-config-helper.ts#L27)
2. We are not passing `configFile` param to it while calling [remove](https://github.com/webpack/webpack-cli/blob/master/packages/remove/index.ts#L13)

**Comment by hemal7735** [comment]
@dhruvdutt thanks for acknowledging this. I already saw the `add` code, and I will raise a PR soon.

**Comment by hemal7735** [comment]
@dhruvdutt We will need to change the same for `update` as well. Shall I raise separate PR for that?

**Comment by evenstensberg** [comment]
Fixed at #680
