### ISSUE TITLE
Migrate: Comment next to migration diff?

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack-cli#68]
I tried out the sweet --migration flag, and it freaking worked!! One thing that was unexpected (until I figured it out), was this diff:

```diff
-               loaders: [
-                       {test: /\.json/, loader:'json'}
-               ]
+               rules: []
```

This is correct but it still caught me off guard so I questioned what I was seeing. 

Would be nice for each transformation would make describe what the transform does and why: 

```diff 
-               loaders: [ 
-                       {test: /\.json/, loader:'json'}
-               ]
+               rules: [] //json-loader is now implemented out of the box.
```

**Comment by TheLarkInn** [comment]
Whether that information be below or above the list is up to you all!

**Comment by okonet** [comment]
I agree we could do a better job at explaining what's gonna happen and why did it happen but I wouldn't add any comments to user's code.

**Comment by pksjce** [comment]
I vote we show diff and reasons for each of the change in the diff  after --migrate has been run. Should get taken up under #49
