### ISSUE TITLE
Feature: Find config recursively

### ISSUE THREAD

**Issue by GMartigny** [webpack/webpack-cli#689]
**Is your feature request related to a problem? Please describe.**
Unlike shellscape/webpack-command (formerly webpack-contrib/webpack-command) configuration file is not searched upward in the directory tree. When using monorepo, I would like to set one configuration's file at the root and not for each sub-modules.

**Describe the solution you'd like**
Being able to define only one webpack configuration file for all sub-modules of a mono-repo.

**Describe alternatives you've considered**
I could use shellscape/webpack-command, but I would like to stay within the official repo.
I could set symbolic links, but it feels overkills.

**Additional context**
File `./webpack.config.js` exists.
Scripts in `./packages/sub/package.json`:
```
"build:cli": "webpack-cli --mode=production",
"build:com": "webpack-command --mode=production"
```
Running `lerna run build:cli` fail to read `./webpack.config.js`, but `lerna run build:com` works.

This feature could change existing behavior, but it seems closer to what could be expected. (works alike `git config`)

**Comment by lakatostamas** [comment]
Hi!
Can I send a PR for this?

**Comment by dhruvdutt** [comment]
Absolutely. 👍
