### ISSUE TITLE
Lock versions of the dependencies 

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#697]
Due to the recent problems happened to the npm world, I'd propose to lock all the versions of our dependencies and development dependencies 

It's not a bulletproof solution must at least it's something

Before: 
```json
"chalk": "^2.4.1" 
```
After:
```json
"chalk": "2.4.1"
```

**Comment by dhruvdutt** [comment]
Can you also suggest recommended security procedures for updating dependencies manually? One platform is [snyk](https://snyk.io/) definitely.

**Comment by ematipico** [comment]
It's already in place in our CI

**Comment by dhruvdutt** [comment]
Yeah, we always check that while upgrading.
Not sure if we need to pin all dependencies explicitly. 
@evenstensberg WDYT?

**Comment by evenstensberg** [comment]
Let's discuss this

**Comment by ematipico** [comment]
This is the place to discuss it :) what do you think even?

**Comment by dhruvdutt** [comment]
Hmmm, makes sense. We can try pinning dependencies.
I will take the responsibility for upgrading packages every fortnight with a proper audit. ✋

**Comment by sendilkumarn** [comment]
Let us add dependabot here and pin the libraries. I think that makes sense with security.

**Comment by ematipico** [comment]
@evenstensberg what are your thoughts about?

**Comment by evenstensberg** [comment]
We got snyk which I think is enough

**Comment by ematipico** [comment]
It's enough for us but unfortunately it's not enough for the security for the users 

We know that if we don't pin our dependencies and there's no lock and it's not been used properly, the consumers will get into their dependency tree all the minor releases/fixes even though it shouldn't be like this. 

Change is for who consumes the library
