### ISSUE TITLE
npm  has deprecated  flatmap-stream` and `event-stream@3.3.6` 

### ISSUE THREAD

**Issue by pruthvi204** [webpack/webpack-cli#698]
**Describe the bug**

A 💯 way to do this is to provide your configuration via a GitHub gist and/or to use markdown when describing which commands you used when the error occurred! Be precise and clear in your description of the bug.

**What is the current behavior?**

What is the current behavior?
flatmap-stream and event-stream has been deprecated yesterday itself. while install npm getting error E404
npm ERR! 404 Not Found: flatmap-stream@0.1.1
how to we install npm now

Other relevant information:
webpack version: 4.20.2
Operating System: ubuntu
Additional tools:

**Screenshots**
![image](https://user-images.githubusercontent.com/43064333/49152758-d494b100-f339-11e8-8c25-18d3633aa5d6.png)

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

.

**Comment by dhruvdutt** [comment]
We don't use either of `flatmap-stream` or `event-stream` package directly.

Where are you trying to run `npm install`? I just tried doing a fresh clone of `webpack-cli` repo and it installed everything correctly.

**Comment by rishabh3112** [comment]
Installations are working fine on the latest npm versions of both `webpack` and `webpack-cli` too.
@pruthvi204 please add steps to reproduce the error.

**Comment by dhruvdutt** [comment]
@pruthvi204 @Mikkou Can you please mention steps for reproducing? Where exactly are you running `npm install`? And why do you think this is an issue with `webpack-cli`?
The screenshots are slightly ambiguous.

**Comment by Mikkou** [comment]
@dhruvdutt i found problem
https://github.com/dominictarr/event-stream/issues/116?ref=hvper.com&utm_source=hvper.com&utm_medium=website

**Comment by mrded** [comment]
Updating `nodemon` to "1.18.7" solves the problem. For some reason it had missing dependency to `event-stream`. Newest version doesn't require `event-stream` at all.

**Comment by ltabosa** [comment]
This [solution](https://github.com/umbraco/Umbraco-CMS/issues/3811#issuecomment-443432943) worked for me.

Remove `package-lock.json` local, Remove `node_modules`, run `npm install`

**Comment by RUPALAVECINO** [comment]
Eliminar `package-lock.json`local, Eliminar `node_modules`, ejecutar`npm install`

**Comment by lenhnv1305** [comment]
> @pruthvi204 @Mikkou Can you please mention steps for reproducing? Where exactly are you running `npm install`? And why do you think this is an issue with `webpack-cli`?
> The screenshots are slightly ambiguous.
this works for me, creating a clone repo then run npm install there and then copy node_modules to the original repo
