### ISSUE TITLE
Enh: Moving from UglifyJSPlugin to TerserPlugin

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#701]
**Is your feature request related to a problem? Please describe.**
Our cli still uses uglify js plugin when it generates/migrate. That library is now ditched by `webpack` , so we should move to the new plugin too 

**Describe the solution you'd like**
Using `TerserPlugin`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by abenezerabebe** [comment]
I'd be happy to pick this one up!

**Comment by sendilkumarn** [comment]
@abenezerabebe Go ahead 👍

**Comment by anshumanv** [comment]
Fixed in https://github.com/webpack/webpack-cli/pull/792 I believe 😄 Anything left here todo?
