### ISSUE TITLE
Improve webpack integration tests

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#705]
**Is your feature request related to a problem? Please describe.**
Inside `binCases` folder, we run a bunch of integrations test where we make sure that the output on webpack is correct against some specific arguments passed via CLI.

At the moment, when we get the output from a `webpack` process, we remove from it hash, timestamps, etc. and we provide this output to the test case.

This prevent from doing further test cases against hashes for example.

This is the function that strips the output BEFORE being consumed by the test

https://github.com/webpack/webpack-cli/blob/master/test/testUtils.js#L66-L77

**Describe the solution you'd like**
The plan would be to create a second utility, ideally called `extractSummary` where we only extract the real content (where we have information about the modules parsed by `webpack`) and use it inside all the tests that at least have the snapshot tests. 

Of course, we will have to remove that `removeTimeStrings`.

The final code should something like this
```js
// my-test.test.js

const { run, extractSummary } = require("../../../testUtils");

test("function-promise", () => {
	const { code, stdout, stderr } = run(__dirname, [
		"--config",
		"./webpack.config.js",
		"--target",
		"async-node",
		"--mode",
		"production"
	]);

	expect(code).toBe(0);
    const summary = extractSummary(stdout)
	expect(summary).toEqual(expect.anything());
	expect(summary).toContain("entry.bundle.js");
	expect(stderr).toHaveLength(0);
	expect(summary).toMatchSnapshot();
});

```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hemal7735** [comment]
@ematipico If I comprehend that correctly,
1.  We want to call `extractHash` as well in the test-case itself
2. `removeTimeStrings` should be renamed to `extractSummary`

**Comment by ematipico** [comment]
`extractHash` only in those tests where it's needed
