### ISSUE TITLE
Enh: Generate .babelrc and do not place babel config in webpack config

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack-cli#706]
**Describe the bug**
```
const webpack = require('webpack');
const path = require('path');

/*
 * SplitChunksPlugin is enabled by default and replaced
 * deprecated CommonsChunkPlugin. It automatically identifies modules which
 * should be splitted of chunk by heuristics using module duplication count and
 * module category (i. e. node_modules). And splits the chunks…
 *
 * It is safe to remove "splitChunks" from the generated configuration
 * and was added as an educational example.
 *
 * https://webpack.js.org/plugins/split-chunks-plugin/
 *
 */

/*
 * We've enabled UglifyJSPlugin for you! This minifies your app
 * in order to load faster and run less javascript.
 *
 * https://github.com/webpack-contrib/uglifyjs-webpack-plugin
 *
 */
module.exports = {
	module: {
		rules: [
			{
				include: [path.resolve(__dirname, 'src')],
				loader: 'babel-loader',

				options: {
					plugins: ['syntax-dynamic-import'],

					presets: [
						[
							'env',
							{
								modules: false
							}
						]
					]
				},

				test: /\.js$/
			}
		]
	},
```

**What is the current behavior?**
Currently as seen above in the example we are putting babel configuration in the config file. This is really an antipattern in my opinion and in what I am teaching to users. We should strive to have the configs as clean as possible and therefore our cli's default output should respect that.

**To Reproduce**
1. `webpack init`
2. Include babel/es2015

**Expected behavior**
In an empty project, with no existing babelrc, we create one and include the configuration set there. 

If there is already a babelrc present then we should have the configuration added and merged. We should handle edge cases secondary as a much lower priority here.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Comment by evenstensberg** [comment]
It's easier for us cause we don't have to generate or check an existing file. Maybe we can combine in a babel generator. Will investigate

**Comment by TheLarkInn** [comment]
If no babelrc is present create, otherwise, thats when we have to decide what is better to do here.

**Comment by anshumanv** [comment]
Just needs a quick check if the user opts for a babel, what you do suggest maybe by default we can go for a separate `.babelrc` file in the project and if that is present we can merge the configs, but what if a user opts to have the babel config in the `webpack.config.js` file just so to handle all configs in one place, there can be two options imo - 

* Ask the user a follow up question about the location of babel config if they opt for babel
* Provide a flag by which user will be able to deviate from the default behavior(separate file) to include it in the webpack config?

Will further investigate and report my findings. 👍

**Comment by evenstensberg** [comment]
https://github.com/webpack/webpack-cli/commit/3814d44d97d519f0b0eae2cc5e400b1899848e37
