### ISSUE TITLE
Enh: Name of webpack config should default to `webpack.config.js`

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack-cli#707]
**What is the current behavior?**
I noticed that in the default setup, that a "webpack.dev.js" file was created. By default webpack looks for webpack.config.js at the root of a project. For the sake of cleanliness and easy to write scripts, we should be outputting webpack.config.js as the default. For dev and prod versions (I'll put in a separate issue for this).

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
Versions

```
"dependencies": {
    "webpack-cli": "^3.1.2"
  },
"devDependencies": {
    "@webpack-cli/init": "^0.1.2",
}
```

**Comment by evenstensberg** [comment]
Will have a look!
