### ISSUE TITLE
Don't scaffold "dist" property if user just chooses default.

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack-cli#708]
**What is the current behavior?**
`output: {path: path.resolve(__dirname, 'dist')}`

**Expected behavior**
If single entry and default output is chosen, do not even create it since webpack always defaults this. We want to stop creating config if we don't need to.

**Comment by evenstensberg** [comment]
Having a look at it. Thanks for reporting!

**Comment by EvsChen** [comment]
@evenstensberg Can I take a try on this?

**Comment by evenstensberg** [comment]
Sure, go ahead

**Comment by dhruvdutt** [comment]
@EvsChen Sure! Let us know if you run into any issues.
