### ISSUE TITLE
[Feature Request]: Let's rework some of the main scaffolding layout

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack-cli#709]
**Describe the solution you'd like**
Let's rework how development and production configs are laid out.

- [x] Always no matter what, config is generated in root of project
- [ ] Config is generated _IF_ defaults are not used
- [x] Config is always named `webpack.config.js` 
- [ ] Development and Production configs are composed or combined using `webpack-merge` not Object.assign
- [ ] Development and Production configs use names webpack.development.js and webpack.production.js (even if shorter is more convenient it matches with mode names).
- [ ] Scripts generated should use `--env.mode development` `--env.mode production` to determine whether or not production or development modes are used. 
- [ ] any config used is a function that returns a config.
- [ ] any config that is needed for both production and development goes into the 	`webpack.config.js` file, or the common config.
- [ ] For multipage application we do not use webpack-dev-server in dev, and instead use --watch in scripts.
- [ ] For SPA (or single entry) we consider using webpack-dev-server as default instead of --watch
- [ ] Dev script is called `dev` and production script is called `prod`.
- [ ] A script called `webpack` is generated so users can run `npm run webpack`. This will be used inside of `dev` and `prod` scripts for composition sakes.

![screen shot 2018-12-08 at 2 44 01 pm](https://user-images.githubusercontent.com/3408176/49691465-c09a3d80-faf7-11e8-8931-2482fa70609e.png)

Hopefully all of this is clear and I added them in checkbox format. These ideas I've created based on positive feedback I've received from my workshops and talks. 

Since all this code is JavaScript i would understand that there are many opinions on how configs are formatted but I would like to go this direction because I believe it is just easier to maintain this way. 

If you look at my repo: https://github.com/TheLarkInn/webpack-workshop-2018/tree/feature/19-sm-css-code-split 

This shows you a fully fleshed out example with many features, integrations, etc and hopefully we can follow this style (even presets which I can document in a separate issue).

**Comment by EvsChen** [comment]
Are we going to track these feats in this issue? I would like to handle some of them.

**Comment by evenstensberg** [comment]
Probably. If there's no PR's open, take one down @EvsChen , thanks!

**Comment by EvsChen** [comment]
I guess I'll handle the config naming first.

**Comment by evenstensberg** [comment]
I've already submitted a PR for that. Other than that, up for grabs

**Comment by anshumanv** [comment]
Working on 1 - Generate webpack config in the root of the project.

😄

**Comment by anshumanv** [comment]
I have a question, what's the workflow when defaults are used? (Point 2) 
@evenstensberg @dhruvdutt

**Comment by evenstensberg** [comment]
Then we run the init generator

**Comment by anshumanv** [comment]
Cool!

Working on point 2 - Run init generator when defaults are used, thanks @evenstensberg! 😄

**Comment by anshumanv** [comment]
>  A script called webpack is generated so users can run npm run webpack. This will be used inside of dev and prod scripts for composition sakes.

I think I have an approach in mind, will be sending a WIP soon. 👍
