### ISSUE TITLE
[Documentation] Add installation guide to webpack-scaffold

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#712]
**Is your feature request related to a problem? Please describe.**
When trying to update the `webpack-scaffold-demo` repo was trying to quickly copy-paste the installation command, but didn't find any.

**Describe the solution you'd like**
Add installation guide to `webpack-scaffold` package.

**Describe alternatives you've considered**
N/A

**Additional context**

1. Go to `packages/webpack-scaffold`
2. Follow the syntax used in any other package for installation with node/CLI etc
3. Paste it in there, add webpack-scaffold instead
4. You're set!

---

### Important

This issue is reserved for first time contributors only, any PR submitted that is not from a first time contributor will get rejected.

**Comment by evenstensberg** [comment]
Webpack scaffold is a yeoman generator but it provides some functions that you can use to compose yeoman generators to create webpack configurations. Does this make sense? 

A regular generator, but you can import functions to generate a webpack configuration

**Comment by sw-yx** [comment]
ok and is this a one-off scaffolding tool that you only use at the start of a project or would this work with existing projects? im guessing the former?

**Comment by evenstensberg** [comment]
It works with excisting projects if you design it such that you parse a config file and then assign props to it, should work. We only get input opts and write to that file after constructing an ast for it and parsing it back as a js file

**Comment by sw-yx** [comment]
oh thats pretty cool! enahnces the usability for sure! 🔥 will keep close watch
