### ISSUE TITLE
[Documentation] Add overview of packages in /packages

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#713]
**Is your feature request related to a problem? Please describe.**
It would be nice with an overview `README.md` on `/packages` so that people can quickly browse and read the readme to get an understanding.

**Describe the solution you'd like**
A elaborative readme with an overview of packages, what they do and how they connect with the main CLI.

**Describe alternatives you've considered**
N/A

**Additional context**

1. Go to `/packages`
2. Add a README there
3. You're set!

**Comment by LakshSingla** [comment]
What all should be included pertaining to a particular package ??

**Comment by evenstensberg** [comment]
Do you mind elaborating? I think the readme should include 

1. Overview
    - what this folder contains and why
2. Contents
  - list of all packages and what they do
