### ISSUE TITLE
babel.config.js is not executed at all when using webpack.config.babel.js with v.3.2.0

### ISSUE THREAD

**Issue by yvele** [webpack/webpack-cli#725]
**Describe the bug**

`babel.config.js` is not executed at all when using `webpack.config.babel.js` with v.3.2.0
Everything is working fine with previous v3.1.2

**What is the current behavior?**

When using `import/export` in my `webpack.config.babel.js` I get

> SyntaxError: Unexpected token export

**To Reproduce**

Use `webpack.config.babel.js` + `babel.config.js` with an `import`or `export`

**Comment by evenstensberg** [comment]
#724 dupe

**Comment by artemkaint** [comment]
it doesn't work again in 4.0.0-alpha-4

**Comment by evenstensberg** [comment]
> Could you try webpack-cli v.3.2.3 ?
