### ISSUE TITLE
npm install issue: `sh: opencollective: command not found` 

### ISSUE THREAD

**Issue by MengRS** [webpack/webpack-cli#729]
**Describe the bug**

When installing webpack-cli (version `3.2.0`) using `npm install -D webpack-cli`, the following output occurs:
`sh: opencollective: command not found` (full output below)

The installation will not complete.

**What is the current behavior?**

Current latest version of webpack-cli (version 3.2.0) will not install.

**To Reproduce**
1. Run `npm install -D webpack-cli`

**Expected behavior**
No error is yielded and webpack-cli is successfully installed / listed in package.json.

**Full Console Error Output**
```
$ npm install -D webpack-cli

> webpack-cli@3.2.0 postinstall /Users/mengrs/Desktop/trail-photos-service/node_modules/webpack-cli
> opencollective postinstall

sh: opencollective: command not found
npm WARN trail-photos@ No repository field.
npm WARN trail-photos@ license should be a valid SPDX license expression

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! webpack-cli@3.2.0 postinstall: `opencollective postinstall`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the webpack-cli@3.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mengrs/.npm/_logs/2019-01-07T01_50_39_971Z-debug.log
trail-photos-service (03_client_and_test) $
```

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
Please note, if I install the previous version of `webpack-cli` (version 3.1.2) using `npm install -D webpack-cli@3.1.2` - I do not encounter any errors and my installation is successful.

**Additional context**
Using node version `6.13.0`.
Not using `yarn`.

**Comment by evenstensberg** [comment]
Will fix

**Comment by evenstensberg** [comment]
`npm install --save webpack-cli` version 3.2.1
