### ISSUE TITLE
Migrate: Relative output path -> absolute output path

### ISSUE THREAD

**Issue by jouni-kantola** [webpack/webpack-cli#73]
**Do you want to request a *feature* or report a *bug*?**

Feature (nitty gritty suggestion, so close it if you don't think it's worth it)

**What is the current behavior?**
In the test config I'm using to test the webpack-cli's migration I use a relative output path `dist`. This is not migrated to an absolute path, which is required according to docs (in practice it isn't really required) and _is_ required by webpack-dev-server.

**If the current behavior is a bug, please provide the steps to reproduce.**

Set `output: { path: 'dist' }`

**What is the expected behavior?**
webpack 1 config:
```
output: {
  path: 'dist',
  filename: '[name].js'
}
```
...becomes webpack 2 config:
```
output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name].js'
  }
```

**If this is a feature request, what is motivation or use case for changing the behavior?**
I'm thinking the migration feature could be a good way to ensure people use an absolute output path, mostly to harmonize how people configure webpack.
- supports this issue: https://github.com/webpack/webpack/issues/3660
- supports how docs describe webpack 2 config (https://webpack.js.org/configuration/output/#output-path) and requirement for webpack-dev-server

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
MacOS
node v7.4.0
webpack-cli: `https://github.com/webpack/webpack-cli.git#a46edbb10e443a0e256038212d4f44042c8e1dc2`

**Comment by pksjce** [comment]
I think this a great suggestion. Will add a transform for this.

**Comment by jouni-kantola** [comment]
@pksjce: When I retested https://github.com/webpack/webpack-cli/issues/69 using https://github.com/webpack/webpack-cli.git#37a594d0346f51c5d62779f835e2293602359a5f, I still get after `--migrate`:
```
output: {
    path: 'dist',
    filename: '[name].js'
}
```

**Comment by jouni-kantola** [comment]
@pksjce: I reported another bug for `--migrate`, with a before/after `webpack.config.js`.
See issue: https://github.com/webpack/webpack-cli/issues/88

There you can see that `path: 'dist'` is left untouched. `const path = require('path');` is added as expected, but the actual output path isn't updated.
