### ISSUE TITLE
CI: Use lerna bootstrap in CI postinstall but not in release

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#730]
**Describe the bug**

Look at a PR or go to travis under our repo and see TS not being generated

**What is the current behavior?**

We aren't building ts on CI's which makes them fail.
 
This is where you elaborate on the current behavior of the cli, how it behaves normally differing from the previous version/build you did. 

**To Reproduce**
N/A

**Expected behavior**

Add CI script to run lerna, but not as a postinstall, because we cannot release webpack-cli with lerna ( it would be too big of a dep)

**Screenshots**
N/A

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
N/A
**Additional context**
N/A

**Comment by EvsChen** [comment]
So, I suppose the solution is to add `lerna bootstrap` in the `install` part of `travis.yml`?

**Comment by evenstensberg** [comment]
aye

**Comment by EvsChen** [comment]
I'll make a PR

**Comment by evenstensberg** [comment]
Sweet, thanks
