### ISSUE TITLE
webpack-cli@3.2.1 postinstall: `lightercollective` 

### ISSUE THREAD

**Issue by brunolm** [webpack/webpack-cli#738]
**Describe the bug**

Error on install.

**What is the current behavior?**

```
webpack-cli@3.2.1 postinstall: lightercollective
```

**To Reproduce**

1. `npm i -D webpack-cli`

**Expected behavior**
Successful install

**Screenshots**
![image](https://user-images.githubusercontent.com/706078/51408348-8637ad80-1b45-11e9-8370-60fc7d2cdecf.png)

**Additional context**
Docker image: `node:8.14.0`

https://stackoverflow.com/q/54133942/340760

**Comment by zslucky** [comment]
Same issue

**Comment by brunolm** [comment]
No, I'm installing with `-D` (`--save-dev`)

**Comment by EricLambrecht** [comment]
I'm having the same issue. It works fine globally, but not locally (as a dev dependency using npm 6.6.0).

**Comment by fkranenburg** [comment]
We have the same issue here. Adding this dependency ourself helps for now, but this is not what we want.

**Comment by ematipico** [comment]
I can't reproduce it with the commands provided (I didn't use Docker). 
Are all of you using Docker? Please provide as much information as possible, triaging the issue is not simple. Or provide a repository where we can replicate the issue.

**Comment by EricLambrecht** [comment]
I solved it after being able to install it without `--no-bin-links`, so the problem was definitely the fact that there was no bin link.

**Comment by zslucky** [comment]
I used a docker image for building in jenkins, `webpack-cli` version `3.2.1` caused this issue

**Comment by EvsChen** [comment]
@ematipico I'm using `yarn add --no-bin-links webpack-cli@3.2.1` and reproduced this issue. My yarn version is `1.1.3`. Without `--no-bin-links` seems working fine. Also `npm v5.6` seems working with `npm install --no-bin-links webpack-cli@3.2.1`. I'm on Mac.

Can you guys provide more info on your system (or docker image)? I think it may be an issue with the symlinks. Mac/windows etc. handle this differently.

![image](https://user-images.githubusercontent.com/20365185/51514375-61478100-1e4a-11e9-8527-08fd6fdc81e0.png)

**Comment by tamasd** [comment]
I have the same issue on Windows 10. I generate the `packages.json` file with gradle (kotlin-frontend). Adding lightercollective as a dependency or devDependency does not help.

**Comment by brunolm** [comment]
Command to repro:

```
docker run -v "${pwd}:/usr/src/app" -w /usr/src/app --rm node:8.14.0 bash -c "npm init -y && npm install webpack-cli@latest postinstall lightercollective"
```

Output:

```
> webpack-cli@3.2.1 postinstall /usr/src/app/node_modules/webpack-cli
> lightercollective

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EINVAL: invalid argument, open '/usr/src/app/node_modules/webpack-cli/package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.Module._extensions..json (module.js:670:20)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/node_modules/webpack-cli/node_modules/lightercollective/index.js:5:15)
    at Module._compile (module.js:653:30)
npm WARN rollback Rolling back...
npm WARN rollback Rolling back...
npm WARN rollback Rolling back...
npm WARN rollback Rolling back...

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-cli@3.2.1 postinstall: `lightercollective`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-cli@3.2.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-22T12_10_25_574Z-debug.log
```

**Comment by Bluexin** [comment]
@tamasd temporary workaround is to specify an older version of `webpack-cli` manually in your dev dependencies :
```groovy
kotlinFrontend {
    /* ... */

    npm {
        /* ... */
        devDependency("webpack-cli", "3.1.2") // cf https://github.com/webpack/webpack-cli/issues/738
    }

    /* ... */
}
```

**Comment by tamasd** [comment]
@Bluexin thanks for the tip, I solved it temporarly by creating an "empty" (`int main() { return 0; }`) lightercollective.exe in my path.

**Comment by nelldkLee** [comment]
I have the same issue on Windows 10. it happens with `-D` option. 
so i just install lightercollective like `npm i -D lightercollective` 
and then `npm i -D webpack-cli` Done. Successful install

**Comment by slakbal** [comment]
also have this problem....

**Comment by evenstensberg** [comment]
Fixing on a new release this weekend

**Comment by evenstensberg** [comment]
Fixed

**Comment by WebReflection** [comment]
To whom it might concern, there are [3 ways to disabled lightercollective](https://github.com/WebReflection/lightercollective/blob/master/index.js#L6-L14)

  * don't include a `collective` entry in your package.json
  * set the rpm config level to silent, error, or warn
  * pass `DISABLE_OPENCOLLECTIVE=1` upfront (`1` or `true` or `y` or `yes`) or set it as ENV variable

I also find it weird nobody bothered me directly in here, and nobody filed a proper issue after digging what is exactly the problem.

lighter collective is few lines of code, it'd be great to improve it instead of removing it, 'cause it should be  a drop-i alternative to opencollective and it should "_just work_".

Regards.

**Comment by evenstensberg** [comment]
Or upgrade

**Comment by WebReflection** [comment]
> Or upgrade

@evenstensberg if that was for me, yes, I've updated lightercollective to avoid undesired errors in unknown envs, instead of asking everyone using it to add `|| exit 0` in their package.json
