### ISSUE TITLE
Close compiler after run

### ISSUE THREAD

**Issue by sokra** [webpack/webpack-cli#739]
**Is your feature request related to a problem? Please describe.**
webpack 5 requires closing the Compiler after running it.

**Describe the solution you'd like**
Call `compiler.close(callback)` when compilation finished. Only when doing a single run.

You can check existance of the close method to support webpack < 5 too: `if(compiler.close)`

**Describe alternatives you've considered**
None

**Additional context**
Cache is persisted when closing. It's also persisted when idle, but slower and it doesn't prevent the process from exiting.

**Comment by evenstensberg** [comment]
Fixed
