### ISSUE TITLE
webpack-cli-donate breaks webpack installation

### ISSUE THREAD

**Issue by AndreKR** [webpack/webpack-cli#748]
Since b4af4675 webpack-cli requires webpack-cli-scripts (which doesn't have a repository listed) *and* runs `webpack-cli-donate` as its postinstall script.

This makes it impossible to install webpack on **both Windows and BusyBox-based Linuxes** like Alpine:

```
>npm update

> webpack-cli@3.2.2 postinstall C:\build\node_modules\webpack-cli
> webpack-cli-donate

'bash' is not recognized as an internal or external command,
operable program or batch file.
```

```
# npm update

> webpack-cli@3.2.2 postinstall /build/node_modules/webpack-cli
> webpack-cli-donate

env: can't execute 'bash': No such file or directory
```

This happens *even though* I'm running my CI jobs with `DISABLE_OPENCOLLECTIVE=true`.

Guys, I'm grateful for all the work that went into Webpack, but things like this aren't really a motivation to donate. :(

**Comment by evenstensberg** [comment]
I’ll fix this 2morrow

**Comment by evenstensberg** [comment]
V.3.2.3 fixed this
