### ISSUE TITLE
Enh: Opencollective post install script

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#752]
**Is your feature request related to a problem? Please describe.**
As this is an open source project we need some sort of donation banner to indicate that we are looking for financial support. 

**Describe the solution you'd like**
A postinstall script in `package.json` that doesn't crash other platforms. I've created a bash script that should be written in JS instead of bash, being outputted when user installs webpack.

**Describe alternatives you've considered**
N/A

**Additional context**

https://github.com/evenstensberg/webpack-cli-scripts/blob/master/scripts/opencollective.sh

**Comment by misterdev** [comment]
I think this can be closed :)

**Comment by ematipico** [comment]
@misterdev 	A small advise: if you use magic comments in your PRs, you will be able to close automatically the issues once they are merged!

```
Closes #xxx
```

More here: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by misterdev** [comment]
Thanks @ematipico! Yeah, I know but this time I forgot to include that somewhere :)
