### ISSUE TITLE
[ENHANCEMENT]: Add integration tests

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack-cli#758]
**Describe the bug**
We need to add e2e tests for both webpack@alpha (5)

**What is the current behavior?**
webpack@5 is broken against webpack-cli@latest right now (I'll work on a PR for this)

**Expected behavior**
Any changes we make in the webpack-cli should run integration tests against @latest and @next tags if possible (or even just master/next branches).

**Other Details**
We should verify that `webpack/webpack`'s 0CJS defaults work in a simple project. (Could even run the examples) via the CLI as a set of mocks/examples.

**Comment by evenstensberg** [comment]
This is on the roadmap, thanks for keeping this in an issue. That is for the next branch though, this task seems appropriate for you @dhruvdutt , as you only need to upgrade webpack and run tests to see what is needed for tests as well as reading the changelog of webpack itself.

**Comment by TheLarkInn** [comment]
The most important part of this issue/enhancement is: 

webpack@next <= test against => webpack-cli@latest

This way any patchlevel changes can catch early breaking changes on both sides.

**Comment by evenstensberg** [comment]
We're syncing with master to have backwards compat. CLI wise changes aren't that huge to seperate branch

**Comment by anshumanv** [comment]
@evenstensberg @dhruvdutt what's the approach to setup the e2e test infrastructure?

How about we go for [nixt](https://github.com/vesln/nixt/)? Looks promising to me.

**Comment by dhruvdutt** [comment]
@anshumanv Sure, thing. Go ahead. 👍

**Comment by evenstensberg** [comment]
I think we're having a good e2e  infra right now using smoketests. Needs a bit of a revisit, and some additional configurations to test against. 

I think we need to add a couple of more tests, one for a folder that doesn't have watch, but for a simple config that compiles with dev-server, opens headless chrome and verifies that content gets rendered on page

**Comment by evilebottnawi** [comment]
bump

**Comment by evilebottnawi** [comment]
I think we can close it, because we have tests for webpack@4 and webpack@5
