### ISSUE TITLE
[0CJS] webpack's defaults should never be altered

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack-cli#759]
**Describe the bug**
Working around a bug on webpack-cli/master, I discovered some of the awesome work going on in webpack-cli@alpha. However, I noticed that the default terminal feedback, additional plugins, the `webpack/webpack` were being modified by default. This shouldn't be possible without the user providing additional flags or options. 

**What is the current behavior?**
Currently webpack's console feedback, display options, and config properties are being overridden when you use webpack-cli@alpha against webpack@5 (also it breaks because `optimize-css-assets-webpack-plugin` is not installed by default but I think solving this main issue prevents the next bug for now)/

**To Reproduce**
1. Create project w/ webpack-cli@alpha and webpack@alpha (5)
2. Create /src/index.js file in project root
3. Run webpack (webpack --mode production)

**Expected behavior**
**None of webpack's defaults are modified**

**Screenshots**
![screen shot 2019-02-11 at 7 44 02 am](https://user-images.githubusercontent.com/3408176/52576404-d74d6100-2dd4-11e9-9ddb-b3b769698948.png)

Above is screenshot of the default webpack/webpack terminal feedback being overridden (in fact there is a bug that lazy loaded chunks are also not being shown here)

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
I believe that the defaults that you are working towards are wonderful, however these should be only enabled if a user opts into a specific preset like `webpack --preset cli-default` or something (just a rough example).

Let's discuss at further length if you disagree, but @sokra and I both feel this is a safe direction to take for now (especially since neither project has no test infrastructure against each-other to validate default changes like this don't break eachother).

**Comment by TheLarkInn** [comment]
This is a v3 release blocker.

**Comment by dhruvdutt** [comment]
@evenstensberg If you can describe the fix, I can pick this up.

**Comment by evenstensberg** [comment]
There's quite some work left on the alpha version, but maybe let's go for the preset version. Means we will keep the current architecture but that will require additional work

**Comment by TheLarkInn** [comment]
Totally understand there's a lot of work left. I submitted the issue this week for two reasons: 

1. Get it in early to prevent massive rework
2. When webpack 5 beta is released, if people accidentally try to install CLI@next their whole dev experience won't be thrown off.

**Comment by evenstensberg** [comment]
I think that is ok. We keep master branch sync with the latest webpack and we seperate the new CLI on `next`

**Comment by evenstensberg** [comment]
I think we're gonna have a optional `use-defaults` flag that will enforce better defaults, other than that, I think we're goodie

**Comment by evilebottnawi** [comment]
bump

**Comment by anshumanv** [comment]
yep we have removed default configuration that we were applying before

**Comment by evilebottnawi** [comment]
So let's close :+1:
