### ISSUE TITLE
[UI] Enpoints for webpack-cli UI

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack-cli#760]
**Is your feature request related to a problem? Please describe.**
The extension of #649, We can now develop endpoints for all possible features of webpack-cli. This issue is for tracking the development on them.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
The endpoints include:
- [ ] init ( in progress under #756 )
- [ ] remove
- [ ] add
- [ ] update
- [ ] running npm scripts ( for serve, build, tests, etc.)

---
Anybody who wants to collaborate are welcome. For any help add a comment below.

**Comment by misterdev** [comment]
Hi @rishabh3112, I'm interested in helping with this. 
The most updated branch is `webpack-cli-ui`?

Is there a small recap of the current state of the project? There are many issues and PR, it's very likely I've missed something :)

I'm going to take a look at the endpoint for the npm scripts, any suggestion is welcome.

**Comment by rishabh3112** [comment]
Great @misterdev,
## current state
Currently we have decided the technologies to work on, express for backend and preact for frontend.
Layouts of pages are in progress after which we would be working on frontend.
Infrastructure for questioning users for scaffolding is setup using TCP classes
Now, writing endpoints.

---
So for now you can explore `webpack-cli-ui` branch and start working on the issue.

**Comment by theaayush8999** [comment]
@rishabh3112 are you working on the GUI(front-end)?

**Comment by theaayush8999** [comment]
I would like to contribute...till now only preact's boilerplate is present in the repo.

**Comment by rishabh3112** [comment]
Hi @theaayush8999 we would be working on GUI after designs are finalised.

**Comment by misterdev** [comment]
@rishabh3112 Who is currently working on GUI design?

**Comment by rishabh3112** [comment]
Follow #654.

**Comment by strongSoda** [comment]
Hi, @rishabh3112  I too am interested to work on this with you. I am following the discussion & roadmap issues.

**Comment by rishabh3112** [comment]
Closing this issue. Thanks, everyone for the feedback 😃.
Further feedback can be shared at rishabh3112/webpack-ui#1
