### ISSUE TITLE
No install possible

### ISSUE THREAD

**Issue by jonyking** [webpack/webpack-cli#764]
**Do you want to request a *feature* or report a *bug*?**
**Bug**

**What is the current behavior?**
**I can not install webpack with.**

**If the current behavior is a bug, please provide the steps to reproduce.**
I have a clean install of node.js (inluding npm). Create a project used npm init and then use `npm install --save-dev webpack`

**What is the expected behavior?**
Installing webpack.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**
**Command not found!**

**Comment by rishabh3112** [comment]
Hi, @jonyking you forget to install `webpack-cli` most probably.
Install both of them using
```bash
npm install webpack webpack-cli --save-dev
```

**Comment by evenstensberg** [comment]
Yes that is correct, you will need to install webpack cli
