### ISSUE TITLE
Module not found err is logged when agreed to install a missing package

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#771]
**Describe the bug**

When running a webpack command and the corresponding package is missing, once you agree to install it `MODULE_NOT_FOUND` err is logged before actually installing the package.

**What is the current behavior?**

Errors logged when agreed to install a missing package.

**To Reproduce**
* Run a webpack command whose package isn't installed say `webpack-cli info`
* Since the package is missing it will prompt whether to install the package, pick yes
* And the `MODULE_NOT_FOUND` is logged before installing the package

**Expected behavior**
It should directly install the package.

**Screenshots**
![image](https://user-images.githubusercontent.com/21009455/53784694-1d14c980-3f3c-11e9-9427-f0a8fd72a3f8.png)

Will be more than happy to look into this and submit a patch, given this is a legit issue. 😄 

Please comment if I missed something.

**Comment by rishabh3112** [comment]
Hi @anshumanv, Thanks for reporting the issue. This is already reported at #741 and is under fix at #742.

**Comment by anshumanv** [comment]
Hi @rishabh3112, thanks for linking me to the resource I missed. Closing. 😄
