### ISSUE TITLE
Docs: Publish docs on every push from gh-pages branch

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#774]
**Do you want to request a *feature* or report a *bug*?**
Docs feature maybe

**What is the current behavior?**
Docs are pushed with the CLI code.

**If the current behavior is a bug, please provide the steps to reproduce.**
NA

**What is the expected behavior?**
I think it makes sense to automate the docs publishing process so docs live separate from the CLI code and are updated on every push, we can simply run a travis hook for every push for this and then we can host them on gh-pages or elsewhere.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Automated docs, cleaner code

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**
```
webpack-cli info

  System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  Binaries:
    Node: 10.14.1 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.119
    Safari: 12.0.3
  npmPackages:
    webpack: 4.x.x => 4.29.6
    webpack-dev-server: ^3.1.10 => 3.2.1
```

Will do a quick PR in case we agree to proceed with this. 😄

**Comment by anshumanv** [comment]
@evenstensberg using Netlify as the hosting service, is that alright?

**Comment by anshumanv** [comment]
Here's a sample how it looks @evenstensberg 😉 

https://webpack-cli.netlify.com/

**Comment by evenstensberg** [comment]
why netify over gh?

**Comment by anshumanv** [comment]
@evenstensberg here's a comparative breakdown - https://www.netlify.com/github-pages-vs-netlify/

Also we don't need to push the docs anywhere too (gh-pages branch for instance) Netlify takes care of that. We can also get updated docs on each PR but we won't need that IMO.

**Comment by evenstensberg** [comment]
I don't think we'll need netify

**Comment by ematipico** [comment]
Is there a way to have github pages without pushing the new documentation every time?

**Comment by anshumanv** [comment]
Yes, manually push them when you need to @ematipico 

So @evenstensberg can we move docs to gh-pages branch and serve from there(cleaner application root)? Without automating the deploys, everything remains the same, just the docs live in the gh-pages branch and are served from there, allows manual editing and more control as we need. 🤔

**Comment by anshumanv** [comment]
Keep the feedback/suggestions as someone finds some solution to host docs more aptly. 😄
