### ISSUE TITLE
Feature: Verify that transformed JS code is valid

### ISSUE THREAD

**Issue by okonet** [webpack/webpack-cli#78]
**Do you want to request a *feature* or report a *bug*?**

feature

**If this is a feature request, what is motivation or use case for changing the behavior?**

Even after a successful transform there is no way to say that the produced code is a valid JS. We could implement a separate step that will validate the produced code for syntax errors and if there are any, we could throw a more helpful error. 

This is easy to achieve using ESLint parser without any rules.

**Comment by ev1stensberg** [comment]
This could be a problem, I disabled `WebackOptionsValidator` for `init` because of different usage. Say if a person uses `webpack-merge`, they will get error'd. Would be nice to have a seperation based on config name

**Comment by ev1stensberg** [comment]
Implemented in newer versions
