### ISSUE TITLE
Scaffold: Better defaults for webpack-cli init questions

### ISSUE THREAD

**Issue by misterdev** [webpack/webpack-cli#788]
**Is your feature request related to a problem? Please describe.**
`webpack-cli init` from my point of view has 2 main purposes, making the setup faster and making it easier expecially for beginners. For these reasons I think the default answers for `webpack-cli init` should be modified to allow creating the simpler possible setup.

**Describe the solution you'd like**
1.  `? Will your application have multiple bundles? (Y/n)`
Having multiple bundles is an "advanced" and less common configuration compared to having just one entry point.
I think the default should be `(y/N)`

2. `? Will you use one of the below CSS solutions?`
Same here, the default option is `SASS` where a better default would be `No`:
    ```
    > SASS
      LESS
      CSS
      PostCSS
      No
    ```
    Also, I use `init` mainly to scaffold node projects where I don't use CSS.

**Additional context**
I think this is a very very small modification that can slightly improve the user experience.

I can work on this if it is something desirable :)

**Comment by rkishan516** [comment]
@evenstensberg & @misterdev Can I work on this ?

**Comment by misterdev** [comment]
Hi @rkishan516, I'm already working on this. Thanks for your interest 👍

**Comment by anshumanv** [comment]
Fixed in #794 
Can be closed. 😄
