### ISSUE TITLE
Installation in Linux

### ISSUE THREAD

**Issue by rkishan516** [webpack/webpack-cli#793]
When we are installing the webpack in Linux distro we are getting Error because before npm , we must use sudo command to give root permission.

CLI will remain same but we can add just `sudo` in Documentation.

**To Reproduce**
Just Update the CONTRIBUTING.md file

**Expected behavior**
After adding `Sudo` Installation will work as it should be. 

If you allow I can give a PR for this.

**Comment by rishabh3112** [comment]
Hi @rkishan516,
Can you share steps to reproduce this?
I use webpack in Linux and not facing any issue regarding permissions.
I guess you may have misconfigured your node installation, try [nvm](https://github.com/creationix/nvm).
Hope this helps 👍

**Comment by rkishan516** [comment]
![Screenshot from 2019-03-17 14-07-58](https://user-images.githubusercontent.com/34465683/54487623-2435c300-48be-11e9-82b6-b9b4995010a7.png)
When I use `npm install`
This is the status.
@rishabh3112 or @dhruvdutt

**Comment by evenstensberg** [comment]
https://stackoverflow.com/questions/25290986/how-to-fix-eacces-issues-with-npm-install fix your permissions inside the directory

**Comment by rkishan516** [comment]
Thanks, For Solution
