### ISSUE TITLE
[BUG]: @webpack-cli/add not working on topScope and merge

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack-cli#795]
**Describe the bug**
When we want to add something to `topScope` raises following error
![Screenshot from 2019-03-18 20-10-56](https://user-images.githubusercontent.com/15812317/54538493-5cbac700-49ba-11e9-8b7e-e834a1ed7c50.png)

**What is the current behavior?**
Currently this error raises as `add-generator` maps properties from `optionsSchema` of webpack. But this schema doesn't include properties that are part of `configuration` object we create in generator.

**To Reproduce**
1. `webpack add`
2. `give answer as topScope`

**Expected behavior**
Add items to topScope

**Screenshots**
uploaded above

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
```

  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (3) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.13.0 - ~/.nvm/versions/node/v10.15.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Browsers:
    Firefox: 65.0.1
  npmGlobalPackages:
    webpack-cli: 3.2.3
    webpack: 4.29.3
```
**Additional context**

**Comment by rishabh3112** [comment]
On researching, I found there is same bug with `merge` too. For solving this I have two solutions:
1. Take multi line input for the object to be merged
2. Take location of config file with which user want to merge current configuration.
Which approach is recommended ?

**Comment by evenstensberg** [comment]
Location
