### ISSUE TITLE
Feature(config-test): Evaluating the webpack configs.

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack-cli#803]
**Is your feature request related to a problem? Please describe.**
Webpack has a steep learning curve, I still remember those difficulties I have faced in my early days with webpack when my webpack config didn't works as I expected it to be.

**Describe the solution you'd like**
Creating a cli package called `test`, which takes the webpack config -> Analyzes it. It will log the error in the config if any. Not only this, the main feature of this package would be that it shows warning if you are doing something wrong. Something wrong means your webpack config could work but you can make some tweaks (which the webpack suggests) in your config in order to get the best performance. 

This could be a game changer if paired with the upcoming cli UI.

It's like eslint on configs.

**Describe alternatives you've considered**
- Create a separate package, if it doesn't exist.

**Additional context**
> `webpack test webpack.config.js`
- Errors in the config if any
- You can use this instead of that......

Can't say about its scope, so let's discuss :fire:

**Comment by evenstensberg** [comment]
yes let's do this

**Comment by evenstensberg** [comment]
just use webpack validate schema for checking

**Comment by anshumanv** [comment]
Can't this be a part of https://github.com/webpack/webpack-cli/issues/588 which will essentially do both -
* Validate the config
* Stress the library for edge cases

So we'll get both functionalities out of it, but yeah a separate package will be a more external thing which people can use to validate their configs. 👍

**Comment by evenstensberg** [comment]
Config evaluation in sep feat

**Comment by evenstensberg** [comment]
For the config evaluation, we could do the following:

1. Same syntax as `apachectl test`
2. Use validation schema and output warn to console

**Comment by anshumanv** [comment]
Core already does the schema validation of the config passed, do we need this? 
/cc @evilebottnawi

**Comment by evilebottnawi** [comment]
I think test command will be great, it is very easy to implement

**Comment by snitin315** [comment]
something like `webpack --test-config webpack.config.js` ?

**Comment by evilebottnawi** [comment]
no, it should be command

**Comment by evilebottnawi** [comment]
webpack test ./webpack.config.js
