### ISSUE TITLE
tests: Tests failing

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack-cli#812]
**Describe the bug**

Tests failing

**To Reproduce**
- clone the repo
- npm install
- npm link
- npm link webpack-cli
- npm run bootstrap
- npm run build
- npm run test

**Expected behaviour**
All tests should pass
**Screenshots**
**Check out this video**

**Additional context**
Am I doing something incorrectly? :confused:

**Comment by evenstensberg** [comment]
No link to video. I just did the same steps and it ain't failing here. Do you mind posting a stack trace?

**Comment by pranshuchittora** [comment]
https://youtu.be/cj0d5N1Qt6c

**Comment by evenstensberg** [comment]
try running `lerna bootstrap` and fetching latest changes from master
