### ISSUE TITLE
Enhancement: Init generator improvements

### ISSUE THREAD

**Issue by misterdev** [webpack/webpack-cli#814]
**What is the current behavior?**
The init generator executed while running `webpack-cli init` creates a webpack configuration file and installs the dependencies, I think it could be improved:
- There are some unused imports and comments in the generated configuration file
- The keys in the configuration object are in a random order, IMO this should be an example of good practices for beginners
- The entry point provided by the user is never set in the final configuration file
- We check many times a variable [isProd](https://github.com/webpack/webpack-cli/blob/master/packages/generators/init-generator.ts#L29) that is initialized to `false` and never updated
- The code could be refactored, `topScope` and `webpackOptions` are initialized sparsely
- When multientry configuration is chosen we suggest naming the entries "app" and "vendor", this seems to be [discouraged](https://webpack.js.org/concepts/entry-points/#separate-app-and-vendor-entries) in v4

**What is the expected behavior?**
- [x] generate some boilerplate too (eg. generate the entry point in `src/index.js`)
- [ ] cleaner code
- [x] cleaner configuration with ordered keys 

I think this would benefit the programmatic usage too.

I'm already working on this, please let me know any opinion and if you think there's something else that can be improved :)

**Comment by pranshuchittora** [comment]
I would like to work on this.

**Comment by misterdev** [comment]
That's nice :) At the moment I have a branch for this but I'm working on other things, I'll open a PR soon.
