### ISSUE TITLE
[NEXT] : CLI UI | Before getting started ?

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack-cli#824]
There are few things that must be addressed before getting started
- What's the [bundle budget](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/budgets.md)
- How the UI is going to be served.
     1. via a local server (by default React)
    2. or as a static site - pre-rendered/SSRed (using Gatsby)
- Is it going to be served as a separate package or with the core cli?
- Exactly what core functionalities it's going to bring over the CLI.
- How much system res it will use?

I know a few things have already been discussed, but let's get the final verdict.

**Comment by ematipico** [comment]
There's already a discussion open, let's the discussion alive there: https://github.com/webpack/webpack-cli/issues/647
