### ISSUE TITLE
[serve]: serving from anywhere in the project is not functional

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#829]
**Describe the bug**
Presently `webpack-cli serve` requires you to be in the project root to function properly but user can be anywhere in the project and till it's a webpack project serving should work from anywhere in the project it is executed.

**What is the current behavior?**
Only works from  project root,

**To Reproduce**
Run `webpack-cli serve` from a dir inside project root.

**Expected behavior**
It should work from anywhere in the project.

**Screenshots**
NA

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
Add any other context about the problem here like linking to an similar issue you might think is the cause.

**Comment by ematipico** [comment]
Is it really a bug or it's an enhancement/feature?

**Comment by anshumanv** [comment]
> Is it really a bug or it's an enhancement/feature?

Should be a bug since the user needs to be able to run serve from any place in the project, should I send a PR? @ematipico

**Comment by ematipico** [comment]
That's the thing: where is it written this requirement? Honest question, I wasn't aware of this behaviour

**Comment by anshumanv** [comment]
> where is it written this requirement? 

I don't think this is stated as a requirement anywhere, but IMO this should be how it should work where user be inside any dir of the project and can serve the project.

What do you think? @ematipico 🤔

**Comment by ematipico** [comment]
I think that this is not a bug because there's not a requirement and few people have complained about the current behaviour. Loads of people run their scripts from project root, less people from a sub directory. It's a nice to have!

So I'd say it's a feature because we are extending a functionality that we already have.

**Comment by anshumanv** [comment]
> So I'd say it's a feature because we are extending a functionality that we already have.

Yeah works, https://github.com/webpack/webpack-cli/pull/831 aims to solve this PTAL 🙏 😄
