### ISSUE TITLE
[cli]: Installation prompt should look for package from project root.

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#830]
**Describe the bug**

Installation prompt is presently searching for packages that are executed like `serve, init` etc in the `cwd` which is not ideal for cases when user is in some other dir inside root and wishes to execute the package so the lookup for whether a package is installed or not is done in the `cwd` and not in the project-root

**What is the current behavior?**
Package lookup is done in present working dir.

**To Reproduce**
`in a webpack project dir, @webpack-cli/serve is already installed`
`
cd some-dir && webpack-cli serve
`

This will throw a prompt to install the package but it is already installed 😟 

**Expected behavior**
Package lookup from project root or the nearest package location.

**Screenshots**
NA

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
Add any other context about the problem here like linking to an similar issue you might think is the cause.

**Comment by anshumanv** [comment]
@ematipico @evenstensberg think this fix is needed?

**Comment by evenstensberg** [comment]
No, we need to symlink

**Comment by anshumanv** [comment]
> No, we need to symlink

Can you help me understand what changes are needed or none at all?

**Comment by evenstensberg** [comment]
You will first need to look for the package in global and then local

**Comment by anshumanv** [comment]
Okay! Updating the PR to look for global -> project root -> cwd

In this order

**Comment by anshumanv** [comment]
@evenstensberg you sure we need to change the workflow? Right now it's looking for cwd first and then goes to global to check if a package is installed, I've proposed to check the project root -> cwd -> global which makes sense IMO, what do you think?

For the serve package it is presently initiated in cwd, but I think the project root is more ideal location to start the webpack-dev-server.

**Comment by ematipico** [comment]
Changing the flow means breaking change... So major release.

**Comment by anshumanv** [comment]
Yeah, I guess for now we can just make a minor improvement of starting off the server from the project root then go to the cwd, just a minor change since I think it makes more sense to start the project from it's root. @ematipico 
No changes to the core flow as per the current PR.
