### ISSUE TITLE
[BUG]: Configuration handling fixes and refactoring

### ISSUE THREAD

**Issue by tomasz-sodzawiczny** [webpack/webpack-cli#839]
Due to how the the config parsing is implemented it has a few unexpected behaviours. I understand where they're coming from in the code and have a few suggestions for the fix(es).

**I'm happy to do the work**, just want to make sure that this direction is correct and there are no other plans/changes needed as I'm refactoring this part.

## Problems 

(See https://github.com/webpack/webpack-cli/pull/838 for tests for the issues described below)

### 1. Providing multiple config files breaks in some cases (even if every config separately works perfectly fine)

It's possible to add multiple configs with `--config` option but it's only works if the files export some config types (functions and objects), not others (arrays and promises).

This is because handling multiple configs is done by the same code as a single config exporting an array - which doesn't support some compositions, see below.

### 2. It's unclear which config compositions are allowed
[The docs](https://webpack.js.org/configuration/configuration-types) are not perfectly clear on what is allowed and what is not.

The implementation behaves quasi-randomly: e.g. a Promise returning an Array is fine, but an Array of Promises is not.

More importantly array of arrays is not supported (which breaks e.g. multi-config setups where some of the configs are arrays, see above).

### 3. ES Modules parsing leads to unexpected results

`default` field parsing is recursive so this is a perfectly fine webpack config:

```js
module.exports = {
  default: {
    default: {
      default: {
        entry: "./entry",
        output: { filename: "entry.bundle.js" }
      }
    }
  }
};
```

Mixing with arrays / promises / functions works as well.

## Solution
I suggest refactoring the code to match following definition:

```
type ConfigObject = {
  entry: ...
}

type Config = ConfigObject
            | Array<Config>
            | Promise<Config>
            | () => Config;
```

I'm not sure if webpack's `validageSchema()` supports circular definitions, this can be worked-around by only validating the ConfigObject and handling the rest manually (this is how promises/functions already work now).

### ES Modules
`default` is accepted only at the top level object exported from a module.

### Misc
Some additional things can be achieved in the progress:
* some code duplication can be removed (currently [`processConfiguredOptions`](https://github.com/webpack/webpack-cli/blob/b8d5511ef3ede072f12f99e398339e6760eb39f1/bin/utils/convert-argv.js#L137) and [`prepareOptions`](https://github.com/webpack/webpack-cli/blob/b8d5511ef3ede072f12f99e398339e6760eb39f1/bin/utils/prepareOptions.js#L3) cover the same thing)
* the config options parsing can be extracted from the 560-line-long `convert-argv.js`

---

What do you think? Are there some red flags for this approach I'm not seeing?

**Comment by evenstensberg** [comment]
@tomasz-sodzawiczny do you mind opening a new PR to the `next` branch? Would be greatly appreciated

**Comment by snitin315** [comment]
Bump

**Comment by anshumanv** [comment]
bump

**Comment by alexander-akait** [comment]
Fixed in master, for ES modules supporting we have separate issue (we are supporting es modules syntax, but here bug on `v8-compile-cache`, hope I will fix it in near future), docs will be improved in near future
