### ISSUE TITLE
[DOCUMENTATION]: Migration of docs to webpack.js.org

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack-cli#840]
Docs are something which is one of the most important references for any developer. What's worse than outdated docs :cry: .

Like these
- [Scaffolding](https://github.com/webpack/webpack-cli/blob/master/SCAFFOLDING.md) 
- [Migrate](https://github.com/webpack/webpack-cli/blob/master/MIGRATE.md)
and many more.

### Solution
The idea is to migrate/shift all the documentation to the webpack.js.org to make it the only source of truth.
Keep only those docs which are required for the development of the cli project.

**Do you want to request a *feature* or report a *bug*?**
Better codebase

**What is the current behaviour?**
Docs are spread all over the project.
 
**What is the expected behaviour?**
Migrate docs to webpack.js.org, for better maintainability.

**Pls discuss :+1:**

**Comment by misterdev** [comment]
There's already a discussion on this: [#2894](https://github.com/webpack/webpack.js.org/pull/2894) :)

**Comment by evilebottnawi** [comment]
bump

**Comment by evilebottnawi** [comment]
We should do some improvement after refactor

**Comment by alexander-akait** [comment]
`Migrate` was deprecated and removed, updating `Scaffolding` will be after https://github.com/webpack/webpack-cli/issues/2430
