### ISSUE TITLE
[Bug]: `npm run docs` fails

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#848]
**Describe the bug**

A 💯 way to do this is to provide your configuration via a GitHub gist and/or to use markdown when describing which commands you used when the error occurred! Be precise and clear in your description of the bug.

**What is the current behavior?**

Running the command results in an error.
This is where you elaborate on the current behavior of the cli, how it behaves normally differing from the previous version/build you did. 

**To Reproduce**
1. clone the repo
2. install deps
3. run `npm run docs`

**Expected behavior**
Documentation is generated

**Screenshots**
```
Using TypeScript 3.1.6 from /Users/evenstensberg/Documents/Github/webpack-cli/node_modules/typedoc/node_modules/typescript/lib
INFO: applying regexp  .*packages/(@webpack-cli/[^/]+)/.*  to calculate module names
INFO: Enabled true
Error: /Users/evenstensberg/Documents/Github/webpack-cli/packages/add/node_modules/@webpack-cli/utils/scaffold.ts(6)
 Cannot find module '../init/types'.
Error: /Users/evenstensberg/Documents/Github/webpack-cli/packages/generate-loader/node_modules/@webpack-cli/generators/addon-generator.ts(6)
 Cannot find module '../generate-loader/types/Yeoman'.
```

**Comment by anshumanv** [comment]
Investigating this 👍
