### ISSUE TITLE
[request] opencollective postinstall should respect DISABLE_OPENCOLLECTIVE

### ISSUE THREAD

**Issue by 3cp** [webpack/webpack-cli#854]
**Is your feature request related to a problem? Please describe.**
The inhouse opencollective postinstall `bin/opencollective.js` should respect DISABLE_OPENCOLLECTIVE (or CI) environment variable just like standard opencollective-postinstall.

https://github.com/opencollective/opencollective-postinstall/blob/7a5c767e043f7e86c452f5f8b96b9cf4db7a8ce5/index.js#L7

**Describe the solution you'd like**
It should respect environment variables DISABLE_OPENCOLLECTIVE and CI, in order to allow user to turn the donation prompt off.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by anshumanv** [comment]
Will fix this. 👍

**Comment by evenstensberg** [comment]
The prompt is showing 1 day per week and only if you install it on that particular day. I don't think it's a big problem.

**Comment by huochunpeng** [comment]
> The prompt is showing 1 day per week and only if you install it on that particular day.

I might missed something obvious. Where is the date related config/code?

**Comment by anshumanv** [comment]
https://github.com/webpack/webpack-cli/blob/309cc1c53fce3fa2cead8955f90182a1d99b5841/bin/cli.js#L322

**Comment by huochunpeng** [comment]
Thx @anshumanv. Your one is different from this topic.

This issue is about the prompt during `npm install`, not when running webpack cli.

https://github.com/webpack/webpack-cli/blob/309cc1c53fce3fa2cead8955f90182a1d99b5841/package.json#L39

https://github.com/webpack/webpack-cli/blob/master/bin/opencollective.js

**Comment by ematipico** [comment]
Yes, this request is legit, we should give the possibility to turn off the prompt at least during CIs
