### ISSUE TITLE
🐞[cli]: throws err when no args passed. 

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack-cli#861]
**Describe the bug**

CLI throws an error when no args passed. Occurs only if `webpack` is not installed.

![Screenshot from 2019-04-26 11-20-44](https://user-images.githubusercontent.com/32242596/56787272-9ed8f300-6819-11e9-95bb-ba786f765f5d.png)

**What is the current behaviour?**
Throws an error.
**To Reproduce**
Steps to reproduce the behaviour:

1. Create a new folder.
2. `npm init -y`
3. `npm i webpack-cli`
4. ` ./node_modules/webpack-cli/bin/cli.js `

**Expected behavior**
Must provide some useful information in order to resolve the issue, instead of showing err logs.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
  System:
    OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 10.12.0 - ~/.nvm/versions/node/v10.12.0/bin/node
    Yarn: 1.12.3 - /usr/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v10.12.0/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 66.0.3
  npmPackages:
    webpack: ^4.30.0 => 4.30.0 
    webpack-cli: ^3.3.1 => 3.3.1 
  npmGlobalPackages:
    webpack-cli: 3.3.1
    webpack: 4.27.1

**Comment by ematipico** [comment]
Have you installed webpack?

**Comment by pranshuchittora** [comment]
No I haven't installed webpack.
This error occurs when `webpack` is not installed and no args passed to the CLI. https://github.com/webpack/webpack-cli/pull/862

**Comment by evenstensberg** [comment]
This is a no fix in my opinion

**Comment by pranshuchittora** [comment]
@evenstensberg 
The fix for this is to output a proper message(steps/warning) in order to channelise the user for a successful run.
