### ISSUE TITLE
[CI]: investigating broken CI

### ISSUE THREAD

**Issue by misterdev** [webpack/webpack-cli#864]
**Describe the bug**
I'm investigating on how to fix the currently broken CI.

Travis on the same commit completed with success previously (see [builds](https://travis-ci.org/webpack/webpack-cli/builds)):

![zio](https://user-images.githubusercontent.com/11232797/56827984-98219e80-6860-11e9-90db-74d8d7bd8797.png)

But now fails on `travis_wait npm ci` ([log](https://travis-ci.org/webpack/webpack-cli/jobs/523674012#L548)).

Does anyone knows what is happening?

**Comment by ematipico** [comment]
I can't tell honestly. Maybe it's an issue with travis + lerna?

**Comment by ematipico** [comment]
Ok, the problem is around Node 12. I'd suggest, to fix this issue, is to remove the stable from our Travis CI configuration and adding Node 12 as separate PR. Probably there's a breaking change around our deps or around travis

**Comment by misterdev** [comment]
Ok, I'll take a look at this. Thank you!

**Comment by misterdev** [comment]
The installation of [`iltorb`](https://github.com/MayhemYDG/iltorb) fails when `node-gyp rebuild` is executed.
It happens on Windows, Linux, and MacOS both on Travis and Azure Pipelines (see #872), the common factor is Node 12, that explains why the CI broke the same day that Node 12 became "stable"

![iltorb](https://user-images.githubusercontent.com/11232797/56915521-03fd4480-6ab7-11e9-94fa-6d4ae2dc93cb.png)

**Comment by misterdev** [comment]
Seems like iltorb doesn't support node 12
We use `bundlesize` that depends on `iltorb`, there's an open PR to fix this [bundlesize#295](https://github.com/siddharthkp/bundlesize/pull/295) I guess we should wait for it to be merged.
