### ISSUE TITLE
[ENHANCEMENT]: move types to @types/jscodeshift

### ISSUE THREAD

**Issue by ematipico** [webpack/webpack-cli#866]
At the moment we use internal interfaces for our AST functions. This is not working as we have duplicates and this will hit really bad on the long run.

We should move to [`@types/jscodeshift`](https://www.npmjs.com/package/@types/jscodeshift)

For this one, ideally it would be better to create PRs for each package, starting from the small ones.

**Comment by anshumanv** [comment]
Will take a look at this. :)

**Comment by evenstensberg** [comment]
@anshumanv thanks :)

**Comment by omginbd** [comment]
Seems like this was about 6 months ago and I'm looking for a "Good First Contribution" ticket, does anyone mind if I start looking into this?

**Comment by evenstensberg** [comment]
Yes!! If you want help, we’re here for you!

**Comment by omginbd** [comment]
👍 Great, I'll get started!

**Comment by hemal7735** [comment]
@ematipico shouldn't we do the same for Webpack options?

should we move [WebpackOptions](https://github.com/webpack/webpack-cli/blob/next/packages/generators/types/index.ts) to [webpack-type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webpack/index.d.ts) ?

**Comment by snitin315** [comment]
bump

**Comment by Cronus1007** [comment]
@snitin Please assign this issue to me.

**Comment by snitin315** [comment]
Feel free to send a PR.

**Comment by Cronus1007** [comment]
@snitin @EugeneHlushko  @ematipico  Sir in my opinion rather than moving to @types/jscodeshift we can apply the cohesion principle.

**Comment by Cronus1007** [comment]
#1933 @anshumanv   Sir I think the linked PR would close this issue for the particular Info package.

**Comment by shreyan-invalid** [comment]
Hey, I am new to open source contribution, I would like to work with this issue, can you guide me through it?

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack-cli/issues/2430
