### ISSUE TITLE
Broken add-generator

### ISSUE THREAD

**Issue by misterdev** [webpack/webpack-cli#875]
**Describe the bug**
Executing `webpack-cli add` and choosing `"amd"` results in an error:
> UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'definitions' of undefined
It seems to happen with most of the options (tested with bail, context, ...)

**To Reproduce**
1. Execute  `webpack-cli add` 
2. Choose `"amd"`

**Screenshots**
![bug-add](https://user-images.githubusercontent.com/11232797/57032494-d0ebba00-6c4a-11e9-8f84-cf2e056a8624.png)

**Comment by rishabh3112** [comment]
Thanks @misterdev, this is already reported at #867 and is fixed in #843 .

**Comment by misterdev** [comment]
Oh great, nice to know!
