### ISSUE TITLE
webpack-cli@3.3.1 postinstall: `node ./bin/opencollective.js` npm ERR! Exit status 134

### ISSUE THREAD

**Issue by Hethsron** [webpack/webpack-cli#878]
**Describe the bug**

A 💯 way to do this is to provide your configuration via a GitHub gist and/or to use markdown when describing which commands you used when the error occurred! Be precise and clear in your description of the bug.

**What is the current behavior?**

This is where you elaborate on the current behavior of the cli, how it behaves normally differing from the previous version/build you did. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
Add any other context about the problem here like linking to an similar issue you might think is the cause.

**Comment by Hethsron** [comment]
@okonet Hi 

I try to install webpack-cli but i have this error 👎 
Aborted
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! webpack-cli@3.3.1 postinstall: `node ./bin/opencollective.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the webpack-cli@3.3.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

What can i do to solve this problem?

**Comment by misterdev** [comment]
Hi, thanks for reporting this. In order to understand what's the problem please fill the template provided when you created the issue. 
The first message of this conversation is the template I'm talking about, you can edit it

Also, please provide a repository to reproduce the error.

Thanks :)

**Comment by evenstensberg** [comment]
Could you give a complete stack trace after removing node modules and running npm install again?

**Comment by evenstensberg** [comment]
webpack-cli v.3.2.2 comes with a fix for this.

**Comment by okonet** [comment]
Repo orgs: Can someone remove me from the project. I’m reviving too many emails and I’m not even working on it. Thanks!

Everyone else: please don’t mention people in issues if this isn’t really necessary.

**Comment by evenstensberg** [comment]
Will do this tomorrow Andrey. Hope you’re doing well! 🤗

**Comment by dev-xror** [comment]
@evenstensberg  I'm getting the same error when trying to install webpack globally... there's no specific errors to check..  I tried different approach but with no luck... please help. :(

![image](https://user-images.githubusercontent.com/49257225/58103537-26afe400-7bb1-11e9-8e9a-d952abc558f4.png)

**Comment by dev-xror** [comment]
@macjohnny I'm getting the same error when trying to install webpack globally... there's no specific errors to check..  I tried different approach but with no luck... please help. :(

![image](https://user-images.githubusercontent.com/49257225/58104892-8ad3a780-7bb3-11e9-8d4f-898250af314b.png)

**Comment by dev-xror** [comment]
@evenstensberg  I'm getting the same error when trying to install webpack-cli globally... there's no specific errors to check..  I tried different approach but with no luck... please help. :(

![image](https://user-images.githubusercontent.com/49257225/58104892-8ad3a780-7bb3-11e9-8d4f-898250af314b.png)

**Comment by misterdev** [comment]
Hi @dev-xror, thanks for reporting this, could you please open a new Issue?

Also:
> Could you give a complete stack trace after removing node modules and running npm install again?

**Comment by wing324** [comment]
Does it fixed? I am using webpack-cli 3.3.2 now, but I still get the same error
$ npm install --save-dev webpack-cli

> webpack-cli@3.3.2 postinstall D:\mygithub\Wcoding\webpack\webpack-demo\node_modules\webpack-cli
> node ./bin/opencollective.js

'node' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-cli@3.3.2 postinstall: `node ./bin/opencollective.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-cli@3.3.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2019-06-06T19_26_21_251Z-debug.log

**Comment by misterdev** [comment]
The most updated conversation about this is #870:

> 1. remove webpack-cli from your pkg json
> 2. `rm -rf node_modules package-lock.json && npm install && npm install --save-dev webpack-cli`

**Comment by wing324** [comment]
> The most updated conversation about this is #870:
> 
> > 1. remove webpack-cli from your pkg json
> > 2. `rm -rf node_modules package-lock.json && npm install && npm install --save-dev webpack-cli`

Hi,
Thank you for your reply. I did what you said, but it still the same error. If you could help me, I would really appreciate it.

**Comment by misterdev** [comment]
Hi! [v3.3.3](https://www.npmjs.com/package/webpack-cli) has just been released with a fix for this. I suggest you to try it and if you still have this problem you can open a new detailed issue :)
