### ISSUE TITLE
Incorrect github tags

### ISSUE THREAD

**Issue by teppeis** [webpack/webpack-cli#879]
**Describe the bug**

v3.3.2 is tagged as `v3.2.2` in GitHub incorrectly.

- https://github.com/webpack/webpack-cli/releases/tag/v3.2.2
- https://github.com/webpack/webpack-cli/commit/f0031fdd037a5ad3d5dca97b23aaac96c9edd4fb

Also, v3.2.2 is tagged as `v.3.2.2` (including a weird dot after "v").

- https://github.com/webpack/webpack-cli/releases/tag/v.3.2.2

In GitHub tags, some versions include the dot and the others don't include it.

- https://github.com/webpack/webpack-cli/tags

All correct in npm.

- https://www.npmjs.com/package/webpack-cli?activeTab=versions

**Expected behavior**

- v3.3.2 should be tagged as `v3.3.2` in GitHub.
- Tags in GitHub should not include a dot after "v".

**Comment by evenstensberg** [comment]
Thanks for reporting. We're gonna follow npm convention from now on.

**Comment by ematipico** [comment]
@teppeis Thank you for reporting. This is now fixed!
