### ISSUE TITLE
Migrate: Remove OccurenceOrderPlugin

### ISSUE THREAD

**Issue by jouni-kantola** [webpack/webpack-cli#88]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
`new webpack.optimize.OccurenceOrderPlugin(true)` doesn't get removed from `webpack.config.js` when migrating the config from webpack 1 to 2. This results in an error after migrated config is used for build.

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack.config.js before migrate:
```const path = require('path');

const webpack = require('webpack');

module.exports = {
  entry: {
    'vendor': ['is-thirteen', 'no-op'],
    'app': './src/index.js'
  },
  output: {
    path: 'dist',
    filename: '[name].[chunkhash].js'
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /(node_modules)/,
        loader: 'babel-loader',
        query: {
          presets: ['env']
        }
      }
    ]
  },
  devtool: 'source-map',
  plugins: [
    new webpack.DefinePlugin({
      __DEV__: false
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: ['vendor', 'manifest'],
      minChunks: Infinity
    }),
    new webpack.optimize.OccurenceOrderPlugin(true)
  ]
};
```

webpack.config.js after migrate:
```
const path = require('path');

const webpack = require('webpack');

module.exports = {
  entry: {
    'vendor': ['is-thirteen', 'no-op'],
    'app': './src/index.js'
  },
  output: {
    path: 'dist',
    filename: '[name].[chunkhash].js'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules)/,
        use: 'babel-loader',
        options: {
          presets: ['env']
        }
      }
    ]
  },
  devtool: 'source-map',
  plugins: [
    new webpack.DefinePlugin({
      __DEV__: false
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: ['vendor', 'manifest'],
      minChunks: Infinity
    }),
    new webpack.optimize.OccurenceOrderPlugin(true)
  ]
};
```
**What is the expected behavior?**
As `OccurenceOrderPlugin` is no longer supported nor needed. Remove it when migrating.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
OS: MacOS
Node: v7.4.0
Deps:
webpack-cli: "https://github.com/webpack/webpack-cli.git#37a594d0346f51c5d62779f835e2293602359a5f"

**Comment by okonet** [comment]
It's called `OccurrenceOrderPlugin` with 2 `r`: https://webpack.github.io/docs/list-of-plugins.html#occurrenceorderplugin
