### ISSUE TITLE
v3.2.2 and v3.3.2 tag mismatch

### ISSUE THREAD

**Issue by marco-ponds** [webpack/webpack-cli#880]
Hello everyone, this is not related to `webpack-cli`'s behaviour, but I believe there's a mismatch in the latest tags.

This tag [v3.2.2](https://github.com/webpack/webpack-cli/releases/tag/v3.2.2) and this tag [v3.3.2](https://github.com/webpack/webpack-cli/releases/tag/v3.3.2) are pointing to the same commit hash `f0031fd`. I think there has been a typo when releasing the latest version of `webpack-cli`, which now is using the wrong tag [v3.2.2](https://github.com/webpack/webpack-cli/releases/tag/v3.2.2).

The tag [v.3.2.2](https://github.com/webpack/webpack-cli/releases/tag/v.3.2.2) represents the real `webpack-cli@3.2.2` and it points to the commit hash `f81762c`. 

I think this was possible because of the different tag name `v.3.2.2` (the real one) vs `v3.2.2` (there is a missing dot after the `v`).

This doesn't represent a real issue since running `npm install webpack-cli@3.3.2` will install the correct version anyway, but It just introduces a bit of confusion.

**Comment by misterdev** [comment]
Hi @marco-ponds, thanks for reporting :)
We can close this now as it has already been fixed (#879)
