### ISSUE TITLE
[BUG]: Dangling processes on exit with `--watch-stdin` and multiple configurations

### ISSUE THREAD

**Issue by LostKobrakai** [webpack/webpack-cli#885]
# Bug report

**What is the current behavior?**
Starting webpack with `--watch-stdin` doesn't properly cleanup after itself. My webpack config returns a function, which returns two configuration objects. When starting webpack via my backend it starts 5 node processes, but when stopping the backend it leaves one node process running. It works when only one configuration object is returned by the function.

**If the current behavior is a bug, please provide the steps to reproduce.**

- Use a webpack config returning two configurations
- Start webpack with `--watch-stdin`
- Close stdin

**What is the expected behavior?**
All processes to be properly stopped without any dangling processes, like it does for only a single configuration.

**Other relevant information:**
webpack version:  4.31.0
Node.js version: 11.9.0
Operating System: MacOS X
Additional tools:

**Comment by evenstensberg** [comment]
I don't think it's going to be a priority fixing this for the `v3` version, but will leave open as this might be an upcoming issue with `v4`

**Comment by alexander-akait** [comment]
Fixed in master, please use `--watch-options-stdin`, fixed for `serve` too
