### ISSUE TITLE
Rename flag `--migrate` to a command (`migrate`)

### ISSUE THREAD

**Issue by okonet** [webpack/webpack-cli#89]
To make it more consistent with other CLI tools I'd propose renaming `webpack --migrate` to `webpack migrate`. Historically, `--` are for options but migrate is a command. So, the usage would look like

```bash
webpack migrate path/to/webpack.config.js
```

This would also allow us passing some arbitrary options to this command (like, code style for prettier etc.) in the future.

**Comment by ev1stensberg** [comment]
I agree, same goes for `init`

**Comment by ev1stensberg** [comment]
Ongoing in #121 , merging to #105 later, closing for now.
