### ISSUE TITLE
[BUG]: 🐞add generator wont add multiple plugin.

### ISSUE THREAD

**Issue by anikethsaha** [webpack/webpack-cli#890]
**Describe the bug**
add generator won't add multiple plugins when running the `add` command multiple times.

**What is the current behavior?**
The generator won't add more than 1 plugin in add generator if asked for multiple times, it will simply overwrite the existing plugin

**To Reproduce**
1. Run command `npx webpack-cli add `
2. Select plugins in the current question
3. Add the plugin
4. it will show the add the appropriate plugin to the config file
5. Repeat the step from `1` and now it should append the new plugin but now it's just replacing it

**Expected behavior**
It should add one more plugin instead of replacing it

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
```bash

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD


```

**Additional context**
Steps for the fix in    [this line](https://github.com/webpack/webpack-cli/blob/11554d6b61baa0dc4a1b78a8e3aad1a33c751041/packages/generators/add-generator.ts#L410)
```
Instead of simply doing the line 
this.configuration.config.webpackOptions[action] = `new ${pluginName}`;
Do these
Add the following steps
 CHECK for the type of this.configuration.config.webpackOptions[action]
if  this.configuration.config.webpackOptions[action] == null then add the string `new ${pluginName}`
else
if it's of type string then, make it to [] and push  `new ${pluginName}`
Elif
type is of [], then push
```

**Comment by anikethsaha** [comment]
@ematipico  is this `AST Transform`  for topScopte bug?

**Comment by evenstensberg** [comment]
Feel free to make a PR that accepts multiple plugins

**Comment by anikethsaha** [comment]
sure @evenstensberg

**Comment by anikethsaha** [comment]
@evenstensberg I think we need to read the users existing config File before this line. And then we need to check if there is already a plugin present and if so and push as an array or else simply create new property as plugin . What what do you think  ? https://github.com/webpack/webpack-cli/blob/11554d6b61baa0dc4a1b78a8e3aad1a33c751041/packages/generators/add-generator.ts#L397

**Comment by anikethsaha** [comment]
If we read the existing config file with `require` method then it is extracting the object creation of the plugins. That is for plugin options like this
```bash
plugins: new CopyWebpackPlugin()
```
with reading with `require` method, it will return 
```bash
plugins: CopyPlugin { patterns: [], options: {} } }
```
Also I tried with `fs.readFileSync` ...there will be a problem to get the file as an `json` object. Tried with `JSON.stringify() and JSON.parse()` but it wont give JSON cause of the module statement on top of the file, these
```bash
const webpack = require('webpack');
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');
```
**Why the reading of the config file required?**
We need to get the existing plugins in order to push the new plugin and if there is not plugin present then add the new plugin. 
If we don't have this then adding multiple plugin names won't be possible.
The current behavior of the `add generator` for the plugin is meant to be for `update generator` which is to overwrite all the plugin with the new ones

**There is one more problem with `require` method for reading the config file:** 
There is a current bug with this generator or maybe with the AST method. It is not adding the `topScope` To the config file when it is required. **I think** the bug is at `ast-utils.ts`

@evenstensberg @ematipico Please take a look at this!

**Comment by evenstensberg** [comment]
Put up a PR and we'll take it from there

**Comment by anikethsaha** [comment]
closing as add package is depreciated
