### ISSUE TITLE
🐞[bootstrap]: Err while bootstrapping

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack-cli#897]
**Describe the bug**
Err while bootstrapping
![Screenshot from 2019-05-27 15-25-59](https://user-images.githubusercontent.com/32242596/58412331-e01c2700-8093-11e9-90f9-454316074941.png)

**What is the current behavior?**
Error
**To Reproduce**
1. `yarn|npm run bootstrap`
2. See error

**Expected behavior**
No Err

**Comment by evenstensberg** [comment]
Just do a rm, and reinstall. Nofix
