### ISSUE TITLE
[ENHANCEMENT]: Inconsistent path resolving for entry

### ISSUE THREAD

**Issue by DanielRuf** [webpack/webpack-cli#899]
**Describe the bug**

It seems there are already relevant issues about this.
But it still happens in webpack 4 or it appeared again.

The following does not work as it can not resolve `src/index.js`
```
webpack --entry src/index.js --output dist/noopener.js
```
But the following does work
```
webpack --entry ./src/index.js --output dist/noopener.js
```

**What is the current behavior?**

`entry` resolved the given path not as `output` does.

**To Reproduce**
1. `git clone git@github.com:DanielRuf/webpack4-entry-test.git`
2. `cd webpack4-entry-test`
3. `yarn`
4. `yarn run start`
5. `yarn run start-broken`

**Expected behavior**
`entry` and `output` should resolve the path the same way

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
```
  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
  Binaries:
    Node: 10.11.0 - /var/folders/39/y8mbv_453bl741p3nc2fkzw8d7s2jg/T/yarn--1558962624550-0.48438054048276014/node
    Yarn: 1.15.2 - /var/folders/39/y8mbv_453bl741p3nc2fkzw8d7s2jg/T/yarn--1558962624550-0.48438054048276014/yarn
    npm: 6.4.1 - /usr/local/opt/nodenv/versions/10.11.0/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 66.0.5
    Safari: 12.0.3
  npmPackages:
    webpack: ^4.32.2 => 4.32.2 
    webpack-cli: ^3.3.2 => 3.3.2 
```

Also see https://travis-ci.com/DanielRuf/webpack4-entry-test/builds/113299603

**Comment by evenstensberg** [comment]
Is the error the same for the next branch?

**Comment by DanielRuf** [comment]
> Is the error the same for the next branch?

I will have to check this when I find some time. Did not yet try it on the `next` branch.

**Comment by evenstensberg** [comment]
Could you try it out and give us feedback if it helped you or not, if it solved the issue? Any other feedback would also be much appreciated!

**Comment by DanielRuf** [comment]
> Could you try it out and give us feedback if it helped you or not, if it solved the issue? Any other feedback would also be much appreciated!

So far I did not find the needed time and at the moment I have no current webpack project where I can test this.

**Comment by snitin315** [comment]
@DanielRuf @evenstensberg  Works fine against beta, I will add a test case for the same to ensure we don't have the same problem.

![Screenshot at 2020-05-05 08-28-31](https://user-images.githubusercontent.com/46647141/81031611-74992700-8eaa-11ea-8fdb-53e05c082b83.png)

**Comment by DanielRuf** [comment]
Thank you @snitin315 and thanks for checking this.

**Comment by DanielRuf** [comment]
Thank you @snitin315 and thanks for checking this. But it looks like you use 4.42.1 which is not the beta version.

**Comment by DanielRuf** [comment]
I am currently testing my own test steps from the issue description. The repo still exists.

**Comment by DanielRuf** [comment]
Not yet fixed in 4.43.0:

<img width="911" alt="Bildschirmfoto 2020-05-05 um 10 24 00" src="https://user-images.githubusercontent.com/827205/81047376-939fb500-8eba-11ea-8eef-942a0cbe8007.png">

**Comment by DanielRuf** [comment]
Not yet fixed in webpack 4.43.0 and webpack-cli `^3.3.2`:

<img width="911" alt="Bildschirmfoto 2020-05-05 um 10 24 00" src="https://user-images.githubusercontent.com/827205/81047376-939fb500-8eba-11ea-8eef-942a0cbe8007.png">

**Comment by DanielRuf** [comment]
Ok so it seems we have some changes in the v4 beta release regarding the CLI arguments:

<img width="880" alt="Bildschirmfoto 2020-05-05 um 10 31 06" src="https://user-images.githubusercontent.com/827205/81047975-c26a5b00-8ebb-11ea-8ec0-9ad119ee55b4.png">

It seems it works with webpack-cli 4.0.0-beta after removing the module-bind argument:

<img width="644" alt="Bildschirmfoto 2020-05-05 um 10 32 12" src="https://user-images.githubusercontent.com/827205/81048047-e0d05680-8ebb-11ea-8f42-a7f89a84ae6c.png">

**Comment by snitin315** [comment]
> Thank you @snitin315 and thanks for checking this. But it looks like you use 4.42.1 which is not the beta version.

Actually my CLI version is beta

**Comment by DanielRuf** [comment]
As this issue was about webpack 4, will it use the new webpack-cli (v4) so it will be fixed there too or do we have to backport it?

**Comment by DanielRuf** [comment]
> Actually my CLI version is beta

Well, you did not provide further details. ;-) I will push my changes to the repository at https://github.com/DanielRuf/webpack4-entry-test

**Comment by DanielRuf** [comment]
> Actually my CLI version is beta

Well, you did not provide further details / it does not become clear from your screenshot. ;-) I will push my changes to the repository at https://github.com/DanielRuf/webpack4-entry-test

**Comment by snitin315** [comment]
Works fine with `webpack-cli@beta`, can we close it?

**Comment by evilebottnawi** [comment]
Yes, fixed and tested
