### ISSUE TITLE
Migrate webpack-dev-server CLI to webpack-cli serve

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack-cli#900]
**Is your feature request related to a problem? Please describe.**
The Dev Server's CLI should live in `webpack-cli`. This will make project configuration easier for users, and will force minimization of configuration changes that the CLI makes, creating uniformity between the Dev Server's CLI and API.

**Describe the solution you'd like**
- `webpack-cli` serve should call the Dev Server API, not the CLI
- Move logic from [`bin/webpack-dev-server`](https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js) to `serve` package
- Minimalize any configuration changes that the CLI makes - it should simply normalize the CLI arguments into Dev Server options, then pass it into the API, and do no further config.
- Dev Server CLI should tell the user to switch to `webpack-cli serve`
- CLI should eventually be removed from the Dev Server in a major version

**Describe alternatives you've considered**
N/A

**Additional context**

EDIT:

- Also, tests need to be added here for `webpack-cli serve`

**Comment by evilebottnawi** [comment]
Bump

**Comment by evilebottnawi** [comment]
Fixed, but with a lot of bugs :disappointed:
