### ISSUE TITLE
[BUG] webpack-cli init doesn't set to production after picking up initial config

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#902]
**Describe the bug**

If you run the `webpack init` feature, you will always end up with a development configuration, as the defaults aren't checked. This is due the fact that `isProd` is set by a variable named `isUsingDefaults` which is hard coded to false. We need to check if the user is using default or production configuration after asking each questions against the defaults we set in webpack.

**What is the current behavior?**

Creates a development config either way.

**To Reproduce**
1. Create a wild config, either one resulting in a development configuration with `webpack init`

**Expected behavior**
Being able to create a production ready configuration in `webpack init`

**Screenshots**
N/A

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
N/A

**Additional context**
https://github.com/webpack/webpack-cli/blob/master/packages/generators/init-generator.ts#L38-L39

**Comment by anikethsaha** [comment]
@evenstensberg  Can we have an option passed in the argument while running the `init` command to mark at production or development? Something like this
`$ webpack-cli init -isProd`
```bash
super(args, opts);
(this.usingDefaults = false), (this.isProd = this.args.isProd || false);
``` 

Similar to this

**Comment by evenstensberg** [comment]
No we need to check against the questions we are asking gradually

**Comment by anikethsaha** [comment]
won't that increase the number of operations for the generator? If we check against each question ?

**Comment by evenstensberg** [comment]
Yes but it’s how the functionality has to be..

**Comment by anikethsaha** [comment]
ohhkay 👍
