### ISSUE TITLE
🏗️[infra]: issue with running individual ts tests with jest

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack-cli#904]
**Describe the bug**
Test files which are written in TS. Can't be run individually with jest(installed globally)

**What is the current behaviour?**
`jest index.test.ts`

![Screenshot from 2019-05-31 21-05-26](https://user-images.githubusercontent.com/32242596/58717289-85aefd80-83e8-11e9-8d75-e46609c28b21.png)

**To Reproduce**
1.Run a single test file written in `.ts`
2. `jest foo.test.ts`
3. See error

**Expected behaviour**
Tests which are written in `js` are running successfully.

![Screenshot from 2019-05-31 21-05-44](https://user-images.githubusercontent.com/32242596/58717527-0ff76180-83e9-11e9-80e8-df98a6966a48.png)

**Solution**
1. I compiled the ts test file to js using `tsc` and it worked.
2. Integrate some third-party test runner based on jest.

**Comment by evenstensberg** [comment]
Feel free to open a pr

**Comment by ematipico** [comment]
You should run the tests from the root folder, not from the sub package. That's how it works. In fact the jest config it's in the root project.

**Comment by anikethsaha** [comment]
if we want to run a specific test in a subfolder, we can use the **jest** command from **root** to that **path**
**example**
```
npx jest packages/generators
```
Isn't this fine ?

**Comment by ematipico** [comment]
I'd say this is not an issue

**Comment by evenstensberg** [comment]
+1

**Comment by pranshuchittora** [comment]
Yep, running from the root works.
:+1:  :tada:

**Comment by evenstensberg** [comment]
Nice
