### ISSUE TITLE
[BUG]: 🐞 webpack-cli add wont lookup for webpack's native plugin in plugins options

### ISSUE THREAD

**Issue by anikethsaha** [webpack/webpack-cli#906]
**Describe the bug**
When using the `add` command and then selecting `plugins` to add and giving webpack's native plugin like `webpack.DefinePlugin` , it will throw error with saying no plugin exists.

**What is the current behavior?**
`webpack-cli add` wont add webpack's native plugin
The error will throw
```bash
? What property do you want to add to? plugins
? What do you want to add to plugins? webpack.DefinePlugin
webpack.DefinePlugin doesn't exist on NPM or is built in webpack, please check for any misspellings.
```

**To Reproduce**
1. `npx webpack-cli add`
2.  in plugins options
3. Give any webpack's native plugin like `webpack.DefinePlugin`
4. It will throw  
> webpack.DefinePlugin doesn't exist on NPM or is built in webpack, please check for any misspellings.

**Fix**
We can have a curated list of all the native plugins and then we can look up to that list and the `npmExist` method before adding the plugin

**Expected behavior**
Should add even webpack's native plugin

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    webpack-cli: ^3.3.2 => 3.3.2

```

**Comment by evenstensberg** [comment]
feel free to open a pr

**Comment by anikethsaha** [comment]
@evenstensberg  sure but I couldn't find much of native plugins other than the mention. Do you have any list or can you mention where I can find them?
I checked at the docs and at webpack repo too. Please mention if I missed any!

**Comment by evenstensberg** [comment]
We're searching through the available plugins that are hooked up on the webpack object. You could dig and debug yourself to figure out?

**Comment by anikethsaha** [comment]
okay I will try it out at best......

**Comment by anikethsaha** [comment]
there are few in here https://github.com/webpack/webpack/tree/master/lib 
atleast we can start with them ...what say ? @evenstensberg

**Comment by evenstensberg** [comment]
That’s where we are finding them from, the logic is already present

**Comment by anikethsaha** [comment]
👍 okay

**Comment by anikethsaha** [comment]
@evenstensberg can you check these
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/21e68259f6fd43aba37e8112e3edb792975f8266/types/webpack/index.d.ts#L676  if we can make the list from here?

**Comment by anikethsaha** [comment]
here is the list till now I made from the type file
```bash
export const nativePluginsList : Array<string> = [
	"webpack.DefinePlugin",
	"webpack.AmdMainTemplatePlugin",
	"webpack.ContextReplacementPlugin",
	"webpack.DllPlugin",
	"webpack.DllReferencePlugin",
	"webpack.EvalSourceMapDevToolPlugin",
	"webpack.ExtendedAPIPlugin",
	"webpack.HashedModuleIdsPlugin",
	"webpack.HotModuleReplacementPlugin",
	"webpack.IgnorePlugin",
	"webpack.LoaderOptionsPlugin",
	"webpack.NamedChunksPlugin",
	"webpack.NormalModuleReplacementPlugin",
	"webpack.PrefetchPlugin",
	"webpack.ProgressPlugin",
	"webpack.EnvironmentPlugin",
	"webpack.ProvidePlugin",
	"webpack.SplitChunksPlugin",
	"webpack.SourceMapDevToolPlugin",
	"webpack.WatchIgnorePlugin",
	"webpack.SingleEntryPlugin",
	"webpack.AggressiveSplittingPlugin",
	"webpack.LimitChunkCountPlugin",
	"webpack.MinChunkSizePlugin",
	"webpack.OccurrenceOrderPlugin",
	"webpack.UglifyJsPlugin"
]
```

**Comment by evenstensberg** [comment]
You don't need to do this, we have a functionality for this (or at least had) to check if the plugin is on the webpack object, check `pluginExist` in the add generator. What you will need to do, is to check the filter in the function with an additional `webpack.` prefix

**Comment by anikethsaha** [comment]
👍 ohh...missed that ....I guess we can extract it to utils . what say ?

**Comment by evenstensberg** [comment]
Yes

**Comment by anikethsaha** [comment]
@evenstensberg we can change the plugin input using this 
```bash
let tempPluginName = answerToAction.actionAnswer
let isPrefixPresent = /webpack./.test(tempPluginName);
tempPluginName = isPrefixPresent ? tempPluginName.replace("webpack.","").trim() : tempPluginName                
```
and changin this line https://github.com/webpack/webpack-cli/blob/6ee3c0b11638997613d22c186d21e0736108d295/packages/generators/add-generator.ts#L303 with the below
```bash
 .filter((x : string ) : string => x == tempPluginName  )
```


And then using `tempPluginName` for further execution of the method will work fine

**Comment by evenstensberg** [comment]
That doesn't look so maintainable. Maybe we could try to reassign a `let` using a `if` statement instead of having that ternary? In my opinion it is clean and easier to read than a ternary.

**Comment by anikethsaha** [comment]
sure 👍 ...and what about the `filter` instead of `find` ....is it fine?

**Comment by evenstensberg** [comment]
Not really. All plugins are suffixed with Plugin so we can rely us on that

**Comment by anikethsaha** [comment]
Actually I am referring to the path where it is looking for the plugin. 
You can see that `DefinePlugin` is present in `webpack/lib` but it is not having its schema in `webpack/schemas/plugins`.

**Comment by evenstensberg** [comment]
that is what I'm refering to as well. We only need to look in `lib` and subfolders there cause we know native plugins are at a "flat" hierachy there

**Comment by anikethsaha** [comment]
we need schemas too to implement them ri8 ?....but some plugin's schema is not present in the schemas path .

**Comment by evenstensberg** [comment]
No

**Comment by evenstensberg** [comment]
If schema for that is not found, we default to only add the plugin

**Comment by anikethsaha** [comment]
Ohh...okok...yeah... I noticed that now only..... 👍
