### ISSUE TITLE
Feature: allow related field in generator questions

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack-cli#908]
**Is your feature request related to a problem? Please describe.**
For UI, we want to show the user that to which property in webpack config is this question-related to. As the logic is implemented in generators itself, we can't fill this property from outside. 

**Describe the solution you'd like**
Questions from the generator to have a `related` field

**Describe alternatives you've considered**
No alternatives IMO.

**Additional context**
Will implement once decided

**Comment by rishabh3112** [comment]
UI label can be added to the issue for visibility.

**Comment by anikethsaha** [comment]
Something like property name along with the description?

**Comment by rishabh3112** [comment]
Yes up to some extent, I am mainly looking to have a general opinion and thus standardize this field across the webpack-scaffold ecosystem. As CLI should be consistent with the behaviour of UI and vice-versa, thus CLI should also provide this with the question in an appropriate way if this has to there.
So, implementation after having the final consensus.

**Comment by anikethsaha** [comment]
LGTM. 
ok, so what I understood *(please correct me If I am wrong)* is that a `related` field in `webpack-scaffold` 's type of question.
but we need to make sure it doesn't break the types. yeoman-generator's prompt method take the question of type `inquirer.Question` so I think If adding an extra field (`related`) in the webpack-scaffold's question objects may break it.
Or do you have a plan for a different approach?

**Comment by evenstensberg** [comment]
This might be hard as we're asking things such as "are you gonna use SASS", which in this case wouldn't be equivalent to `module.rules`. I don't think we would need to provide this mapping, but a mapping is needed, which is the `.yo-rc` file

**Comment by rishabh3112** [comment]
Thanks!! I was looking for this so as to provide a insight on what this question do thus scaffolding wouldn't be a complete black box for user.
Can you explain a bit more on `.yo-rc` file and it's usecase here ?

**Comment by evenstensberg** [comment]
The yo file is a reflection of a webpack configuration, so there's a direct mapping there

**Comment by rishabh3112** [comment]
Okay, you meant to give a overview to user at the end of scaffolding?

**Comment by evenstensberg** [comment]
> For UI, we want to show the user that to which property in webpack config is this question-related to. As the logic is implemented in generators itself, we can't fill this property from outside.

We can, because we already have a config to use `.yo-rc`. So we have a mapping here

**Comment by rishabh3112** [comment]
I am asking for providing the details during prompting, because `.yo-rc` is generated at the end of execution of generator.
More precisely at `writing()` of generator.

**Comment by evenstensberg** [comment]
Gotcha. So we should use a socket or the server to prompt these questions, skip prompting if not useful. Does that help?

**Comment by evenstensberg** [comment]
It’s a concurrency thing, we’ll need to wait until generator is done and choose not to generate the ast transform until we’re done. This is possible as the function to transform is abstracted

**Comment by rishabh3112** [comment]
No need to scarp prompting as sockets work with prompting at UI :)

Currently `this.prompt()` of generators is overloaded before running it such that `prompting` prompts over sockets thus works on use exactly same generator w/o rewrites that are used at CLI.
That's why all webpack scaffolds works directly from npm.

**Comment by rishabh3112** [comment]
> It’s a concurrency thing, we’ll need to wait until generator is done and choose not to generate the ast transform until we’re done. This is possible as the function to transform is abstracted

This way be can find what has previous done to config, not what the current would be doing. Hopes this clears the I have?

**Comment by evenstensberg** [comment]
Gotcha. I'm just making a point about us not needing to change the scaffolding for ui except with the ability to generate a scaffold without asking questions

**Comment by rishabh3112** [comment]
Got it now. We can create scaffolds w/o prompting too. In my previous attempt for UI, `One Click project` option runs with generator under the hood w/o prompting!

P.S>
I think my idea here is a bit unclear to be understandable. Will open a PR from where I can explain the idea I have in mind.

**Comment by evenstensberg** [comment]
Great do that. Nothing explains better than code
