### ISSUE TITLE
[FEATURE]: Add webpack-cli to Entropic

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#916]
**Is your feature request related to a problem? Please describe.**
It would be good to have the CLI package as a part of Entropic.

**Describe the solution you'd like**
Webpack-CLI published to entropic, READMEs with installation guides updated accordingly.

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/entropic-dev/entropic

Mind taking this on @ematipico as you've got write access most of the places and knows how to version correctly?

**Comment by evilebottnawi** [comment]
bump

**Comment by alexander-akait** [comment]
I think we don't need this, anyway feel free to feedback
