### ISSUE TITLE
[chore]: Export all utils from root file in generators and utils package

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#918]
**Describe the bug**
All utils need to be exported from the root file which is absent now in the generators package and the utils package

**What is the current behavior?**
Need to import each util from a file `package/

**Expected behavior**
I think it makes sense to aggregate them all in the root file and then export everything from there.

ex - 
`import { configRoot } from 'utils'`

**Screenshots**
NA

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
Nothing so far, happy to discuss. :)

**Comment by evenstensberg** [comment]
I don't think that is needed. We're ending up with a big file rather than local util files from local util folders, which are scoped to their functionality. Thanks for the issue though!
