### ISSUE TITLE
[test]: Add tests for path-utils

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#922]
**Do you want to request a *feature* or report a *bug*?**
feat

**What is the current behavior?**
No tests for path-utils

**What is the expected behavior?**
Need tests

**If this is a feature request, what is motivation or use case for changing the behavior?**
More coverage

Working on it
**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**

**Comment by evenstensberg** [comment]
I'm going to close this and have you to reopen it with a more elaborative issue ticket

**Comment by anshumanv** [comment]
Sorry for the missing details, you think it makes sense to add tests for helper functions from - https://github.com/webpack/webpack-cli/blob/master/packages/utils/path-utils.ts

Will reopen adding more details if you approve. ✅

**Comment by evenstensberg** [comment]
Submit a new one
