### ISSUE TITLE
[refactor]: Better type checking using util functions

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#930]
**Describe the bug**

Presently we're using `typeof` to determine types of vars, which is not nice, since `typeof  new String('asd')` won't be a string, hence we need to introduce some utils for all cases like these for more robust determination.

**What is the current behavior?**
presently just `typeof varname` approach is used. 

**To Reproduce**
NA

**Expected behavior**

**Screenshots**
NA

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
Not right now.

**Comment by evenstensberg** [comment]
Could you provide resources to back up your claims along with examples from the source code?

**Comment by anikethsaha** [comment]
Like a utility method for type checking ?

**Comment by evenstensberg** [comment]
Instead of `typeof value === structure` yea, but this is up for disussion, no evidence saying it's failing

**Comment by anikethsaha** [comment]
yeah true.
may be we can implement this for some method to overcome this 
```
typeof [23,2334,3]
"object"
typeof {}
"object"
```

**Comment by rishabh3112** [comment]
We already have `Array.isArray` for that and already is being used at CLI. I can't think of the scenarios where it may be needed this kind of library explicitly. Maybe there is a failing type check that Anshuman may have in mind and is being used at CLI somewhere?

**Comment by anikethsaha** [comment]
Ok then let's wait for Anshuman 's reply here...for any specific bug.

**Comment by anshumanv** [comment]
We're using `typeof` everywhere to check for data types - https://github.com/webpack/webpack-cli/search?q=typeof&unscoped_q=typeof

what if a string is created using `new String('abc')`, typeof will return Object here, so a helper function like 

`
function isString (value) {
  return typeof value === 'string' || value instanceof String;
}
`

can be used, similarly for other types that we're checking, we can introduce these helper functions to check the data type better, not really encountered any cases as of now though.

**Comment by evenstensberg** [comment]
I don't think that is needed, as we're not creating new strings, we're modifying existing ones. We're checking every type pretty strictly in addition to typescript, so this is fine.
