### ISSUE TITLE
[FEATURE]: Display Manual command for webpack-cli

### ISSUE THREAD

**Issue by anikethsaha** [webpack/webpack-cli#936]
**Is your feature request related to a problem? Please describe.**
Currently, if we are in terminal and not sure about what a particular webpack config property does then we need to check the docs and other sites.

This is the command which will work similar to **man command in linux**. 
The command will print the details of a particular webpack config property in the terminal on a go. the command will look like this 
```bash
 $ webpack-cli man [property-name] 
```
Here in the terminal itself, the user can write a command like 
```bash
# example
$ webpack-cli man loaders
```
and then it will print the details along with the code supporting the `loader` property of the config file.

It will show the most and minimum details required to implement it not deep details.
 
**Describe the solution you'd like**
Below is what the feature I am expecting to look like

<img src="https://imgur.com/XLRcQlo.gif" />

I have implemented this feature in this just for demo purpose and we don't need to add any other extra dependency it works fine with the existing one

**Describe alternatives you've considered**
Checking the docs

**Usage**

*This will print when no argument is passed that is ` $  webpack-cli man `*

```bash

    This Is a Manual For webpack config file

    $ webpack-cli man [webpack config name]

    example command:-

    $  webpack-cli man plugin


```

**Additional context**
The implementation can be improved as I have manually extracted the points from the docs. Also, I have made a curated list of command in a js object where its `propertyname : explaination `
In order to highlight the code and any notes or quotes, created a utility method to implement markdown like support for the explanation 
Like for code its
```
---
INSIDE HERE ALL THE CODE
---

```
for quotes 
```
>>> QUOTES OR NOTES HERE >>>
```

**Comment by anikethsaha** [comment]
code implementation here : [repo-link](https://gitlab.com/anik220798/webpack-cli-man)

**Comment by evenstensberg** [comment]
We don't need this for now, cli interface gonna ble replaced soon
