### ISSUE TITLE
[Enhancement]: Fix 'any' type for linting warnings

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#940]
**Describe the bug**

There's some places in the code where `any` is used and the linter is complaining about that.

**What is the current behavior?**

type `any` is used and the linter is complaining

**To Reproduce**
1. `npm install`
2. `npm run bootstrap`
3. `npm run build`
4. `npm run lint`

**Expected behavior**
No warnings from the linter

**Screenshots**

![Skjermbilde 2019-06-07 kl  23 44 15](https://user-images.githubusercontent.com/16735925/59135144-2ddf3c00-897e-11e9-8c7d-398cd6b2d0a6.png)

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
N/A

**Additional context**
N/A

**Comment by anikethsaha** [comment]
Will try to resolve it...

**Comment by anikethsaha** [comment]
I think those ` self ` should be of type `Generator` as those are objects of custom generator which are extending `Generator` type. 
Like this? https://github.com/webpack/webpack-cli/pull/945/commits/5a44ab1e85a90945e83dc347a70f3e46185b956f
But getting some type errors which is kind of weird,

**Comment by evenstensberg** [comment]
Yes, I thought so as well but the linter wasn't happy bout that

**Comment by anikethsaha** [comment]
Yeah, the linter should not give error as far as the code is concern. May be need custom type which extends the `Generator` type

**Comment by evenstensberg** [comment]
Do that

**Comment by anikethsaha** [comment]
yeah...trying..for that only.. 👍

**Comment by anshumanv** [comment]
Not seeing this anymore, can be closed.
