### ISSUE TITLE
[Enhancement]: getPackageManager considered flaky

### ISSUE THREAD

**Issue by evenstensberg** [webpack/webpack-cli#941]
**Describe the bug**

When determining the current package version, the lookup path for yarn is wrong and causes sometimes misleading information

**What is the current behavior?**

Npm is almost used everytime

**To Reproduce**
1. Go to `packages/utils/package-manager` L77
2. Reproduce by creating new tests or using the init generator

**Expected behavior**
Both npm and yarn is respected, both locally and globally.

**Screenshots**
N/A

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
N/A

**Additional context**
N/A

**Comment by jamesgeorge007** [comment]
@evenstensberg I would take this up :+1: Can you point me to the required files to be worked upon?

**Comment by evenstensberg** [comment]
Sure! https://github.com/webpack/webpack-cli/blob/master/packages/utils/package-manager.ts#L55 needs to have better logic. Currently it doesn't work as expected

**Comment by Deathrow77** [comment]
@evenstensberg Can I take up this issue?

**Comment by Deathrow77** [comment]
@webpack-bot claim

**Comment by Deathrow77** [comment]
@evenstensberg Please correct me if I am wrong. The default package manager has to npm. Only if we have yarn installed locally, will we use yarn. In every other case, NPM will be the package manager. Right?

**Comment by ematipico** [comment]
@Deathrow77 yes, npm should be the default

**Comment by Deathrow77** [comment]
@ematipico So, there's no need to check for local NPM. We can set it to default package manager, check for local yarn and then, try spawning yarn. If local yarn exists, we use that. Else We try the spawn and if it returns an error, npm is the returned.
        ```
const hasLocalYarn = fs.existsSync(path.resolve(process.cwd(), "yarn.lock"));
	let defaultPackageManager = "npm";
	if(hasLocalYarn)
	{
		defaultPackageManager = "yarn";
	}
	else if(spawn.sync("yarn", [" --version"], { stdio: "ignore" }).error)
		return defaultPackageManager;
	else
		return defaultPackageManager;
```

**Comment by Deathrow77** [comment]
@ematipico I don't think there's a need to check for localNPM here. We just need to check for localYarn. I am using the following logic -

1. Set npm as the defaultPackageManager.
2. Check for local Yarn. If present, update the defaultPackageManager to yarn. If absent, return npm.
3. Try spawning yarn -v as well. If it return error, return npm.

However, this is bringing up an error with the test related to "npm update" command. Since, yarn doesn't have an update subcommand, it is throwing an error if yarn is the package manager.
Should I change the tests as well to match the outputs obtained from the new logic ?

**Comment by ematipico** [comment]
@Deathrow77 yes I think a change to the test should be done. Also, we are releasing a major version, we can apply a breaking change I think

**Comment by buoyantair** [comment]
Hey folks! Is this PR still up for grabs! 🙌

**Comment by anshumanv** [comment]
Hey @buoyantair, thanks for showing interest in the issue!

Sure, feel free to send a PR. You can take refer https://github.com/webpack/webpack-cli/pull/1248#pullrequestreview-363247269 on how to proceed about this. :)

**Comment by ematipico** [comment]
The logic has been moved.

**Comment by buoyantair** [comment]
@ematipico Thanks for letting me know!

**Comment by buoyantair** [comment]
@anshumanv Thanks! I will definitely have a look 👍

**Comment by buoyantair** [comment]
Hi.. Looks like this issue is already resolved in the latest `next` branch... I realised now that I was working on outdated code....
