### ISSUE TITLE
Enhancements: Improve CommonChunksPlugin with Initial Scaffold

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack-cli#95]
**Mentioned on Twitter by Addy Osmani & "necolas" **

**Do you want to request a *feature* or report a *bug*?**

https://twitter.com/addyosmani/status/845317139959443456

**What is the current behavior?**

On rebuilds, a module changes hashes which means its being rebuilt, even though it hasn't changed. 

**What is the expected behavior?**

We should make hashes not changed if the module hasn't either. 

Sure. He meant that he had multiple chunks where when he would do a new build even if the code for those chunks didn't change the manifest for their entry chunk would and then the hashes for those entries also changed. Meant long term caching basically broke.

 Sean covered a workaround in his post
 1. A new CommonsChunk with minChunks infinity and name not equalling a entry chunk (this extracts the runtime into its on entry chunk with no modules)

2. Use OccurenceOrderPlugin to sort ids

3. Use whatever Commons chunk strategy you want on top to accomplish vendor caching

4. Use the recordsPath property to create a hard source control of your previous builds module ids so that they do not change when you run a new build or update your app code.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Feature Request -> Better perf for scaffolds straight away.

**Comment by okonet** [comment]
> Use OccurenceOrderPlugin to sort ids

This is deprecated in Webpack 2 AFAIK

**Comment by ev1stensberg** [comment]
I think this was solved as apart of the initial generator at #105
