### ISSUE TITLE
[Enhancement]: Refactoring the prompt-command.js package manager check

### ISSUE THREAD

**Issue by anikethsaha** [webpack/webpack-cli#953]
**Is your refactoring related to a problem? Please describe.**
Currently, the package manager check is done using this condition
```javascript 
const isYarn = fs.existsSync(path.resolve(process.cwd(), "yarn.lock"));
// then
if (isYarn){ ... }
```

it can be replaced with this 
```javascript
process.env.npm_execpath !== undefined && process.env.npm_execpath.includes("yarn")
```

**Why**
it will work fine(better) when this package is installed globally and a user is in the fresh project folder with no lock file
its been used in `cli.js` so I guess it can be implemented here too

**Describe the solution you'd like**
```javascript
process.env.npm_execpath !== undefined && process.env.npm_execpath.includes("yarn")
```

**Describe alternatives you've considered**
The current one

**Additional context**
NA

**Comment by evenstensberg** [comment]
Submit a PR

**Comment by anikethsaha** [comment]
👍
