### ISSUE TITLE
🐞[infra]: weird behaviour by commit hook

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack-cli#956]
**Describe the bug**
After commit, the code gets automatically formatted and linting throws an error in weird characters.

**What is the current behavior?**
Error and bad linting.

**To Reproduce**
1. I changed a few .ts files and after doing `git commit`
2. FIles gets automatically formatted
3. Running `yarn lint` throws error because of bad auto linting.

**Expected behavior**
No formatting after commit 

**Screenshots**

![Screenshot from 2019-06-11 14-57-02](https://user-images.githubusercontent.com/32242596/59260763-d381fc00-8c59-11e9-8c03-3a9f52ba2cbb.png)

**Comment by anikethsaha** [comment]
that's the `prettier-eslint` pkg, you can remove the `--write` flag from the npm scripts of format,

**Comment by evenstensberg** [comment]
This needs to be fixed, feel free to send a PR

**Comment by anshumanv** [comment]
This is because of the prettier config and eslint config being conflicting for some reason, would encourage to explore the properties which are conflicting and then only enabling one of them. Would also make #938 easy to solve

**Comment by jamesgeorge007** [comment]
@evenstensberg I shall go ahead if this is still open to be worked on :clap:

**Comment by evenstensberg** [comment]
Go for it!

**Comment by ematipico** [comment]
To solve the issue, just the instructions here: 
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/README.md#usage-with-prettier
