### ISSUE TITLE
[test]: Add tests for utils to find project root

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#967]
**Do you want to request a *feature* or report a *bug*?**
I think we should have tests for util to find project root present in `path-utils` - https://github.com/webpack/webpack-cli/blob/master/packages/utils/path-utils.ts

**What is the current behavior?**
No tests for the function

**If the current behavior is a bug, please provide the steps to reproduce.**
NA

**What is the expected behavior?**
Have some tests to test behavior in various cases.

**If this is a feature request, what is motivation or use case for changing the behavior?**
NA

**Please paste the results of `webpack-cli info` here, and mention other relevant information such as programming language.**
```sh
  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Safari: 12.1.1
  npmPackages:
    webpack: 4.x.x => 4.33.0
    webpack-dev-server: 3.7.1 => 3.5.1
  npmGlobalPackages:
    webpack-cli: 3.3.4
    webpack: 4.30.0
```

**Comment by anshumanv** [comment]
@evenstensberg @ematipico is it within scope to add tests for this?

**Comment by ematipico** [comment]
The only way that I can come up with a way of testing such things is by using Docker. Are you aware of a better way to test them?

**Comment by evenstensberg** [comment]
I think we've had some PR's to fix this, @anshumanv ?

**Comment by anshumanv** [comment]
Maybe other utils but not the `findProjectRoot` function.

**Comment by evenstensberg** [comment]
Could you send a pr?
