### ISSUE TITLE
📝[tests]: tests failing on master

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack-cli#978]
**Describe the bug**
8 Tests are failing on the current master.

**What is the current behavior?**
Failing tests

**To Reproduce**
1. Pull the latest master (as of June 27 2019)
2. `yarn test`
3. Scroll down and see failing tests.

**Expected behavior**
All tests should pass with flying colours.

**Screenshots**
![Screenshot from 2019-06-28 02-14-01](https://user-images.githubusercontent.com/32242596/60299614-bf711680-994a-11e9-989b-3a156027cdb8.png)

**Additional context**
I ran `yarn bootstrap` prior testing.

**Comment by evenstensberg** [comment]
which ones?

**Comment by pranshuchittora** [comment]
Summary of all failing tests
 FAIL  test/binCases/output/output-library-many/output-library-many.test.js
  ● output-library-many

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

      21 | 	const summary = extractSummary(stdout);
      22 | 
    > 23 | 	expect(code).toBe(0);
         | 	             ^
      24 | 	expect(summary).toEqual(expect.anything());
      25 | 	expect(summary).toContain("index.js");
      26 | 	expect(stderr).toHaveLength(0);

      at Object.<anonymous>.test (test/binCases/output/output-library-many/output-library-many.test.js:23:15)

 FAIL  test/binCases/output/output-library-single/output-library-single.test.js
  ● output-library-single

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

      19 | 	const summary = extractSummary(stdout);
      20 | 
    > 21 | 	expect(code).toBe(0);
         | 	             ^
      22 | 	expect(summary).toEqual(expect.anything());
      23 | 	expect(summary).toContain("index.js");
      24 | 	expect(stderr).toHaveLength(0);

      at Object.<anonymous>.test (test/binCases/output/output-library-single/output-library-single.test.js:21:15)

 FAIL  test/binCases/stats/custom-preset/custom-preset.test.js
  ● custom-preset

    expect(received).toHaveLength(expected)

    Expected length: 0
    Received length: 92
    Received string: "
    webpack not installed
    
    Install webpack to start bundling: 
     $ yarn add webpack --dev
    
    "

      18 | 	const summary = extractSummary(stdout);
      19 | 
    > 20 | 	expect(stderr).toHaveLength(0);
         | 	               ^
      21 | 	expect(code).toBe(0);
      22 | 	expect(summary).toHaveLength(0);
      23 | });

      at Object.<anonymous>.test (test/binCases/stats/custom-preset/custom-preset.test.js:20:17)

 FAIL  test/binCases/output/output-argument/output-argument.test.js
  ● output-argument

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

      14 | 	const summary = extractSummary(stdout);
      15 | 
    > 16 | 	expect(code).toBe(0);
         | 	             ^
      17 | 	expect(summary).toEqual(expect.anything());
      18 | 	expect(summary).toContain("bundle.js");
      19 | 	expect(summary).toContain("index.js");

      at Object.<anonymous>.test (test/binCases/output/output-argument/output-argument.test.js:16:15)

 FAIL  test/binCases/mode/none/none.test.js
  ● none

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

       6 | 	const { code, stdout, stderr } = run(__dirname, ["./index.js", "--mode", "none"]);
       7 | 
    >  8 | 	expect(code).toBe(0);
         | 	             ^
       9 | 
      10 | 	const summary = extractSummary(stdout);
      11 | 

      at Object.<anonymous>.test (test/binCases/mode/none/none.test.js:8:15)

 FAIL  test/binCases/stats/build-delimiter/build-delimiter.test.js
  ● build-delimiter

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

      15 | 	const summary = extractSummary(stdout);
      16 | 
    > 17 | 	expect(code).toBe(0);
         | 	             ^
      18 | 	expect(summary).toContain("success");
      19 | 	expect(stderr).toHaveLength(0);
      20 | });

      at Object.<anonymous>.test (test/binCases/stats/build-delimiter/build-delimiter.test.js:17:15)

 FAIL  test/binCases/config-location/not-found/not-found.test.js
  ● not-found

    expect(received).toBe(expected) // Object.is equality

    Expected: 0
    Received: 1

      14 | 		"production"
      15 | 	]);
    > 16 | 	expect(code).toBe(0);
         | 	             ^
      17 | 	expect(stdout).toContain("./src/index.js");
      18 | 	expect(stderr).toHaveLength(0);
      19 | });

      at Object.<anonymous>.test (test/binCases/config-location/not-found/not-found.test.js:16:15)

 FAIL  test/binCases/no-options/none/none.test.js
  ● none

    expect(received).toBe(expected) // Object.is equality

    Expected: 2
    Received: 1

       5 | test("none", () => {
       6 | 	const { code, stdout, stderr } = run(__dirname);
    >  7 | 	expect(code).toBe(2);
         | 	             ^
       8 | 	expect(stdout).toEqual(expect.anything());
       9 | 	expect(stderr).toContain("Insufficient number of arguments or no entry found.");
      10 | 	expect(stderr).toContain("Alternatively, run 'webpack(-cli) --help' for usage info.");

      at Object.<anonymous>.test (test/binCases/no-options/none/none.test.js:7:15)


Test Suites: 8 failed, 8 skipped, 62 passed, 70 of 78 total
Tests:       8 failed, 8 skipped, 185 passed, 201 total
Snapshots:   95 passed, 95 total
Time:        43.606s

**Comment by evenstensberg** [comment]
Works here. Run install and bootstrap first

**Comment by pranshuchittora** [comment]
I pulled the new changes in the master and ran `bootstrap`.

```
Test Suites: 8 failed, 8 skipped, 62 passed, 70 of 78 total
Tests:       8 failed, 8 skipped, 185 passed, 201 total
Snapshots:   95 passed, 95 total
Time:        41.363s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
Unfortunately, tests are still failing.

**Comment by evenstensberg** [comment]
Have you tried using npm?

**Comment by pranshuchittora** [comment]
Oops, no difference,

I ran `npm run bootstrap` then `npm run test`

```
Test Suites: 8 failed, 8 skipped, 62 passed, 70 of 78 total
Tests:       8 failed, 8 skipped, 185 passed, 201 total
Snapshots:   95 passed, 95 total
Time:        28.564s, estimated 33s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-cli@3.3.5 test: `nyc jest --maxWorkers=4 --reporters=default --reporters=jest-junit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack-cli@3.3.5 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by evenstensberg** [comment]
You need to publish node and npm version

**Comment by pranshuchittora** [comment]
> You need to publish node and npm version

Do you mean my node and npm version?

```
 node -v     
v10.12.0

 npm -v      
6.5.0
```
