### ISSUE TITLE
[BUG]: Wrong priority in picking config file between .coffee and .js

### ISSUE THREAD

**Issue by MadSheogorath** [webpack/webpack-cli#980]
# Bug report

**What is the current behavior?**
Webpack tries to load webpack.config.coffee first when both webpack.config.coffee and webpack.config.js are present. As a result we'll get a syntax error in case we have no coffeescript dependency installed.

**If the current behavior is a bug, please provide the steps to reproduce.**
Put webpack.config.coffee, configure File Watcher for .coffee file type, get corresponding compiled webpack.config.js, run webpack --mode=production

**What is the expected behavior?**
It should try to load webpack.config.js first (in case if user just compiles his .coffee config into .js and does not want to install additional coffeescript dependency into his project). Only if there's no .js config file then try to use .coffee.

**Other relevant information:**
webpack version:  4.35.0
Node.js version: 8.11.1
Operating System: Windows 7
Additional tools: JetBrains WebStorm

**Comment by anikethsaha** [comment]
**First**
> ## I think this is the only file which should always be in `.js` that's it !.

---
**Now Workaround**
you can do it  
- add `webpack.config.coffee` in your `webpack.config.js` with proper coffee loader
- this should output to something like `coffee.webpack.config.js` *(weird naming btw)*
- in the build command , 
```json
"build": "webpack --mode=production --config webpack.config.js && webpack --mode=production --config coffee.webpack.config.js ",
```
- enjoy ?

I am assuming this is build script, you dont want anything in watch mode, if you want then use some other library like [concurrently](https://www.npmjs.com/package/concurrently) 

**OR**
manually compile the `.coffee` to `.js` and use it

**Comment by MadSheogorath** [comment]
Why do I use .coffee and file watchers. Well because it's very handy. I have global file watchers configured for all my projects and I do not need to switch my mind between .js and .coffee syntax no matter what I do.

Yes there are workarounds, I admit that. But still it would be cool to have correct load priority (I believe it is something very easy to fix actually).

For now I just have coffeescript dependency installed and that solves my problem but still... This is a workaround.

**Comment by MadSheogorath** [comment]
> I think this is the only file which should always be in `.js` that's it !.

Not agree. Because if you use coffee, you don't want to make config.js, you want to make config.coffee which will be compiled into .js automatically.

**Comment by evenstensberg** [comment]
We need to fix this in v4, discarding coffeescript

**Comment by evenstensberg** [comment]
@jhnns do you think it's worth supporting coffeescript, or should we choose some set of ext we support?

**Comment by phated** [comment]
@evenstensberg you can let https://www.npmjs.com/package/rechoir & https://www.npmjs.com/package/interpret do the heavy lifting. They are battle tested.

**Comment by evenstensberg** [comment]
We're doing that in the old upstream (master), I think problem was that people started beginning to worry about the size of the dependencies we were having. I'm +1 for having interpret still

**Comment by pspeter3** [comment]
How does it work without interpret?

**Comment by evenstensberg** [comment]
You'll need to have the same functionality either way, interpret has an object with matching ext + paths to that, meaning we won't need to create an object with that ourselves
