### ISSUE TITLE
missing loader for Sass in generated config file

### ISSUE THREAD

**Issue by DanielRuf** [webpack/webpack-cli#985]
**Describe the bug**

I have installed the latest version of `webpack-cli` and `@webpack-cli/init` but it still does not add `sass-loader` to the config.

Is this by design?

**What is the current behavior?**

Scaffolding a project with the `Sass` answer does not add the needed `sass-loader`.

**To Reproduce**
1. Run `webpack-cli init`
2. Choose the `SASS` option
3. Check the generated webpack.config.js

**Expected behavior**
The generated config should have the `sass-loader`.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
  Binaries:
    Node: 12.4.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.13.0 - ~\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.9.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
```

**Comment by DanielRuf** [comment]
Not sure but may related or similar cause as previously with PostCSS: https://github.com/webpack/webpack-cli/issues/427

**Comment by pranshuchittora** [comment]
Able to reproduce.

![Screenshot from 2019-07-29 23-53-10](https://user-images.githubusercontent.com/32242596/62072339-0f017580-b25c-11e9-8328-3b459ac3597b.png)

**Comment by pranavsrivatsaVL** [comment]
Hello @DanielRuf , 
Is anyone working on this ? Or can i start on this ?

**Comment by DanielRuf** [comment]
> Is anyone working on this ? Or can i start on this ?

Hi @pranavsrivatsaVL,

I guess so far no one is working on this. At least I do not have the time for this.
So you can start working on a PR to fix this.

**Comment by pranavsrivatsaVL** [comment]
Okay. Will start working on this. Any pointers on where i should start looking at folder structure wise?

**Comment by evenstensberg** [comment]
https://github.com/webpack/webpack-cli/commit/51831c79bb701b7a21778ae7c90f7753a270c24d
