### ISSUE TITLE
Mixin-deep dependency vulnerability from npm audit

### ISSUE THREAD

**Issue by lkwdwrd** [webpack/webpack-cli#994]
**Describe the bug**

`npm install webpack-cli` reports vulnerabilities in the dependency mixin-deep.

Path  webpack-cli > findup-sync > micromatch > snapdragon > base > mixin-deep

See https://www.npmjs.com/advisories/1013

**What is the current behavior?**

When running `npm install webpack-cli` severe security vulnerabilities are reported.

**To Reproduce**
run `npm install webpack-cli`

**Expected behavior**
0 reported security vulnerabilities when installing the package.

**Additional context**
This report is from today. Several new audit issues are cropping up in various popular packages. Reporting to track fixes and update when fixes are available.

**Comment by ShellOliver** [comment]
**Version** 3.3.5
Another high vulnerability is the package `set-value`.
**path:** `webpack-cli > findup-sync > micromatch > snapdragon > base > cache-base > union-value > set-value`

more info: https://nodesecurity.io/advisories/1012 

reproduce:
run `npm install webpack-cli`
in package.json -> `"webpack-cli": "^3.3.5"`

`npm audit
`

**Comment by anikethsaha** [comment]
`webpack-cli` is for running in the user machine as a development. Not for production. 
So we can wait for those packages to fix their issues 👍

**Comment by evenstensberg** [comment]
Fixed

**Comment by evenstensberg** [comment]
Please upgrade to `v3.3.6`
